// @generated by packages/synthdef-compiler/scripts/generate-rust.ts from specs/ugens.json — do not edit.
// Regenerate with `yarn generate:synthdef-compiler`.

#![allow(
    non_camel_case_types,
    unused_mut,
    unused_variables,
    clippy::useless_conversion,
    clippy::needless_update
)]

use crate::{Rate, SynthDef, UGenInput};

sc_ugens! {
    #[doc = "Read the contents of a buffer at a specified index"]
    #[doc = ""]
    #[doc = "reads the contents of a buffer at a given index."]
    BufRd class r"BufRd" {
        rates [ (ar, Audio), (kr, Control) ]
        fields [
            #[doc = "The number of channels of the supplied buffer. This must be a fixed integer and not a signal or a control proxy. The architecture of the synth design cannot change after it is compiled. (Warning: if you supply a bufnum of a buffer that has a different number of channels than you have specified to buf-rd , it will fail silently)."]
            u32 num_channels: u32 = 1u32,
            #[doc = "The index of the buffer to use"]
            input bufnum: UGenInput = UGenInput::Constant(0.0),
            #[doc = "Audio rate modulatable index into the buffer. Warning: The phase argument only offers precision for addressing 2**24 samples (about 6.3 minutes at 44100Hz)"]
            input phase: UGenInput = UGenInput::Constant(0.0),
            #[doc = "1 means true, 0 means false. This is modulatable."]
            input r#loop: UGenInput = UGenInput::Constant(1.0),
            #[doc = "1 means no interpolation, 2 is linear, 4 is cubic interpolation"]
            input interpolation: UGenInput = UGenInput::Constant(2.0),
        ]
        outputs ( from num_channels )
        push [ (input bufnum), (input phase), (input r#loop), (input interpolation) ]
    }
    #[doc = "writes to a buffer at a given index. Note, buf-wr (in difference to buf-rd) does not do multichannel expansion, because input is an array."]
    BufWr class r"BufWr" {
        rates [ (ar, Audio), (kr, Control) ]
        fields [
            #[doc = "input ugens (channelArray)"]
            array input_array: Vec<UGenInput> = Vec::new(),
            #[doc = "the index of the buffer to use"]
            input bufnum: UGenInput = UGenInput::Constant(0.0),
            #[doc = "modulatable index into the buffer (has to be audio rate)."]
            input phase: UGenInput = UGenInput::Constant(0.0),
            #[doc = "1 means true, 0 means false. This is modulatable"]
            input r#loop: UGenInput = UGenInput::Constant(1.0),
        ]
        outputs ( fixed 1 )
        push [ (input bufnum), (input phase), (input r#loop), (array input_array) ]
    }
    ClearBuf class r"ClearBuf" {
        rates [ (ir, Scalar) ]
        fields [
            input buf: UGenInput = UGenInput::Constant(0.0),
        ]
        outputs ( fixed 0 )
        push [ (input buf) ]
    }
    LocalBuf class r"LocalBuf" {
        rates [ (ir, Scalar) ]
        fields [
            u32 num_channels: u32 = 1u32,
            input num_frames: UGenInput = UGenInput::Constant(0.0),
        ]
        outputs ( from num_channels )
        push [ (input num_frames) ]
    }
    MaxLocalBufs class r"MaxLocalBufs" {
        rates [ (ir, Scalar) ]
        fields [
            input num_local_bufs: UGenInput = UGenInput::Constant(0.0),
        ]
        outputs ( fixed 1 )
        push [ (input num_local_bufs) ]
    }
    #[doc = "Plays back a sample resident in a buffer"]
    PlayBuf class r"PlayBuf" {
        rates [ (ar, Audio), (kr, Control) ]
        fields [
            #[doc = "The number of channels that the buffer will be. This must be a fixed integer. The architechture of the SynthDef cannot change after it is compiled. Warning: if you supply a bufnum of a buffer that has a different numChannels then you have specified to the play-buf, it will fail silently."]
            u32 num_channels: u32 = 1u32,
            #[doc = "The index of the buffer to use."]
            input bufnum: UGenInput = UGenInput::Constant(0.0),
            #[doc = "1.0 is the server's sample rate, 2.0 is one octave up, 0.5 is one octave down -1.0 is backwards normal rate ... etc. Interpolation is cubic. Note: if the buffer's sample rate is different from the server's, you will need to multiply the desired playback rate by (file's rate / server's rate). The UGen (buf-rate-scale bufnum) returns this factor."]
            input rate: UGenInput = UGenInput::Constant(1.0),
            #[doc = "A trigger causes a jump to the startPos. A trigger occurs when a signal changes from <= 0 to > 0."]
            input trigger: UGenInput = UGenInput::Constant(1.0),
            #[doc = "Sample frame to start playback."]
            input start_pos: UGenInput = UGenInput::Constant(0.0),
            #[doc = "1 means true, 0 means false. This is modulateable."]
            input r#loop: UGenInput = UGenInput::Constant(0.0),
            #[doc = "an integer representing an action to be executed when the buffer is finished playing. This can be used to free the enclosing synth. Action is only evaluated if loop is 0"]
            input action: UGenInput = UGenInput::Constant(0.0),
        ]
        outputs ( from num_channels )
        push [ (input bufnum), (input rate), (input trigger), (input start_pos), (input r#loop), (input action) ]
    }
    #[doc = "record a stream of values into a buffer. If recLevel is 1.0 and preLevel is 0.0 then the new input overwrites the old data. If they are both 1.0 then the new data is added to the existing data. (Any other settings are also valid.) Note that the number of channels must be fixed for the defsynth, it cannot vary depending on which buffer you use."]
    RecordBuf class r"RecordBuf" {
        rates [ (ar, Audio), (kr, Control) ]
        fields [
            #[doc = "an Array of input channels"]
            array input_array: Vec<UGenInput> = Vec::new(),
            #[doc = "the index of the buffer to use"]
            input bufnum: UGenInput = UGenInput::Constant(0.0),
            #[doc = "an offset into the buffer in frames,"]
            input offset: UGenInput = UGenInput::Constant(0.0),
            #[doc = "value to multiply by input before mixing with existing data."]
            input rec_level: UGenInput = UGenInput::Constant(1.0),
            #[doc = "value to multiply to existing data in buffer before mixing with input"]
            input pre_level: UGenInput = UGenInput::Constant(0.0),
            #[doc = "If zero, then recording stops, otherwise recording proceeds."]
            input run: UGenInput = UGenInput::Constant(1.0),
            #[doc = "If zero then don't loop, otherwise do. This is modulate-able."]
            input r#loop: UGenInput = UGenInput::Constant(1.0),
            #[doc = "a trigger causes a jump to the offset position in the Buffer. A trigger occurs when a signal changes from <= 0 to > 0."]
            input trigger: UGenInput = UGenInput::Constant(1.0),
            #[doc = "an integer representing an action to be executed when the buffer is finished playing. This can be used to free the enclosing synth. Action is only evaluated if loop is 0"]
            input action: UGenInput = UGenInput::Constant(0.0),
        ]
        outputs ( fixed 1 )
        push [ (input bufnum), (input offset), (input rec_level), (input pre_level), (input run), (input r#loop), (input trigger), (input action), (array input_array) ]
    }
    ScopeOut class r"ScopeOut" {
        rates [ (ar, Audio), (kr, Control) ]
        fields [
            array input_array: Vec<UGenInput> = Vec::new(),
            input bufnum: UGenInput = UGenInput::Constant(0.0),
        ]
        outputs ( fixed 1 )
        push [ (input bufnum), (array input_array) ]
    }
    ScopeOut2 class r"ScopeOut2" {
        rates [ (ar, Audio), (kr, Control) ]
        fields [
            array input_array: Vec<UGenInput> = Vec::new(),
            input scope_num: UGenInput = UGenInput::Constant(0.0),
            input max_frames: UGenInput = UGenInput::Constant(4096.0),
            input scope_frames: UGenInput = UGenInput::Constant(4096.0),
        ]
        outputs ( fixed 1 )
        push [ (input scope_num), (input max_frames), (input scope_frames), (array input_array) ]
    }
    SetBuf class r"SetBuf" {
        rates [ (ar, Audio), (kr, Control) ]
        fields [
            input buf: UGenInput = UGenInput::Constant(0.0),
            input values: UGenInput = UGenInput::Constant(0.0),
            input offset: UGenInput = UGenInput::Constant(0.0),
        ]
        outputs ( fixed 0 )
        push [ (input buf), (input values), (input offset) ]
    }
    #[doc = "sample playback from a buffer with fine control for doing granular synthesis. Triggers generate grains from a single channel (mono) buffer. Each grain has a Hann envelope (sin^2(x) for x from 0 to pi) and is panned between two channels of multiple outputs."]
    TGrains class r"TGrains" {
        rates [ (ar, Audio) ]
        fields [
            #[doc = "number of output channels"]
            u32 num_channels: u32 = 2u32,
            #[doc = "at each trigger, the following arguments are sampled and used as the arguments of a new grain. A trigger occurs when a signal changes from <= 0 to > 0. If the trigger is audio rate then the grains will start with sample accuracy."]
            input trigger: UGenInput = UGenInput::Constant(0.0),
            #[doc = "the index of the buffer to use. It must be a one channel (mono) buffer."]
            input bufnum: UGenInput = UGenInput::Constant(0.0),
            #[doc = "1.0 is normal, 2.0 is one octave up, 0.5 is one octave down -1.0 is backwards normal rate. Unlike PlayBuf, the rate is multiplied by BufRate, so you needn't do that yourself."]
            input rate: UGenInput = UGenInput::Constant(1.0),
            #[doc = "the position in the buffer in seconds at which the grain envelope will reach maximum amplitude."]
            input center_pos: UGenInput = UGenInput::Constant(0.0),
            #[doc = "duration of the grain in seconds"]
            input dur: UGenInput = UGenInput::Constant(0.1),
            #[doc = "a value from -1 to 1. Determines where to pan the output in the same manner as PanAz."]
            input pan: UGenInput = UGenInput::Constant(0.0),
            #[doc = "amplitude of the grain."]
            input amp: UGenInput = UGenInput::Constant(0.1),
            #[doc = "1,2,or 4. Determines whether the grain uses (1) no interpolation, (2) linear interpolation, or (4) cubic interpolation."]
            input interp: UGenInput = UGenInput::Constant(4.0),
        ]
        outputs ( from num_channels )
        push [ (input trigger), (input bufnum), (input rate), (input center_pos), (input dur), (input pan), (input amp), (input interp) ]
    }
}
