// @generated by packages/synthdef-compiler/scripts/generate-rust.ts from specs/ugens.json — do not edit.
// Regenerate with `yarn generate:synthdef-compiler`.

#![allow(
    non_camel_case_types,
    unused_mut,
    unused_variables,
    clippy::useless_conversion,
    clippy::needless_update
)]

use crate::{Rate, SynthDef, UGenInput};

sc_ugens! {
    #[doc = "a linear-interpolating (cusp map chaotic) sound generator based on the difference equation: xn+1 = a - b*sqrt(|xn|)"]
    CuspL class r"CuspL" {
        rates [ (ar, Audio) ]
        fields [
            #[doc = "iteration frequency in Hertz"]
            input freq: UGenInput = UGenInput::Constant(22050.0),
            #[doc = "first coefficient"]
            input a: UGenInput = UGenInput::Constant(1.0),
            #[doc = "2nd coefficient"]
            input b: UGenInput = UGenInput::Constant(1.9),
            #[doc = "initial value of x"]
            input xi: UGenInput = UGenInput::Constant(0.0),
        ]
        outputs ( fixed 1 )
        push [ (input freq), (input a), (input b), (input xi) ]
    }
    #[doc = "a non-interpolating (cusp map chaotic) sound generator based on the difference equation: xn+1 = a - b*sqrt(|xn|)"]
    CuspN class r"CuspN" {
        rates [ (ar, Audio) ]
        fields [
            #[doc = "iteration frequency in Hertz"]
            input freq: UGenInput = UGenInput::Constant(22050.0),
            #[doc = "first coefficient"]
            input a: UGenInput = UGenInput::Constant(1.0),
            #[doc = "2nd coefficient"]
            input b: UGenInput = UGenInput::Constant(1.9),
            #[doc = "initial value of x"]
            input xi: UGenInput = UGenInput::Constant(0.0),
        ]
        outputs ( fixed 1 )
        push [ (input freq), (input a), (input b), (input xi) ]
    }
    #[doc = "a cubic-interpolating feedback sine with chaotic phase indexing sound generator. This uses a linear congruential function to drive the phase indexing of a sine wave. For im = 1, fb = 0, and a = 1 a normal sinewave results."]
    FBSineC class r"FBSineC" {
        rates [ (ar, Audio) ]
        fields [
            #[doc = "iteration frequency in Hertz"]
            input freq: UGenInput = UGenInput::Constant(22050.0),
            #[doc = "index multiplier amount"]
            input im: UGenInput = UGenInput::Constant(1.0),
            #[doc = "feedback amount"]
            input fb: UGenInput = UGenInput::Constant(0.1),
            #[doc = "phase multiplier amount"]
            input a: UGenInput = UGenInput::Constant(1.1),
            #[doc = "phase increment amount"]
            input c: UGenInput = UGenInput::Constant(0.5),
            #[doc = "initial value of x"]
            input xi: UGenInput = UGenInput::Constant(0.1),
            #[doc = "initial value of y"]
            input yi: UGenInput = UGenInput::Constant(0.1),
        ]
        outputs ( fixed 1 )
        push [ (input freq), (input im), (input fb), (input a), (input c), (input xi), (input yi) ]
    }
    #[doc = "a linear-interpolating feedback sine with chaotic phase indexing sound generator. This uses a linear congruential function to drive the phase indexing of a sine wave. For im = 1, fb = 0, and a = 1 a normal sinewave results."]
    FBSineL class r"FBSineL" {
        rates [ (ar, Audio) ]
        fields [
            #[doc = "iteration frequency in Hertz"]
            input freq: UGenInput = UGenInput::Constant(22050.0),
            #[doc = "index multiplier amount"]
            input im: UGenInput = UGenInput::Constant(1.0),
            #[doc = "feedback amount"]
            input fb: UGenInput = UGenInput::Constant(0.1),
            #[doc = "phase multiplier amount"]
            input a: UGenInput = UGenInput::Constant(1.1),
            #[doc = "phase increment amount"]
            input c: UGenInput = UGenInput::Constant(0.5),
            #[doc = "initial value of x"]
            input xi: UGenInput = UGenInput::Constant(0.1),
            #[doc = "initial value of y"]
            input yi: UGenInput = UGenInput::Constant(0.1),
        ]
        outputs ( fixed 1 )
        push [ (input freq), (input im), (input fb), (input a), (input c), (input xi), (input yi) ]
    }
    #[doc = "a non-interpolating feedback sine with chaotic phase indexing sound generator. This uses a linear congruential function to drive the phase indexing of a sine wave. For im = 1, fb = 0, and a = 1 a normal sinewave results."]
    FBSineN class r"FBSineN" {
        rates [ (ar, Audio) ]
        fields [
            #[doc = "iteration frequency in Hertz"]
            input freq: UGenInput = UGenInput::Constant(22050.0),
            #[doc = "index multiplier amount"]
            input im: UGenInput = UGenInput::Constant(1.0),
            #[doc = "feedback amount"]
            input fb: UGenInput = UGenInput::Constant(0.1),
            #[doc = "phase multiplier amount"]
            input a: UGenInput = UGenInput::Constant(1.1),
            #[doc = "phase increment amount"]
            input c: UGenInput = UGenInput::Constant(0.5),
            #[doc = "initial value of x"]
            input xi: UGenInput = UGenInput::Constant(0.1),
            #[doc = "initial value of y"]
            input yi: UGenInput = UGenInput::Constant(0.1),
        ]
        outputs ( fixed 1 )
        push [ (input freq), (input im), (input fb), (input a), (input c), (input xi), (input yi) ]
    }
    #[doc = "A linear-interpolating (gingerbreadman map chaotic) sound generator based on the difference equations: xn+1 = 1 - yn + |xn| yn+1 = xn"]
    GbmanL class r"GbmanL" {
        rates [ (ar, Audio) ]
        fields [
            #[doc = "iteration frequency in Hz"]
            input freq: UGenInput = UGenInput::Constant(22050.0),
            #[doc = "initial value of x"]
            input xi: UGenInput = UGenInput::Constant(1.2),
            #[doc = "initial value of y"]
            input yi: UGenInput = UGenInput::Constant(2.1),
        ]
        outputs ( fixed 1 )
        push [ (input freq), (input xi), (input yi) ]
    }
    #[doc = "A non-interpolating (gingerbreadman map chaotic) sound generator based on the difference equations: xn+1 = 1 - yn + |xn| yn+1 = xn"]
    GbmanN class r"GbmanN" {
        rates [ (ar, Audio) ]
        fields [
            #[doc = "iteration frequency in Hz"]
            input freq: UGenInput = UGenInput::Constant(22050.0),
            #[doc = "initial value of x"]
            input xi: UGenInput = UGenInput::Constant(1.2),
            #[doc = "initial value of y"]
            input yi: UGenInput = UGenInput::Constant(2.1),
        ]
        outputs ( fixed 1 )
        push [ (input freq), (input xi), (input yi) ]
    }
    #[doc = "a cubic-interpolating (henon map chaotic) sound generator based on the difference equation: x[n+2] = 1 - a*(x[n+1]^)2 + bx[n]. This equation was discovered by French astronomer Michel Hénon while studying the orbits of stars in globular clusters."]
    HenonC class r"HenonC" {
        rates [ (ar, Audio) ]
        fields [
            #[doc = "iteration frequency in Hertz"]
            input freq: UGenInput = UGenInput::Constant(22050.0),
            #[doc = "1st coefficient"]
            input a: UGenInput = UGenInput::Constant(1.4),
            #[doc = "2nd coefficient"]
            input b: UGenInput = UGenInput::Constant(0.3),
            #[doc = "initial value of x"]
            input x0: UGenInput = UGenInput::Constant(0.0),
            #[doc = "second value of x"]
            input x1: UGenInput = UGenInput::Constant(0.0),
        ]
        outputs ( fixed 1 )
        push [ (input freq), (input a), (input b), (input x0), (input x1) ]
    }
    #[doc = "a linear-interpolating (henon map chaotic) sound generator based on the difference equation: x[n+2] = 1 - a*(x[n+1]^)2 + bx[n]. This equation was discovered by French astronomer Michel Hénon while studying the orbits of stars in globular clusters."]
    HenonL class r"HenonL" {
        rates [ (ar, Audio) ]
        fields [
            #[doc = "iteration frequency in Hertz"]
            input freq: UGenInput = UGenInput::Constant(22050.0),
            #[doc = "1st coefficient"]
            input a: UGenInput = UGenInput::Constant(1.4),
            #[doc = "2nd coefficient"]
            input b: UGenInput = UGenInput::Constant(0.3),
            #[doc = "initial value of x"]
            input x0: UGenInput = UGenInput::Constant(0.0),
            #[doc = "second value of x"]
            input x1: UGenInput = UGenInput::Constant(0.0),
        ]
        outputs ( fixed 1 )
        push [ (input freq), (input a), (input b), (input x0), (input x1) ]
    }
    #[doc = "a non-interpolating (henon map chaotic) sound generator based on the difference equation: x[n+2] = 1 - a*(x[n+1]^)2 + bx[n]. This equation was discovered by French astronomer Michel Hénon while studying the orbits of stars in globular clusters."]
    HenonN class r"HenonN" {
        rates [ (ar, Audio) ]
        fields [
            #[doc = "iteration frequency in Hertz"]
            input freq: UGenInput = UGenInput::Constant(22050.0),
            #[doc = "1st coefficient"]
            input a: UGenInput = UGenInput::Constant(1.4),
            #[doc = "2nd coefficient"]
            input b: UGenInput = UGenInput::Constant(0.3),
            #[doc = "initial value of x"]
            input x0: UGenInput = UGenInput::Constant(0.0),
            #[doc = "second value of x"]
            input x1: UGenInput = UGenInput::Constant(0.0),
        ]
        outputs ( fixed 1 )
        push [ (input freq), (input a), (input b), (input x0), (input x1) ]
    }
    #[doc = "a cubic-interpolating (latoocarfian chaotic) sound generator. Parameters a and b should be in the range from -3 to +3, and parameters c and d should be in the range from 0.5 to 1.5. The function can, depending on the parameters given, give continuous chaotic output, converge to a single value (silence) or oscillate in a cycle (tone)."]
    LatoocarfianC class r"LatoocarfianC" {
        rates [ (ar, Audio) ]
        fields [
            #[doc = "iteration frequency in Hertz"]
            input freq: UGenInput = UGenInput::Constant(22050.0),
            #[doc = "1st coefficient"]
            input a: UGenInput = UGenInput::Constant(1.0),
            #[doc = "2nd coefficient"]
            input b: UGenInput = UGenInput::Constant(3.0),
            #[doc = "3rd coefficient"]
            input c: UGenInput = UGenInput::Constant(0.5),
            #[doc = "4th coefficient"]
            input d: UGenInput = UGenInput::Constant(0.5),
            #[doc = "initial value of x"]
            input xi: UGenInput = UGenInput::Constant(0.5),
            #[doc = "initial value of y"]
            input yi: UGenInput = UGenInput::Constant(0.5),
        ]
        outputs ( fixed 1 )
        push [ (input freq), (input a), (input b), (input c), (input d), (input xi), (input yi) ]
    }
    #[doc = "a linear-interpolating (latoocarfian chaotic) sound generator. Parameters a and b should be in the range from -3 to +3, and parameters c and d should be in the range from 0.5 to 1.5. The function can, depending on the parameters given, give continuous chaotic output, converge to a single value (silence) or oscillate in a cycle (tone)."]
    LatoocarfianL class r"LatoocarfianL" {
        rates [ (ar, Audio) ]
        fields [
            #[doc = "iteration frequency in Hertz"]
            input freq: UGenInput = UGenInput::Constant(22050.0),
            #[doc = "1st coefficient"]
            input a: UGenInput = UGenInput::Constant(1.0),
            #[doc = "2nd coefficient"]
            input b: UGenInput = UGenInput::Constant(3.0),
            #[doc = "3rd coefficient"]
            input c: UGenInput = UGenInput::Constant(0.5),
            #[doc = "4th coefficient"]
            input d: UGenInput = UGenInput::Constant(0.5),
            #[doc = "initial value of x"]
            input xi: UGenInput = UGenInput::Constant(0.5),
            #[doc = "initial value of y"]
            input yi: UGenInput = UGenInput::Constant(0.5),
        ]
        outputs ( fixed 1 )
        push [ (input freq), (input a), (input b), (input c), (input d), (input xi), (input yi) ]
    }
    #[doc = "a non-interpolating (latoocarfian chaotic) sound generator. Parameters a and b should be in the range from -3 to +3, and parameters c and d should be in the range from 0.5 to 1.5. The function can, depending on the parameters given, give continuous chaotic output, converge to a single value (silence) or oscillate in a cycle (tone)."]
    LatoocarfianN class r"LatoocarfianN" {
        rates [ (ar, Audio) ]
        fields [
            #[doc = "iteration frequency in Hertz"]
            input freq: UGenInput = UGenInput::Constant(22050.0),
            #[doc = "1st coefficient"]
            input a: UGenInput = UGenInput::Constant(1.0),
            #[doc = "2nd coefficient"]
            input b: UGenInput = UGenInput::Constant(3.0),
            #[doc = "3rd coefficient"]
            input c: UGenInput = UGenInput::Constant(0.5),
            #[doc = "4th coefficient"]
            input d: UGenInput = UGenInput::Constant(0.5),
            #[doc = "initial value of x"]
            input xi: UGenInput = UGenInput::Constant(0.5),
            #[doc = "initial value of y"]
            input yi: UGenInput = UGenInput::Constant(0.5),
        ]
        outputs ( fixed 1 )
        push [ (input freq), (input a), (input b), (input c), (input d), (input xi), (input yi) ]
    }
    #[doc = "a cubic-interpolating (linear congruential chaotic) sound generator. The output signal is automatically scaled to a range of [-1, 1]."]
    LinCongC class r"LinCongC" {
        rates [ (ar, Audio) ]
        fields [
            #[doc = "iteration frequency in Hertz."]
            input freq: UGenInput = UGenInput::Constant(22050.0),
            #[doc = "multiplier amount"]
            input a: UGenInput = UGenInput::Constant(1.1),
            #[doc = "increment amount"]
            input c: UGenInput = UGenInput::Constant(0.13),
            #[doc = "modulus amount"]
            input m: UGenInput = UGenInput::Constant(1.0),
            #[doc = "initial value of x"]
            input xi: UGenInput = UGenInput::Constant(0.0),
        ]
        outputs ( fixed 1 )
        push [ (input freq), (input a), (input c), (input m), (input xi) ]
    }
    #[doc = "a linear-interpolating (linear congruential chaotic) sound generator. The output signal is automatically scaled to a range of [-1, 1]."]
    LinCongL class r"LinCongL" {
        rates [ (ar, Audio) ]
        fields [
            #[doc = "iteration frequency in Hertz."]
            input freq: UGenInput = UGenInput::Constant(22050.0),
            #[doc = "multiplier amount"]
            input a: UGenInput = UGenInput::Constant(1.1),
            #[doc = "increment amount"]
            input c: UGenInput = UGenInput::Constant(0.13),
            #[doc = "modulus amount"]
            input m: UGenInput = UGenInput::Constant(1.0),
            #[doc = "initial value of x"]
            input xi: UGenInput = UGenInput::Constant(0.0),
        ]
        outputs ( fixed 1 )
        push [ (input freq), (input a), (input c), (input m), (input xi) ]
    }
    #[doc = "a non-interpolating (linear congruential chaotic) sound generator. The output signal is automatically scaled to a range of [-1, 1]."]
    LinCongN class r"LinCongN" {
        rates [ (ar, Audio) ]
        fields [
            #[doc = "iteration frequency in Hertz."]
            input freq: UGenInput = UGenInput::Constant(22050.0),
            #[doc = "multiplier amount"]
            input a: UGenInput = UGenInput::Constant(1.1),
            #[doc = "increment amount"]
            input c: UGenInput = UGenInput::Constant(0.13),
            #[doc = "modulus amount"]
            input m: UGenInput = UGenInput::Constant(1.0),
            #[doc = "initial value of x"]
            input xi: UGenInput = UGenInput::Constant(0.0),
        ]
        outputs ( fixed 1 )
        push [ (input freq), (input a), (input c), (input m), (input xi) ]
    }
    #[doc = "lorenz chaotic generator. A strange attractor discovered by Edward N. Lorenz while studying mathematical models of the atmosphere. The time step amount h determines the rate at which the ODE is evaluated. Higher values will increase the rate, but cause more instability. A safe choice is the default amount of 0.05."]
    LorenzL class r"LorenzL" {
        rates [ (ar, Audio) ]
        fields [
            #[doc = "iteration frequency in Hertz"]
            input freq: UGenInput = UGenInput::Constant(22050.0),
            #[doc = "1st variable"]
            input s: UGenInput = UGenInput::Constant(10.0),
            #[doc = "2nd variable"]
            input r: UGenInput = UGenInput::Constant(28.0),
            #[doc = "3rd variable"]
            input b: UGenInput = UGenInput::Constant(2.667),
            #[doc = "integration time stamp"]
            input h: UGenInput = UGenInput::Constant(0.05),
            #[doc = "initial value of x"]
            input xi: UGenInput = UGenInput::Constant(0.1),
            #[doc = "initial value of y"]
            input yi: UGenInput = UGenInput::Constant(0.0),
            #[doc = "initial value of z"]
            input zi: UGenInput = UGenInput::Constant(0.0),
        ]
        outputs ( fixed 1 )
        push [ (input freq), (input s), (input r), (input b), (input h), (input xi), (input yi), (input zi) ]
    }
    #[doc = "a cubic-interpolating (general quadratic map chaotic) sound generator based on the difference equation: xn+1 = axn2 + bxn + c"]
    QuadC class r"QuadC" {
        rates [ (ar, Audio) ]
        fields [
            #[doc = "iteration frequency in Hertz"]
            input freq: UGenInput = UGenInput::Constant(22050.0),
            #[doc = "1st coefficient"]
            input a: UGenInput = UGenInput::Constant(1.0),
            #[doc = "2nd coefficient"]
            input b: UGenInput = UGenInput::Constant(-1.0),
            #[doc = "3rd coefficient"]
            input c: UGenInput = UGenInput::Constant(-0.75),
            #[doc = "initial value of x"]
            input xi: UGenInput = UGenInput::Constant(0.0),
        ]
        outputs ( fixed 1 )
        push [ (input freq), (input a), (input b), (input c), (input xi) ]
    }
    #[doc = "a linear-interpolating (general quadratic map chaotic) sound generator based on the difference equation: xn+1 = axn2 + bxn + c"]
    QuadL class r"QuadL" {
        rates [ (ar, Audio) ]
        fields [
            #[doc = "iteration frequency in Hertz"]
            input freq: UGenInput = UGenInput::Constant(22050.0),
            #[doc = "1st coefficient"]
            input a: UGenInput = UGenInput::Constant(1.0),
            #[doc = "2nd coefficient"]
            input b: UGenInput = UGenInput::Constant(-1.0),
            #[doc = "3rd coefficient"]
            input c: UGenInput = UGenInput::Constant(-0.75),
            #[doc = "initial value of x"]
            input xi: UGenInput = UGenInput::Constant(0.0),
        ]
        outputs ( fixed 1 )
        push [ (input freq), (input a), (input b), (input c), (input xi) ]
    }
    #[doc = "a non-interpolating (general quadratic map chaotic) sound generator based on the difference equation: xn+1 = axn2 + bxn + c"]
    QuadN class r"QuadN" {
        rates [ (ar, Audio) ]
        fields [
            #[doc = "iteration frequency in Hertz"]
            input freq: UGenInput = UGenInput::Constant(22050.0),
            #[doc = "1st coefficient"]
            input a: UGenInput = UGenInput::Constant(1.0),
            #[doc = "2nd coefficient"]
            input b: UGenInput = UGenInput::Constant(-1.0),
            #[doc = "3rd coefficient"]
            input c: UGenInput = UGenInput::Constant(-0.75),
            #[doc = "initial value of x"]
            input xi: UGenInput = UGenInput::Constant(0.0),
        ]
        outputs ( fixed 1 )
        push [ (input freq), (input a), (input b), (input c), (input xi) ]
    }
    #[doc = "linear-interpolating standard map chaotic generator. The standard map is an area preserving map of a cylinder discovered by the plasma physicist Boris Chirikov."]
    StandardL class r"StandardL" {
        rates [ (ar, Audio) ]
        fields [
            #[doc = "iteration frequency in Hertz"]
            input freq: UGenInput = UGenInput::Constant(22050.0),
            #[doc = "perturbation amount"]
            input k: UGenInput = UGenInput::Constant(1.0),
            #[doc = "initial value of x"]
            input xi: UGenInput = UGenInput::Constant(0.5),
            #[doc = "initial value of y"]
            input yi: UGenInput = UGenInput::Constant(0.0),
        ]
        outputs ( fixed 1 )
        push [ (input freq), (input k), (input xi), (input yi) ]
    }
    #[doc = "standard map chaotic generator. The standard map is an area preserving map of a cylinder discovered by the plasma physicist Boris Chirikov."]
    StandardN class r"StandardN" {
        rates [ (ar, Audio) ]
        fields [
            #[doc = "iteration frequency in Hertz"]
            input freq: UGenInput = UGenInput::Constant(22050.0),
            #[doc = "perturbation amount"]
            input k: UGenInput = UGenInput::Constant(1.0),
            #[doc = "initial value of x"]
            input xi: UGenInput = UGenInput::Constant(0.5),
            #[doc = "initial value of y"]
            input yi: UGenInput = UGenInput::Constant(0.0),
        ]
        outputs ( fixed 1 )
        push [ (input freq), (input k), (input xi), (input yi) ]
    }
}
