// @generated by packages/synthdef-compiler/scripts/generate-rust.ts from specs/ugens.json — do not edit.
// Regenerate with `yarn generate:synthdef-compiler`.

#![allow(
    non_camel_case_types,
    unused_mut,
    unused_variables,
    clippy::useless_conversion,
    clippy::needless_update
)]

use crate::{Rate, SynthDef, UGenInput};

sc_ugens! {
    #[doc = "all pass delay line, cubic interpolation"]
    AllpassC class r"AllpassC" {
        rates [ (ar, Audio), (kr, Control) ]
        fields [
            #[doc = "the input signal"]
            input r#in: UGenInput = UGenInput::Constant(0.0),
            #[doc = "the maximum delay time in seconds. Used to initialize the delay buffer size"]
            input max_delay_time: UGenInput = UGenInput::Constant(0.2),
            #[doc = "delay time in seconds"]
            input delay_time: UGenInput = UGenInput::Constant(0.2),
            #[doc = "time for the echoes to decay by 60 decibels. If this time is negative then the feedback coefficient will be negative, thus emphasizing only odd harmonics at an octave lower."]
            input decay_time: UGenInput = UGenInput::Constant(1.0),
        ]
        outputs ( fixed 1 )
        push [ (input r#in), (input max_delay_time), (input delay_time), (input decay_time) ]
    }
    #[doc = "all pass delay line, linear interpolation"]
    AllpassL class r"AllpassL" {
        rates [ (ar, Audio), (kr, Control) ]
        fields [
            #[doc = "the input signal"]
            input r#in: UGenInput = UGenInput::Constant(0.0),
            #[doc = "the maximum delay time in seconds. Used to initialize the delay buffer size"]
            input max_delay_time: UGenInput = UGenInput::Constant(0.2),
            #[doc = "delay time in seconds"]
            input delay_time: UGenInput = UGenInput::Constant(0.2),
            #[doc = "time for the echoes to decay by 60 decibels. If this time is negative then the feedback coefficient will be negative, thus emphasizing only odd harmonics at an octave lower."]
            input decay_time: UGenInput = UGenInput::Constant(1.0),
        ]
        outputs ( fixed 1 )
        push [ (input r#in), (input max_delay_time), (input delay_time), (input decay_time) ]
    }
    #[doc = "all pass delay line, no interpolation. See also AllpassC which uses cubic interpolation, and AllpassL which uses linear interpolation. Cubic interpolation is more computationally expensive than linear, but more accurate."]
    AllpassN class r"AllpassN" {
        rates [ (ar, Audio), (kr, Control) ]
        fields [
            #[doc = "the input signal"]
            input r#in: UGenInput = UGenInput::Constant(0.0),
            #[doc = "the maximum delay time in seconds. Used to initialize the delay buffer size"]
            input max_delay_time: UGenInput = UGenInput::Constant(0.2),
            #[doc = "delay time in seconds"]
            input delay_time: UGenInput = UGenInput::Constant(0.2),
            #[doc = "time for the echoes to decay by 60 decibels. If this time is negative then the feedback coefficient will be negative, thus emphasizing only odd harmonics at an octave lower."]
            input decay_time: UGenInput = UGenInput::Constant(1.0),
        ]
        outputs ( fixed 1 )
        push [ (input r#in), (input max_delay_time), (input delay_time), (input decay_time) ]
    }
    #[doc = "buffer based all pass delay line with cubic interpolation"]
    BufAllpassC class r"BufAllpassC" {
        rates [ (ar, Audio) ]
        fields [
            #[doc = "buffer number"]
            input buf: UGenInput = UGenInput::Constant(0.0),
            #[doc = "the input signal"]
            input r#in: UGenInput = UGenInput::Constant(0.0),
            #[doc = "delay time in seconds"]
            input delay_time: UGenInput = UGenInput::Constant(0.2),
            #[doc = "time for the echoes to decay by 60 decibels. If this time is negative then the feedback coefficient will be negative, thus emphasizing only odd harmonics at an octave lower."]
            input decay_time: UGenInput = UGenInput::Constant(1.0),
        ]
        outputs ( fixed 1 )
        push [ (input buf), (input r#in), (input delay_time), (input decay_time) ]
    }
    #[doc = "buffer based all pass delay line with linear interpolation"]
    BufAllpassL class r"BufAllpassL" {
        rates [ (ar, Audio) ]
        fields [
            #[doc = "buffer number"]
            input buf: UGenInput = UGenInput::Constant(0.0),
            #[doc = "the input signal"]
            input r#in: UGenInput = UGenInput::Constant(0.0),
            #[doc = "delay time in seconds"]
            input delay_time: UGenInput = UGenInput::Constant(0.2),
            #[doc = "time for the echoes to decay by 60 decibels. If this time is negative then the feedback coefficient will be negative, thus emphasizing only odd harmonics at an octave lower."]
            input decay_time: UGenInput = UGenInput::Constant(1.0),
        ]
        outputs ( fixed 1 )
        push [ (input buf), (input r#in), (input delay_time), (input decay_time) ]
    }
    #[doc = "buffer based all pass delay line with no interpolation. See also BufAllpassC which uses cubic interpolation, and BufAllpassL which uses linear interpolation. Cubic interpolation is more computationally expensive than linear, but more accurate."]
    BufAllpassN class r"BufAllpassN" {
        rates [ (ar, Audio) ]
        fields [
            #[doc = "buffer number"]
            input buf: UGenInput = UGenInput::Constant(0.0),
            #[doc = "the input signal"]
            input r#in: UGenInput = UGenInput::Constant(0.0),
            #[doc = "delay time in seconds"]
            input delay_time: UGenInput = UGenInput::Constant(0.2),
            #[doc = "time for the echoes to decay by 60 decibels. If this time is negative then the feedback coefficient will be negative, thus emphasizing only odd harmonics at an octave lower."]
            input decay_time: UGenInput = UGenInput::Constant(1.0),
        ]
        outputs ( fixed 1 )
        push [ (input buf), (input r#in), (input delay_time), (input decay_time) ]
    }
    #[doc = "buffer based comb delay line with cubic interpolation"]
    BufCombC class r"BufCombC" {
        rates [ (ar, Audio) ]
        fields [
            #[doc = "buffer number"]
            input buf: UGenInput = UGenInput::Constant(0.0),
            #[doc = "the input signal"]
            input r#in: UGenInput = UGenInput::Constant(0.0),
            #[doc = "delay time in seconds"]
            input delay_time: UGenInput = UGenInput::Constant(0.2),
            #[doc = "time for the echoes to decay by 60 decibels. If this time is negative then the feedback coefficient will be negative, thus emphasizing only odd harmonics at an octave lower."]
            input decay_time: UGenInput = UGenInput::Constant(1.0),
        ]
        outputs ( fixed 1 )
        push [ (input buf), (input r#in), (input delay_time), (input decay_time) ]
    }
    #[doc = "buffer based comb delay line with linear interpolation"]
    BufCombL class r"BufCombL" {
        rates [ (ar, Audio) ]
        fields [
            #[doc = "buffer number"]
            input buf: UGenInput = UGenInput::Constant(0.0),
            #[doc = "the input signal"]
            input r#in: UGenInput = UGenInput::Constant(0.0),
            #[doc = "delay time in seconds"]
            input delay_time: UGenInput = UGenInput::Constant(0.2),
            #[doc = "time for the echoes to decay by 60 decibels. If this time is negative then the feedback coefficient will be negative, thus emphasizing only odd harmonics at an octave lower."]
            input decay_time: UGenInput = UGenInput::Constant(1.0),
        ]
        outputs ( fixed 1 )
        push [ (input buf), (input r#in), (input delay_time), (input decay_time) ]
    }
    #[doc = "buffer based comb delay line with no interpolation. See also [BufCombL] which uses linear interpolation, and BufCombC which uses cubic interpolation. Cubic interpolation is more computationally expensive than linear, but more accurate."]
    BufCombN class r"BufCombN" {
        rates [ (ar, Audio) ]
        fields [
            #[doc = "buffer number"]
            input buf: UGenInput = UGenInput::Constant(0.0),
            #[doc = "the input signal"]
            input r#in: UGenInput = UGenInput::Constant(0.0),
            #[doc = "delay time in seconds"]
            input delay_time: UGenInput = UGenInput::Constant(0.2),
            #[doc = "time for the echoes to decay by 60 decibels. If this time is negative then the feedback coefficient will be negative, thus emphasizing only odd harmonics at an octave lower."]
            input decay_time: UGenInput = UGenInput::Constant(1.0),
        ]
        outputs ( fixed 1 )
        push [ (input buf), (input r#in), (input delay_time), (input decay_time) ]
    }
    #[doc = "buffer based simple delay line with cubic interpolation"]
    BufDelayC class r"BufDelayC" {
        rates [ (ar, Audio), (kr, Control) ]
        fields [
            #[doc = "buffer number"]
            input buf: UGenInput = UGenInput::Constant(0.0),
            #[doc = "the input signal"]
            input r#in: UGenInput = UGenInput::Constant(0.0),
            #[doc = "delay time in seconds"]
            input delay_time: UGenInput = UGenInput::Constant(0.2),
        ]
        outputs ( fixed 1 )
        push [ (input buf), (input r#in), (input delay_time) ]
    }
    #[doc = "buffer based simple delay line with linear interpolation"]
    BufDelayL class r"BufDelayL" {
        rates [ (ar, Audio), (kr, Control) ]
        fields [
            #[doc = "buffer number"]
            input buf: UGenInput = UGenInput::Constant(0.0),
            #[doc = "the input signal"]
            input r#in: UGenInput = UGenInput::Constant(0.0),
            #[doc = "delay time in seconds"]
            input delay_time: UGenInput = UGenInput::Constant(0.2),
        ]
        outputs ( fixed 1 )
        push [ (input buf), (input r#in), (input delay_time) ]
    }
    #[doc = "buffer based simple delay line with no interpolation. See also BufDelayL which uses linear interpolation, and BufDelayC which uses cubic interpolation. Cubic interpolation is more computationally expensive than linear, but more accurate."]
    BufDelayN class r"BufDelayN" {
        rates [ (ar, Audio), (kr, Control) ]
        fields [
            #[doc = "buffer number"]
            input buf: UGenInput = UGenInput::Constant(0.0),
            #[doc = "the input signal"]
            input r#in: UGenInput = UGenInput::Constant(0.0),
            #[doc = "delay time in seconds"]
            input delay_time: UGenInput = UGenInput::Constant(0.2),
        ]
        outputs ( fixed 1 )
        push [ (input buf), (input r#in), (input delay_time) ]
    }
    #[doc = "comb delay line, cubic interpolation"]
    CombC class r"CombC" {
        rates [ (ar, Audio), (kr, Control) ]
        fields [
            #[doc = "the input signal"]
            input r#in: UGenInput = UGenInput::Constant(0.0),
            #[doc = "the maximum delay time in seconds. Used to initialize the delay buffer size"]
            input max_delay_time: UGenInput = UGenInput::Constant(0.2),
            #[doc = "delay time in seconds"]
            input delay_time: UGenInput = UGenInput::Constant(0.2),
            #[doc = "time for the echoes to decay by 60 decibels. If this time is negative then the feedback coefficient will be negative, thus emphasizing only odd harmonics at an octave lower."]
            input decay_time: UGenInput = UGenInput::Constant(1.0),
        ]
        outputs ( fixed 1 )
        push [ (input r#in), (input max_delay_time), (input delay_time), (input decay_time) ]
    }
    #[doc = "comb delay line, linear interpolation"]
    CombL class r"CombL" {
        rates [ (ar, Audio), (kr, Control) ]
        fields [
            #[doc = "the input signal"]
            input r#in: UGenInput = UGenInput::Constant(0.0),
            #[doc = "the maximum delay time in seconds. Used to initialize the delay buffer size"]
            input max_delay_time: UGenInput = UGenInput::Constant(0.2),
            #[doc = "delay time in seconds"]
            input delay_time: UGenInput = UGenInput::Constant(0.2),
            #[doc = "time for the echoes to decay by 60 decibels. If this time is negative then the feedback coefficient will be negative, thus emphasizing only odd harmonics at an octave lower."]
            input decay_time: UGenInput = UGenInput::Constant(1.0),
        ]
        outputs ( fixed 1 )
        push [ (input r#in), (input max_delay_time), (input delay_time), (input decay_time) ]
    }
    #[doc = "comb delay line, no interpolation. See also CombL which uses linear interpolation, and CombC which uses cubic interpolation. Cubic interpolation is more computationally expensive than linear, but more accurate."]
    CombN class r"CombN" {
        rates [ (ar, Audio), (kr, Control) ]
        fields [
            #[doc = "the input signal"]
            input r#in: UGenInput = UGenInput::Constant(0.0),
            #[doc = "the maximum delay time in seconds. Used to initialize the delay buffer size"]
            input max_delay_time: UGenInput = UGenInput::Constant(0.2),
            #[doc = "delay time in seconds"]
            input delay_time: UGenInput = UGenInput::Constant(0.2),
            #[doc = "time for the echoes to decay by 60 decibels. If this time is negative then the feedback coefficient will be negative, thus emphasizing only odd harmonics at an octave lower."]
            input decay_time: UGenInput = UGenInput::Constant(1.0),
        ]
        outputs ( fixed 1 )
        push [ (input r#in), (input max_delay_time), (input delay_time), (input decay_time) ]
    }
    #[doc = "Tap a delay line from a del-tap-wr UGen"]
    DelTapRd class r"DelTapRd" {
        rates [ (ar, Audio), (kr, Control) ]
        fields [
            #[doc = "buffer where del-tap-wr has written signal. Max delay time is based on buffer size."]
            input buffer: UGenInput = UGenInput::Constant(0.0),
            #[doc = "the current phase of the del-tap-wr UGen. This is the output of DelTapWr."]
            input phase: UGenInput = UGenInput::Constant(0.0),
            #[doc = "A delay time in seconds."]
            input delay: UGenInput = UGenInput::Constant(0.0),
            #[doc = "the kind of interpolation to be used. 1 is none, 2 is linear, 4 is cubic."]
            input interp: UGenInput = UGenInput::Constant(1.0),
        ]
        outputs ( fixed 1 )
        push [ (input buffer), (input phase), (input delay), (input interp) ]
    }
    #[doc = "Tap a delay line from a del-tap-wr UGen"]
    DelTapWr class r"DelTapWr" {
        rates [ (ar, Audio), (kr, Control) ]
        fields [
            #[doc = "the buffer to write signal into. Max delay time is based on buffer size."]
            input buffer: UGenInput = UGenInput::Constant(0.0),
            #[doc = "the signal to write to the buffer."]
            input r#in: UGenInput = UGenInput::Constant(0.0),
        ]
        outputs ( fixed 1 )
        push [ (input buffer), (input r#in) ]
    }
    #[doc = "delay input signal by one frame of samples. Note: for audio-rate signals the delay is 1 audio frame, and for control-rate signals the delay is 1 control period."]
    Delay1 class r"Delay1" {
        rates [ (ar, Audio), (kr, Control) ]
        fields [
            #[doc = "input to be delayed."]
            input r#in: UGenInput = UGenInput::Constant(0.0),
        ]
        outputs ( fixed 1 )
        push [ (input r#in) ]
    }
    #[doc = "delay input signal by two frames of samples"]
    Delay2 class r"Delay2" {
        rates [ (ar, Audio), (kr, Control) ]
        fields [
            #[doc = "input to be delayed."]
            input r#in: UGenInput = UGenInput::Constant(0.0),
        ]
        outputs ( fixed 1 )
        push [ (input r#in) ]
    }
    #[doc = "simple delay line, cubic interpolation."]
    DelayC class r"DelayC" {
        rates [ (ar, Audio), (kr, Control) ]
        fields [
            #[doc = "the input signal"]
            input r#in: UGenInput = UGenInput::Constant(0.0),
            #[doc = "the maximum delay time in seconds. Used to initialize the delay buffer size"]
            input max_delay_time: UGenInput = UGenInput::Constant(0.2),
            #[doc = "delay time in seconds"]
            input delay_time: UGenInput = UGenInput::Constant(0.2),
        ]
        outputs ( fixed 1 )
        push [ (input r#in), (input max_delay_time), (input delay_time) ]
    }
    #[doc = "simple delay line, linear interpolation."]
    DelayL class r"DelayL" {
        rates [ (ar, Audio), (kr, Control) ]
        fields [
            #[doc = "the input signal"]
            input r#in: UGenInput = UGenInput::Constant(0.0),
            #[doc = "the maximum delay time in seconds. Used to initialize the delay buffer size"]
            input max_delay_time: UGenInput = UGenInput::Constant(0.2),
            #[doc = "delay time in seconds"]
            input delay_time: UGenInput = UGenInput::Constant(0.2),
        ]
        outputs ( fixed 1 )
        push [ (input r#in), (input max_delay_time), (input delay_time) ]
    }
    #[doc = "simple delay line, no interpolation. See also DelayL which uses linear interpolation, and DelayC which uses cubic interpolation. Cubic interpolation is more computationally expensive than linear, but more accurate."]
    DelayN class r"DelayN" {
        rates [ (ar, Audio), (kr, Control) ]
        fields [
            #[doc = "the input signal"]
            input r#in: UGenInput = UGenInput::Constant(0.0),
            #[doc = "the maximum delay time in seconds. Used to initialize the delay buffer size"]
            input max_delay_time: UGenInput = UGenInput::Constant(0.2),
            #[doc = "delay time in seconds"]
            input delay_time: UGenInput = UGenInput::Constant(0.2),
        ]
        outputs ( fixed 1 )
        push [ (input r#in), (input max_delay_time), (input delay_time) ]
    }
}
