// @generated by packages/synthdef-compiler/scripts/generate-rust.ts from specs/ugens.json — do not edit.
// Regenerate with `yarn generate:synthdef-compiler`.

#![allow(
    non_camel_case_types,
    unused_mut,
    unused_variables,
    clippy::useless_conversion,
    clippy::needless_update
)]

use crate::{Rate, SynthDef, UGenInput};

sc_ugens! {
    #[doc = "fast fourier transform, converts input data from the time to the frequency domain and stores the result in a buffer (audio waveform -> graph equalizer bands) Output is -1 except when an FFT frame is ready, when the output is the buffer index. This creates a special kind of slower pseudo-rate (built on top of control rate) which all the pv-ugens understand."]
    FFT class r"FFT" {
        rates [ (kr, Control) ]
        fields [
            #[doc = "The buffer where a frame will be held. Its size must be a power of two. local-buf is useful here, because processes should not share data between synths. (Note: most PV UGens operate on this data in place. Use buffer-2n if you wish to create an external buffer."]
            input buffer: UGenInput = UGenInput::Constant(0.0),
            #[doc = "the signal to be analyzed. The signal's rate determines the rate at which the input is read."]
            input r#in: UGenInput = UGenInput::Constant(0.0),
            #[doc = "the amount of offset from one FFT analysis frame to the next, measured in multiples of the analysis frame size. This can range between zero and one, and the default is 0.5 (meaning each frame has a 50% overlap with the preceding/following frames)."]
            input hop: UGenInput = UGenInput::Constant(0.5),
            #[doc = "defines how the data is windowed: RECT is for rectangular windowing, simple but typically not recommended; SINE (the default) is for Sine windowing, typically recommended for phase-vocoder work; HANN is for Hann windowing, typically recommended for analysis work."]
            input wintype: UGenInput = UGenInput::Constant(0.0),
            #[doc = "is a simple control allowing FFT analysis to be active (>0) or inactive (<=0). This is mainly useful for signal analysis processes which are only intended to analyse at specific times rather than continuously"]
            input active: UGenInput = UGenInput::Constant(1.0),
            #[doc = "the windowed audio frames are usually the same size as the buffer. If you wish the FFT to be zero-padded then you can specify a window size smaller than the actual buffer size (e.g. window size 1024 with buffer size 2048). Both values must still be a power of two. Leave this at its default of zero for no zero-padding."]
            input winsize: UGenInput = UGenInput::Constant(0.0),
        ]
        outputs ( fixed 1 )
        push [ (input buffer), (input r#in), (input hop), (input wintype), (input active), (input winsize) ]
    }
    #[doc = "Outputs the necessary signal for FFT chains, without doing an FFT on a signal"]
    FFTTrigger class r"FFTTrigger" {
        rates [ (kr, Control) ]
        fields [
            #[doc = "a buffer to condition for FFT use"]
            input buffer: UGenInput = UGenInput::Constant(0.0),
            #[doc = "the hop size for timing triggers"]
            input hop: UGenInput = UGenInput::Constant(0.5),
            #[doc = "a flag. If 0.0, the buffer will be prepared for complex data, if > 0.0, polar data is set up."]
            input polar: UGenInput = UGenInput::Constant(0.0),
        ]
        outputs ( fixed 1 )
        push [ (input buffer), (input hop), (input polar) ]
    }
    #[doc = "inverse fast fourier transform, converts buffer data from frequency domain to time domain The IFFT UGen converts the FFT data in-place (in the original FFT buffer) and overlap-adds the result to produce a continuous signal at its output."]
    IFFT class r"IFFT" {
        rates [ (ar, Audio), (kr, Control) ]
        fields [
            #[doc = "The FFT chain signal coming originally from an FFT UGen, perhaps via other PV UGens."]
            input chain: UGenInput = UGenInput::Constant(0.0),
            #[doc = "defines how the data is windowed: RECT is for rectangular windowing, simple but typically not recommended; SINE (the default) is for Sine windowing, typically recommended for phase-vocoder work; HANN is for Hann windowing, typically recommended for analysis work."]
            input wintype: UGenInput = UGenInput::Constant(0.0),
            #[doc = "can be used to account for zero-padding, in the same way as the FFT UGen."]
            input winsize: UGenInput = UGenInput::Constant(0.0),
        ]
        outputs ( fixed 1 )
        push [ (input chain), (input wintype), (input winsize) ]
    }
    #[doc = "complex addition: RealA + RealB, ImagA + ImagB"]
    PV_Add class r"PV_Add" {
        rates [ (kr, Control) ]
        fields [
            #[doc = "fft buffer A"]
            input buffer_a: UGenInput = UGenInput::Constant(0.0),
            #[doc = "fft buffer B"]
            input buffer_b: UGenInput = UGenInput::Constant(0.0),
        ]
        outputs ( fixed 1 )
        push [ (input buffer_a), (input buffer_b) ]
    }
    #[doc = "randomizes the order of the bins. The trigger will select a new random ordering."]
    PV_BinScramble class r"PV_BinScramble" {
        rates [ (kr, Control) ]
        fields [
            #[doc = "fft buffer"]
            input buffer: UGenInput = UGenInput::Constant(0.0),
            #[doc = "scrambles more bins as wipe moves from zero to one."]
            input wipe: UGenInput = UGenInput::Constant(0.0),
            #[doc = "a value from zero to one, indicating the maximum randomized distance of a bin from its original location in the spectrum."]
            input width: UGenInput = UGenInput::Constant(0.2),
            #[doc = "a trigger selects a new random ordering."]
            input trig: UGenInput = UGenInput::Constant(0.0),
        ]
        outputs ( fixed 1 )
        push [ (input buffer), (input wipe), (input width), (input trig) ]
    }
    #[doc = "shift and scale the positions of the bins. Can be used as a very crude frequency shifter/scaler."]
    PV_BinShift class r"PV_BinShift" {
        rates [ (kr, Control) ]
        fields [
            #[doc = "fft buffer."]
            input buffer: UGenInput = UGenInput::Constant(0.0),
            #[doc = "scale bin location by factor."]
            input stretch: UGenInput = UGenInput::Constant(1.0),
            #[doc = "add an offset to bin position."]
            input shift: UGenInput = UGenInput::Constant(0.0),
        ]
        outputs ( fixed 1 )
        push [ (input buffer), (input stretch), (input shift) ]
    }
    #[doc = "copies low bins from one input and the high bins of the other"]
    PV_BinWipe class r"PV_BinWipe" {
        rates [ (kr, Control) ]
        fields [
            #[doc = "fft buffer A"]
            input buffer_a: UGenInput = UGenInput::Constant(0.0),
            #[doc = "fft buffer B"]
            input buffer_b: UGenInput = UGenInput::Constant(0.0),
            #[doc = "can range between -1 and +1; if wipe == 0 then the output is the same as inA; if wipe > 0 then it begins replacing with bins from inB from the bottom up;if wipe < 0 then it begins replacing with bins from inB from the top down."]
            input wipe: UGenInput = UGenInput::Constant(0.0),
        ]
        outputs ( fixed 1 )
        push [ (input buffer_a), (input buffer_b), (input wipe) ]
    }
    #[doc = "clears bins above or below a cutoff point"]
    PV_BrickWall class r"PV_BrickWall" {
        rates [ (kr, Control) ]
        fields [
            #[doc = "fft buffer"]
            input buffer: UGenInput = UGenInput::Constant(0.0),
            #[doc = "can range between -1 and +1. if wipe == 0 then there is no effect; if wipe > 0 then it acts like a high pass filter, clearing bins from the bottom up; if wipe < 0 then it acts like a low pass filter, clearing bins from the top down."]
            input wipe: UGenInput = UGenInput::Constant(0.0),
        ]
        outputs ( fixed 1 )
        push [ (input buffer), (input wipe) ]
    }
    #[doc = "converts the FFT frames to their complex conjugate (i.e. reverses the sign of their imaginary part). This is not usually a useful audio effect in itself, but may be a component of other analysis or transformation processes..."]
    PV_Conj class r"PV_Conj" {
        rates [ (kr, Control) ]
        fields [
            #[doc = "fft buffer"]
            input buffer: UGenInput = UGenInput::Constant(0.0),
        ]
        outputs ( fixed 1 )
        push [ (input buffer) ]
    }
    #[doc = "copies the spectral frame in bufferA to bufferB at that point in the chain of PV UGens. This allows for parallel processing of spectral data without the need for multiple FFT UGens, and to copy out data at that point in the chain for other purposes. bufferA and bufferB must be the same size."]
    PV_Copy class r"PV_Copy" {
        rates [ (kr, Control) ]
        fields [
            #[doc = "source buffer"]
            input buffer_a: UGenInput = UGenInput::Constant(0.0),
            #[doc = "destination buffer"]
            input buffer_b: UGenInput = UGenInput::Constant(0.0),
        ]
        outputs ( fixed 1 )
        push [ (input buffer_a), (input buffer_b) ]
    }
    #[doc = "combines magnitudes of first input and phases of the second input"]
    PV_CopyPhase class r"PV_CopyPhase" {
        rates [ (kr, Control) ]
        fields [
            #[doc = "fft buffer A"]
            input buffer_a: UGenInput = UGenInput::Constant(0.0),
            #[doc = "fft buffer B"]
            input buffer_b: UGenInput = UGenInput::Constant(0.0),
        ]
        outputs ( fixed 1 )
        push [ (input buffer_a), (input buffer_b) ]
    }
    #[doc = "adds a different constant random phase shift to each bin. The trigger will select a new set of random phases."]
    PV_Diffuser class r"PV_Diffuser" {
        rates [ (kr, Control) ]
        fields [
            #[doc = "fft buffer"]
            input buffer: UGenInput = UGenInput::Constant(0.0),
            #[doc = "a trigger selects a new set of random values."]
            input trig: UGenInput = UGenInput::Constant(0.0),
        ]
        outputs ( fixed 1 )
        push [ (input buffer), (input trig) ]
    }
    #[doc = "complex division"]
    PV_Div class r"PV_Div" {
        rates [ (kr, Control) ]
        fields [
            #[doc = "fft buffer A"]
            input buffer_a: UGenInput = UGenInput::Constant(0.0),
            #[doc = "fft buffer B"]
            input buffer_b: UGenInput = UGenInput::Constant(0.0),
        ]
        outputs ( fixed 1 )
        push [ (input buffer_a), (input buffer_b) ]
    }
    #[doc = "passes only bins whose magnitude is above a threshold and above their nearest neighbors"]
    PV_LocalMax class r"PV_LocalMax" {
        rates [ (kr, Control) ]
        fields [
            #[doc = "fft buffer"]
            input buffer: UGenInput = UGenInput::Constant(0.0),
            #[doc = "magnitude threshold."]
            input threshold: UGenInput = UGenInput::Constant(0.0),
        ]
        outputs ( fixed 1 )
        push [ (input buffer), (input threshold) ]
    }
    #[doc = "passes only bins whose magnitude is above a threshold"]
    PV_MagAbove class r"PV_MagAbove" {
        rates [ (kr, Control) ]
        fields [
            #[doc = "fft buffer"]
            input buffer: UGenInput = UGenInput::Constant(0.0),
            #[doc = "magnitude threshold."]
            input threshold: UGenInput = UGenInput::Constant(0.0),
        ]
        outputs ( fixed 1 )
        push [ (input buffer), (input threshold) ]
    }
    #[doc = "passes only bins whose magnitude is below a threshold"]
    PV_MagBelow class r"PV_MagBelow" {
        rates [ (kr, Control) ]
        fields [
            #[doc = "fft buffer"]
            input buffer: UGenInput = UGenInput::Constant(0.0),
            #[doc = "magnitude threshold."]
            input threshold: UGenInput = UGenInput::Constant(0.0),
        ]
        outputs ( fixed 1 )
        push [ (input buffer), (input threshold) ]
    }
    #[doc = "clips bin magnitudes to a maximum threshold"]
    PV_MagClip class r"PV_MagClip" {
        rates [ (kr, Control) ]
        fields [
            #[doc = "fft buffer"]
            input buffer: UGenInput = UGenInput::Constant(0.0),
            #[doc = "magnitude threshold."]
            input threshold: UGenInput = UGenInput::Constant(0.0),
        ]
        outputs ( fixed 1 )
        push [ (input buffer), (input threshold) ]
    }
    #[doc = "divides magnitudes of two inputs and keeps the phases of the first input"]
    PV_MagDiv class r"PV_MagDiv" {
        rates [ (kr, Control) ]
        fields [
            #[doc = "fft buffer A."]
            input buffer_a: UGenInput = UGenInput::Constant(0.0),
            #[doc = "fft buffer B."]
            input buffer_b: UGenInput = UGenInput::Constant(0.0),
            #[doc = "number to use when bins are zeroed out, i.e. causing division by zero"]
            input zeroed: UGenInput = UGenInput::Constant(0.0001),
        ]
        outputs ( fixed 1 )
        push [ (input buffer_a), (input buffer_b), (input zeroed) ]
    }
    #[doc = "freezes magnitudes at current levels when freeze > 0"]
    PV_MagFreeze class r"PV_MagFreeze" {
        rates [ (kr, Control) ]
        fields [
            #[doc = "fft buffer"]
            input buffer: UGenInput = UGenInput::Constant(0.0),
            #[doc = "if freeze > 0 then magnitudes are frozen at current levels."]
            input freeze: UGenInput = UGenInput::Constant(0.0),
        ]
        outputs ( fixed 1 )
        push [ (input buffer), (input freeze) ]
    }
    #[doc = "multiplies magnitudes of two inputs and keeps the phases of the first input"]
    PV_MagMul class r"PV_MagMul" {
        rates [ (kr, Control) ]
        fields [
            #[doc = "fft buffer A"]
            input buffer_a: UGenInput = UGenInput::Constant(0.0),
            #[doc = "fft buffer B"]
            input buffer_b: UGenInput = UGenInput::Constant(0.0),
        ]
        outputs ( fixed 1 )
        push [ (input buffer_a), (input buffer_b) ]
    }
    #[doc = "magnitudes are multiplied with noise"]
    PV_MagNoise class r"PV_MagNoise" {
        rates [ (kr, Control) ]
        fields [
            #[doc = "fft buffer"]
            input buffer: UGenInput = UGenInput::Constant(0.0),
        ]
        outputs ( fixed 1 )
        push [ (input buffer) ]
    }
    #[doc = "shift and stretch the positions of only the magnitude of the bins. Can be used as a very crude frequency shifter/scaler."]
    PV_MagShift class r"PV_MagShift" {
        rates [ (kr, Control) ]
        fields [
            #[doc = "fft buffer."]
            input buffer: UGenInput = UGenInput::Constant(0.0),
            #[doc = "scale bin location by factor."]
            input stretch: UGenInput = UGenInput::Constant(1.0),
            #[doc = "add an offset to bin position."]
            input shift: UGenInput = UGenInput::Constant(0.0),
        ]
        outputs ( fixed 1 )
        push [ (input buffer), (input stretch), (input shift) ]
    }
    #[doc = "average a bin's magnitude with its neighbors"]
    PV_MagSmear class r"PV_MagSmear" {
        rates [ (kr, Control) ]
        fields [
            #[doc = "fft buffer"]
            input buffer: UGenInput = UGenInput::Constant(0.0),
            #[doc = "number of bins to average on each side of bin. As this number rises, so will CPU usage."]
            input bins: UGenInput = UGenInput::Constant(0.0),
        ]
        outputs ( fixed 1 )
        push [ (input buffer), (input bins) ]
    }
    #[doc = "squares the magnitudes and renormalizes to previous peak. This makes weak bins weaker."]
    PV_MagSquared class r"PV_MagSquared" {
        rates [ (kr, Control) ]
        fields [
            #[doc = "fft buffer"]
            input buffer: UGenInput = UGenInput::Constant(0.0),
        ]
        outputs ( fixed 1 )
        push [ (input buffer) ]
    }
    #[doc = "output copies bins with the maximum magnitude of the two inputs"]
    PV_Max class r"PV_Max" {
        rates [ (kr, Control) ]
        fields [
            #[doc = "fft buffer A"]
            input buffer_a: UGenInput = UGenInput::Constant(0.0),
            #[doc = "fft buffer B"]
            input buffer_b: UGenInput = UGenInput::Constant(0.0),
        ]
        outputs ( fixed 1 )
        push [ (input buffer_a), (input buffer_b) ]
    }
    #[doc = "output copies bins with the minimum magnitude of the two inputs"]
    PV_Min class r"PV_Min" {
        rates [ (kr, Control) ]
        fields [
            #[doc = "fft buffer A"]
            input buffer_a: UGenInput = UGenInput::Constant(0.0),
            #[doc = "fft buffer B"]
            input buffer_b: UGenInput = UGenInput::Constant(0.0),
        ]
        outputs ( fixed 1 )
        push [ (input buffer_a), (input buffer_b) ]
    }
    #[doc = "complex multiplication: (RealA * RealB) - (ImagA * ImagB) (ImagA * RealB) + (RealA * ImagB)"]
    PV_Mul class r"PV_Mul" {
        rates [ (kr, Control) ]
        fields [
            #[doc = "fft buffer A"]
            input buffer_a: UGenInput = UGenInput::Constant(0.0),
            #[doc = "fft buffer B"]
            input buffer_b: UGenInput = UGenInput::Constant(0.0),
        ]
        outputs ( fixed 1 )
        push [ (input buffer_a), (input buffer_b) ]
    }
    #[doc = "shift phase of all bins"]
    PV_PhaseShift class r"PV_PhaseShift" {
        rates [ (kr, Control) ]
        fields [
            #[doc = "fft buffer"]
            input buffer: UGenInput = UGenInput::Constant(0.0),
            #[doc = "phase shift in radians"]
            input shift: UGenInput = UGenInput::Constant(0.0),
        ]
        outputs ( fixed 1 )
        push [ (input buffer), (input shift) ]
    }
    #[doc = "shift phase of all bins by 270 degrees"]
    PV_PhaseShift270 class r"PV_PhaseShift270" {
        rates [ (kr, Control) ]
        fields [
            #[doc = "fft buffer"]
            input buffer: UGenInput = UGenInput::Constant(0.0),
        ]
        outputs ( fixed 1 )
        push [ (input buffer) ]
    }
    #[doc = "shift phase of all bins by 90 degrees"]
    PV_PhaseShift90 class r"PV_PhaseShift90" {
        rates [ (kr, Control) ]
        fields [
            #[doc = "fft buffer"]
            input buffer: UGenInput = UGenInput::Constant(0.0),
        ]
        outputs ( fixed 1 )
        push [ (input buffer) ]
    }
    #[doc = "randomly clear bins"]
    PV_RandComb class r"PV_RandComb" {
        rates [ (kr, Control) ]
        fields [
            #[doc = "fft buffer."]
            input buffer: UGenInput = UGenInput::Constant(0.0),
            #[doc = "clears bins from input in a random order as wipe goes from 0 to 1."]
            input wipe: UGenInput = UGenInput::Constant(0.0),
            #[doc = "a trigger selects a new random ordering."]
            input trig: UGenInput = UGenInput::Constant(0.0),
        ]
        outputs ( fixed 1 )
        push [ (input buffer), (input wipe), (input trig) ]
    }
    #[doc = "cross fades between two sounds by copying bins in a random order"]
    PV_RandWipe class r"PV_RandWipe" {
        rates [ (kr, Control) ]
        fields [
            #[doc = "fft buffer A."]
            input buffer_a: UGenInput = UGenInput::Constant(0.0),
            #[doc = "fft buffer B."]
            input buffer_b: UGenInput = UGenInput::Constant(0.0),
            #[doc = "copies bins from bufferB in a random order as wipe goes from 0 to 1."]
            input wipe: UGenInput = UGenInput::Constant(0.0),
            #[doc = "a trigger selects a new random ordering."]
            input trig: UGenInput = UGenInput::Constant(0.0),
        ]
        outputs ( fixed 1 )
        push [ (input buffer_a), (input buffer_b), (input wipe), (input trig) ]
    }
    #[doc = "makes a series of gaps in a spectrum"]
    PV_RectComb class r"PV_RectComb" {
        rates [ (kr, Control) ]
        fields [
            #[doc = "fft buffer."]
            input buffer: UGenInput = UGenInput::Constant(0.0),
            #[doc = "number of teeth in the comb."]
            input num_teeth: UGenInput = UGenInput::Constant(0.0),
            #[doc = "starting phase of comb pulse."]
            input phase: UGenInput = UGenInput::Constant(0.0),
            #[doc = "pulse width of comb."]
            input width: UGenInput = UGenInput::Constant(0.5),
        ]
        outputs ( fixed 1 )
        push [ (input buffer), (input num_teeth), (input phase), (input width) ]
    }
    #[doc = "alternates blocks of bins between the two inputs"]
    PV_RectComb2 class r"PV_RectComb2" {
        rates [ (kr, Control) ]
        fields [
            #[doc = "fft buffer A."]
            input buffer_a: UGenInput = UGenInput::Constant(0.0),
            #[doc = "fft buffer B."]
            input buffer_b: UGenInput = UGenInput::Constant(0.0),
            #[doc = "number of teeth in the comb."]
            input num_teeth: UGenInput = UGenInput::Constant(0.0),
            #[doc = "starting phase of comb pulse."]
            input phase: UGenInput = UGenInput::Constant(0.0),
            #[doc = "pulse width of comb."]
            input width: UGenInput = UGenInput::Constant(0.5),
        ]
        outputs ( fixed 1 )
        push [ (input buffer_a), (input buffer_b), (input num_teeth), (input phase), (input width) ]
    }
}
