// @generated by packages/synthdef-compiler/scripts/generate-rust.ts from specs/ugens.json — do not edit.
// Regenerate with `yarn generate:synthdef-compiler`.

#![allow(
    non_camel_case_types,
    unused_mut,
    unused_variables,
    clippy::useless_conversion,
    clippy::needless_update
)]

use crate::{Rate, SynthDef, UGenInput};

sc_ugens! {
    #[doc = "Strict convolution of two continuously changing inputs. Also see convolution2 for a cheaper CPU cost alternative for the case of a fixed kernel which can be changed with a trigger message. See Steven W Smith, The Scientist and Engineer's Guide to Digital Signal Processing: chapter 18: http:// www.dspguide.com/ch18.htm"]
    Convolution class r"Convolution" {
        rates [ (ar, Audio) ]
        fields [
            #[doc = "processing target"]
            input r#in: UGenInput = UGenInput::Constant(0.0),
            #[doc = "processing kernel."]
            input kernel: UGenInput = UGenInput::Constant(0.0),
            #[doc = "size of FFT frame, must be a power of two"]
            input framesize: UGenInput = UGenInput::Constant(512.0),
        ]
        outputs ( fixed 1 )
        push [ (input r#in), (input kernel), (input framesize) ]
    }
    #[doc = "Strict convolution with fixed kernel which can be updated using a trigger signal. See Steven W Smith, The Scientist and Engineer's Guide to Digital Signal Processing: chapter 18: http:// www.dspguide.com/ch18.htm"]
    Convolution2 class r"Convolution2" {
        rates [ (ar, Audio) ]
        fields [
            #[doc = "processing target"]
            input r#in: UGenInput = UGenInput::Constant(0.0),
            #[doc = "buffer index for the fixed kernel, may be modulated in combination with the trigger"]
            input kernel: UGenInput = UGenInput::Constant(0.0),
            #[doc = "update the kernel on a change from <= 0 to > 0"]
            input trigger: UGenInput = UGenInput::Constant(0.0),
            #[doc = "size of FFT frame, must be a power of two. Convolution uses twice this number internally, maximum value you can give this argument is 2^16 = 65536. Note that it gets progressively more expensive to run for higher powers! 512, 1024, 2048, 4096 standard."]
            input framesize: UGenInput = UGenInput::Constant(2048.0),
        ]
        outputs ( fixed 1 )
        push [ (input r#in), (input kernel), (input trigger), (input framesize) ]
    }
    #[doc = "Strict convolution with fixed kernel which can be updated using a trigger signal. There is a linear crossfade between the buffers upon change. See Steven W Smith, The Scientist and Engineer's Guide to Digital Signal Processing: chapter 18: http://www.dspguide.com/ch18.htm"]
    Convolution2L class r"Convolution2L" {
        rates [ (ar, Audio) ]
        fields [
            #[doc = "processing target"]
            input r#in: UGenInput = UGenInput::Constant(0.0),
            #[doc = "buffer index for the fixed kernel, may be modulated in combination with the trigger"]
            input kernel: UGenInput = UGenInput::Constant(0.0),
            #[doc = "update the kernel on a change from <= 0 to > 0"]
            input trigger: UGenInput = UGenInput::Constant(0.0),
            #[doc = "size of FFT frame, must be a power of two. Convolution uses twice this number internally, maximum value you can give this argument is 2^16=65536. Note that it gets progressively more expensive to run for higher powers! 512, 1024, 2048, 4096 standard."]
            input framesize: UGenInput = UGenInput::Constant(2048.0),
            #[doc = "The number of periods over which a crossfade is made. The default is 1. This must be an integer."]
            input crossfade: UGenInput = UGenInput::Constant(1.0),
        ]
        outputs ( fixed 1 )
        push [ (input r#in), (input kernel), (input trigger), (input framesize), (input crossfade) ]
    }
    #[doc = "Strict convolution with fixed kernel which can be updated using a trigger signal. The convolution is performed in the time domain, which is highly inefficient, and probably only useful for either very short kernel sizes, or for control rate signals."]
    Convolution3 class r"Convolution3" {
        rates [ (ar, Audio), (kr, Control) ]
        fields [
            #[doc = "processing target"]
            input r#in: UGenInput = UGenInput::Constant(0.0),
            #[doc = "buffer index for the fixed kernel, may be modulated in combination with the trigger"]
            input kernel: UGenInput = UGenInput::Constant(0.0),
            #[doc = "update the kernel on a change from <= 0 to > 0"]
            input trigger: UGenInput = UGenInput::Constant(0.0),
            #[doc = "size of FFT frame, does not have to be a power of two."]
            input framesize: UGenInput = UGenInput::Constant(2048.0),
        ]
        outputs ( fixed 1 )
        push [ (input r#in), (input kernel), (input trigger), (input framesize) ]
    }
    #[doc = "Applies the conformal mapping z -> (z-a)/(1-za*) to the phase vocoder bins z with a given by the real and imag inputs to the UGen. i.e., makes a transformation of the complex plane so the output is full of phase vocoder artifacts but may be musically fun. Usually keep |a|<1 but you can of course try bigger values to make it really noisy. a=0 should give back the input mostly unperturbed. See http://mathworld.wolfram.com/ConformalMapping.html"]
    PV_ConformalMap class r"PV_ConformalMap" {
        rates [ (kr, Control) ]
        fields [
            #[doc = "buffer number of buffer to act on, passed in through a chain (see examples below)."]
            input buffer: UGenInput = UGenInput::Constant(0.0),
            #[doc = "real part of a."]
            input areal: UGenInput = UGenInput::Constant(0.0),
            #[doc = "imaginary part of a."]
            input aimag: UGenInput = UGenInput::Constant(0.0),
        ]
        outputs ( fixed 1 )
        push [ (input buffer), (input areal), (input aimag) ]
    }
    #[doc = "FFT onset detector based on work described in: Hainsworth, S. (2003) Techniques for the Automated Analysis of Musical Audio. PhD, University of Cambridge engineering dept. See especially p128. The Hainsworth metric is a modification of the Kullback Liebler distance. The onset detector has general ability to spot spectral change, so may have some ability to track chord changes aside from obvious transient jolts, but there's no guarantee it won't be confused by frequency modulation artifacts. Hainsworth metric on it's own gives good results but Foote might be useful in some situations: experimental."]
    PV_HainsworthFoote class r"PV_HainsworthFoote" {
        rates [ (ar, Audio) ]
        fields [
            #[doc = "FFT buffer to read from"]
            input buffer: UGenInput = UGenInput::Constant(0.0),
            #[doc = "What strength of detection signal from Hainsworth metric to use."]
            input proph: UGenInput = UGenInput::Constant(0.0),
            #[doc = "What strength of detection signal from Foote metric to use. The Foote metric is normalised to [0.0,1.0]"]
            input propf: UGenInput = UGenInput::Constant(0.0),
            #[doc = "Threshold hold level for allowing a detection"]
            input threshold: UGenInput = UGenInput::Constant(1.0),
            #[doc = "If triggered, minimum wait until a further frame can cause another spot (useful to stop multiple detects on heavy signals)"]
            input wait_time: UGenInput = UGenInput::Constant(0.04),
        ]
        outputs ( fixed 1 )
        push [ (input buffer), (input proph), (input propf), (input threshold), (input wait_time) ]
    }
    #[doc = "FFT feature detector for onset detection based on work described in: Jensen,K. & Andersen, T. H. (2003). Real-time Beat Estimation Using Feature Extraction. In Proceedings of the Computer Music Modeling and Retrieval Symposium, Lecture Notes in Computer Science. Springer Verlag. First order derivatives of the features are taken. Threshold may need to be set low to pick up on changes."]
    PV_JensenAndersen class r"PV_JensenAndersen" {
        rates [ (ar, Audio) ]
        fields [
            #[doc = "FFT buffer to read from."]
            input buffer: UGenInput = UGenInput::Constant(0.0),
            #[doc = "Proportion of spectral centroid feature."]
            input propsc: UGenInput = UGenInput::Constant(0.25),
            #[doc = "Proportion of high frequency energy feature."]
            input prophfe: UGenInput = UGenInput::Constant(0.25),
            #[doc = "Proportion of high frequency content feature."]
            input prophfc: UGenInput = UGenInput::Constant(0.25),
            #[doc = "Proportion of spectral flux feature."]
            input propsf: UGenInput = UGenInput::Constant(0.25),
            #[doc = "Threshold level for allowing a detection"]
            input threshold: UGenInput = UGenInput::Constant(1.0),
            #[doc = "If triggered, minimum wait until a further frame can cause another spot (useful to stop multiple detects on heavy signals)"]
            input wait_time: UGenInput = UGenInput::Constant(0.04),
        ]
        outputs ( fixed 1 )
        push [ (input buffer), (input propsc), (input prophfe), (input prophfc), (input propsf), (input threshold), (input wait_time) ]
    }
    #[doc = "A running sum over a user specified number of samples, useful for running RMS power windowing."]
    RunningSum class r"RunningSum" {
        rates [ (ar, Audio), (kr, Control) ]
        fields [
            #[doc = "Input signal"]
            input r#in: UGenInput = UGenInput::Constant(0.0),
            #[doc = "How many samples to take the running sum over (initialisation time only, not modulatable."]
            input numsamp: UGenInput = UGenInput::Constant(40.0),
        ]
        outputs ( fixed 1 )
        push [ (input r#in), (input numsamp) ]
    }
    #[doc = "Strict convolution with fixed kernel which can be updated using a trigger signal. There is a linear crossfade between the buffers upon change. Like convolution2L, but convolves with two buffers and outputs a stereo signal. This saves one FFT transformation per period, as compared to using two copies of convolution2L. Useful applications could include stereo reverberation or HRTF convolution. See Steven W Smith, The Scientist and Engineer's Guide to Digital Signal Processing: chapter 18: http://www.dspguide.com/ch18.htm"]
    StereoConvolution2L class r"StereoConvolution2L" {
        rates [ (ar, Audio) ]
        fields [
            #[doc = "processing target"]
            input r#in: UGenInput = UGenInput::Constant(0.0),
            #[doc = "buffer index for the fixed kernel of the left channel, may be modulated in combination with the trigger"]
            input kernel_l: UGenInput = UGenInput::Constant(0.0),
            #[doc = "buffer index for the fixed kernel of the right channel, may be modulated in combination with the trigger"]
            input kernel_r: UGenInput = UGenInput::Constant(0.0),
            #[doc = "update the kernel on a change from <= 0 to > 0"]
            input trigger: UGenInput = UGenInput::Constant(0.0),
            #[doc = "size of FFT frame, must be a power of two. Convolution uses twice this number internally, maximum value you can give this argument is 2^16=65536. Note that it gets progressively more expensive to run for higher powers! 512, 1024, 2048, 4096 standard."]
            input framesize: UGenInput = UGenInput::Constant(2048.0),
            #[doc = "The number of periods over which a crossfade is made. This must be an integer."]
            input crossfade: UGenInput = UGenInput::Constant(1.0),
        ]
        outputs ( fixed 2 )
        push [ (input r#in), (input kernel_l), (input kernel_r), (input trigger), (input framesize), (input crossfade) ]
    }
}
