// @generated by packages/synthdef-compiler/scripts/generate-rust.ts from specs/ugens.json — do not edit.
// Regenerate with `yarn generate:synthdef-compiler`.

#![allow(
    non_camel_case_types,
    unused_mut,
    unused_variables,
    clippy::useless_conversion,
    clippy::needless_update
)]

use crate::{Rate, SynthDef, UGenInput};

sc_ugens! {
    APF class r"APF" {
        rates [ (ar, Audio), (kr, Control) ]
        fields [
            input r#in: UGenInput = UGenInput::Constant(0.0),
            input freq: UGenInput = UGenInput::Constant(440.0),
            input radius: UGenInput = UGenInput::Constant(0.8),
        ]
        outputs ( fixed 1 )
        push [ (input r#in), (input freq), (input radius) ]
    }
    #[doc = "second order Butterworth bandpass filter"]
    #[doc = ""]
    #[doc = "A band pass filter permits the frequencies around a specified centre frequency to pass unaltered through the filter while the frequencies either side are attenuated. The frequencies that pass through are known as the bandwidth or the band pass of the filter. Used to create timbres consisting of fizzy harmonics, lo-fi qualities or very thin sounds that may form the basis of sound effects."]
    BPF class r"BPF" {
        rates [ (ar, Audio), (kr, Control) ]
        fields [
            #[doc = "input signal to be processed"]
            input r#in: UGenInput = UGenInput::Constant(0.0),
            #[doc = "centre frequency in Hertz"]
            input freq: UGenInput = UGenInput::Constant(440.0),
            #[doc = "the reciprocal of Q. bandwidth / cutoffFreq"]
            input rq: UGenInput = UGenInput::Constant(1.0),
        ]
        outputs ( fixed 1 )
        push [ (input r#in), (input freq), (input rq) ]
    }
    #[doc = "two zero fixed midpass which cuts out 0 Hz and the Nyquist frequency. Implements the formula: out(i) = 0.5 * (in(i) - in(i-2))"]
    BPZ2 class r"BPZ2" {
        rates [ (ar, Audio), (kr, Control) ]
        fields [
            input r#in: UGenInput = UGenInput::Constant(0.0),
        ]
        outputs ( fixed 1 )
        push [ (input r#in) ]
    }
    #[doc = "second order Butterworth band reject filter"]
    #[doc = ""]
    #[doc = "Band reject filters, also known as notch filters, attenuate a selected range of frequencies effectively creating a notch in the sound. This type of filter is handy for scooping out frequencies, thinning out a sound while leaving the fundamental intact, making them useful for creating timbres that contain a discernable pitch but do not have a high level of harmonic content."]
    BRF class r"BRF" {
        rates [ (ar, Audio), (kr, Control) ]
        fields [
            #[doc = "input signal to be processed"]
            input r#in: UGenInput = UGenInput::Constant(0.0),
            #[doc = "centre frequency in Hertz"]
            input freq: UGenInput = UGenInput::Constant(440.0),
            #[doc = "the reciprocal of Q. bandwidth / cutoffFreq"]
            input rq: UGenInput = UGenInput::Constant(1.0),
        ]
        outputs ( fixed 1 )
        push [ (input r#in), (input freq), (input rq) ]
    }
    #[doc = "two zero fixed midcut which cuts out frequencies around 1/2 of the Nyquist frequency. Implements the formula: out(i) = 0.5 * (in(i) + in(i-2))"]
    BRZ2 class r"BRZ2" {
        rates [ (ar, Audio), (kr, Control) ]
        fields [
            input r#in: UGenInput = UGenInput::Constant(0.0),
        ]
        outputs ( fixed 1 )
        push [ (input r#in) ]
    }
    #[doc = "triggered exponential decay."]
    #[doc = ""]
    #[doc = "This is essentially the same as integrator except that instead of supplying the coefficient directly, it is calculated from a 60 dB decay time. This is the time required for the integrator to lose 99.9 % of its value or -60dB. This is useful for exponential decaying envelopes triggered by impulses."]
    Decay class r"Decay" {
        rates [ (ar, Audio), (kr, Control) ]
        fields [
            #[doc = "input signal"]
            input r#in: UGenInput = UGenInput::Constant(0.0),
            #[doc = "60 dB decay time in seconds"]
            input decay_time: UGenInput = UGenInput::Constant(1.0),
        ]
        outputs ( fixed 1 )
        push [ (input r#in), (input decay_time) ]
    }
    #[doc = "triggered exponential attack and exponential decay. Decay has a very sharp attack and can produce clicks. Decay2 rounds off the attack by subtracting one Decay from another. (decay in attack-time decay-time) equivalent to: (- (decay in attack-time decay-time) (decay in attack-time decay-time))"]
    Decay2 class r"Decay2" {
        rates [ (ar, Audio), (kr, Control) ]
        fields [
            #[doc = "input signal"]
            input r#in: UGenInput = UGenInput::Constant(0.0),
            #[doc = "60 dB attack time in seconds."]
            input attack_time: UGenInput = UGenInput::Constant(0.01),
            #[doc = "60 dB decay time in seconds."]
            input decay_time: UGenInput = UGenInput::Constant(1.0),
        ]
        outputs ( fixed 1 )
        push [ (input r#in), (input attack_time), (input decay_time) ]
    }
    #[doc = "If the signal input starts with silence at the beginning of the synth's duration, then DetectSilence will wait indefinitely until the first sound before starting to monitor for silence. This UGen outputs 1 if silence is detected, otherwise 0."]
    DetectSilence class r"DetectSilence" {
        rates [ (ar, Audio), (kr, Control) ]
        fields [
            #[doc = "any source"]
            input r#in: UGenInput = UGenInput::Constant(0.0),
            #[doc = "when input falls below this, evaluate done action"]
            input amp: UGenInput = UGenInput::Constant(0.0001),
            #[doc = "the minimum duration of the input signal which input must fall below thresh before this triggers. The default is 0.1 seconds"]
            input time: UGenInput = UGenInput::Constant(0.1),
            #[doc = "the action to perform when silence is detected. Default: NO-ACTION"]
            input action: UGenInput = UGenInput::Constant(0.0),
        ]
        outputs ( fixed 1 )
        push [ (input r#in), (input amp), (input time), (input action) ]
    }
    #[doc = "first order filter section. Formula is equivalent to: out(i) = (a0 * in(i)) + (a1 * in(i-1)) + (b1 * out(i-1))"]
    FOS class r"FOS" {
        rates [ (ar, Audio), (kr, Control) ]
        fields [
            #[doc = "input signal"]
            input r#in: UGenInput = UGenInput::Constant(0.0),
            #[doc = "first coefficient"]
            input a0: UGenInput = UGenInput::Constant(0.0),
            #[doc = "second coefficient"]
            input a1: UGenInput = UGenInput::Constant(0.0),
            #[doc = "third coefficient"]
            input b1: UGenInput = UGenInput::Constant(0.0),
        ]
        outputs ( fixed 1 )
        push [ (input r#in), (input a0), (input a1), (input b1) ]
    }
    #[doc = "a resonant filter whose impulse response is like that of a sine wave with a Decay2 envelope over it. The great advantage to this filter over FOF is that there is no limit to the number of overlapping grains since the grain is just the impulse response of the filter. Note that if attacktime == decaytime then the signal cancels out and if attacktime > decaytime then the impulse response is inverted."]
    Formlet class r"Formlet" {
        rates [ (ar, Audio), (kr, Control) ]
        fields [
            #[doc = "input signal to be processed"]
            input r#in: UGenInput = UGenInput::Constant(0.0),
            #[doc = "resonant frequency in Hertz"]
            input freq: UGenInput = UGenInput::Constant(440.0),
            #[doc = "60 dB attack time in seconds"]
            input attack_time: UGenInput = UGenInput::Constant(1.0),
            #[doc = "60 dB decay time in seconds"]
            input decay_time: UGenInput = UGenInput::Constant(1.0),
        ]
        outputs ( fixed 1 )
        push [ (input r#in), (input freq), (input attack_time), (input decay_time) ]
    }
    #[doc = "second order high pass filter"]
    #[doc = ""]
    #[doc = "A high pass filter lets through the frequencies above the cutoff point and successfully dampens the frequencies below the cutoff point. This effectively removes the fundamental frequency of the sound, leaving only the fizz harmonic overtones. High pass filters are rarely used in the creation of instruments and are predominantly used to create effervexcent sound effects of bright timbres that can be laid over the top of another low pass sound to increase the harmonic content."]
    HPF class r"HPF" {
        rates [ (ar, Audio), (kr, Control) ]
        fields [
            #[doc = "input signal to be processed"]
            input r#in: UGenInput = UGenInput::Constant(0.0),
            #[doc = "cutoff frequency"]
            input freq: UGenInput = UGenInput::Constant(440.0),
        ]
        outputs ( fixed 1 )
        push [ (input r#in), (input freq) ]
    }
    #[doc = "two point difference filter. Implements the formula: out(i) = 0.5 * (in(i) - in(i-1))"]
    HPZ1 class r"HPZ1" {
        rates [ (ar, Audio), (kr, Control) ]
        fields [
            input r#in: UGenInput = UGenInput::Constant(0.0),
        ]
        outputs ( fixed 1 )
        push [ (input r#in) ]
    }
    #[doc = "two zero fixed highpass. Implements the formula: out(i) = 0.25 * (in(i) - (2*in(i-1)) + in(i-2))"]
    HPZ2 class r"HPZ2" {
        rates [ (ar, Audio), (kr, Control) ]
        fields [
            input r#in: UGenInput = UGenInput::Constant(0.0),
        ]
        outputs ( fixed 1 )
        push [ (input r#in) ]
    }
    #[doc = "leaky integrator. Integrates an input signal with a leak. The formula implemented is: out(0) = in(0) + (coef * out(-1))"]
    Integrator class r"Integrator" {
        rates [ (ar, Audio), (kr, Control) ]
        fields [
            #[doc = "input signal"]
            input r#in: UGenInput = UGenInput::Constant(0.0),
            #[doc = "leak coefficient"]
            input coef: UGenInput = UGenInput::Constant(1.0),
        ]
        outputs ( fixed 1 )
        push [ (input r#in), (input coef) ]
    }
    #[doc = "second order Butterworth low pass filter"]
    #[doc = ""]
    #[doc = "A low pass filter is a standard subtractive synthesis tool which removes frequencies above a defined cut-off point. This typically has the effect of making bright sounds duller. Using a low pass filter allows you to have fine-grained control of the level of brightness/dullness to tune your timbre in addition to allowing you to modulate the effect in real time thus creating movement in the sound."]
    LPF class r"LPF" {
        rates [ (ar, Audio), (kr, Control) ]
        fields [
            #[doc = "input signal to be processed"]
            input r#in: UGenInput = UGenInput::Constant(0.0),
            #[doc = "cutoff frequency"]
            input freq: UGenInput = UGenInput::Constant(440.0),
        ]
        outputs ( fixed 1 )
        push [ (input r#in), (input freq) ]
    }
    #[doc = "two point average filter. Implements the formula: out(i) = 0.5 * (in(i) + in(i-1))"]
    LPZ1 class r"LPZ1" {
        rates [ (ar, Audio), (kr, Control) ]
        fields [
            input r#in: UGenInput = UGenInput::Constant(0.0),
        ]
        outputs ( fixed 1 )
        push [ (input r#in) ]
    }
    #[doc = "two zero fixed lowpass. Implements the formula: out(i) = 0.25 * (in(i) + (2*in(i-1)) + in(i-2))"]
    LPZ2 class r"LPZ2" {
        rates [ (ar, Audio), (kr, Control) ]
        fields [
            input r#in: UGenInput = UGenInput::Constant(0.0),
        ]
        outputs ( fixed 1 )
        push [ (input r#in) ]
    }
    #[doc = "exponential lag, useful for smoothing out control signals. This is essentially the same as OnePole except that instead of supplying the coefficient directly, it is calculated from a 60 dB lag time. This is the time required for the filter to converge to within 0.01 % of a value."]
    Lag class r"Lag" {
        rates [ (ar, Audio), (kr, Control) ]
        fields [
            #[doc = "input signal"]
            input r#in: UGenInput = UGenInput::Constant(0.0),
            #[doc = "60 dB lag time in seconds"]
            input lag_time: UGenInput = UGenInput::Constant(0.1),
        ]
        outputs ( fixed 1 )
        push [ (input r#in), (input lag_time) ]
    }
    #[doc = "equivalent to (lag (lag in time) time), resulting in a smoother transition. This saves on CPU as you only have to calculate the decay factor once instead of twice. See lag for more details."]
    Lag2 class r"Lag2" {
        rates [ (ar, Audio), (kr, Control) ]
        fields [
            #[doc = "input signal"]
            input r#in: UGenInput = UGenInput::Constant(0.0),
            #[doc = "60 dB lag time in seconds"]
            input lag_time: UGenInput = UGenInput::Constant(0.1),
        ]
        outputs ( fixed 1 )
        push [ (input r#in), (input lag_time) ]
    }
    #[doc = "equivalent to (lag-ud (lag-ud in up-t down-t) up-t down-t) thus resulting in a smoother transition. This saves on CPU as you only have to calculate the decay factor once instead of twice. See Lag for more details."]
    Lag2UD class r"Lag2UD" {
        rates [ (ar, Audio), (kr, Control) ]
        fields [
            #[doc = "input signal"]
            input r#in: UGenInput = UGenInput::Constant(0.0),
            #[doc = "60 dB lag time in seconds for the upgoing signal"]
            input lag_time_up: UGenInput = UGenInput::Constant(0.1),
            #[doc = "60 dB lag time in seconds for the downgoing signal"]
            input lag_time_down: UGenInput = UGenInput::Constant(0.1),
        ]
        outputs ( fixed 1 )
        push [ (input r#in), (input lag_time_up), (input lag_time_down) ]
    }
    #[doc = "lag3 is equivalent to (lag (lag (lag in time) time) time), thus resulting in a smoother transition. This saves on CPU as you only have to calculate the decay factor once instead of three times. See Lag for more details."]
    Lag3 class r"Lag3" {
        rates [ (ar, Audio), (kr, Control) ]
        fields [
            #[doc = "input signal"]
            input r#in: UGenInput = UGenInput::Constant(0.0),
            #[doc = "60 dB lag time in seconds"]
            input lag_time: UGenInput = UGenInput::Constant(0.1),
        ]
        outputs ( fixed 1 )
        push [ (input r#in), (input lag_time) ]
    }
    #[doc = "equivalent to (lag-ud (lag-ud (lag-ud (in up-t down-t) up-t down-t) up-t, down-t) thus resulting in a smoother transition. This saves on CPU as you only have to calculate the decay factor once instead of three times."]
    Lag3UD class r"Lag3UD" {
        rates [ (ar, Audio), (kr, Control) ]
        fields [
            #[doc = "input signal"]
            input r#in: UGenInput = UGenInput::Constant(0.0),
            #[doc = "60 dB lag time in seconds for the upgoing signal"]
            input lag_time_up: UGenInput = UGenInput::Constant(0.1),
            #[doc = "60 dB lag time in seconds for the downgoing signal"]
            input lag_time_down: UGenInput = UGenInput::Constant(0.1),
        ]
        outputs ( fixed 1 )
        push [ (input r#in), (input lag_time_up), (input lag_time_down) ]
    }
    #[doc = "the same as Lag except that you can supply a different 60 dB time for when the signal goes up, from when the signal goes down"]
    LagUD class r"LagUD" {
        rates [ (ar, Audio), (kr, Control) ]
        fields [
            #[doc = "input signal"]
            input r#in: UGenInput = UGenInput::Constant(0.0),
            #[doc = "60 dB lag time in seconds for the upgoing signal"]
            input lag_time_up: UGenInput = UGenInput::Constant(0.1),
            #[doc = "60 dB lag time in seconds for the downgoing signal"]
            input lag_time_down: UGenInput = UGenInput::Constant(0.1),
        ]
        outputs ( fixed 1 )
        push [ (input r#in), (input lag_time_up), (input lag_time_down) ]
    }
    #[doc = "removes a DC offset from signal. For example, a square wave contains prolonged sections of the cycle which are at +1 and -1 (the top and bottom of the square sections). If you were to pass this wave through leak-dc, then these top parts would taper back towards 0 with a greater slope as you move coef from 1 to 0.. Good starting point coef values are to 0.995 for audio rate and 0.9 for control rate"]
    LeakDC class r"LeakDC" {
        rates [ (ar, Audio), (kr, Control) ]
        fields [
            #[doc = "input signal"]
            input r#in: UGenInput = UGenInput::Constant(0.0),
            #[doc = "leak coefficient. A value of 1 indicates no leakage and 0 indicates high leakage - essentially the rate at which the offset will return back to 0"]
            input coef: UGenInput = UGenInput::Constant(0.995),
        ]
        outputs ( fixed 1 )
        push [ (input r#in), (input coef) ]
    }
    #[doc = "returns the median of the last length input points. This non linear filter is good at reducing impulse noise from a signal."]
    Median class r"Median" {
        rates [ (ar, Audio), (kr, Control) ]
        fields [
            #[doc = "number of input points in which to find the median. Must be an odd number from 1 to 31. If length is 1 then Median has no effect."]
            input length: UGenInput = UGenInput::Constant(3.0),
            #[doc = "Input signal to be processed"]
            input r#in: UGenInput = UGenInput::Constant(0.0),
        ]
        outputs ( fixed 1 )
        push [ (input length), (input r#in) ]
    }
    #[doc = "attenuates or boosts a frequency band"]
    MidEQ class r"MidEQ" {
        rates [ (ar, Audio), (kr, Control) ]
        fields [
            #[doc = "input signal to be processed"]
            input r#in: UGenInput = UGenInput::Constant(0.0),
            #[doc = "center frequency of the band in Hertz"]
            input freq: UGenInput = UGenInput::Constant(440.0),
            #[doc = "the reciprocal of Q. bandwidth / cutoffFreq"]
            input rq: UGenInput = UGenInput::Constant(1.0),
            #[doc = "amount of boost (db > 0) or attenuation (db < 0) of the frequency band"]
            input db: UGenInput = UGenInput::Constant(0.0),
        ]
        outputs ( fixed 1 )
        push [ (input r#in), (input freq), (input rq), (input db) ]
    }
    #[doc = "A one pole filter. Implements the formula: out(i) = ((1 - abs(coef)) * in(i)) + (coef * out(i-1))"]
    OnePole class r"OnePole" {
        rates [ (ar, Audio), (kr, Control) ]
        fields [
            #[doc = "input signal to be processed"]
            input r#in: UGenInput = UGenInput::Constant(0.0),
            #[doc = "feedback coefficient. Should be between -1 and +1"]
            input coef: UGenInput = UGenInput::Constant(0.5),
        ]
        outputs ( fixed 1 )
        push [ (input r#in), (input coef) ]
    }
    #[doc = "A one zero filter. Implements the formula : out(i) = ((1 - abs(coef)) * in(i)) + (coef * in(i-1))"]
    OneZero class r"OneZero" {
        rates [ (ar, Audio), (kr, Control) ]
        fields [
            #[doc = "input signal to be processed"]
            input r#in: UGenInput = UGenInput::Constant(0.0),
            #[doc = "feed forward coefficient. +0.5 makes a two point averaging filter (see also lpz1), -0.5 makes a differentiator (see also hpz1), +1 makes a single sample delay (see also delay1), -1 makes an inverted single sample delay."]
            input coef: UGenInput = UGenInput::Constant(0.5),
        ]
        outputs ( fixed 1 )
        push [ (input r#in), (input coef) ]
    }
    #[doc = "resonant high pass filter"]
    #[doc = ""]
    #[doc = "A resonant high pass filter lets through the frequencies above the cutoff point and successfully dampens the frequencies below the cutoff point. This effectively removes the fundamental frequency of the sound, leaving only the fizz harmonic overtones. However, in addition to this behaviour, the resonant high pass filter also emphasises/resonates the frequencies around the cutoff point. The amount of emphasis is controlled by the rq param with a lower rq resulting in greater resonance. High amounts of resonance (rq ~0) can create a whistling sound around the cutoff frequency. High pass filters are rarely used in the creation of instruments and are predominantly used to create effervescent sound effects of bright timbres that can be laid over the top of another low pass sound to increase the harmonic content."]
    RHPF class r"RHPF" {
        rates [ (ar, Audio), (kr, Control) ]
        fields [
            #[doc = "input signal to be processed"]
            input r#in: UGenInput = UGenInput::Constant(0.0),
            #[doc = "cutoff frequency"]
            input freq: UGenInput = UGenInput::Constant(440.0),
            #[doc = "the reciprocal of Q. bandwidth / cutoffFreq. A lower rq results in more resonance"]
            input rq: UGenInput = UGenInput::Constant(1.0),
        ]
        outputs ( fixed 1 )
        push [ (input r#in), (input freq), (input rq) ]
    }
    #[doc = "resonant low pass filter"]
    #[doc = ""]
    #[doc = "A resonant low pass filter is a standard subtractive synthesis tool which removes frequencies above a defined cut-off point. This typically has the effect of making bright sounds duller. However, in addition to this behaviour, the resonant low pass filter also emphasises/resonates the frequencies around the cutoff point. The amount of emphasis is controlled by the rq param with a lower rq resulting in greater resonance. High amounts of resonance (rq ~0) can create a whistling sound around the cutoff frequency. Using a low pass filter allows you to have fine-grained control of the level of brightness/dullness to tune your timbre in addition to allowing you to modulate the effect in real time thus creating movement in the sound."]
    RLPF class r"RLPF" {
        rates [ (ar, Audio), (kr, Control) ]
        fields [
            #[doc = "input signal to be processed"]
            input r#in: UGenInput = UGenInput::Constant(0.0),
            #[doc = "cutoff frequency"]
            input freq: UGenInput = UGenInput::Constant(440.0),
            #[doc = "the reciprocal of Q. bandwidth / cutoffFreq. A lower rq results in more resonance."]
            input rq: UGenInput = UGenInput::Constant(1.0),
        ]
        outputs ( fixed 1 )
        push [ (input r#in), (input freq), (input rq) ]
    }
    #[doc = "similar to lag but with a linear rather than exponential lag, useful for smoothing out control signals"]
    Ramp class r"Ramp" {
        rates [ (ar, Audio), (kr, Control) ]
        fields [
            #[doc = "input signal"]
            input r#in: UGenInput = UGenInput::Constant(0.0),
            #[doc = "60 dB lag time in seconds"]
            input lag_time: UGenInput = UGenInput::Constant(0.1),
        ]
        outputs ( fixed 1 )
        push [ (input r#in), (input lag_time) ]
    }
    #[doc = "A Note on Constant-Gain Digital Resonators,\\\" Computer Music Journal, vol 18, no. 4, pp. 8-10, Winter 1994.\\\" Computer Music Journal, vol 18, no. 4, pp. 8-10, Winter 1994."]
    Resonz class r"Resonz" {
        rates [ (ar, Audio), (kr, Control) ]
        fields [
            #[doc = "input signal to be processed"]
            input r#in: UGenInput = UGenInput::Constant(0.0),
            #[doc = "resonant frequency in Hertz"]
            input freq: UGenInput = UGenInput::Constant(440.0),
            #[doc = "bandwidth ratio (reciprocal of Q). rq = bandwidth / centerFreq"]
            input bwr: UGenInput = UGenInput::Constant(1.0),
        ]
        outputs ( fixed 1 )
        push [ (input r#in), (input freq), (input bwr) ]
    }
    #[doc = "Ringz is the same as Resonz, except that instead of a resonance parameter, the bandwidth is specified in a 60dB ring decay time. One Ringz is equivalent to one component of the klank ugen"]
    Ringz class r"Ringz" {
        rates [ (ar, Audio), (kr, Control) ]
        fields [
            #[doc = "input signal to be processed"]
            input r#in: UGenInput = UGenInput::Constant(0.0),
            #[doc = "resonant frequency in Hertz"]
            input freq: UGenInput = UGenInput::Constant(440.0),
            #[doc = "the 60 dB decay time of the filter"]
            input decay_time: UGenInput = UGenInput::Constant(1.0),
        ]
        outputs ( fixed 1 )
        push [ (input r#in), (input freq), (input decay_time) ]
    }
    #[doc = "second order filter section (biquad). Formula is equivalent to: out(i) = (a0 * in(i)) + (a1 * in(i-1)) + (a2 * in(i-2)) + (b1 * out(i-1)) + (b2 * out(i-2))"]
    SOS class r"SOS" {
        rates [ (ar, Audio), (kr, Control) ]
        fields [
            #[doc = "input signal"]
            input r#in: UGenInput = UGenInput::Constant(0.0),
            #[doc = "1st coefficient"]
            input a0: UGenInput = UGenInput::Constant(0.0),
            #[doc = "2nd coefficient"]
            input a1: UGenInput = UGenInput::Constant(0.0),
            #[doc = "3rd coefficient"]
            input a2: UGenInput = UGenInput::Constant(0.0),
            #[doc = "4th coefficient"]
            input b1: UGenInput = UGenInput::Constant(0.0),
            #[doc = "5th coefficient"]
            input b2: UGenInput = UGenInput::Constant(0.0),
        ]
        outputs ( fixed 1 )
        push [ (input r#in), (input a0), (input a1), (input a2), (input b1), (input b2) ]
    }
    #[doc = "Smooth the curve by limiting the slope of the input signal to up and dn"]
    Slew class r"Slew" {
        rates [ (ar, Audio), (kr, Control) ]
        fields [
            #[doc = "input signal"]
            input r#in: UGenInput = UGenInput::Constant(0.0),
            #[doc = "maximum upward slope"]
            input up: UGenInput = UGenInput::Constant(1.0),
            #[doc = "maximum downward slope"]
            input dn: UGenInput = UGenInput::Constant(1.0),
        ]
        outputs ( fixed 1 )
        push [ (input r#in), (input up), (input dn) ]
    }
    #[doc = "Measures the rate of change per second of a signal. Formula implemented is: out[i] = (in[i] - in[i-1]) * sampling_rate"]
    Slope class r"Slope" {
        rates [ (ar, Audio), (kr, Control) ]
        fields [
            #[doc = "input signal to measure"]
            input r#in: UGenInput = UGenInput::Constant(0.0),
        ]
        outputs ( fixed 1 )
        push [ (input r#in) ]
    }
    #[doc = "a two pole filter. This provides lower level access to setting of pole location. For general purposes Resonz is better."]
    TwoPole class r"TwoPole" {
        rates [ (ar, Audio), (kr, Control) ]
        fields [
            #[doc = "input signal to be processed"]
            input r#in: UGenInput = UGenInput::Constant(0.0),
            #[doc = "frequency of pole angle"]
            input freq: UGenInput = UGenInput::Constant(440.0),
            #[doc = "radius of pole. Should be between 0 and +1"]
            input radius: UGenInput = UGenInput::Constant(0.8),
        ]
        outputs ( fixed 1 )
        push [ (input r#in), (input freq), (input radius) ]
    }
    #[doc = "a two zero filter"]
    TwoZero class r"TwoZero" {
        rates [ (ar, Audio), (kr, Control) ]
        fields [
            #[doc = "input signal to be processed"]
            input r#in: UGenInput = UGenInput::Constant(0.0),
            #[doc = "frequency of zero angle"]
            input freq: UGenInput = UGenInput::Constant(440.0),
            #[doc = "radius of zero"]
            input radius: UGenInput = UGenInput::Constant(0.8),
        ]
        outputs ( fixed 1 )
        push [ (input r#in), (input freq), (input radius) ]
    }
}
