// @generated by packages/synthdef-compiler/scripts/generate-rust.ts from specs/ugens.json — do not edit.
// Regenerate with `yarn generate:synthdef-compiler`.

#![allow(
    non_camel_case_types,
    unused_mut,
    unused_variables,
    clippy::useless_conversion,
    clippy::needless_update
)]

use crate::{Rate, SynthDef, UGenInput};

sc_ugens! {
    #[doc = "current number of channels of soundfile in buffer"]
    BufChannels class r"BufChannels" {
        rates [ (kr, Control), (ir, Scalar) ]
        fields [
            #[doc = "a buffer"]
            input buf: UGenInput = UGenInput::Constant(0.0),
        ]
        outputs ( fixed 1 )
        push [ (input buf) ]
    }
    #[doc = "returns the current duration of a buffer in seconds."]
    BufDur class r"BufDur" {
        rates [ (kr, Control), (ir, Scalar) ]
        fields [
            #[doc = "a buffer"]
            input buf: UGenInput = UGenInput::Constant(0.0),
        ]
        outputs ( fixed 1 )
        push [ (input buf) ]
    }
    #[doc = "returns the current number of allocated frames i.e. the size of the buffer. This is the equivalent of Clojure's count on a seq."]
    BufFrames class r"BufFrames" {
        rates [ (kr, Control), (ir, Scalar) ]
        fields [
            #[doc = "a buffer"]
            input buf: UGenInput = UGenInput::Constant(0.0),
        ]
        outputs ( fixed 1 )
        push [ (input buf) ]
    }
    #[doc = "returns a ratio by which the playback of a buffer is to be scaled"]
    BufRateScale class r"BufRateScale" {
        rates [ (kr, Control), (ir, Scalar) ]
        fields [
            #[doc = "a buffer"]
            input buf: UGenInput = UGenInput::Constant(0.0),
        ]
        outputs ( fixed 1 )
        push [ (input buf) ]
    }
    #[doc = "returns the buffers current sample rate"]
    BufSampleRate class r"BufSampleRate" {
        rates [ (kr, Control), (ir, Scalar) ]
        fields [
            #[doc = "a buffer"]
            input buf: UGenInput = UGenInput::Constant(0.0),
        ]
        outputs ( fixed 1 )
        push [ (input buf) ]
    }
    #[doc = "current number of samples allocated in the buffer"]
    BufSamples class r"BufSamples" {
        rates [ (kr, Control), (ir, Scalar) ]
        fields [
            #[doc = "a buffer"]
            input buf: UGenInput = UGenInput::Constant(0.0),
        ]
        outputs ( fixed 1 )
        push [ (input buf) ]
    }
    #[doc = "test for infinity, not-a-number, and denormals. If one of these is found, it posts a warning. Its output is as follows: 0 = a normal float, 1 = NaN, 2 = infinity, and 3 = a denormal."]
    CheckBadValues class r"CheckBadValues" {
        rates [ (ar, Audio), (kr, Control) ]
        fields [
            #[doc = "the UGen whose output is to be tested"]
            input r#in: UGenInput = UGenInput::Constant(0.0),
            #[doc = "an id number to identify this UGen."]
            input id: UGenInput = UGenInput::Constant(0.0),
            #[doc = "One of three post modes: 0 = no posting; 1 = post a line for every bad value; 2 = post a line only when the floating-point classification changes (e.g., normal -> NaN and vice versa)"]
            input post: UGenInput = UGenInput::Constant(2.0),
        ]
        outputs ( fixed 1 )
        push [ (input r#in), (input id), (input post) ]
    }
    #[doc = "returns the current control rate block duration of the server in seconds"]
    ControlDur class r"ControlDur" {
        rates [ (ir, Scalar) ]
        fields [
        ]
        outputs ( fixed 1 )
        push [  ]
    }
    #[doc = "returns the current control rate of the server"]
    ControlRate class r"ControlRate" {
        rates [ (ir, Scalar) ]
        fields [
        ]
        outputs ( fixed 1 )
        push [  ]
    }
    #[doc = "returns the number of audio buses allocated on the server."]
    NumAudioBuses class r"NumAudioBuses" {
        rates [ (ir, Scalar) ]
        fields [
        ]
        outputs ( fixed 1 )
        push [  ]
    }
    #[doc = "returns the number of buffers allocated on the server"]
    NumBuffers class r"NumBuffers" {
        rates [ (ir, Scalar) ]
        fields [
        ]
        outputs ( fixed 1 )
        push [  ]
    }
    #[doc = "returns the number of control buses allocated on the server"]
    NumControlBuses class r"NumControlBuses" {
        rates [ (ir, Scalar) ]
        fields [
        ]
        outputs ( fixed 1 )
        push [  ]
    }
    #[doc = "returns the number of input buses allocated on the server. This is the number of hardware inputs provided by the host machine such as a mic."]
    NumInputBuses class r"NumInputBuses" {
        rates [ (ir, Scalar) ]
        fields [
        ]
        outputs ( fixed 1 )
        push [  ]
    }
    #[doc = "returns the number of output buses allocated on the server. This is the number of hardware outputs provided by the host machine such as left and right speakers."]
    NumOutputBuses class r"NumOutputBuses" {
        rates [ (ir, Scalar) ]
        fields [
        ]
        outputs ( fixed 1 )
        push [  ]
    }
    #[doc = "returns the number of currently running synths"]
    NumRunningSynths class r"NumRunningSynths" {
        rates [ (kr, Control), (ir, Scalar) ]
        fields [
        ]
        outputs ( fixed 1 )
        push [  ]
    }
    #[doc = "This ugen has been internalised for scserver compatibility. Please use the poll cgen instead."]
    Poll class r"Poll" {
        rates [ (ar, Audio), (kr, Control) ]
        fields [
            #[doc = "a non-positive to positive transition telling Poll to return a value"]
            input trig: UGenInput = UGenInput::Constant(0.0),
            #[doc = "the signal you want to poll"]
            input r#in: UGenInput = UGenInput::Constant(0.0),
            #[doc = "a string or symbol to be printed with the polled value"]
            input label: UGenInput = UGenInput::Constant(0.0),
            #[doc = "if greater than 0, a '/tr' message is sent back to the client (similar to send-trig)"]
            input trig_id: UGenInput = UGenInput::Constant(-1.0),
        ]
        outputs ( fixed 1 )
        push [ (input trig), (input r#in), (input label), (input trig_id) ]
    }
    RadiansPerSample class r"RadiansPerSample" {
        rates [ (ir, Scalar) ]
        fields [
        ]
        outputs ( fixed 1 )
        push [  ]
    }
    #[doc = "returns the current sample duration of the server in seconds"]
    SampleDur class r"SampleDur" {
        rates [ (ir, Scalar) ]
        fields [
        ]
        outputs ( fixed 1 )
        push [  ]
    }
    #[doc = "returns the current sample rate"]
    SampleRate class r"SampleRate" {
        rates [ (ir, Scalar) ]
        fields [
        ]
        outputs ( fixed 1 )
        push [  ]
    }
    #[doc = "offset from synth start within one sample"]
    SubsampleOffset class r"SubsampleOffset" {
        rates [ (ir, Scalar) ]
        fields [
        ]
        outputs ( fixed 1 )
        push [  ]
    }
}
