// @generated by packages/synthdef-compiler/scripts/generate-rust.ts from specs/ugens.json — do not edit.
// Regenerate with `yarn generate:synthdef-compiler`.

#![allow(
    non_camel_case_types,
    unused_mut,
    unused_variables,
    clippy::useless_conversion,
    clippy::needless_update
)]

use crate::{Rate, SynthDef, UGenInput};

sc_ugens! {
    #[doc = "Toggles between two values when a key on the keyboard is up or down. Note that this ugen does not prevent normal typing."]
    KeyState class r"KeyState" {
        rates [ (kr, Control) ]
        fields [
            #[doc = "The keycode value of the key to check."]
            input keycode: UGenInput = UGenInput::Constant(0.0),
            #[doc = "The value to output when the key is not pressed."]
            input minval: UGenInput = UGenInput::Constant(0.0),
            #[doc = "The value to output when the key is pressed."]
            input maxval: UGenInput = UGenInput::Constant(1.0),
            #[doc = "lag factor"]
            input lag: UGenInput = UGenInput::Constant(0.2),
        ]
        outputs ( fixed 1 )
        push [ (input keycode), (input minval), (input maxval), (input lag) ]
    }
    #[doc = "toggles between two values when the left mouse button is up or down"]
    MouseButton class r"MouseButton" {
        rates [ (kr, Control) ]
        fields [
            #[doc = "value when the key is not pressed"]
            input up: UGenInput = UGenInput::Constant(0.0),
            #[doc = "value when the key is pressed"]
            input down: UGenInput = UGenInput::Constant(1.0),
            #[doc = "lag factor"]
            input lag: UGenInput = UGenInput::Constant(0.2),
        ]
        outputs ( fixed 1 )
        push [ (input up), (input down), (input lag) ]
    }
    #[doc = "maps the current mouse X coordinate to a value between min and max"]
    MouseX class r"MouseX" {
        rates [ (kr, Control) ]
        fields [
            #[doc = "minimum value (when mouse is at the left of the screen)"]
            input min: UGenInput = UGenInput::Constant(0.0),
            #[doc = "maximum value (when mouse is at the right of the screen)"]
            input max: UGenInput = UGenInput::Constant(1.0),
            #[doc = "mapping curve - either LINEAR or EXPONENTIAL (LIN and EXP abbreviations are allowed). Default is LINEAR."]
            input warp: UGenInput = UGenInput::Constant(0.0),
            #[doc = "lag factor to dezipper cursor movement."]
            input lag: UGenInput = UGenInput::Constant(0.2),
        ]
        outputs ( fixed 1 )
        push [ (input min), (input max), (input warp), (input lag) ]
    }
    #[doc = "maps the current mouse Y coordinate to a value between min and max"]
    MouseY class r"MouseY" {
        rates [ (kr, Control) ]
        fields [
            #[doc = "minimum value (when mouse is at the top of the screen)"]
            input min: UGenInput = UGenInput::Constant(0.0),
            #[doc = "maximum value (when mouse is at the bottom of the screen)"]
            input max: UGenInput = UGenInput::Constant(1.0),
            #[doc = "mapping curve - either LINEAR or EXPONENTIAL (LIN and EXP abbreviations are allowed). Default is LINEAR"]
            input warp: UGenInput = UGenInput::Constant(0.0),
            #[doc = "lag factor to smooth out cursor movement."]
            input lag: UGenInput = UGenInput::Constant(0.2),
        ]
        outputs ( fixed 1 )
        push [ (input min), (input max), (input warp), (input lag) ]
    }
}
