// @generated by packages/synthdef-compiler/scripts/generate-rust.ts from specs/ugens.json — do not edit.
// Regenerate with `yarn generate:synthdef-compiler`.

#![allow(
    non_camel_case_types,
    unused_mut,
    unused_variables,
    clippy::useless_conversion,
    clippy::needless_update
)]

use crate::{Rate, SynthDef, UGenInput};

sc_ugens! {
    #[doc = "audio rate to control rate converter via linear interpolation"]
    A2K class r"A2K" {
        rates [ (kr, Control) ]
        fields [
            #[doc = "input signal"]
            input r#in: UGenInput = UGenInput::Constant(0.0),
        ]
        outputs ( fixed 1 )
        push [ (input r#in) ]
    }
    #[doc = "Basic psychoacoustic amplitude compensation.\" , :rates #{:ir :ar :kr} :check (when-ar (first-input-ar \"freq must be audio rate\")) :doc \"amplitude compensation: because higher frequencies are normally perceived as louder. Note that for frequencies very much smaller than root the amplitudes can become very high. In this case limit the freqor use amp-comp-a Implements the (optimized) formula: compensationFactor = (root / freq) ** exp"]
    #[doc = ""]
    #[doc = "amplitude compensation: because higher frequencies are normally perceived as louder. Note that for frequencies very much smaller than root the amplitudes can become very high. In this case limit the freqor use amp-comp-a Implements the (optimized) formula: compensationFactor = (root / freq) ** exp"]
    AmpComp class r"AmpComp" {
        rates [ (ar, Audio), (kr, Control), (ir, Scalar) ]
        fields [
            #[doc = "Input frequency value. For freq == root, the output is 1.0."]
            input freq: UGenInput = UGenInput::Constant(261.6256),
            #[doc = "Root freq relative to which the curve is calculated (usually lowest freq)"]
            input root: UGenInput = UGenInput::Constant(261.6256),
            #[doc = "Exponent: how steep the curve decreases for increasing freq"]
            input exp: UGenInput = UGenInput::Constant(0.3333),
        ]
        outputs ( fixed 1 )
        push [ (input freq), (input root), (input exp) ]
    }
    #[doc = "Basic psychoacoustic amplitude compensation (ANSI A-weighting curve)."]
    #[doc = ""]
    #[doc = "Higher frequencies are normally perceived as louder, which amp-comp-a compensates. Following the measurings by Fletcher and Munson, the ANSI standard describes a function for loudness vs. frequency. Note that this curve is only valid for standardized amplitude. 1 For a simpler but more flexible curve, see amp-comp"]
    AmpCompA class r"AmpCompA" {
        rates [ (ar, Audio), (kr, Control), (ir, Scalar) ]
        fields [
            #[doc = "Input frequency value. For freq == root, the output is root-amp"]
            input freq: UGenInput = UGenInput::Constant(1000.0),
            #[doc = "Root freq relative to which the curve is calculated (usually lowest freq)"]
            input root: UGenInput = UGenInput::Constant(0.0),
            #[doc = "Amplitude at the minimum point of the curve (around 2512 Hz)"]
            input min_amp: UGenInput = UGenInput::Constant(0.32),
            #[doc = "Amplitude at the root frequency."]
            input root_amp: UGenInput = UGenInput::Constant(1.0),
        ]
        outputs ( fixed 1 )
        push [ (input freq), (input root), (input min_amp), (input root_amp) ]
    }
    #[doc = "outputs the initial value you give it."]
    DC class r"DC" {
        rates [ (ar, Audio), (kr, Control) ]
        fields [
            #[doc = "constant value to output, cannot be modulated, set at initialisation time"]
            input r#in: UGenInput = UGenInput::Constant(0.0),
        ]
        outputs ( fixed 1 )
        push [ (input r#in) ]
    }
    #[doc = "control rate to audio rate converter via linear interpolation."]
    K2A class r"K2A" {
        rates [ (ar, Audio) ]
        fields [
            #[doc = "input signal"]
            input r#in: UGenInput = UGenInput::Constant(0.0),
        ]
        outputs ( fixed 1 )
        push [ (input r#in) ]
    }
    #[doc = "Map a linear range to an exponential range"]
    #[doc = ""]
    #[doc = "Convert from a linear range to an exponential range. The dstlo and dsthi arguments must be nonzero and have the same sign."]
    LinExp class r"LinExp" {
        rates [ (ar, Audio), (kr, Control) ]
        fields [
            #[doc = "Input to convert"]
            input r#in: UGenInput = UGenInput::Constant(0.0),
            #[doc = "Lower limit of input range"]
            input srclo: UGenInput = UGenInput::Constant(0.0),
            #[doc = "Upper limit of input range"]
            input srchi: UGenInput = UGenInput::Constant(1.0),
            #[doc = "Lower limit of output range"]
            input dstlo: UGenInput = UGenInput::Constant(1.0),
            #[doc = "Upper limit of output range"]
            input dsthi: UGenInput = UGenInput::Constant(2.0),
        ]
        outputs ( fixed 1 )
        push [ (input r#in), (input srclo), (input srchi), (input dstlo), (input dsthi) ]
    }
    #[doc = "Line generator."]
    #[doc = ""]
    #[doc = "Generates a line from the start value to the end value."]
    Line class r"Line" {
        rates [ (ar, Audio), (kr, Control) ]
        fields [
            #[doc = "Starting value"]
            input start: UGenInput = UGenInput::Constant(0.0),
            #[doc = "Ending value"]
            input end: UGenInput = UGenInput::Constant(1.0),
            #[doc = "Duration in seconds"]
            input dur: UGenInput = UGenInput::Constant(1.0),
            #[doc = "A done action to be evaluated when the line is completed. Default: NO-ACTION"]
            input action: UGenInput = UGenInput::Constant(0.0),
        ]
        outputs ( fixed 1 )
        push [ (input start), (input end), (input dur), (input action) ]
    }
    #[doc = "Continuously outputs 0"]
    Silent class r"Silent" {
        rates [ (ar, Audio) ]
        fields [
            #[doc = "Number of channels of silence."]
            u32 num_channels: u32 = 1u32,
        ]
        outputs ( from num_channels )
        push [  ]
    }
    #[doc = "control rate trigger to audio rate trigger converter (maximally one per control period)."]
    T2A class r"T2A" {
        rates [ (ar, Audio) ]
        fields [
            #[doc = "input signal"]
            input r#in: UGenInput = UGenInput::Constant(0.0),
            #[doc = "sample offset within control period"]
            input offset: UGenInput = UGenInput::Constant(0.0),
        ]
        outputs ( fixed 1 )
        push [ (input r#in), (input offset) ]
    }
    #[doc = "audio rate trigger to control rate trigger converter. Uses the maxiumum trigger in the input during each control period."]
    T2K class r"T2K" {
        rates [ (kr, Control) ]
        fields [
            #[doc = "input signal"]
            input r#in: UGenInput = UGenInput::Constant(0.0),
        ]
        outputs ( fixed 1 )
        push [ (input r#in) ]
    }
    #[doc = "Exponential line generator."]
    #[doc = ""]
    #[doc = "Generates an exponential curve from the start value to the end value. Both the start and end values must be non-zero and have the same sign."]
    XLine class r"XLine" {
        rates [ (ar, Audio), (kr, Control) ]
        fields [
            #[doc = "Starting value"]
            input start: UGenInput = UGenInput::Constant(1.0),
            #[doc = "Ending value"]
            input end: UGenInput = UGenInput::Constant(2.0),
            #[doc = "Duration in seconds"]
            input dur: UGenInput = UGenInput::Constant(1.0),
            #[doc = "A done action to be evaluated when the line is completed. Default: NO-ACTION"]
            input action: UGenInput = UGenInput::Constant(0.0),
        ]
        outputs ( fixed 1 )
        push [ (input start), (input end), (input dur), (input action) ]
    }
}
