// @generated by packages/synthdef-compiler/scripts/generate-rust.ts from specs/ugens.json — do not edit.
// Regenerate with `yarn generate:synthdef-compiler`.

#![allow(
    non_camel_case_types,
    unused_mut,
    unused_variables,
    clippy::useless_conversion,
    clippy::needless_update
)]

use crate::{Rate, SynthDef, UGenInput};

sc_ugens! {
    #[doc = "models the path of a bouncing object that is reflected by a vibrating surface"]
    Ball class r"Ball" {
        rates [ (ar, Audio), (kr, Control) ]
        fields [
            #[doc = "modulated surface level"]
            input r#in: UGenInput = UGenInput::Constant(0.0),
            #[doc = "gravity"]
            input g: UGenInput = UGenInput::Constant(1.0),
            #[doc = "damping on impact"]
            input damp: UGenInput = UGenInput::Constant(0.0),
            #[doc = "proximity from which on attraction to surface starts"]
            input friction: UGenInput = UGenInput::Constant(0.01),
        ]
        outputs ( fixed 1 )
        push [ (input r#in), (input g), (input damp), (input friction) ]
    }
    #[doc = "A reverb coded from experiments with faust. Valid parameter range from 0 to 1. Values outside this range are clipped by the UGen."]
    FreeVerb class r"FreeVerb" {
        rates [ (ar, Audio) ]
        fields [
            #[doc = "The input signal"]
            input r#in: UGenInput = UGenInput::Constant(0.0),
            #[doc = "Dry/wet balance. range 0..1"]
            input mix: UGenInput = UGenInput::Constant(0.33),
            #[doc = "Room size. rage 0..1"]
            input room: UGenInput = UGenInput::Constant(0.5),
            #[doc = "Reverb HF damp. range 0..1"]
            input damp: UGenInput = UGenInput::Constant(0.5),
        ]
        outputs ( fixed 1 )
        push [ (input r#in), (input mix), (input room), (input damp) ]
    }
    #[doc = "A two-channel reverb coded from experiments with faust. Valid parameter range from 0 to 1. Values outside this range are clipped by the UGen."]
    FreeVerb2 class r"FreeVerb2" {
        rates [ (ar, Audio) ]
        fields [
            #[doc = "Input signal channel 1"]
            input r#in: UGenInput = UGenInput::Constant(0.0),
            #[doc = "Input signal channel 2"]
            input in2: UGenInput = UGenInput::Constant(0.0),
            #[doc = "Dry/wet balance. range 0..1"]
            input mix: UGenInput = UGenInput::Constant(0.33),
            #[doc = "Room size. rage 0..1"]
            input room: UGenInput = UGenInput::Constant(0.5),
            #[doc = "Reverb HF damp. range 0..1"]
            input damp: UGenInput = UGenInput::Constant(0.5),
        ]
        outputs ( fixed 2 )
        push [ (input r#in), (input in2), (input mix), (input room), (input damp) ]
    }
    #[doc = "FreqShift implements single sideband amplitude modulation, also known as frequency shifting, but not to be confused with pitch shifting. Frequency shifting moves all the components of a signal by a fixed amount but does not preserve the original harmonic relationships."]
    FreqShift class r"FreqShift" {
        rates [ (ar, Audio) ]
        fields [
            #[doc = "The signal to process"]
            input r#in: UGenInput = UGenInput::Constant(0.0),
            #[doc = "Amount of shift in cycles per second"]
            input freq: UGenInput = UGenInput::Constant(0.0),
            #[doc = "Phase of the frequency shift (0 - 2pi)"]
            input phase: UGenInput = UGenInput::Constant(0.0),
        ]
        outputs ( fixed 1 )
        push [ (input r#in), (input freq), (input phase) ]
    }
    #[doc = "A two-channel reverb UGen, based on the \\\"GVerb\\\" LADSPA effect by Juhana Sadeharju (kouhia at nic.funet.fi). WARNING - in the current version of the server, there are severe noise issues when you attempt to modify the roomsize or set it to a value greater than 40."]
    GVerb class r"GVerb" {
        rates [ (ar, Audio) ]
        fields [
            #[doc = "mono input"]
            input r#in: UGenInput = UGenInput::Constant(0.0),
            #[doc = "in squared meters."]
            input roomsize: UGenInput = UGenInput::Constant(10.0),
            #[doc = "in seconds"]
            input revtime: UGenInput = UGenInput::Constant(3.0),
            #[doc = "0 to 1, high frequency rolloff, 0 damps the reverb signal completely, 1 not at all"]
            input damping: UGenInput = UGenInput::Constant(0.5),
            #[doc = "0 to 1, same as damping control, but on the input signal"]
            input inputbw: UGenInput = UGenInput::Constant(0.5),
            #[doc = "a control on the stereo spread and diffusion of the reverb signal"]
            input spread: UGenInput = UGenInput::Constant(15.0),
            #[doc = "amount of dry signal"]
            input drylevel: UGenInput = UGenInput::Constant(1.0),
            #[doc = "amount of early reflection level"]
            input earlyreflevel: UGenInput = UGenInput::Constant(0.7),
            #[doc = "amount of tail level"]
            input taillevel: UGenInput = UGenInput::Constant(0.5),
            #[doc = "to set the size of the delay lines."]
            input maxroomsize: UGenInput = UGenInput::Constant(300.0),
        ]
        outputs ( fixed 2 )
        push [ (input r#in), (input roomsize), (input revtime), (input damping), (input inputbw), (input spread), (input drylevel), (input earlyreflevel), (input taillevel), (input maxroomsize) ]
    }
    #[doc = "An implementation of the dynamic stochastic synthesis generator conceived by Iannis Xenakis and described in Formalized Music (1992, Stuyvesant, NY: Pendragon Press) chapter 9 (pp 246-254) and chapters 13 and 14 (pp 289-322). The BASIC program in the book was written by Marie-Helene Serra so I think it helpful to credit her too. The program code has been adapted to avoid infinities in the probability distribution functions. The distributions are hard-coded in C but there is an option to have new amplitude or time breakpoints sampled from a continuous controller input."]
    Gendy1 class r"Gendy1" {
        rates [ (ar, Audio), (kr, Control) ]
        fields [
            #[doc = "Choice of probability distribution for the next perturbation of the amplitude of a control point. The distributions are (adapted from the GENDYN program in Formalized Music): 0- LINEAR,1- CAUCHY, 2- LOGIST, 3- HYPERBCOS, 4- ARCSINE, 5- EXPON, 6- SINUS, Where the sinus (Xenakis' name) is in this implementation taken as sampling from a third party oscillator. See example below."]
            input ampdist: UGenInput = UGenInput::Constant(1.0),
            #[doc = "Choice of distribution for the perturbation of the current inter control point duration."]
            input durdist: UGenInput = UGenInput::Constant(1.0),
            #[doc = "A parameter for the shape of the amplitude probability distribution, requires values in the range 0.0001 to 1 (there are safety checks in the code so don't worry too much if you want to modulate!)"]
            input adparam: UGenInput = UGenInput::Constant(1.0),
            #[doc = "A parameter for the shape of the duration probability distribution, requires values in the range 0.0001 to 1"]
            input ddparam: UGenInput = UGenInput::Constant(1.0),
            #[doc = "Minimum allowed frequency of oscillation for the Gendy1 oscillator, so gives the largest period the duration is allowed to take on."]
            input minfreq: UGenInput = UGenInput::Constant(440.0),
            #[doc = "Maximum allowed frequency of oscillation for the Gendy1 oscillator, so gives the smallest period the duration is allowed to take on."]
            input maxfreq: UGenInput = UGenInput::Constant(660.0),
            #[doc = "Normally 0.0 to 1.0, multiplier for the distribution's delta value for amplitude. An ampscale of 1.0 allows the full range of -1 to 1 for a change of amplitude."]
            input ampscale: UGenInput = UGenInput::Constant(0.5),
            #[doc = "Normally 0.0 to 1.0, multiplier for the distribution's delta value for duration. An ampscale of 1.0 allows the full range of -1 to 1 for a change of duration."]
            input durscale: UGenInput = UGenInput::Constant(0.5),
            #[doc = "Initialise the number of control points in the memory. Xenakis specifies 12. There would be this number of control points per cycle of the oscillator, though the oscillator's period will constantly change due to the duration distribution."]
            input init_cps: UGenInput = UGenInput::Constant(12.0),
            #[doc = "Current number of utilised control points, allows modulation."]
            input knum: UGenInput = UGenInput::Constant(12.0),
        ]
        outputs ( fixed 1 )
        push [ (input ampdist), (input durdist), (input adparam), (input ddparam), (input minfreq), (input maxfreq), (input ampscale), (input durscale), (input init_cps), (input knum) ]
    }
    #[doc = "See gendy1 help file for background. This variant of GENDYN is closer to that presented in Hoffmann, Peter. (2000) The New GENDYN Program. Computer Music Journal 24:2, pp 31-38."]
    Gendy2 class r"Gendy2" {
        rates [ (ar, Audio), (kr, Control) ]
        fields [
            #[doc = "Choice of probability distribution for the next perturbation of the amplitude of a control point. The distributions are (adapted from the GENDYN program in Formalized Music): 0- LINEAR, 1- CAUCHY, 2- LOGIST, 3- HYPERBCOS, 4- ARCSINE, 5- EXPON, 6- SINUS, Where the sinus (Xenakis' name) is in this implementation taken as sampling from a third party oscillator."]
            input ampdist: UGenInput = UGenInput::Constant(1.0),
            #[doc = "Choice of distribution for the perturbation of the current inter control point duration."]
            input durdist: UGenInput = UGenInput::Constant(1.0),
            #[doc = "A parameter for the shape of the amplitude probability distribution, requires values in the range 0.0001 to 1 (there are safety checks in the code so don't worry too much if you want to modulate!)"]
            input adparam: UGenInput = UGenInput::Constant(1.0),
            #[doc = "A parameter for the shape of the duration probability distribution, requires values in the range 0.0001 to 1"]
            input ddparam: UGenInput = UGenInput::Constant(1.0),
            #[doc = "Minimum allowed frequency of oscillation for the Gendy1 oscillator, so gives the largest period the duration is allowed to take on."]
            input minfreq: UGenInput = UGenInput::Constant(440.0),
            #[doc = "Maximum allowed frequency of oscillation for the Gendy1 oscillator, so gives the smallest period the duration is allowed to take on."]
            input maxfreq: UGenInput = UGenInput::Constant(660.0),
            #[doc = "Normally 0.0 to 1.0, multiplier for the distribution's delta value for amplitude. An ampscale of 1.0 allows the full range of -1 to 1 for a change of amplitude."]
            input ampscale: UGenInput = UGenInput::Constant(0.5),
            #[doc = "Normally 0.0 to 1.0, multiplier for the distribution's delta value for duration. An ampscale of 1.0 allows the full range of -1 to 1 for a change of duration."]
            input durscale: UGenInput = UGenInput::Constant(0.5),
            #[doc = "Initialise the number of control points in the memory. Xenakis specifies 12. There would be this number of control points per cycle of the oscillator, though the oscillator's period will constantly change due to the duration distribution."]
            input init_cps: UGenInput = UGenInput::Constant(12.0),
            #[doc = "Current number of utilised control points, allows modulation."]
            input knum: UGenInput = UGenInput::Constant(12.0),
            #[doc = "parameter for Lehmer random number generator perturbed by Xenakis as in ((old*a)+c)%1.0"]
            input a: UGenInput = UGenInput::Constant(1.17),
            #[doc = "parameter for Lehmer random number generator perturbed by Xenakis"]
            input c: UGenInput = UGenInput::Constant(0.31),
        ]
        outputs ( fixed 1 )
        push [ (input ampdist), (input durdist), (input adparam), (input ddparam), (input minfreq), (input maxfreq), (input ampscale), (input durscale), (input init_cps), (input knum), (input a), (input c) ]
    }
    #[doc = "See Gendy1 help file for background. This variant of GENDYN normalises the durations in each period to force oscillation at the desired pitch. The breakpoints still get perturbed as in Gendy1. There is some glitching in the oscillator caused by the stochastic effects: control points as they vary cause big local jumps of amplitude. Put ampscale and durscale low to minimise this. All parameters can be modulated at control rate except for initCPs which is used only at initialisation."]
    Gendy3 class r"Gendy3" {
        rates [ (ar, Audio), (kr, Control) ]
        fields [
            #[doc = "Choice of probability distribution for the next perturbation of the amplitude of a control point. The distributions are (adapted from the GENDYN program in Formalized Music): 0- LINEAR,1- CAUCHY, 2- LOGIST, 3- HYPERBCOS, 4- ARCSINE, 5- EXPON, 6- SINUS, Where the sinus (Xenakis' name) is in this implementation taken as sampling from a third party oscillator."]
            input ampdist: UGenInput = UGenInput::Constant(1.0),
            #[doc = "Choice of distribution for the perturbation of the current inter control point duration."]
            input durdist: UGenInput = UGenInput::Constant(1.0),
            #[doc = "A parameter for the shape of the amplitude probability distribution, requires values in the range 0.0001 to 1 (there are safety checks in the code so don't worry too much if you want to modulate!)"]
            input adparam: UGenInput = UGenInput::Constant(1.0),
            #[doc = "A parameter for the shape of the duration probability distribution, requires values in the range 0.0001 to 1"]
            input ddparam: UGenInput = UGenInput::Constant(1.0),
            #[doc = "Oscillation frquency."]
            input freq: UGenInput = UGenInput::Constant(440.0),
            #[doc = "Normally 0.0 to 1.0, multiplier for the distribution's delta value for amplitude. An ampscale of 1.0 allows the full range of -1 to 1 for a change of amplitude."]
            input ampscale: UGenInput = UGenInput::Constant(0.5),
            #[doc = "Normally 0.0 to 1.0, multiplier for the distribution's delta value for duration. An ampscale of 1.0 allows the full range of -1 to 1 for a change of duration."]
            input durscale: UGenInput = UGenInput::Constant(0.5),
            #[doc = "Initialise the number of control points in the memory. Xenakis specifies 12. There would be this number of control points per cycle of the oscillator, though the oscillator's period will constantly change due to the duration distribution."]
            input init_cps: UGenInput = UGenInput::Constant(12.0),
            #[doc = "Current number of utilised control points, allows modulation."]
            input knum: UGenInput = UGenInput::Constant(12.0),
        ]
        outputs ( fixed 1 )
        push [ (input ampdist), (input durdist), (input adparam), (input ddparam), (input freq), (input ampscale), (input durscale), (input init_cps), (input knum) ]
    }
    Hilbert class r"Hilbert" {
        rates [ (ar, Audio) ]
        fields [
            input r#in: UGenInput = UGenInput::Constant(0.0),
        ]
        outputs ( fixed 2 )
        push [ (input r#in) ]
    }
    #[doc = "A digital implementation of the Moog VCF (filter)."]
    MoogFF class r"MoogFF" {
        rates [ (ar, Audio), (kr, Control) ]
        fields [
            #[doc = "The input signal"]
            input r#in: UGenInput = UGenInput::Constant(0.0),
            #[doc = "The cutoff frequency"]
            input freq: UGenInput = UGenInput::Constant(100.0),
            #[doc = "The filter resonance gain, between zero and 4"]
            input gain: UGenInput = UGenInput::Constant(2.0),
            #[doc = "When greater than zero, this will reset the state of the digital filters at the beginning of a computational block."]
            input reset: UGenInput = UGenInput::Constant(0.0),
        ]
        outputs ( fixed 1 )
        push [ (input r#in), (input freq), (input gain), (input reset) ]
    }
    #[doc = "Partitioned convolution. Various additional buffers must be supplied. Mono impulse response only! If inputting multiple channels, you'll need independent PartConvs, one for each channel. But the charm is: impulse response can be as large as you like (CPU load increases with IR size. Various tradeoffs based on fftsize choice, due to rarer but larger FFTs. This plug-in uses amortisation to spread processing and avoid spikes). Normalisation factors difficult to anticipate; convolution piles up multiple copies of the input on top of itself, so can easily overload."]
    PartConv class r"PartConv" {
        rates [ (ar, Audio) ]
        fields [
            #[doc = "Processing target."]
            input r#in: UGenInput = UGenInput::Constant(0.0),
            #[doc = "Spectral convolution partition size (twice partition size). You must ensure that the blocksize divides the partition size and there are at least two blocks per partition (to allow for amortisation)"]
            input fftsize: UGenInput = UGenInput::Constant(0.0),
            #[doc = "Prepared buffer of spectra for each partition of the inpulse response"]
            input irbufnum: UGenInput = UGenInput::Constant(0.0),
        ]
        outputs ( fixed 1 )
        push [ (input r#in), (input fftsize), (input irbufnum) ]
    }
    #[doc = "A time domain granular pitch shifter. Grains have a triangular amplitude envelope and an overlap of 4:1."]
    PitchShift class r"PitchShift" {
        rates [ (ar, Audio) ]
        fields [
            #[doc = "The input signal."]
            input r#in: UGenInput = UGenInput::Constant(0.0),
            #[doc = "The size of the grain window in seconds. This value cannot be modulated."]
            input window_size: UGenInput = UGenInput::Constant(0.2),
            #[doc = "The ratio of the pitch shift. Must be from 0.0 to 4.0"]
            input pitch_ratio: UGenInput = UGenInput::Constant(1.0),
            #[doc = "The maximum random deviation of the pitch from the pitchRatio."]
            input pitch_dispersion: UGenInput = UGenInput::Constant(0.0),
            #[doc = "A random offset of from zero to timeDispersion seconds is added to the delay of each grain. Use of some dispersion can alleviate a hard comb filter effect due to uniform grain placement. It can also be an effect in itself. timeDispersion can be no larger than windowSize."]
            input time_dispersion: UGenInput = UGenInput::Constant(0.0),
        ]
        outputs ( fixed 1 )
        push [ (input r#in), (input window_size), (input pitch_ratio), (input pitch_dispersion), (input time_dispersion) ]
    }
    #[doc = "Implements the Karplus-Strong style of synthesis, where a delay line (normally starting with noise) is filtered and fed back on itself so that over time it becomes periodic."]
    Pluck class r"Pluck" {
        rates [ (ar, Audio) ]
        fields [
            #[doc = "An excitation signal."]
            input r#in: UGenInput = UGenInput::Constant(0.0),
            #[doc = "Upon a negative to positive transition, the excitation signal will be fed into the delay line."]
            input trig: UGenInput = UGenInput::Constant(1.0),
            #[doc = "The max delay time in seconds (initializes the internal delay buffer)."]
            input maxdelaytime: UGenInput = UGenInput::Constant(0.2),
            #[doc = "Delay time in seconds."]
            input delaytime: UGenInput = UGenInput::Constant(0.2),
            #[doc = "Time for the echoes to decay by 60 decibels. Negative times emphasize odd partials."]
            input decaytime: UGenInput = UGenInput::Constant(1.0),
            #[doc = "The coef of the internal OnePole filter. Values should be between -1 and +1 (larger values will be unstable... so be careful!)."]
            input coef: UGenInput = UGenInput::Constant(0.5),
        ]
        outputs ( fixed 1 )
        push [ (input r#in), (input trig), (input maxdelaytime), (input delaytime), (input decaytime), (input coef) ]
    }
    #[doc = "Physical model of resonating spring"]
    Spring class r"Spring" {
        rates [ (ar, Audio), (kr, Control) ]
        fields [
            #[doc = "Modulated input force"]
            input r#in: UGenInput = UGenInput::Constant(0.0),
            #[doc = "Spring constant (incl. mass)"]
            input spring: UGenInput = UGenInput::Constant(1.0),
            #[doc = "Damping"]
            input damp: UGenInput = UGenInput::Constant(0.0),
        ]
        outputs ( fixed 1 )
        push [ (input r#in), (input spring), (input damp) ]
    }
    #[doc = "models the impacts of a bouncing object that is reflected by a vibrating surface"]
    TBall class r"TBall" {
        rates [ (ar, Audio), (kr, Control) ]
        fields [
            #[doc = "modulated surface level"]
            input r#in: UGenInput = UGenInput::Constant(0.0),
            #[doc = "gravity"]
            input g: UGenInput = UGenInput::Constant(10.0),
            #[doc = "damping on impact"]
            input damp: UGenInput = UGenInput::Constant(0.0),
            #[doc = "proximity from which on attraction to surface starts"]
            input friction: UGenInput = UGenInput::Constant(0.01),
        ]
        outputs ( fixed 1 )
        push [ (input r#in), (input g), (input damp), (input friction) ]
    }
}
