// @generated by packages/synthdef-compiler/scripts/generate-rust.ts from specs/ugens.json — do not edit.
// Regenerate with `yarn generate:synthdef-compiler`.

#![allow(
    non_camel_case_types,
    unused_mut,
    unused_variables,
    clippy::useless_conversion,
    clippy::needless_update
)]

use crate::{Rate, SynthDef, UGenInput};

sc_ugens! {
    #[doc = "Noise whose spectrum falls off in power by 6 dB per octave."]
    #[doc = ""]
    #[doc = "Useful for generating percussive sounds such as snares and hand claps. Also useful for simulating wind or sea effects, for producing breath effects in wind instrument timbres or for producing the typical trance leads."]
    BrownNoise class r"BrownNoise" {
        rates [ (ar, Audio), (kr, Control) ]
        fields [
        ]
        outputs ( fixed 1 )
        push [  ]
    }
    #[doc = "Noise whose values are either -1 or 1."]
    #[doc = ""]
    #[doc = "This produces the maximum energy for the least peak to peak amplitude. Useful for generating percussive sounds such as snares and hand claps. Also useful for simulating wind or sea effects, for producing breath effects in wind instrument timbres or for producing the typical trance leads."]
    ClipNoise class r"ClipNoise" {
        rates [ (ar, Audio), (kr, Control) ]
        fields [
        ]
        outputs ( fixed 1 )
        push [  ]
    }
    #[doc = "Chaotic noise generator"]
    #[doc = ""]
    #[doc = "A noise generator based on a chaotic function. Useful for generating percussive sounds such as snares and hand claps. Also useful for simulating wind or sea effects, for producing breath effects in wind instrument timbres or for producing the typical trance leads."]
    Crackle class r"Crackle" {
        rates [ (ar, Audio), (kr, Control) ]
        fields [
            #[doc = "a parameter of the chaotic function with useful values from just below 1.0 to just above 2.0. Towards 2.0 the sound crackles."]
            input chaos_param: UGenInput = UGenInput::Constant(1.5),
        ]
        outputs ( fixed 1 )
        push [ (input chaos_param) ]
    }
    #[doc = "Generates random impulses from 0 to +1."]
    Dust class r"Dust" {
        rates [ (ar, Audio), (kr, Control) ]
        fields [
            #[doc = "average number of impulses per second"]
            input density: UGenInput = UGenInput::Constant(0.0),
        ]
        outputs ( fixed 1 )
        push [ (input density) ]
    }
    #[doc = "Generates random impulses from -1 to +1."]
    Dust2 class r"Dust2" {
        rates [ (ar, Audio), (kr, Control) ]
        fields [
            #[doc = "average number of impulses per second."]
            input density: UGenInput = UGenInput::Constant(0.0),
        ]
        outputs ( fixed 1 )
        push [ (input density) ]
    }
    #[doc = "Random impulses from -1 to +1 given a density"]
    #[doc = ""]
    #[doc = "Creates a sequence of random impulses from -1 to +1. Generates noise which results from flipping random bits in a word. This type of noise has a high RMS level relative to its peak to peak level. The spectrum is emphasized towards lower frequencies. Useful for generating percussive sounds such as snares and hand claps. Also useful for simulating wind or sea effects, for producing breath effects in wind instrument timbres or for producing the typical trance leads."]
    GrayNoise class r"GrayNoise" {
        rates [ (ar, Audio), (kr, Control) ]
        fields [
        ]
        outputs ( fixed 1 )
        push [  ]
    }
    #[doc = "Returns a unique output value from zero to one for each input value according to a hash function. The same input value will always produce the same output value. The input need not be from zero to one."]
    Hasher class r"Hasher" {
        rates [ (ar, Audio), (kr, Control) ]
        fields [
            #[doc = "input signal"]
            input r#in: UGenInput = UGenInput::Constant(0.0),
        ]
        outputs ( fixed 1 )
        push [ (input r#in) ]
    }
    #[doc = "Randomly generates the values -1 or +1 at a rate given by the nearest integer division of the sample rate by the freq argument. It is probably pretty hard on your speakers!"]
    LFClipNoise class r"LFClipNoise" {
        rates [ (ar, Audio), (kr, Control) ]
        fields [
            #[doc = "approximate rate at which to generate random values."]
            input freq: UGenInput = UGenInput::Constant(500.0),
        ]
        outputs ( fixed 1 )
        push [ (input freq) ]
    }
    #[doc = "Like lf-clip-noise, it generates the values -1 or +1 at a rate given by the freq argument, with two differences: * no time quantization * fast recovery from low freq values. (lf-clip-noise, as well as lf-noise0,1,2 quantize to the nearest integer division of the samplerate, and they poll the freq argument only when scheduled; thus they often seem to hang when freqs get very low). If you don't need very high or very low freqs, or use fixed freqs lf-noise0 is more efficient."]
    LFDClipNoise class r"LFDClipNoise" {
        rates [ (ar, Audio), (kr, Control) ]
        fields [
            #[doc = "rate at which to generate random values."]
            input freq: UGenInput = UGenInput::Constant(500.0),
        ]
        outputs ( fixed 1 )
        push [ (input freq) ]
    }
    #[doc = "Like lf-noise0, it generates random values between -1 and 1 at a rate given by the freq argument, with two differences: p * no time quantization * fast recovery from low freq values. (lf-noise0,1,2 quantize to the nearest integer division of the samplerate and they poll the freq argument only when scheduled, and thus seem to hang when freqs get very low). If you don't need very high or very low freqs, or use fixed freqs lf-noise0 is more efficient."]
    LFDNoise0 class r"LFDNoise0" {
        rates [ (ar, Audio), (kr, Control) ]
        fields [
            #[doc = "rate at which to generate random values."]
            input freq: UGenInput = UGenInput::Constant(500.0),
        ]
        outputs ( fixed 1 )
        push [ (input freq) ]
    }
    #[doc = "Like lf-noise1, it generates linearly interpolated random values between -1 and 1 at a rate given by the freq argument, with two differences: * no time quantization * fast recovery from low freq values. (lf-noise0,1,2 quantize to the nearest integer division of the samplerate and they poll the freq argument only when scheduled, and thus seem to hang when freqs get very low). If you don't need very high or very low freqs, or use fixed freqs lf-noise1 is more efficient."]
    LFDNoise1 class r"LFDNoise1" {
        rates [ (ar, Audio), (kr, Control) ]
        fields [
            #[doc = "rate at which to generate random values."]
            input freq: UGenInput = UGenInput::Constant(500.0),
        ]
        outputs ( fixed 1 )
        push [ (input freq) ]
    }
    #[doc = "Similar to lf-noise2, it generates polynomially interpolated random values between -1 and 1 at a rate given by the freq argument, with 3 differences: * no time quantization * fast recovery from low freq values * cubic instead of quadratic interpolation (lf-noise0,1,2 quantize to the nearest integer division of the samplerate and they poll the freq argument only when scheduled, and thus seem to hang when freqs get very low). If you don't need very high or very low freqs, or use fixed freqs lf-noise2 is more efficient."]
    LFDNoise3 class r"LFDNoise3" {
        rates [ (ar, Audio), (kr, Control) ]
        fields [
            #[doc = "rate at which to generate random values."]
            input freq: UGenInput = UGenInput::Constant(500.0),
        ]
        outputs ( fixed 1 )
        push [ (input freq) ]
    }
    #[doc = "Generates random values between -1 and 1 at a rate (the rate is not guaranteed but approximate)"]
    LFNoise0 class r"LFNoise0" {
        rates [ (ar, Audio), (kr, Control) ]
        fields [
            #[doc = "approximate rate at which to generate random values."]
            input freq: UGenInput = UGenInput::Constant(500.0),
        ]
        outputs ( fixed 1 )
        push [ (input freq) ]
    }
    #[doc = "Generates linearly interpolated random values between -1 and 1 at the supplied rate (the rate is not guaranteed but approximate)."]
    LFNoise1 class r"LFNoise1" {
        rates [ (ar, Audio), (kr, Control) ]
        fields [
            #[doc = "approximate rate at which to generate random values."]
            input freq: UGenInput = UGenInput::Constant(500.0),
        ]
        outputs ( fixed 1 )
        push [ (input freq) ]
    }
    #[doc = "Generates quadratically interpolated random values between -1 and 1 at the supplied rate (the rate is not guaranteed but approximate). Note: quadratic interpolation means that the noise values can occasionally extend beyond the normal range of +-1, if the freq varies in certain ways. If this is undesirable then you might like to clip2 the values or use a linearly-interpolating unit instead."]
    LFNoise2 class r"LFNoise2" {
        rates [ (ar, Audio), (kr, Control) ]
        fields [
            #[doc = "approximate rate at which to generate random values."]
            input freq: UGenInput = UGenInput::Constant(500.0),
        ]
        outputs ( fixed 1 )
        push [ (input freq) ]
    }
    #[doc = "A noise generator based on the logistic map: y = chaos-param * y * (1.0 - y) y will stay in the range of 0.0 to 1.0 for normal values of the chaos-param. This leads to a DC offset and may cause a pop when you stop the Synth. For output you might want to combine this UGen with a LeakDC or rescale around 0.0 via mul and add: see example below."]
    Logistic class r"Logistic" {
        rates [ (ar, Audio), (kr, Control) ]
        fields [
            #[doc = "a parameter of the chaotic function with useful values from 0.0 to 4.0. Chaos occurs from 3.57 up. Don't use values outside this range if you don't want the UGen to blow up."]
            input chaos_param: UGenInput = UGenInput::Constant(3.0),
            #[doc = "Frequency of calculation; if over the sampling rate, this is clamped to the sampling rate"]
            input freq: UGenInput = UGenInput::Constant(1000.0),
            #[doc = "Initial value of y (see equation below)"]
            input init: UGenInput = UGenInput::Constant(0.5),
        ]
        outputs ( fixed 1 )
        push [ (input chaos_param), (input freq), (input init) ]
    }
    #[doc = "Masks off bits in the mantissa of the floating point sample value. This introduces a quantization noise, but is less severe than linearly quantizing the signal."]
    MantissaMask class r"MantissaMask" {
        rates [ (ar, Audio), (kr, Control) ]
        fields [
            #[doc = "input signal"]
            input r#in: UGenInput = UGenInput::Constant(0.0),
            #[doc = "the number of mantissa bits to preserve. a number from 0 to 23."]
            input bits: UGenInput = UGenInput::Constant(3.0),
        ]
        outputs ( fixed 1 )
        push [ (input r#in), (input bits) ]
    }
    #[doc = "Noise whose spectrum falls off in power by 3 dB per octave."]
    #[doc = ""]
    #[doc = "Noise that gives equal power over the span of each octave. Useful for generating percussive sounds such as snares and hand claps. Also useful for simulating wind or sea effects, for producing breath effects in wind instrument timbres or for producing the typical trance leads. This version gives 8 octaves of pink noise."]
    PinkNoise class r"PinkNoise" {
        rates [ (ar, Audio), (kr, Control) ]
        fields [
        ]
        outputs ( fixed 1 )
        push [  ]
    }
    #[doc = "Noise whose spectrum has equal power at all frequencies."]
    #[doc = ""]
    #[doc = "Noise that contains equal amounts of energy at every frequency - comparable to radio static. Useful for generating percussive sounds such as snares and hand claps. Also useful for simulating wind or sea effects, for producing breath effects in wind instrument timbres or for producing the typical trance leads."]
    WhiteNoise class r"WhiteNoise" {
        rates [ (ar, Audio), (kr, Control) ]
        fields [
        ]
        outputs ( fixed 1 )
        push [  ]
    }
}
