// @generated by packages/synthdef-compiler/scripts/generate-rust.ts from specs/ugens.json — do not edit.
// Regenerate with `yarn generate:synthdef-compiler`.

#![allow(
    non_camel_case_types,
    unused_mut,
    unused_variables,
    clippy::useless_conversion,
    clippy::needless_update
)]

use crate::{Rate, SynthDef, UGenInput};

sc_ugens! {
    #[doc = "When it receives a trigger, it tosses a coin, and either passes the trigger or doesn't."]
    CoinGate class r"CoinGate" {
        rates [ (ar, Audio), (kr, Control) ]
        fields [
            #[doc = "Value between 0 and 1 determines probability of either possibilities"]
            input prob: UGenInput = UGenInput::Constant(0.0),
            #[doc = "Trigger signal"]
            input trig: UGenInput = UGenInput::Constant(0.0),
        ]
        outputs ( fixed 1 )
        push [ (input prob), (input trig) ]
    }
    #[doc = "Generates a single random float value in an exponential distributions from lo to hi."]
    ExpRand class r"ExpRand" {
        rates [ (ir, Scalar) ]
        fields [
            #[doc = "Minimum value of generated float"]
            input lo: UGenInput = UGenInput::Constant(0.01),
            #[doc = "Maximum value of generated float"]
            input hi: UGenInput = UGenInput::Constant(1.0),
        ]
        outputs ( fixed 1 )
        push [ (input lo), (input hi) ]
    }
    #[doc = "Generates a single random integer value in uniform distribution from lo to hi"]
    IRand class r"IRand" {
        rates [ (ir, Scalar) ]
        fields [
            #[doc = "Minimum value of generated integer"]
            input lo: UGenInput = UGenInput::Constant(0.0),
            #[doc = "Maximum value of generated integer"]
            input hi: UGenInput = UGenInput::Constant(127.0),
        ]
        outputs ( fixed 1 )
        push [ (input lo), (input hi) ]
    }
    #[doc = "Generates a single random float value in linear distribution from lo to hi, skewed towards lo if minmax < 0, otherwise skewed towards hi."]
    LinRand class r"LinRand" {
        rates [ (ir, Scalar) ]
        fields [
            #[doc = "Minimum value of generated float"]
            input lo: UGenInput = UGenInput::Constant(0.0),
            #[doc = "Maximum value of generated float"]
            input hi: UGenInput = UGenInput::Constant(1.0),
            #[doc = "Skew direction (towards lo if negative otherwise hi)"]
            input minmax: UGenInput = UGenInput::Constant(0.0),
        ]
        outputs ( fixed 1 )
        push [ (input lo), (input hi), (input minmax) ]
    }
    #[doc = "Generates a single random float value in a sum of n uniform distributions from lo to hi. n = 1 : uniform distribution - same as Rand n = 2 : triangular distribution n = 3 : smooth hump As n increases, distribution converges towards gaussian"]
    NRand class r"NRand" {
        rates [ (ir, Scalar) ]
        fields [
            #[doc = "Minimum value of generated float"]
            input lo: UGenInput = UGenInput::Constant(0.0),
            #[doc = "Maximum value of generated float"]
            input hi: UGenInput = UGenInput::Constant(1.0),
            #[doc = "Distribution choice"]
            input n: UGenInput = UGenInput::Constant(0.0),
        ]
        outputs ( fixed 1 )
        push [ (input lo), (input hi), (input n) ]
    }
    Rand class r"Rand" {
        rates [ (ir, Scalar) ]
        fields [
            input lo: UGenInput = UGenInput::Constant(0.0),
            input hi: UGenInput = UGenInput::Constant(1.0),
        ]
        outputs ( fixed 1 )
        push [ (input lo), (input hi) ]
    }
    #[doc = "Choose which random number generator to use for this synth. All synths that use the same generator reproduce the same sequence of numbers when the same seed is set again."]
    RandID class r"RandID" {
        rates [ (kr, Control), (ir, Scalar) ]
        fields [
            #[doc = "Seed id"]
            input seed: UGenInput = UGenInput::Constant(0.0),
        ]
        outputs ( fixed 1 )
        push [ (input seed) ]
    }
    #[doc = "When the trigger signal changes from nonpositive to positive, the synth's random generator seed is reset to the given value. All synths that use the same random number generator reproduce the same sequence of numbers again."]
    RandSeed class r"RandSeed" {
        rates [ (ar, Audio), (kr, Control), (ir, Scalar) ]
        fields [
            #[doc = "Trigger signal"]
            input trig: UGenInput = UGenInput::Constant(0.0),
            #[doc = "Seed value"]
            input seed: UGenInput = UGenInput::Constant(56789.0),
        ]
        outputs ( fixed 1 )
        push [ (input trig), (input seed) ]
    }
    #[doc = "Generates a random float value in exponential distribution from lo to hi each time the trig signal changes from nonpositive to positive values lo and hi must both have the same sign and be non-zero."]
    TExpRand class r"TExpRand" {
        rates [ (ar, Audio), (kr, Control) ]
        fields [
            #[doc = "Minimum value of generated float"]
            input lo: UGenInput = UGenInput::Constant(0.01),
            #[doc = "Maximum value of generated float"]
            input hi: UGenInput = UGenInput::Constant(1.0),
            #[doc = "Trigger signal"]
            input trig: UGenInput = UGenInput::Constant(0.0),
        ]
        outputs ( fixed 1 )
        push [ (input lo), (input hi), (input trig) ]
    }
    #[doc = "Generates a random integer value in uniform distribution from lo to hi each time the trig signal changes from nonpositive to positive values"]
    TIRand class r"TIRand" {
        rates [ (ar, Audio), (kr, Control) ]
        fields [
            #[doc = "Minimum value of generated integer"]
            input lo: UGenInput = UGenInput::Constant(0.0),
            #[doc = "Maximum value of generated integer"]
            input hi: UGenInput = UGenInput::Constant(127.0),
            #[doc = "Trigger signal"]
            input trig: UGenInput = UGenInput::Constant(0.0),
        ]
        outputs ( fixed 1 )
        push [ (input lo), (input hi), (input trig) ]
    }
    #[doc = "Generates a random float value in uniform distribution from lo to hi each time the trig signal changes from nonpositive to positive values"]
    TRand class r"TRand" {
        rates [ (ar, Audio), (kr, Control) ]
        fields [
            #[doc = "Minimum value of generated float"]
            input lo: UGenInput = UGenInput::Constant(0.0),
            #[doc = "Maximum value of generated float"]
            input hi: UGenInput = UGenInput::Constant(1.0),
            #[doc = "Trigger signal"]
            input trig: UGenInput = UGenInput::Constant(0.0),
        ]
        outputs ( fixed 1 )
        push [ (input lo), (input hi), (input trig) ]
    }
}
