// @generated by packages/synthdef-compiler/scripts/generate-rust.ts from specs/ugens.json — do not edit.
// Regenerate with `yarn generate:synthdef-compiler`.

#![allow(
    non_camel_case_types,
    unused_mut,
    unused_variables,
    clippy::useless_conversion,
    clippy::needless_update
)]

use crate::{Rate, SynthDef, UGenInput};

sc_ugens! {
    #[doc = "Clip a signal outside given thresholds."]
    #[doc = ""]
    #[doc = "Clip a signal outside given thresholds. This differs from the ugen clip2 in that it allows one to set both low and high thresholds."]
    Clip class r"Clip" {
        rates [ (ar, Audio), (kr, Control) ]
        fields [
            #[doc = "The signal to be clipped"]
            input r#in: UGenInput = UGenInput::Constant(0.0),
            #[doc = "Low threshold of clipping. Must be less then hi"]
            input lo: UGenInput = UGenInput::Constant(0.0),
            #[doc = "High threshold of clipping. Must be greater then lo"]
            input hi: UGenInput = UGenInput::Constant(1.0),
        ]
        outputs ( fixed 1 )
        push [ (input r#in), (input lo), (input hi) ]
    }
    #[doc = "Fold a signal outside given thresholds."]
    #[doc = ""]
    #[doc = "Folds input wave to within the lo and hi thresholds. This differs from the ugen fold2 in that it allows one to set both low and high thresholds."]
    Fold class r"Fold" {
        rates [ (ar, Audio), (kr, Control) ]
        fields [
            #[doc = "input signal"]
            input r#in: UGenInput = UGenInput::Constant(0.0),
            #[doc = "low threshold"]
            input lo: UGenInput = UGenInput::Constant(0.0),
            #[doc = "high threshold"]
            input hi: UGenInput = UGenInput::Constant(1.0),
        ]
        outputs ( fixed 1 )
        push [ (input r#in), (input lo), (input hi) ]
    }
    #[doc = "Gate or hold"]
    #[doc = ""]
    #[doc = "Lets signal flow when trig is positive, otherwise holds last input value"]
    Gate class r"Gate" {
        rates [ (ar, Audio), (kr, Control) ]
        fields [
            #[doc = "Input signal."]
            input r#in: UGenInput = UGenInput::Constant(0.0),
            #[doc = "Trigger. Trigger can be any signal. A trigger happens when the signal changes from non-positive to positive."]
            input trig: UGenInput = UGenInput::Constant(0.0),
        ]
        outputs ( fixed 1 )
        push [ (input r#in), (input trig) ]
    }
    #[doc = "Tests if a signal is within a given range"]
    #[doc = ""]
    #[doc = "If in is >= lo and <= hi output 1.0, otherwise output 0.0. Output is initially zero."]
    InRange class r"InRange" {
        rates [ (ar, Audio), (kr, Control), (ir, Scalar) ]
        fields [
            #[doc = "input signal"]
            input r#in: UGenInput = UGenInput::Constant(0.0),
            #[doc = "low threshold"]
            input lo: UGenInput = UGenInput::Constant(0.0),
            #[doc = "high threshold"]
            input hi: UGenInput = UGenInput::Constant(1.0),
        ]
        outputs ( fixed 1 )
        push [ (input r#in), (input lo), (input hi) ]
    }
    #[doc = "Test if a point is within a given rectangle."]
    #[doc = ""]
    #[doc = "Outputs one if the 2d coordinate of x,y input values falls inside a rectangle, else zero"]
    InRect class r"InRect" {
        rates [ (ar, Audio), (kr, Control) ]
        fields [
            #[doc = "X component signal"]
            input x: UGenInput = UGenInput::Constant(0.0),
            #[doc = "Y component signal"]
            input y: UGenInput = UGenInput::Constant(0.0),
            input left: UGenInput = UGenInput::Constant(0.0),
            input top: UGenInput = UGenInput::Constant(0.0),
            input right: UGenInput = UGenInput::Constant(0.0),
            input bottom: UGenInput = UGenInput::Constant(0.0),
        ]
        outputs ( fixed 1 )
        push [ (input x), (input y), (input left), (input top), (input right), (input bottom) ]
    }
    #[doc = "Output the last value before the input changed"]
    #[doc = ""]
    #[doc = "Output the last value before the input changed by a threshold of diff"]
    LastValue class r"LastValue" {
        rates [ (ar, Audio), (kr, Control) ]
        fields [
            #[doc = "input signal"]
            input r#in: UGenInput = UGenInput::Constant(0.0),
            #[doc = "difference threshold"]
            input diff: UGenInput = UGenInput::Constant(0.01),
        ]
        outputs ( fixed 1 )
        push [ (input r#in), (input diff) ]
    }
    #[doc = "Sample and hold"]
    #[doc = ""]
    #[doc = "Holds input signal value when triggered."]
    Latch class r"Latch" {
        rates [ (ar, Audio), (kr, Control) ]
        fields [
            #[doc = "Input signal."]
            input r#in: UGenInput = UGenInput::Constant(0.0),
            #[doc = "Trigger. Trigger can be any signal. A trigger happens when the signal changes from non-positive to positive."]
            input trig: UGenInput = UGenInput::Constant(0.0),
        ]
        outputs ( fixed 1 )
        push [ (input r#in), (input trig) ]
    }
    #[doc = "Output least changed"]
    #[doc = ""]
    #[doc = "output whichever signal changed the least"]
    LeastChange class r"LeastChange" {
        rates [ (ar, Audio), (kr, Control) ]
        fields [
            #[doc = "first input"]
            input a: UGenInput = UGenInput::Constant(0.0),
            #[doc = "second input"]
            input b: UGenInput = UGenInput::Constant(0.0),
        ]
        outputs ( fixed 1 )
        push [ (input a), (input b) ]
    }
    #[doc = "Output most changed"]
    #[doc = ""]
    #[doc = "output whichever signal changed the most"]
    MostChange class r"MostChange" {
        rates [ (ar, Audio), (kr, Control) ]
        fields [
            #[doc = "first input"]
            input a: UGenInput = UGenInput::Constant(0.0),
            #[doc = "second input"]
            input b: UGenInput = UGenInput::Constant(0.0),
        ]
        outputs ( fixed 1 )
        push [ (input a), (input b) ]
    }
    #[doc = "Track peak signal amplitude"]
    #[doc = ""]
    #[doc = "Outputs the peak amplitude of the signal so far, a trigger resets to current value"]
    Peak class r"Peak" {
        rates [ (ar, Audio), (kr, Control) ]
        fields [
            #[doc = "Trigger. Trigger can be any signal. A trigger happens when the signal changes from non-positive to positive."]
            input trig: UGenInput = UGenInput::Constant(0.0),
            #[doc = "Resets the counter to zero when triggered."]
            input reset: UGenInput = UGenInput::Constant(0.0),
        ]
        outputs ( fixed 1 )
        push [ (input trig), (input reset) ]
    }
    #[doc = "Track peak signal amplitude"]
    #[doc = ""]
    #[doc = "Outputs the peak signal amplitude, falling with decay over time until reaching signal level"]
    PeakFollower class r"PeakFollower" {
        rates [ (ar, Audio), (kr, Control) ]
        fields [
            #[doc = "input signal."]
            input r#in: UGenInput = UGenInput::Constant(0.0),
            #[doc = "decay factor."]
            input decay: UGenInput = UGenInput::Constant(0.999),
        ]
        outputs ( fixed 1 )
        push [ (input r#in), (input decay) ]
    }
    #[doc = "Resettable linear ramp between two levels"]
    #[doc = ""]
    #[doc = "Phasor is a linear ramp between start and end values. When its trigger input crosses from non-positive to positive, Phasor's output will jump to its reset position. Upon reaching the end of its ramp Phasor will wrap back to its start. N.B. Since end is defined as the wrap point, its value is never actually output."]
    Phasor class r"Phasor" {
        rates [ (ar, Audio), (kr, Control) ]
        fields [
            #[doc = "When triggered, reset value to reset-pos (default: 0, phasor outputs start initially)"]
            input trig: UGenInput = UGenInput::Constant(0.0),
            #[doc = "The amount of change per sample i.e at a rate of 1 the value of each sample will be 1 greater than the preceding sample"]
            input rate: UGenInput = UGenInput::Constant(1.0),
            #[doc = "Starting point of the ramp"]
            input start: UGenInput = UGenInput::Constant(0.0),
            #[doc = "End point of the ramp"]
            input end: UGenInput = UGenInput::Constant(1.0),
            #[doc = "The value to jump to upon receiving a trigger"]
            input reset_pos: UGenInput = UGenInput::Constant(0.0),
        ]
        outputs ( fixed 1 )
        push [ (input trig), (input rate), (input start), (input end), (input reset_pos) ]
    }
    #[doc = "Autocorrelation pitch follower"]
    #[doc = ""]
    #[doc = "This is a better pitch follower than zero-crossing, but more costly of CPU. For most purposes the default settings can be used and only in needs to be supplied. Pitch returns two values (via an Array of OutputProxys, a freq which is the pitch estimate and has-freq, which tells whether a pitch was found. Some vowels are still problematic, for instance a wide open mouth sound somewhere between a low pitched short 'a' sound as in 'sat', and long 'i' sound as in 'fire', contains enough overtone energy to confuse the algorithm. None of these settings are time variable."]
    Pitch class r"Pitch" {
        rates [ (kr, Control) ]
        fields [
            #[doc = "Input signal"]
            input r#in: UGenInput = UGenInput::Constant(0.0),
            #[doc = "Value of output pitch until first pitch detected."]
            input init_freq: UGenInput = UGenInput::Constant(440.0),
            #[doc = "Minimum frequency of execution."]
            input min_freq: UGenInput = UGenInput::Constant(60.0),
            #[doc = "Maximum frequency of execution."]
            input max_freq: UGenInput = UGenInput::Constant(4000.0),
            #[doc = "The target rate to periodically execute in cps. Clipped between min-freq and max-freq."]
            input exec_freq: UGenInput = UGenInput::Constant(100.0),
            #[doc = "Number of lags for course search. A larger value will cause the coarse search to take longer, a smaller value will cause the subsequent fine search to take longer."]
            input max_bins_per_octave: UGenInput = UGenInput::Constant(16.0),
            #[doc = "Median filter value of length median on the output estimation. Helps eliminate outliers and jitter. Value of 1 means no filter."]
            input median: UGenInput = UGenInput::Constant(1.0),
            #[doc = "Minum peak to peak amplitude of input signal before pitch estimation is performed."]
            input amp_threshold: UGenInput = UGenInput::Constant(0.01),
            #[doc = "Finds the next peak that is above peak-threshold times the amplitude of the peak at lag zero. A value of 0.5 does a pretty good job of eliminating overtones."]
            input peak_threshold: UGenInput = UGenInput::Constant(0.5),
            #[doc = "Down sample the input signal by an integer factor. Helps reduce CPU overthead. Also reduces pitch resolution."]
            input down_sample: UGenInput = UGenInput::Constant(1.0),
            #[doc = "Clarity measurement (purity of the pitched signal) if greater than 0."]
            input clar: UGenInput = UGenInput::Constant(0.0),
        ]
        outputs ( fixed 2 )
        push [ (input r#in), (input init_freq), (input min_freq), (input max_freq), (input exec_freq), (input max_bins_per_octave), (input median), (input amp_threshold), (input peak_threshold), (input down_sample), (input clar) ]
    }
    #[doc = "Pulse counter"]
    #[doc = ""]
    #[doc = "Each input trigger increments a counter value that is output."]
    PulseCount class r"PulseCount" {
        rates [ (ar, Audio), (kr, Control) ]
        fields [
            #[doc = "Trigger. Trigger can be any signal. A trigger happens when the signal changes from non-positive to positive."]
            input trig: UGenInput = UGenInput::Constant(0.0),
            #[doc = "Resets the counter to zero when triggered."]
            input reset: UGenInput = UGenInput::Constant(0.0),
        ]
        outputs ( fixed 1 )
        push [ (input trig), (input reset) ]
    }
    #[doc = "Pulse divider"]
    #[doc = ""]
    #[doc = "Outputs a trigger every div input triggers"]
    PulseDivider class r"PulseDivider" {
        rates [ (ar, Audio), (kr, Control) ]
        fields [
            #[doc = "Trigger. Trigger can be any signal. A trigger happens when the signal changes from non-positive to positive."]
            input trig: UGenInput = UGenInput::Constant(0.0),
            #[doc = "Number of pulses to divide by."]
            input div: UGenInput = UGenInput::Constant(2.0),
            #[doc = "Starting value for the trigger count. This lets you start somewhere in the middle of a count, or if startCount is negative it adds that many counts to the first time the output is triggers."]
            input start_val: UGenInput = UGenInput::Constant(0.0),
        ]
        outputs ( fixed 1 )
        push [ (input trig), (input div), (input start_val) ]
    }
    #[doc = "Track maximum level"]
    #[doc = ""]
    #[doc = "Outputs the maximum value received at the input. When triggered, the maximum output value is reset to the current value."]
    RunningMax class r"RunningMax" {
        rates [ (ar, Audio), (kr, Control) ]
        fields [
            #[doc = "Input signal."]
            input r#in: UGenInput = UGenInput::Constant(0.0),
            #[doc = "Trigger. Trigger can be any signal. A trigger happens when the signal changes from non-positive to positive."]
            input trig: UGenInput = UGenInput::Constant(0.0),
        ]
        outputs ( fixed 1 )
        push [ (input r#in), (input trig) ]
    }
    #[doc = "Track minimum level"]
    #[doc = ""]
    #[doc = "Outputs the minimum value received at the input. When triggered, the minimum output value is reset to the current value."]
    RunningMin class r"RunningMin" {
        rates [ (ar, Audio), (kr, Control) ]
        fields [
            #[doc = "Input signal."]
            input r#in: UGenInput = UGenInput::Constant(0.0),
            #[doc = "Trigger. Trigger can be any signal. A trigger happens when the signal changes from non-positive to positive."]
            input trig: UGenInput = UGenInput::Constant(0.0),
        ]
        outputs ( fixed 1 )
        push [ (input r#in), (input trig) ]
    }
    #[doc = "Schmidt trigger"]
    #[doc = ""]
    #[doc = "Outout one when signal greater than high, and zero when lower than low."]
    Schmidt class r"Schmidt" {
        rates [ (ar, Audio), (kr, Control) ]
        fields [
            #[doc = "input signal"]
            input r#in: UGenInput = UGenInput::Constant(0.0),
            #[doc = "low threshold"]
            input lo: UGenInput = UGenInput::Constant(0.0),
            #[doc = "high threshold"]
            input hi: UGenInput = UGenInput::Constant(1.0),
        ]
        outputs ( fixed 1 )
        push [ (input r#in), (input lo), (input hi) ]
    }
    #[doc = "Send information via OSC to Overtone"]
    #[doc = ""]
    #[doc = "Send an array of values from the server via an message. The OSC message is formed with cmd-name as the path, followed by two compulsary args: node-id (the id of the node that sent the message) and reply-id (the value specified in the params). These args are then followed by the list of values specified in the params. For example, if the ugen is used as follows: (send-reply tr \\\"/foobar\\\" [1 2 3] 42) When the trig tr triggers, Overtone will receive an event that looks like the following (where 32 represents the node-id of the synth that sent the message): {:path \\\"/foobar\\"]
    SendReply class r"SendReply" {
        rates [ (ar, Audio), (kr, Control) ]
        fields [
            #[doc = "Input trigger signal"]
            input trig: UGenInput = UGenInput::Constant(0.0),
            #[doc = "A string or symbol, as a message name."]
            input cmd_name: UGenInput = UGenInput::Constant(0.0),
            #[doc = "Array of ugens, or valid ugen inputs"]
            input values: UGenInput = UGenInput::Constant(0.0),
            #[doc = "Integer id (similar to that used by send-trig)"]
            input reply_id: UGenInput = UGenInput::Constant(-1.0),
        ]
        outputs ( fixed 0 )
        push [ (input trig), (input cmd_name), (input values), (input reply_id) ]
    }
    #[doc = "Send a /tr OSC message to Overtone"]
    #[doc = ""]
    #[doc = "On receiving a trigger sends a :trigger event with id and value. This command is the mechanism that synths can use to trigger events in clients. The trigger message sent back to the client is this: int - node ID int - trigger ID float - trigger value This is then presented as an event on the event-stream which is a map containing the key :path with the string \\\"/tr\\\" and the key :args containing a sequence of the values in the above order. i.e. {:path /tr, :args (34 3 123.0)} See on-trigger, on-latest-trigger and on-sync-trigger for registering handlers for trigger events."]
    SendTrig class r"SendTrig" {
        rates [ (ar, Audio), (kr, Control) ]
        fields [
            #[doc = "input trigger signal"]
            input r#in: UGenInput = UGenInput::Constant(0.0),
            #[doc = "an integer that will be passed with the trigger message. This is useful if you have more than one send-trig in a synth design. Consider using trig-id to genearate a unique id."]
            input id: UGenInput = UGenInput::Constant(0.0),
            #[doc = "A ugen or float that will be polled at the time of trigger, and its value passed with the trigger message"]
            input value: UGenInput = UGenInput::Constant(0.0),
        ]
        outputs ( fixed 0 )
        push [ (input r#in), (input id), (input value) ]
    }
    #[doc = "Set-reset flip flop"]
    #[doc = ""]
    #[doc = "When a trigger is received the output is set to 1.0 Subsequent triggers have no effect When a trigger is received in the reset input, the output is set back to 0.0 One use of this is to have some precipitating event cause something to happen until you reset it."]
    SetResetFF class r"SetResetFF" {
        rates [ (ar, Audio), (kr, Control) ]
        fields [
            #[doc = "Trigger. Trigger can be any signal. A trigger happens when the signal changes from non-positive to positive."]
            input trig: UGenInput = UGenInput::Constant(0.0),
            #[doc = "Resets the counter to zero when triggered."]
            input reset: UGenInput = UGenInput::Constant(0.0),
        ]
        outputs ( fixed 1 )
        push [ (input trig), (input reset) ]
    }
    #[doc = "Pulse counter"]
    #[doc = ""]
    #[doc = "Triggers increment a counter which is output as a signal. The counter loops around from max to min by step increments"]
    Stepper class r"Stepper" {
        rates [ (ar, Audio), (kr, Control) ]
        fields [
            #[doc = "Trigger. Trigger can be any signal. A trigger happens when the signal changes from non-positive to positive."]
            input trig: UGenInput = UGenInput::Constant(0.0),
            #[doc = "Resets the counter to resetval when triggered."]
            input reset: UGenInput = UGenInput::Constant(0.0),
            #[doc = "minimum value of the counter."]
            input min: UGenInput = UGenInput::Constant(0.0),
            #[doc = "maximum value of the counter."]
            input max: UGenInput = UGenInput::Constant(7.0),
            #[doc = "step value each trigger. May be negative."]
            input step: UGenInput = UGenInput::Constant(1.0),
            #[doc = "value to which the counter is reset when it receives a reset trigger."]
            input resetval: UGenInput = UGenInput::Constant(1.0),
        ]
        outputs ( fixed 1 )
        push [ (input trig), (input reset), (input min), (input max), (input step), (input resetval) ]
    }
    #[doc = "Triggered linear ramp"]
    #[doc = ""]
    #[doc = "outputs a linear increasing signal by rate/second when trig input crosses from non-positive to positive"]
    Sweep class r"Sweep" {
        rates [ (ar, Audio), (kr, Control) ]
        fields [
            #[doc = "trigger input"]
            input trig: UGenInput = UGenInput::Constant(0.0),
            #[doc = "rate in seconds"]
            input rate: UGenInput = UGenInput::Constant(1.0),
        ]
        outputs ( fixed 1 )
        push [ (input trig), (input rate) ]
    }
    #[doc = "Trigger delay"]
    #[doc = ""]
    #[doc = "Delays an input trigger by dur, ignoring other triggers in the meantime"]
    TDelay class r"TDelay" {
        rates [ (ar, Audio), (kr, Control) ]
        fields [
            #[doc = "input trigger signal."]
            input trig: UGenInput = UGenInput::Constant(0.0),
            #[doc = "delay time in seconds."]
            input dur: UGenInput = UGenInput::Constant(0.1),
        ]
        outputs ( fixed 1 )
        push [ (input trig), (input dur) ]
    }
    #[doc = "Triggered window"]
    #[doc = ""]
    #[doc = "When triggered, returns a random index value based on array as a list of probabilities. By default the list of probabilities should sum to 1.0, when the normalize flag is set to 1, the values get normalized by the ugen (less efficient)."]
    TWindex class r"TWindex" {
        rates [ (ar, Audio), (kr, Control) ]
        fields [
            #[doc = "Trigger - can be any signal. A trigger happens when the signal changes from non-positive to positive."]
            input trig: UGenInput = UGenInput::Constant(0.0),
            #[doc = "list of probabilities"]
            array channels_array: Vec<UGenInput> = Vec::new(),
            #[doc = "normalise flag - 0 off, 1 on"]
            input normalize: UGenInput = UGenInput::Constant(0.0),
        ]
        outputs ( fixed 1 )
        push [ (input trig), (input normalize), (array channels_array) ]
    }
    #[doc = "Trigger timer"]
    #[doc = ""]
    #[doc = "Outputs time since last trigger"]
    Timer class r"Timer" {
        rates [ (ar, Audio), (kr, Control) ]
        fields [
            #[doc = "trigger input"]
            input trig: UGenInput = UGenInput::Constant(0.0),
        ]
        outputs ( fixed 1 )
        push [ (input trig) ]
    }
    #[doc = "Toggle flip flop"]
    #[doc = ""]
    #[doc = "Flip-flops between zero and one each trigger"]
    ToggleFF class r"ToggleFF" {
        rates [ (ar, Audio), (kr, Control) ]
        fields [
            #[doc = "trigger input"]
            input trig: UGenInput = UGenInput::Constant(0.0),
        ]
        outputs ( fixed 1 )
        push [ (input trig) ]
    }
    Trapezoid class r"Trapezoid" {
        rates [ (ar, Audio), (kr, Control) ]
        fields [
            input r#in: UGenInput = UGenInput::Constant(0.0),
            input a: UGenInput = UGenInput::Constant(0.2),
            input b: UGenInput = UGenInput::Constant(0.4),
            input c: UGenInput = UGenInput::Constant(0.6),
            input d: UGenInput = UGenInput::Constant(0.8),
        ]
        outputs ( fixed 1 )
        push [ (input r#in), (input a), (input b), (input c), (input d) ]
    }
    #[doc = "Timed trigger"]
    #[doc = ""]
    #[doc = "When a nonpositive to positive transition occurs at the input, Trig outputs the level of the triggering input for the specified duration, otherwise it outputs zero."]
    Trig class r"Trig" {
        rates [ (ar, Audio), (kr, Control) ]
        fields [
            #[doc = "trigger. Trigger can be any signal. A trigger happens when the signal changes from non-positive to positive."]
            input trig: UGenInput = UGenInput::Constant(0.0),
            #[doc = "duration of the trigger output in seconds."]
            input dur: UGenInput = UGenInput::Constant(0.1),
        ]
        outputs ( fixed 1 )
        push [ (input trig), (input dur) ]
    }
    #[doc = "Timed trigger"]
    #[doc = ""]
    #[doc = "Outputs one for dur seconds whenever the input goes from negative to positive, otherwise outputs 0."]
    Trig1 class r"Trig1" {
        rates [ (ar, Audio), (kr, Control) ]
        fields [
            #[doc = "trigger. Trigger can be any signal. A trigger happens when the signal changes from non-positive to positive."]
            input trig: UGenInput = UGenInput::Constant(0.0),
            #[doc = "duration of the trigger output in seconds."]
            input dur: UGenInput = UGenInput::Constant(0.1),
        ]
        outputs ( fixed 1 )
        push [ (input trig), (input dur) ]
    }
    #[doc = "Wrap a signal outside given thresholds."]
    #[doc = ""]
    #[doc = "Wraps input wave to the low and high thresholds. This differs from the ugen wrap2 in that it allows one to set both low and high thresholds."]
    Wrap class r"Wrap" {
        rates [ (ar, Audio), (kr, Control) ]
        fields [
            #[doc = "input signal"]
            input r#in: UGenInput = UGenInput::Constant(0.0),
            #[doc = "low threshold"]
            input lo: UGenInput = UGenInput::Constant(0.0),
            #[doc = "high threshold"]
            input hi: UGenInput = UGenInput::Constant(1.0),
        ]
        outputs ( fixed 1 )
        push [ (input r#in), (input lo), (input hi) ]
    }
    #[doc = "Zero crossing frequency follower"]
    #[doc = ""]
    #[doc = "Outputs a frequency based upon the distance between interceptions of the X axis. The X intercepts are determined via linear interpolation so this gives better than just integer wavelength resolution. This is a very crude pitch follower, but can be useful in some situations."]
    ZeroCrossing class r"ZeroCrossing" {
        rates [ (ar, Audio), (kr, Control) ]
        fields [
            #[doc = "input signal"]
            input r#in: UGenInput = UGenInput::Constant(0.0),
        ]
        outputs ( fixed 1 )
        push [ (input r#in) ]
    }
}
