import { spawnSync } from "node:child_process";
import { readFileSync, writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import path from "node:path";

type Scalar = "i32" | "f32" | "string";
type OptionScalar = "i32" | "f32";
type List = "i32" | "string" | "controlId";
type Tuple = "i32" | "f32" | "string" | "controlId" | "numericValue" | "controlValue" | "oscArg";
type FieldForm =
  | { scalar: Scalar }
  | { optionScalar: OptionScalar }
  | "completion"
  | "blob"
  | { list: List }
  | "variadic"
  | { tail: Tuple[] }
  | { setnTail: { head: Tuple; values: Tuple } };
type FieldSpec = { name: string; form: FieldForm; doc?: string };
type CommandSpec = {
  address: string;
  struct: string;
  category: string;
  doc?: string;
  decode?: boolean;
  fields: FieldSpec[];
};
type RegistrySpec = { commands: CommandSpec[] };

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "../../..");
const categories = [
  ["top-level", "top_level"],
  ["synthdef", "synthdef"],
  ["node", "node"],
  ["synth", "synth"],
  ["group", "group"],
  ["ugen", "ugen"],
  ["buffer", "buffer"],
  ["control-bus", "control_bus"],
  ["nrt", "nrt"],
  ["bridge", "bridge"],
] as const;
const header =
  "// @generated by packages/server-commands/scripts/generate-rust.ts from specs/server-commands.json — do not edit.\n// Regenerate with `yarn generate:server-commands`.\n";

function object(value: unknown, where: string): Record<string, unknown> {
  if (value === null || typeof value !== "object" || Array.isArray(value))
    throw new Error(`${where}: expected object`);
  return value as Record<string, unknown>;
}
function keys(value: Record<string, unknown>, allowed: string[], where: string): void {
  const bad = Object.keys(value).filter((key) => !allowed.includes(key));
  if (bad.length) throw new Error(`${where}: unknown key(s): ${bad.join(", ")}`);
}
function oneOf<T extends string>(value: unknown, allowed: readonly T[], where: string): T {
  if (typeof value !== "string" || !allowed.includes(value as T))
    throw new Error(`${where}: invalid value ${JSON.stringify(value)}`);
  return value as T;
}
function parseSpec(raw: unknown): RegistrySpec {
  const registry = object(raw, "spec");
  keys(registry, ["commands"], "spec");
  if (!Array.isArray(registry.commands)) throw new Error("spec.commands: expected array");
  const commands = registry.commands.map((rawCommand, ci): CommandSpec => {
    const where = `commands[${ci}]`;
    const command = object(rawCommand, where);
    keys(command, ["address", "struct", "category", "doc", "decode", "fields"], where);
    for (const key of ["address", "struct", "category"] as const)
      if (typeof command[key] !== "string") throw new Error(`${where}.${key}: expected string`);
    if (command.doc !== undefined && typeof command.doc !== "string")
      throw new Error(`${where}.doc: expected string`);
    if (command.decode !== undefined && typeof command.decode !== "boolean")
      throw new Error(`${where}.decode: expected boolean`);
    if (!Array.isArray(command.fields)) throw new Error(`${where}.fields: expected array`);
    const fields = command.fields.map((rawField, fi): FieldSpec => {
      const fw = `${where}.fields[${fi}]`;
      const field = object(rawField, fw);
      keys(field, ["name", "form", "doc"], fw);
      if (typeof field.name !== "string") throw new Error(`${fw}.name: expected string`);
      if (field.doc !== undefined && typeof field.doc !== "string")
        throw new Error(`${fw}.doc: expected string`);
      let form: FieldForm;
      if (field.form === "completion" || field.form === "blob" || field.form === "variadic")
        form = field.form;
      else {
        const fo = object(field.form, `${fw}.form`);
        const formKeys = Object.keys(fo);
        if (formKeys.length !== 1) throw new Error(`${fw}.form: expected exactly one form key`);
        const kind = formKeys[0];
        if (kind === "scalar")
          form = { scalar: oneOf(fo.scalar, ["i32", "f32", "string"], `${fw}.form.scalar`) };
        else if (kind === "optionScalar")
          form = {
            optionScalar: oneOf(fo.optionScalar, ["i32", "f32"], `${fw}.form.optionScalar`),
          };
        else if (kind === "list")
          form = { list: oneOf(fo.list, ["i32", "string", "controlId"], `${fw}.form.list`) };
        else if (kind === "tail") {
          if (!Array.isArray(fo.tail) || !fo.tail.length)
            throw new Error(`${fw}.form.tail: expected non-empty array`);
          form = {
            tail: fo.tail.map((v, i) =>
              oneOf(
                v,
                ["i32", "f32", "string", "controlId", "numericValue", "controlValue", "oscArg"],
                `${fw}.form.tail[${i}]`,
              ),
            ),
          };
        } else if (kind === "setnTail") {
          const st = object(fo.setnTail, `${fw}.form.setnTail`);
          keys(st, ["head", "values"], `${fw}.form.setnTail`);
          form = {
            setnTail: {
              head: oneOf(
                st.head,
                ["i32", "f32", "string", "controlId", "numericValue", "controlValue", "oscArg"],
                `${fw}.form.setnTail.head`,
              ),
              values: oneOf(
                st.values,
                ["i32", "f32", "string", "controlId", "numericValue", "controlValue", "oscArg"],
                `${fw}.form.setnTail.values`,
              ),
            },
          };
        } else throw new Error(`${fw}.form: unknown form ${kind}`);
      }
      return { name: field.name, form, ...(field.doc === undefined ? {} : { doc: field.doc }) };
    });
    return {
      address: command.address as string,
      struct: command.struct as string,
      category: command.category as string,
      fields,
      ...(command.doc === undefined ? {} : { doc: command.doc }),
      ...(command.decode === undefined ? {} : { decode: command.decode }),
    };
  });
  const known = new Set<string>(categories.map(([category]) => category));
  for (const command of commands)
    if (!known.has(command.category))
      throw new Error(`command ${command.struct}: unknown category ${command.category}`);
  return { commands };
}

const rustType = (type: string): string =>
  ({
    i32: "i32",
    f32: "f32",
    string: "String",
    controlId: "ControlId",
    numericValue: "NumericValue",
    controlValue: "ControlValue",
    oscArg: "OscArg",
  })[type] ??
  (() => {
    throw new Error(`unknown type ${type}`);
  })();
function docs(doc: string | undefined, indent: string): string {
  return doc === undefined
    ? ""
    : doc
        .split("\n")
        .map(
          (line) => `${indent}#[doc = "${line.replaceAll("\\", "\\\\").replaceAll('"', '\\"')}"]\n`,
        )
        .join("");
}
function renderCommand(command: CommandSpec): string {
  if (
    command.decode &&
    command.fields.some(
      ({ form }) => typeof form !== "object" || !("scalar" in form) || form.scalar !== "i32",
    )
  )
    throw new Error(`${command.struct}: decode commands may contain only scalar i32 fields`);
  let out =
    docs(command.doc, "    ") +
    `    "${command.address}" ${command.struct}${command.decode ? " decode" : ""} {\n`;
  for (const field of command.fields) {
    out += docs(field.doc, "        ");
    const form = field.form;
    let declaration: string;
    if (form === "completion" || form === "blob" || form === "variadic")
      declaration = `${form} ${field.name}`;
    else if ("scalar" in form) declaration = `scalar ${field.name}: ${rustType(form.scalar)}`;
    else if ("optionScalar" in form)
      declaration = `opt ${field.name}: ${rustType(form.optionScalar)}`;
    else if ("list" in form) declaration = `list ${field.name}: ${rustType(form.list)}`;
    else if ("tail" in form)
      declaration = `tail ${field.name}: (${form.tail.map(rustType).join(", ")})`;
    else
      declaration = `setn ${field.name}: (${rustType(form.setnTail.head)}, ${rustType(form.setnTail.values)})`;
    out += `        ${declaration},\n`;
  }
  return out + "    }\n";
}

/** Canonicalize through rustfmt (stdin — the @generated skip only applies
 *  to on-disk files) so the committed output always satisfies the repo's
 *  `cargo fmt --check` gate. */
function rustfmt(content: string, rel: string): string {
  const r = spawnSync("rustfmt", ["--edition", "2021", "--emit", "stdout"], {
    input: content,
    encoding: "utf8",
  });
  if (r.status !== 0) throw new Error(`rustfmt failed for ${rel}: ${r.stderr}`);
  return r.stdout;
}

export function render(): Map<string, string> {
  const specPath = path.join(root, "packages/server-commands/specs/server-commands.json");
  const spec = parseSpec(JSON.parse(readFileSync(specPath, "utf8")));
  const rendered = new Map<string, string>();
  const base = "src-tauri/crates/scserver-commands/src/commands";
  for (const [category, file] of categories) {
    const body = spec.commands
      .filter((command) => command.category === category)
      .map(renderCommand)
      .join("");
    rendered.set(
      `${base}/${file}.rs`,
      `${header}\n#![allow(unused_imports, unused_mut)]\n\nuse rosc::OscType;\nuse serde::{Deserialize, Serialize};\n#[cfg(feature = "wasm")]\nuse tsify::Tsify;\n\nuse crate::args::OscArg;\nuse crate::OscMessage;\n\nuse super::prelude::{ControlId, ControlValue, NumericValue};\n\nsc_commands! {\n${body}}\n`,
    );
  }
  const modules = categories.map(([, file]) => `mod ${file};\npub use ${file}::*;`).join("\n\n");
  const arms = (payload: boolean) =>
    spec.commands
      .filter((command) => Boolean(command.fields.length) === payload)
      .map((command) => `        ${command.struct} "${command.address}",`)
      .join("\n");
  rendered.set(
    `${base}/mod.rs`,
    `${header}\nuse serde::{Deserialize, Serialize};\n#[cfg(feature = "wasm")]\nuse tsify::Tsify;\n\nuse crate::OscMessage;\n\nmod prelude;\npub use prelude::*;\n\n${modules}\n\ndefine_known_message! {\n    payload {\n${arms(true)}\n    }\n    unit {\n${arms(false)}\n    }\n}\n`,
  );
  for (const [rel, content] of rendered) rendered.set(rel, rustfmt(content, rel));
  return rendered;
}

function main(): void {
  const args = process.argv.slice(2);
  const check = args.length === 1 && args[0] === "--check";
  if (args.length && !check)
    throw new Error(
      `usage: yarn tsx ${path.relative(root, fileURLToPath(import.meta.url))} [--check]`,
    );
  let mismatch = false;
  for (const [relative, content] of render()) {
    const target = path.join(root, relative);
    let current: string | undefined;
    try {
      current = readFileSync(target, "utf8");
    } catch (error) {
      if ((error as NodeJS.ErrnoException).code !== "ENOENT") throw error;
    }
    if (current === content) continue;
    if (check) {
      console.log(relative);
      mismatch = true;
    } else {
      writeFileSync(target, content);
      console.log(`wrote ${relative}`);
    }
  }
  if (mismatch) process.exitCode = 1;
}
if (process.argv[1] && path.resolve(process.argv[1]) === fileURLToPath(import.meta.url)) main();
