/**
 * The binary boundary: thin wrappers over the wasm-bindgen build of the
 * scserver-commands crate (`pkg/`, regenerated by
 * `yarn generate:server-commands`). Instantiation is explicit and happens
 * at module load: node (vitest included) feeds the wasm bytes from disk,
 * browsers let the glue fetch its own Vite-emitted asset. Every export
 * below is synchronous afterwards, and throws on malformed input.
 */

import {
  at_unix_ms,
  decode_reply,
  decode_reply_packet,
  encode as encodeMessage,
  encode_bundle,
  type OscTimetag,
  type ServerMessage,
  type ServerReply,
} from "../pkg/scserver_commands.js";
import { initWasm } from "../pkg/init.js";

// Explicit instantiation at module load — the generated loader feeds fs
// bytes in node (vitest included) and lets the glue fetch the Vite-emitted
// asset in browsers. Everything below is synchronous afterwards.
await initWasm();

/** Serialise one typed command to OSC wire bytes. */
export function encode(msg: ServerMessage): Uint8Array {
  return encodeMessage(msg);
}

/** Serialise many commands into one standard OSC bundle — scsynth applies
 *  the whole bundle atomically at the timetag. */
export function encodeBundle(time: OscTimetag, msgs: ServerMessage[]): Uint8Array {
  return encode_bundle(time, msgs);
}

/** Classify one OSC reply message into its typed variant. */
export function decodeReply(bytes: Uint8Array): ServerReply {
  return decode_reply(bytes);
}

/** Decode a raw inbound packet — a bare message or a `#bundle` — into typed
 *  replies. Nested bundles are rejected (scsynth never sends them). */
export function decodeReplyPacket(bytes: Uint8Array): ServerReply[] {
  return decode_reply_packet(bytes);
}

/** NTP timetag from a wall-clock Unix ms timestamp (`Date.now()` style);
 *  negative/non-finite input yields the OSC "immediate" tag. */
export function atUnixMs(ms: number): OscTimetag {
  return at_unix_ms(ms);
}
