/**
 * The binary boundary: thin wrappers over the jco-transpiled wasm component
 * (`pkg/`, regenerated by `yarn generate:server-commands` from the
 * scserver-commands crate). Importing this module instantiates the wasm via
 * the transpiled top-level await — node loads the file through fs, browsers
 * fetch-compile it — so every export below is synchronous afterwards.
 * jco lifts WIT `result<_, string>` as a throw, so all wrappers throw on
 * malformed input.
 */

import { commands, replies } from "../pkg/scserver.js";
import type { ServerMessage } from "../pkg/interfaces/scserver-commands-commands.js";
import type { ServerReply } from "../pkg/interfaces/scserver-commands-replies.js";
import type { OscTime } from "../pkg/interfaces/scserver-commands-core.js";

/** Serialise one typed command to OSC wire bytes. */
export function encode(msg: ServerMessage): Uint8Array {
  return commands.encode(msg);
}

/** Serialise many commands into one standard OSC bundle — scsynth applies
 *  the whole bundle atomically at the timetag. */
export function encodeBundle(time: OscTime, msgs: ServerMessage[]): Uint8Array {
  return commands.encodeBundle(time, msgs);
}

/** Classify one OSC reply message into its typed variant. */
export function decodeReply(bytes: Uint8Array): ServerReply {
  return replies.decode(bytes);
}

/** Decode a raw inbound packet — a bare message or a `#bundle` (leading
 *  `#`, 0x23) — into typed replies. Nested bundles are rejected by the
 *  component (scsynth never sends them). */
export function decodeReplyPacket(bytes: Uint8Array): ServerReply[] {
  return bytes[0] === 0x23 ? replies.decodeBundle(bytes).replies : [replies.decode(bytes)];
}

/** NTP timetag from a wall-clock Unix ms timestamp (`Date.now()` style);
 *  negative/non-finite input yields the OSC "immediate" tag. */
export function atUnixMs(ms: number): OscTime {
  return commands.atUnixMs(ms);
}
