// @generated by packages/server-commands/scripts/generate-rust.ts from specs/server-commands.json — do not edit.
// Regenerate with `yarn generate:server-commands`.

#![allow(unused_imports, unused_mut)]

use rosc::OscType;
use serde::{Deserialize, Serialize};
#[cfg(feature = "wasm")]
use tsify::Tsify;

use crate::args::OscArg;
use crate::OscMessage;

use super::prelude::{ControlId, ControlValue, NumericValue};

sc_commands! {
    #[doc = "sc-app bridge extension (not in the SC command reference): register a scope-slot stream with the bridge. The bridge is the consumer, so the struct also carries from_message/decode parsers."]
    "/scope/subscribe" ScopeSubscribe decode {
        #[doc = "Client-minted subscription id, echoed on every chunk."]
        scalar sub_id: i32,
        #[doc = "scsynth SHM scope-buffer index to stream."]
        scalar scope: i32,
        #[doc = "Channel count (informational — the SHM header carries the truth)."]
        scalar channels: i32,
        #[doc = "Requested frames per chunk (informational, as above)."]
        scalar chunk_size: i32,
    }
    #[doc = "sc-app bridge extension (not in the SC command reference): drop a scope-slot stream."]
    "/scope/unsubscribe" ScopeUnsubscribe decode {
        #[doc = "The subscription id to drop."]
        scalar sub_id: i32,
    }
    #[doc = "sc-app bridge extension (not in the SC command reference): a SuperDirt/Strudel event, routed by the bridge to the strudel peer. The wire format is SuperDirt's alternating key/value arg list."]
    "/dirt/play" DirtPlay {
        #[doc = "Repeated tuples: parameter name; parameter value."]
        tail pairs: (String, OscArg),
    }
}
