// @generated by packages/server-commands/scripts/generate-rust.ts from specs/server-commands.json — do not edit.
// Regenerate with `yarn generate:server-commands`.

#![allow(unused_imports, unused_mut)]

use rosc::OscType;
use serde::{Deserialize, Serialize};
#[cfg(feature = "wasm")]
use tsify::Tsify;

use crate::args::OscArg;
use crate::OscMessage;

use super::prelude::{ControlId, ControlValue, NumericValue};

sc_commands! {
    #[doc = "Allocate buffer space."]
    "/b_alloc" BAlloc {
        #[doc = "buffer number"]
        scalar bufnum: i32,
        #[doc = "number of frames"]
        scalar num_frames: i32,
        #[doc = "number of channels (optional. default = 1 channel)"]
        opt num_channels: i32,
        #[doc = "an OSC message to execute upon completion. (optional)"]
        completion completion_msg,
        #[doc = "the required sample rate (optional. default (or 0) = the server's sample rate)"]
        opt sample_rate: f32,
    }
    #[doc = "Allocate buffer space and read a sound file."]
    "/b_allocRead" BAllocRead {
        #[doc = "buffer number"]
        scalar bufnum: i32,
        #[doc = "path name of a sound file."]
        scalar path: String,
        #[doc = "starting frame in file (optional. default = 0)"]
        opt start_frame: i32,
        #[doc = "number of frames to read (optional. default = 0, see below)"]
        opt number_of_frames: i32,
        #[doc = "an OSC message to execute upon completion. (optional)"]
        completion completion_msg,
    }
    #[doc = "Allocate buffer space and read channels from a sound file."]
    "/b_allocReadChannel" BAllocReadChannel {
        #[doc = "buffer number"]
        scalar bufnum: i32,
        #[doc = "path name of a sound file"]
        scalar path: String,
        #[doc = "starting frame in file"]
        scalar start_frame: i32,
        #[doc = "number of frames to read"]
        scalar number_of_frames: i32,
        #[doc = "source file channel indices (one or more) to read"]
        list channels: i32,
        #[doc = "an OSC message to execute upon completion. (optional)"]
        completion completion_msg,
    }
    #[doc = "Close soundfile."]
    "/b_close" BClose {
        #[doc = "buffer number"]
        scalar bufnum: i32,
        #[doc = "an OSC message to execute upon completion. (optional)"]
        completion completion_msg,
    }
    #[doc = "Fill ranges of sample value(s)."]
    "/b_fill" BFill {
        #[doc = "buffer number"]
        scalar bufnum: i32,
        #[doc = "Repeated tuples: sample starting index; number of samples to fill (M); value."]
        tail tail: (i32, i32, f32),
    }
    #[doc = "Free buffer data."]
    "/b_free" BFree {
        #[doc = "buffer number"]
        scalar bufnum: i32,
        #[doc = "an OSC message to execute upon completion. (optional)"]
        completion completion_msg,
    }
    #[doc = "Call a command to fill a buffer."]
    "/b_gen" BGen {
        #[doc = "buffer number"]
        scalar bufnum: i32,
        #[doc = "command name"]
        scalar cmd: String,
        #[doc = "command arguments — variadic trailing OSC args (types depend on the specific `/b_gen` command being invoked, e.g. `sine1`, `cheby`)."]
        variadic command_arguments,
    }
    #[doc = "Get sample value(s)."]
    "/b_get" BGet {
        #[doc = "buffer number"]
        scalar bufnum: i32,
        #[doc = "sample indices (one or more) — the server replies with the value at each index."]
        list sample_indices: i32,
    }
    #[doc = "Get ranges of sample value(s)."]
    "/b_getn" BGetn {
        #[doc = "buffer number"]
        scalar bufnum: i32,
        #[doc = "Repeated tuples: starting sample index; number of sequential samples to get (M)."]
        tail tail: (i32, i32),
    }
    #[doc = "Get buffer info."]
    "/b_query" BQuery {
        #[doc = "buffer numbers to query"]
        list bufnums: i32,
    }
    #[doc = "Read sound file data into an existing buffer."]
    "/b_read" BRead {
        #[doc = "buffer number"]
        scalar bufnum: i32,
        #[doc = "path name of a sound file."]
        scalar path: String,
        #[doc = "starting frame in file (optional. default = 0)"]
        opt start_frame: i32,
        #[doc = "number of frames to read (optional. default = -1, see below)"]
        opt number_of_frames: i32,
        #[doc = "starting frame in buffer (optional. default = 0)"]
        opt starting_frame: i32,
        #[doc = "leave file open (optional. default = 0)"]
        opt leave_file_open: i32,
        #[doc = "an OSC message to execute upon completion. (optional)"]
        completion completion_msg,
    }
    #[doc = "Read sound file channel data into an existing buffer."]
    "/b_readChannel" BReadChannel {
        #[doc = "buffer number"]
        scalar bufnum: i32,
        #[doc = "path name of a sound file"]
        scalar path: String,
        #[doc = "starting frame in file"]
        scalar start_frame: i32,
        #[doc = "number of frames to read"]
        scalar number_of_frames: i32,
        #[doc = "starting frame in buffer"]
        scalar starting_frame: i32,
        #[doc = "leave file open"]
        scalar leave_file_open: i32,
        #[doc = "source file channel indices (one or more) to read"]
        list channels: i32,
        #[doc = "an OSC message to execute upon completion. (optional)"]
        completion completion_msg,
    }
    #[doc = "Set sample value(s)."]
    "/b_set" BSet {
        #[doc = "buffer number"]
        scalar bufnum: i32,
        #[doc = "Repeated tuples: a sample index; a sample value."]
        tail tail: (i32, f32),
    }
    #[doc = "Set ranges of sample value(s)."]
    "/b_setn" BSetn {
        #[doc = "buffer number"]
        scalar bufnum: i32,
        #[doc = "Repeated ranges — each `(start_index, samples[])` range writes `samples.len()` consecutive samples starting at `start_index`. The count is computed from the vector length, not passed separately."]
        setn tail: (i32, f32),
    }
    #[doc = "Set the sampling rate of the buffer."]
    "/b_setSampleRate" BSetSampleRate {
        #[doc = "buffer number"]
        scalar bufnum: i32,
        #[doc = "the desired sampling rate. 0 or nil will set to the Server's sample rate."]
        scalar the_desired_sampling: f32,
    }
    #[doc = "Write sound file data."]
    "/b_write" BWrite {
        #[doc = "buffer number"]
        scalar bufnum: i32,
        #[doc = "path name of a sound file."]
        scalar path: String,
        #[doc = "header format."]
        scalar header_format: String,
        #[doc = "sample format."]
        scalar sample_format: String,
        #[doc = "number of frames to write (optional. default = -1, see below)"]
        opt number_of_frames: i32,
        #[doc = "starting frame in buffer (optional. default = 0)"]
        opt starting_frame: i32,
        #[doc = "leave file open (optional. default = 0)"]
        opt leave_file_open: i32,
        #[doc = "an OSC message to execute upon completion. (optional)"]
        completion completion_msg,
    }
    #[doc = "Zero sample data."]
    "/b_zero" BZero {
        #[doc = "buffer number"]
        scalar bufnum: i32,
        #[doc = "an OSC message to execute upon completion. (optional)"]
        completion completion_msg,
    }
}
