// @generated by packages/server-commands/scripts/generate-rust.ts from specs/server-commands.json — do not edit.
// Regenerate with `yarn generate:server-commands`.

#![allow(unused_imports, unused_mut)]

use rosc::OscType;
use serde::{Deserialize, Serialize};
#[cfg(feature = "wasm")]
use tsify::Tsify;

use crate::args::OscArg;
use crate::OscMessage;

use super::prelude::{ControlId, ControlValue, NumericValue};

sc_commands! {
    #[doc = "Fill ranges of bus value(s)."]
    "/c_fill" CFill {
        #[doc = "Repeated tuples: starting bus index; number of buses to fill (M); value."]
        tail tail: (i32, i32, NumericValue),
    }
    #[doc = "Get bus value(s)."]
    "/c_get" CGet {
        #[doc = "bus indices (one or more)"]
        list bus_indices: i32,
    }
    #[doc = "Get ranges of bus value(s)."]
    "/c_getn" CGetn {
        #[doc = "Repeated tuples: starting bus index; number of sequential buses to get (M)."]
        tail tail: (i32, i32),
    }
    #[doc = "Set bus value(s)."]
    "/c_set" CSet {
        #[doc = "Repeated tuples: a bus index; a control value."]
        tail tail: (i32, NumericValue),
    }
    #[doc = "Set ranges of bus value(s)."]
    "/c_setn" CSetn {
        #[doc = "Repeated ranges — each `(start_bus, values[])` writes `values.len()` consecutive buses starting at `start_bus`. The count is encoded from the vector length."]
        setn tail: (i32, NumericValue),
    }
}
