// @generated by packages/server-commands/scripts/generate-rust.ts from specs/server-commands.json — do not edit.
// Regenerate with `yarn generate:server-commands`.

#![allow(unused_imports, unused_mut)]

use rosc::OscType;
use serde::{Deserialize, Serialize};
#[cfg(feature = "wasm")]
use tsify::Tsify;

use crate::args::OscArg;
use crate::OscMessage;

use super::prelude::{ControlId, ControlValue, NumericValue};

sc_commands! {
    #[doc = "Free all synths in this group and all its sub-groups."]
    "/g_deepFree" GDeepFree {
        #[doc = "group IDs (one or more)"]
        list group_ids: i32,
    }
    #[doc = "Post a representation of this group's node subtree."]
    "/g_dumpTree" GDumpTree {
        #[doc = "Repeated tuples: group ID; flag; if not 0 the current control (arg) values for synths will be posted."]
        tail tail: (i32, i32),
    }
    #[doc = "Delete all nodes in a group."]
    "/g_freeAll" GFreeAll {
        #[doc = "group IDs (one or more)"]
        list group_ids: i32,
    }
    #[doc = "Add node to head of group."]
    "/g_head" GHead {
        #[doc = "Repeated tuples: group ID; node ID."]
        tail tail: (i32, i32),
    }
    #[doc = "Create a new group."]
    "/g_new" GNew {
        #[doc = "Repeated tuples: new group ID; add action (0,1,2, 3 or 4 see below); add target ID."]
        tail tail: (i32, i32, i32),
    }
    #[doc = "Get a representation of this group's node subtree."]
    "/g_queryTree" GQueryTree {
        #[doc = "Repeated tuples: group ID; flag: if not 0 the current control (arg) values for synths will be included."]
        tail tail: (i32, i32),
    }
    #[doc = "Add node to tail of group."]
    "/g_tail" GTail {
        #[doc = "Repeated tuples: group ID; node ID."]
        tail tail: (i32, i32),
    }
    #[doc = "Create a new parallel group."]
    "/p_new" PNew {
        #[doc = "Repeated tuples: new group ID; add action (0,1,2, 3 or 4 see below); add target ID."]
        tail tail: (i32, i32, i32),
    }
}
