// @generated by packages/server-commands/scripts/generate-rust.ts from specs/server-commands.json — do not edit.
// Regenerate with `yarn generate:server-commands`.

use serde::{Deserialize, Serialize};
#[cfg(feature = "wasm")]
use tsify::Tsify;

use crate::OscMessage;

mod prelude;
pub use prelude::*;

mod top_level;
pub use top_level::*;

mod synthdef;
pub use synthdef::*;

mod node;
pub use node::*;

mod synth;
pub use synth::*;

mod group;
pub use group::*;

mod ugen;
pub use ugen::*;

mod buffer;
pub use buffer::*;

mod control_bus;
pub use control_bus::*;

mod nrt;
pub use nrt::*;

mod bridge;
pub use bridge::*;

define_known_message! {
    payload {
        BAlloc "/b_alloc",
        BAllocRead "/b_allocRead",
        BAllocReadChannel "/b_allocReadChannel",
        BClose "/b_close",
        BFill "/b_fill",
        BFree "/b_free",
        BGen "/b_gen",
        BGet "/b_get",
        BGetn "/b_getn",
        BQuery "/b_query",
        BRead "/b_read",
        BReadChannel "/b_readChannel",
        BSet "/b_set",
        BSetn "/b_setn",
        BSetSampleRate "/b_setSampleRate",
        BWrite "/b_write",
        BZero "/b_zero",
        CFill "/c_fill",
        CGet "/c_get",
        CGetn "/c_getn",
        CSet "/c_set",
        CSetn "/c_setn",
        GDeepFree "/g_deepFree",
        GDumpTree "/g_dumpTree",
        GFreeAll "/g_freeAll",
        GHead "/g_head",
        GNew "/g_new",
        GQueryTree "/g_queryTree",
        GTail "/g_tail",
        PNew "/p_new",
        Cmd "/cmd",
        DumpOSC "/dumpOSC",
        Error "/error",
        Notify "/notify",
        Sync "/sync",
        NAfter "/n_after",
        NBefore "/n_before",
        NFill "/n_fill",
        NFree "/n_free",
        NMap "/n_map",
        NMapa "/n_mapa",
        NMapan "/n_mapan",
        NMapn "/n_mapn",
        NOrder "/n_order",
        NQuery "/n_query",
        NRun "/n_run",
        NSet "/n_set",
        NSetn "/n_setn",
        NTrace "/n_trace",
        SGet "/s_get",
        SGetn "/s_getn",
        SNew "/s_new",
        SNoid "/s_noid",
        DFree "/d_free",
        DLoad "/d_load",
        DLoadDir "/d_loadDir",
        DRecv "/d_recv",
        UCmd "/u_cmd",
        ScopeSubscribe "/scope/subscribe",
        ScopeUnsubscribe "/scope/unsubscribe",
        DirtPlay "/dirt/play",
    }
    unit {
        ClearSched "/clearSched",
        Quit "/quit",
        RtMemoryStatus "/rtMemoryStatus",
        Status "/status",
        Version "/version",
        NrtEnd "/nrt_end",
    }
}
