// @generated by packages/server-commands/scripts/generate-rust.ts from specs/server-commands.json — do not edit.
// Regenerate with `yarn generate:server-commands`.

#![allow(unused_imports, unused_mut)]

use rosc::OscType;
use serde::{Deserialize, Serialize};
#[cfg(feature = "wasm")]
use tsify::Tsify;

use crate::args::OscArg;
use crate::OscMessage;

use super::prelude::{ControlId, ControlValue, NumericValue};

sc_commands! {
    #[doc = "Place a node after another."]
    "/n_after" NAfter {
        #[doc = "Repeated tuples: the ID of the node to place (A); the ID of the node after which the above is placed (B)."]
        tail tail: (i32, i32),
    }
    #[doc = "Place a node before another."]
    "/n_before" NBefore {
        #[doc = "Repeated tuples: the ID of the node to place (A); the ID of the node before which the above is placed (B)."]
        tail tail: (i32, i32),
    }
    #[doc = "Fill ranges of a node's control value(s)."]
    "/n_fill" NFill {
        #[doc = "node ID"]
        scalar node_id: i32,
        #[doc = "Repeated tuples: a control index or name; number of values to fill (M); value."]
        tail tail: (ControlId, i32, NumericValue),
    }
    #[doc = "Delete a node."]
    "/n_free" NFree {
        #[doc = "node IDs (one or more)"]
        list node_ids: i32,
    }
    #[doc = "Map a node's controls to read from a bus."]
    "/n_map" NMap {
        #[doc = "node ID"]
        scalar node_id: i32,
        #[doc = "Repeated tuples: a control index or name; control bus index."]
        tail tail: (ControlId, i32),
    }
    #[doc = "Map a node's controls to read from an audio bus."]
    "/n_mapa" NMapa {
        #[doc = "node ID"]
        scalar node_id: i32,
        #[doc = "Repeated tuples: a control index or name; audio bus index."]
        tail tail: (ControlId, i32),
    }
    #[doc = "Map a node's controls to read from audio buses."]
    "/n_mapan" NMapan {
        #[doc = "node ID"]
        scalar node_id: i32,
        #[doc = "Repeated tuples: a control index or name; audio bus index; number of controls to map."]
        tail tail: (ControlId, i32, i32),
    }
    #[doc = "Map a node's controls to read from buses."]
    "/n_mapn" NMapn {
        #[doc = "node ID"]
        scalar node_id: i32,
        #[doc = "Repeated tuples: a control index or name; control bus index; number of controls to map."]
        tail tail: (ControlId, i32, i32),
    }
    #[doc = "Move and order a list of nodes."]
    "/n_order" NOrder {
        #[doc = "add action (0,1,2 or 3 see below)"]
        scalar add_action: i32,
        #[doc = "add target ID"]
        scalar target_id: i32,
        #[doc = "node IDs (one or more) to reorder relative to the target"]
        list node_ids: i32,
    }
    #[doc = "Get info about a node."]
    "/n_query" NQuery {
        #[doc = "node IDs (one or more) to query"]
        list node_ids: i32,
    }
    #[doc = "Turn node on or off."]
    "/n_run" NRun {
        #[doc = "Repeated tuples: node ID; run flag."]
        tail tail: (i32, i32),
    }
    #[doc = "Set a node's control value(s)."]
    "/n_set" NSet {
        #[doc = "node ID"]
        scalar node_id: i32,
        #[doc = "Repeated tuples: a control index or name; a control value."]
        tail tail: (ControlId, NumericValue),
    }
    #[doc = "Set ranges of a node's control value(s)."]
    "/n_setn" NSetn {
        #[doc = "node ID"]
        scalar node_id: i32,
        #[doc = "Repeated ranges — each `(control, values[])` writes `values.len()` consecutive controls starting at `control`. The count is encoded from the vector length."]
        setn tail: (ControlId, NumericValue),
    }
    #[doc = "Trace a node."]
    "/n_trace" NTrace {
        #[doc = "node IDs (one or more) to trace"]
        list node_ids: i32,
    }
}
