// @generated by packages/server-commands/scripts/generate-rust.ts from specs/server-commands.json — do not edit.
// Regenerate with `yarn generate:server-commands`.

#![allow(unused_imports, unused_mut)]

use rosc::OscType;
use serde::{Deserialize, Serialize};
#[cfg(feature = "wasm")]
use tsify::Tsify;

use crate::args::OscArg;
use crate::OscMessage;

use super::prelude::{ControlId, ControlValue, NumericValue};

sc_commands! {
    #[doc = "Get control value(s)."]
    "/s_get" SGet {
        #[doc = "synth ID"]
        scalar node_id: i32,
        #[doc = "controls (one or more) — each by index or name"]
        list controls: ControlId,
    }
    #[doc = "Get ranges of control value(s)."]
    "/s_getn" SGetn {
        #[doc = "synth ID"]
        scalar node_id: i32,
        #[doc = "Repeated tuples: a control index or name; number of sequential controls to get (M)."]
        tail tail: (ControlId, i32),
    }
    #[doc = "Create a new synth."]
    "/s_new" SNew {
        #[doc = "synth definition name"]
        scalar def_name: String,
        #[doc = "synth ID"]
        scalar node_id: i32,
        #[doc = "add action (0,1,2, 3 or 4 see below)"]
        scalar add_action: i32,
        #[doc = "add target ID"]
        scalar target_id: i32,
        #[doc = "Repeated tuples: a control index or name; floating point and integer arguments are interpreted as control value. a symbol argument consisting of the letter 'c' or 'a' (for control or audio) followed by the bus's index.."]
        tail tail: (ControlId, ControlValue),
    }
    #[doc = "Auto-reassign synth's ID to a reserved value."]
    "/s_noid" SNoid {
        #[doc = "synth IDs (one or more) to reassign"]
        list synth_ids: i32,
    }
}
