// @generated by packages/server-commands/scripts/generate-rust.ts from specs/server-commands.json — do not edit.
// Regenerate with `yarn generate:server-commands`.

#![allow(unused_imports, unused_mut)]

use rosc::OscType;
use serde::{Deserialize, Serialize};
#[cfg(feature = "wasm")]
use tsify::Tsify;

use crate::args::OscArg;
use crate::OscMessage;

use super::prelude::{ControlId, ControlValue, NumericValue};

sc_commands! {
    #[doc = "Delete synth definition."]
    "/d_free" DFree {
        #[doc = "synthdef names (one or more) to delete"]
        list synth_def_names: String,
    }
    #[doc = "Load synth definition."]
    "/d_load" DLoad {
        #[doc = "pathname of file. Can be a pattern like \"synthdefs/perc-*\""]
        scalar pathname_of_file: String,
        #[doc = "an OSC message to execute upon completion. (optional)"]
        completion completion_msg,
    }
    #[doc = "Load a directory of synth definitions."]
    "/d_loadDir" DLoadDir {
        #[doc = "pathname of directory."]
        scalar pathname_of_directory: String,
        #[doc = "an OSC message to execute upon completion. (optional)"]
        completion completion_msg,
    }
    #[doc = "Receive a synth definition file."]
    "/d_recv" DRecv {
        #[doc = "buffer of data."]
        blob buffer_of_data,
        #[doc = "an OSC message to execute upon completion. (optional)"]
        completion completion_msg,
    }
}
