// @generated by packages/server-commands/scripts/generate-rust.ts from specs/server-commands.json — do not edit.
// Regenerate with `yarn generate:server-commands`.

#![allow(unused_imports, unused_mut)]

use rosc::OscType;
use serde::{Deserialize, Serialize};
#[cfg(feature = "wasm")]
use tsify::Tsify;

use crate::args::OscArg;
use crate::OscMessage;

use super::prelude::{ControlId, ControlValue, NumericValue};

sc_commands! {
    #[doc = "Clear all scheduled bundles. Removes all bundles from the scheduling queue."]
    "/clearSched" ClearSched {
    }
    #[doc = "Plug-in defined command."]
    "/cmd" Cmd {
        #[doc = "command name"]
        scalar cmd: String,
        #[doc = "variadic trailing OSC args — types depend on the specific plug-in-defined command being invoked."]
        variadic any_arguments,
    }
    #[doc = "Display incoming OSC messages."]
    "/dumpOSC" DumpOSC {
        #[doc = "code"]
        scalar code: i32,
    }
    #[doc = "Enable/disable error message posting."]
    "/error" Error {
        #[doc = "mode"]
        scalar mode: i32,
    }
    #[doc = "Register to receive notifications from server"]
    "/notify" Notify {
        #[doc = "1 to receive notifications, 0 to stop receiving them."]
        scalar enable: i32,
        #[doc = "client ID (optional)"]
        opt client_id: i32,
    }
    #[doc = "Quit program. Exits the synthesis server."]
    "/quit" Quit {
    }
    #[doc = "Queries the amount of currently free real-time memory (in bytes)."]
    "/rtMemoryStatus" RtMemoryStatus {
    }
    #[doc = "Query the status. Replies to sender with the following message:"]
    "/status" Status {
    }
    #[doc = "Notify when async commands have completed."]
    "/sync" Sync {
        #[doc = "a unique number identifying this command."]
        scalar a_unique_number: i32,
    }
    #[doc = "Query the SuperCollider version. Replies to sender with the following message:"]
    "/version" Version {
    }
}
