// @generated by packages/server-commands/scripts/generate-rust.ts from specs/server-commands.json — do not edit.
// Regenerate with `yarn generate:server-commands`.

#![allow(unused_imports, unused_mut)]

use rosc::OscType;
use serde::{Deserialize, Serialize};
#[cfg(feature = "wasm")]
use tsify::Tsify;

use crate::args::OscArg;
use crate::OscMessage;

use super::prelude::{ControlId, ControlValue, NumericValue};

sc_commands! {
    #[doc = "Send a command to a unit generator."]
    "/u_cmd" UCmd {
        #[doc = "node ID"]
        scalar node_id: i32,
        #[doc = "unit generator index"]
        scalar unit_generator_index: i32,
        #[doc = "command name"]
        scalar cmd: String,
        #[doc = "variadic trailing OSC args — types depend on the UGen command being invoked."]
        variadic any_arguments,
    }
}
