// @generated by packages/server-commands/scripts/generate-rust.ts from specs/server-commands.json — do not edit.
// Regenerate with `yarn generate:server-commands`.

/// Allocate buffer space.
#[wasm_bindgen(js_name = "bAlloc", skip_typescript)]
pub fn b_alloc(bufnum: JsValue, num_frames: JsValue, opts: JsValue) -> Result<Uint8Array, JsError> {
    let num_channels = opt_key(&opts, "numChannels");
    let completion_msg = opt_key(&opts, "completionMsg");
    let sample_rate = opt_key(&opts, "sampleRate");
    if sample_rate.is_some() && completion_msg.is_none() {
        return Err(JsError::new(
            "bAlloc: sampleRate requires completionMsg (it rides later on the wire)",
        ));
    }
    encode_msg(KnownMessage::BAlloc(BAlloc {
        bufnum: js_i32(&bufnum, "bAlloc: bufnum")?,
        num_frames: js_i32(&num_frames, "bAlloc: numFrames")?,
        num_channels: match &num_channels {
            Some(v) => Some(js_i32(v, "bAlloc: numChannels")?),
            None => {
                if completion_msg.is_some() || sample_rate.is_some() {
                    Some(1)
                } else {
                    None
                }
            }
        },
        completion_msg: match &completion_msg {
            Some(v) => Some(js_blob(v, "bAlloc: completionMsg")?),
            None => None,
        },
        sample_rate: match &sample_rate {
            Some(v) => Some(js_f32(v, "bAlloc: sampleRate")?),
            None => None,
        },
    }))
}

/// Allocate buffer space and read a sound file.
#[wasm_bindgen(js_name = "bAllocRead", skip_typescript)]
pub fn b_alloc_read(bufnum: JsValue, path: JsValue, opts: JsValue) -> Result<Uint8Array, JsError> {
    let start_frame = opt_key(&opts, "startFrame");
    let number_of_frames = opt_key(&opts, "numberOfFrames");
    let completion_msg = opt_key(&opts, "completionMsg");
    encode_msg(KnownMessage::BAllocRead(BAllocRead {
        bufnum: js_i32(&bufnum, "bAllocRead: bufnum")?,
        path: js_string(&path, "bAllocRead: path")?,
        start_frame: match &start_frame {
            Some(v) => Some(js_i32(v, "bAllocRead: startFrame")?),
            None => {
                if number_of_frames.is_some() || completion_msg.is_some() {
                    Some(0)
                } else {
                    None
                }
            }
        },
        number_of_frames: match &number_of_frames {
            Some(v) => Some(js_i32(v, "bAllocRead: numberOfFrames")?),
            None => {
                if completion_msg.is_some() {
                    Some(0)
                } else {
                    None
                }
            }
        },
        completion_msg: match &completion_msg {
            Some(v) => Some(js_blob(v, "bAllocRead: completionMsg")?),
            None => None,
        },
    }))
}

/// Allocate buffer space and read channels from a sound file.
#[wasm_bindgen(js_name = "bAllocReadChannel", skip_typescript)]
pub fn b_alloc_read_channel(
    bufnum: JsValue,
    path: JsValue,
    start_frame: JsValue,
    number_of_frames: JsValue,
    channels: JsValue,
    completion_msg: JsValue,
) -> Result<Uint8Array, JsError> {
    encode_msg(KnownMessage::BAllocReadChannel(BAllocReadChannel {
        bufnum: js_i32(&bufnum, "bAllocReadChannel: bufnum")?,
        path: js_string(&path, "bAllocReadChannel: path")?,
        start_frame: js_i32(&start_frame, "bAllocReadChannel: startFrame")?,
        number_of_frames: js_i32(&number_of_frames, "bAllocReadChannel: numberOfFrames")?,
        channels: js_list(&channels, "bAllocReadChannel: channels", js_i32)?,
        completion_msg: if completion_msg.is_undefined() {
            None
        } else {
            Some(js_blob(
                &completion_msg,
                "bAllocReadChannel: completionMsg",
            )?)
        },
    }))
}

/// Close soundfile.
#[wasm_bindgen(js_name = "bClose", skip_typescript)]
pub fn b_close(bufnum: JsValue, completion_msg: JsValue) -> Result<Uint8Array, JsError> {
    encode_msg(KnownMessage::BClose(BClose {
        bufnum: js_i32(&bufnum, "bClose: bufnum")?,
        completion_msg: if completion_msg.is_undefined() {
            None
        } else {
            Some(js_blob(&completion_msg, "bClose: completionMsg")?)
        },
    }))
}

/// Fill ranges of sample value(s).
#[wasm_bindgen(js_name = "bFill", skip_typescript)]
pub fn b_fill(bufnum: JsValue, tail: JsValue) -> Result<Uint8Array, JsError> {
    encode_msg(KnownMessage::BFill(BFill {
        bufnum: js_i32(&bufnum, "bFill: bufnum")?,
        tail: js_triples(&tail, "bFill: tail", js_i32, js_i32, js_f32)?,
    }))
}

/// Free buffer data.
#[wasm_bindgen(js_name = "bFree", skip_typescript)]
pub fn b_free(bufnum: JsValue, completion_msg: JsValue) -> Result<Uint8Array, JsError> {
    encode_msg(KnownMessage::BFree(BFree {
        bufnum: js_i32(&bufnum, "bFree: bufnum")?,
        completion_msg: if completion_msg.is_undefined() {
            None
        } else {
            Some(js_blob(&completion_msg, "bFree: completionMsg")?)
        },
    }))
}

/// Call a command to fill a buffer.
#[wasm_bindgen(js_name = "bGen", skip_typescript)]
pub fn b_gen(
    bufnum: JsValue,
    cmd: JsValue,
    command_arguments: JsValue,
) -> Result<Uint8Array, JsError> {
    encode_msg(KnownMessage::BGen(BGen {
        bufnum: js_i32(&bufnum, "bGen: bufnum")?,
        cmd: js_string(&cmd, "bGen: cmd")?,
        command_arguments: js_list(&command_arguments, "bGen: commandArguments", js_osc_arg)?,
    }))
}

/// Get sample value(s).
#[wasm_bindgen(js_name = "bGet", skip_typescript)]
pub fn b_get(bufnum: JsValue, sample_indices: JsValue) -> Result<Uint8Array, JsError> {
    encode_msg(KnownMessage::BGet(BGet {
        bufnum: js_i32(&bufnum, "bGet: bufnum")?,
        sample_indices: js_list(&sample_indices, "bGet: sampleIndices", js_i32)?,
    }))
}

/// Get ranges of sample value(s).
#[wasm_bindgen(js_name = "bGetn", skip_typescript)]
pub fn b_getn(bufnum: JsValue, tail: JsValue) -> Result<Uint8Array, JsError> {
    encode_msg(KnownMessage::BGetn(BGetn {
        bufnum: js_i32(&bufnum, "bGetn: bufnum")?,
        tail: js_pairs(&tail, "bGetn: tail", js_i32, js_i32)?,
    }))
}

/// Get buffer info.
#[wasm_bindgen(js_name = "bQuery", skip_typescript)]
pub fn b_query(bufnums: JsValue) -> Result<Uint8Array, JsError> {
    encode_msg(KnownMessage::BQuery(BQuery {
        bufnums: js_list(&bufnums, "bQuery: bufnums", js_i32)?,
    }))
}

/// Read sound file data into an existing buffer.
#[wasm_bindgen(js_name = "bRead", skip_typescript)]
pub fn b_read(bufnum: JsValue, path: JsValue, opts: JsValue) -> Result<Uint8Array, JsError> {
    let start_frame = opt_key(&opts, "startFrame");
    let number_of_frames = opt_key(&opts, "numberOfFrames");
    let starting_frame = opt_key(&opts, "startingFrame");
    let leave_file_open = opt_key(&opts, "leaveFileOpen");
    let completion_msg = opt_key(&opts, "completionMsg");
    encode_msg(KnownMessage::BRead(BRead {
        bufnum: js_i32(&bufnum, "bRead: bufnum")?,
        path: js_string(&path, "bRead: path")?,
        start_frame: match &start_frame {
            Some(v) => Some(js_i32(v, "bRead: startFrame")?),
            None => {
                if number_of_frames.is_some()
                    || starting_frame.is_some()
                    || leave_file_open.is_some()
                    || completion_msg.is_some()
                {
                    Some(0)
                } else {
                    None
                }
            }
        },
        number_of_frames: match &number_of_frames {
            Some(v) => Some(js_i32(v, "bRead: numberOfFrames")?),
            None => {
                if starting_frame.is_some() || leave_file_open.is_some() || completion_msg.is_some()
                {
                    Some(-1)
                } else {
                    None
                }
            }
        },
        starting_frame: match &starting_frame {
            Some(v) => Some(js_i32(v, "bRead: startingFrame")?),
            None => {
                if leave_file_open.is_some() || completion_msg.is_some() {
                    Some(0)
                } else {
                    None
                }
            }
        },
        leave_file_open: match &leave_file_open {
            Some(v) => Some(js_i32(v, "bRead: leaveFileOpen")?),
            None => {
                if completion_msg.is_some() {
                    Some(0)
                } else {
                    None
                }
            }
        },
        completion_msg: match &completion_msg {
            Some(v) => Some(js_blob(v, "bRead: completionMsg")?),
            None => None,
        },
    }))
}

/// Read sound file channel data into an existing buffer.
#[wasm_bindgen(js_name = "bReadChannel", skip_typescript)]
pub fn b_read_channel(
    bufnum: JsValue,
    path: JsValue,
    start_frame: JsValue,
    number_of_frames: JsValue,
    starting_frame: JsValue,
    leave_file_open: JsValue,
    channels: JsValue,
    completion_msg: JsValue,
) -> Result<Uint8Array, JsError> {
    encode_msg(KnownMessage::BReadChannel(BReadChannel {
        bufnum: js_i32(&bufnum, "bReadChannel: bufnum")?,
        path: js_string(&path, "bReadChannel: path")?,
        start_frame: js_i32(&start_frame, "bReadChannel: startFrame")?,
        number_of_frames: js_i32(&number_of_frames, "bReadChannel: numberOfFrames")?,
        starting_frame: js_i32(&starting_frame, "bReadChannel: startingFrame")?,
        leave_file_open: js_i32(&leave_file_open, "bReadChannel: leaveFileOpen")?,
        channels: js_list(&channels, "bReadChannel: channels", js_i32)?,
        completion_msg: if completion_msg.is_undefined() {
            None
        } else {
            Some(js_blob(&completion_msg, "bReadChannel: completionMsg")?)
        },
    }))
}

/// Set sample value(s).
#[wasm_bindgen(js_name = "bSet", skip_typescript)]
pub fn b_set(bufnum: JsValue, tail: JsValue) -> Result<Uint8Array, JsError> {
    encode_msg(KnownMessage::BSet(BSet {
        bufnum: js_i32(&bufnum, "bSet: bufnum")?,
        tail: js_pairs(&tail, "bSet: tail", js_i32, js_f32)?,
    }))
}

/// Set ranges of sample value(s).
#[wasm_bindgen(js_name = "bSetn", skip_typescript)]
pub fn b_setn(bufnum: JsValue, tail: JsValue) -> Result<Uint8Array, JsError> {
    encode_msg(KnownMessage::BSetn(BSetn {
        bufnum: js_i32(&bufnum, "bSetn: bufnum")?,
        tail: js_setn(&tail, "bSetn: tail", js_i32, js_f32)?,
    }))
}

/// Set the sampling rate of the buffer.
#[wasm_bindgen(js_name = "bSetSampleRate", skip_typescript)]
pub fn b_set_sample_rate(
    bufnum: JsValue,
    the_desired_sampling: JsValue,
) -> Result<Uint8Array, JsError> {
    encode_msg(KnownMessage::BSetSampleRate(BSetSampleRate {
        bufnum: js_i32(&bufnum, "bSetSampleRate: bufnum")?,
        the_desired_sampling: js_f32(&the_desired_sampling, "bSetSampleRate: theDesiredSampling")?,
    }))
}

/// Write sound file data.
#[wasm_bindgen(js_name = "bWrite", skip_typescript)]
pub fn b_write(
    bufnum: JsValue,
    path: JsValue,
    header_format: JsValue,
    sample_format: JsValue,
    opts: JsValue,
) -> Result<Uint8Array, JsError> {
    let number_of_frames = opt_key(&opts, "numberOfFrames");
    let starting_frame = opt_key(&opts, "startingFrame");
    let leave_file_open = opt_key(&opts, "leaveFileOpen");
    let completion_msg = opt_key(&opts, "completionMsg");
    encode_msg(KnownMessage::BWrite(BWrite {
        bufnum: js_i32(&bufnum, "bWrite: bufnum")?,
        path: js_string(&path, "bWrite: path")?,
        header_format: js_string(&header_format, "bWrite: headerFormat")?,
        sample_format: js_string(&sample_format, "bWrite: sampleFormat")?,
        number_of_frames: match &number_of_frames {
            Some(v) => Some(js_i32(v, "bWrite: numberOfFrames")?),
            None => {
                if starting_frame.is_some() || leave_file_open.is_some() || completion_msg.is_some()
                {
                    Some(-1)
                } else {
                    None
                }
            }
        },
        starting_frame: match &starting_frame {
            Some(v) => Some(js_i32(v, "bWrite: startingFrame")?),
            None => {
                if leave_file_open.is_some() || completion_msg.is_some() {
                    Some(0)
                } else {
                    None
                }
            }
        },
        leave_file_open: match &leave_file_open {
            Some(v) => Some(js_i32(v, "bWrite: leaveFileOpen")?),
            None => {
                if completion_msg.is_some() {
                    Some(0)
                } else {
                    None
                }
            }
        },
        completion_msg: match &completion_msg {
            Some(v) => Some(js_blob(v, "bWrite: completionMsg")?),
            None => None,
        },
    }))
}

/// Zero sample data.
#[wasm_bindgen(js_name = "bZero", skip_typescript)]
pub fn b_zero(bufnum: JsValue, completion_msg: JsValue) -> Result<Uint8Array, JsError> {
    encode_msg(KnownMessage::BZero(BZero {
        bufnum: js_i32(&bufnum, "bZero: bufnum")?,
        completion_msg: if completion_msg.is_undefined() {
            None
        } else {
            Some(js_blob(&completion_msg, "bZero: completionMsg")?)
        },
    }))
}

/// Fill ranges of bus value(s).
#[wasm_bindgen(js_name = "cFill", skip_typescript)]
pub fn c_fill(tail: JsValue) -> Result<Uint8Array, JsError> {
    encode_msg(KnownMessage::CFill(CFill {
        tail: js_triples(&tail, "cFill: tail", js_i32, js_i32, js_numeric_value)?,
    }))
}

/// Get bus value(s).
#[wasm_bindgen(js_name = "cGet", skip_typescript)]
pub fn c_get(bus_indices: JsValue) -> Result<Uint8Array, JsError> {
    encode_msg(KnownMessage::CGet(CGet {
        bus_indices: js_list(&bus_indices, "cGet: busIndices", js_i32)?,
    }))
}

/// Get ranges of bus value(s).
#[wasm_bindgen(js_name = "cGetn", skip_typescript)]
pub fn c_getn(tail: JsValue) -> Result<Uint8Array, JsError> {
    encode_msg(KnownMessage::CGetn(CGetn {
        tail: js_pairs(&tail, "cGetn: tail", js_i32, js_i32)?,
    }))
}

/// Set bus value(s).
#[wasm_bindgen(js_name = "cSet", skip_typescript)]
pub fn c_set(tail: JsValue) -> Result<Uint8Array, JsError> {
    encode_msg(KnownMessage::CSet(CSet {
        tail: js_pairs(&tail, "cSet: tail", js_i32, js_numeric_value)?,
    }))
}

/// Set ranges of bus value(s).
#[wasm_bindgen(js_name = "cSetn", skip_typescript)]
pub fn c_setn(tail: JsValue) -> Result<Uint8Array, JsError> {
    encode_msg(KnownMessage::CSetn(CSetn {
        tail: js_setn(&tail, "cSetn: tail", js_i32, js_numeric_value)?,
    }))
}

/// Free all synths in this group and all its sub-groups.
#[wasm_bindgen(js_name = "gDeepFree", skip_typescript)]
pub fn g_deep_free(group_ids: JsValue) -> Result<Uint8Array, JsError> {
    encode_msg(KnownMessage::GDeepFree(GDeepFree {
        group_ids: js_list(&group_ids, "gDeepFree: groupIds", js_i32)?,
    }))
}

/// Post a representation of this group's node subtree.
#[wasm_bindgen(js_name = "gDumpTree", skip_typescript)]
pub fn g_dump_tree(tail: JsValue) -> Result<Uint8Array, JsError> {
    encode_msg(KnownMessage::GDumpTree(GDumpTree {
        tail: js_pairs(&tail, "gDumpTree: tail", js_i32, js_i32)?,
    }))
}

/// Delete all nodes in a group.
#[wasm_bindgen(js_name = "gFreeAll", skip_typescript)]
pub fn g_free_all(group_ids: JsValue) -> Result<Uint8Array, JsError> {
    encode_msg(KnownMessage::GFreeAll(GFreeAll {
        group_ids: js_list(&group_ids, "gFreeAll: groupIds", js_i32)?,
    }))
}

/// Add node to head of group.
#[wasm_bindgen(js_name = "gHead", skip_typescript)]
pub fn g_head(tail: JsValue) -> Result<Uint8Array, JsError> {
    encode_msg(KnownMessage::GHead(GHead {
        tail: js_pairs(&tail, "gHead: tail", js_i32, js_i32)?,
    }))
}

/// Create a new group.
#[wasm_bindgen(js_name = "gNew", skip_typescript)]
pub fn g_new(tail: JsValue) -> Result<Uint8Array, JsError> {
    encode_msg(KnownMessage::GNew(GNew {
        tail: js_triples(&tail, "gNew: tail", js_i32, js_i32, js_i32)?,
    }))
}

/// Get a representation of this group's node subtree.
#[wasm_bindgen(js_name = "gQueryTree", skip_typescript)]
pub fn g_query_tree(tail: JsValue) -> Result<Uint8Array, JsError> {
    encode_msg(KnownMessage::GQueryTree(GQueryTree {
        tail: js_pairs(&tail, "gQueryTree: tail", js_i32, js_i32)?,
    }))
}

/// Add node to tail of group.
#[wasm_bindgen(js_name = "gTail", skip_typescript)]
pub fn g_tail(tail: JsValue) -> Result<Uint8Array, JsError> {
    encode_msg(KnownMessage::GTail(GTail {
        tail: js_pairs(&tail, "gTail: tail", js_i32, js_i32)?,
    }))
}

/// Create a new parallel group.
#[wasm_bindgen(js_name = "pNew", skip_typescript)]
pub fn p_new(tail: JsValue) -> Result<Uint8Array, JsError> {
    encode_msg(KnownMessage::PNew(PNew {
        tail: js_triples(&tail, "pNew: tail", js_i32, js_i32, js_i32)?,
    }))
}

/// Clear all scheduled bundles. Removes all bundles from the scheduling queue.
#[wasm_bindgen(js_name = "clearSched", skip_typescript)]
pub fn clear_sched() -> Result<Uint8Array, JsError> {
    encode_msg(KnownMessage::ClearSched)
}

/// Plug-in defined command.
#[wasm_bindgen(js_name = "cmd", skip_typescript)]
pub fn cmd(cmd: JsValue, any_arguments: JsValue) -> Result<Uint8Array, JsError> {
    encode_msg(KnownMessage::Cmd(Cmd {
        cmd: js_string(&cmd, "cmd: cmd")?,
        any_arguments: js_list(&any_arguments, "cmd: anyArguments", js_osc_arg)?,
    }))
}

/// Display incoming OSC messages.
#[wasm_bindgen(js_name = "dumpOSC", skip_typescript)]
pub fn dump_osc(code: JsValue) -> Result<Uint8Array, JsError> {
    encode_msg(KnownMessage::DumpOSC(DumpOSC {
        code: js_i32(&code, "dumpOSC: code")?,
    }))
}

/// Enable/disable error message posting.
#[wasm_bindgen(js_name = "error", skip_typescript)]
pub fn error(mode: JsValue) -> Result<Uint8Array, JsError> {
    encode_msg(KnownMessage::Error(Error {
        mode: js_i32(&mode, "error: mode")?,
    }))
}

/// Register to receive notifications from server
#[wasm_bindgen(js_name = "notify", skip_typescript)]
pub fn notify(enable: JsValue, client_id: JsValue) -> Result<Uint8Array, JsError> {
    encode_msg(KnownMessage::Notify(Notify {
        enable: js_i32(&enable, "notify: enable")?,
        client_id: if client_id.is_undefined() {
            None
        } else {
            Some(js_i32(&client_id, "notify: clientId")?)
        },
    }))
}

/// Quit program. Exits the synthesis server.
#[wasm_bindgen(js_name = "quit", skip_typescript)]
pub fn quit() -> Result<Uint8Array, JsError> {
    encode_msg(KnownMessage::Quit)
}

/// Queries the amount of currently free real-time memory (in bytes).
#[wasm_bindgen(js_name = "rtMemoryStatus", skip_typescript)]
pub fn rt_memory_status() -> Result<Uint8Array, JsError> {
    encode_msg(KnownMessage::RtMemoryStatus)
}

/// Query the status. Replies to sender with the following message:
#[wasm_bindgen(js_name = "status", skip_typescript)]
pub fn status() -> Result<Uint8Array, JsError> {
    encode_msg(KnownMessage::Status)
}

/// Notify when async commands have completed.
#[wasm_bindgen(js_name = "sync", skip_typescript)]
pub fn sync(a_unique_number: JsValue) -> Result<Uint8Array, JsError> {
    encode_msg(KnownMessage::Sync(Sync {
        a_unique_number: js_i32(&a_unique_number, "sync: aUniqueNumber")?,
    }))
}

/// Query the SuperCollider version. Replies to sender with the following message:
#[wasm_bindgen(js_name = "version", skip_typescript)]
pub fn version() -> Result<Uint8Array, JsError> {
    encode_msg(KnownMessage::Version)
}

/// Place a node after another.
#[wasm_bindgen(js_name = "nAfter", skip_typescript)]
pub fn n_after(tail: JsValue) -> Result<Uint8Array, JsError> {
    encode_msg(KnownMessage::NAfter(NAfter {
        tail: js_pairs(&tail, "nAfter: tail", js_i32, js_i32)?,
    }))
}

/// Place a node before another.
#[wasm_bindgen(js_name = "nBefore", skip_typescript)]
pub fn n_before(tail: JsValue) -> Result<Uint8Array, JsError> {
    encode_msg(KnownMessage::NBefore(NBefore {
        tail: js_pairs(&tail, "nBefore: tail", js_i32, js_i32)?,
    }))
}

/// Fill ranges of a node's control value(s).
#[wasm_bindgen(js_name = "nFill", skip_typescript)]
pub fn n_fill(node_id: JsValue, tail: JsValue) -> Result<Uint8Array, JsError> {
    encode_msg(KnownMessage::NFill(NFill {
        node_id: js_i32(&node_id, "nFill: nodeId")?,
        tail: js_triples(
            &tail,
            "nFill: tail",
            js_control_id,
            js_i32,
            js_numeric_value,
        )?,
    }))
}

/// Delete a node.
#[wasm_bindgen(js_name = "nFree", skip_typescript)]
pub fn n_free(node_ids: JsValue) -> Result<Uint8Array, JsError> {
    encode_msg(KnownMessage::NFree(NFree {
        node_ids: js_list(&node_ids, "nFree: nodeIds", js_i32)?,
    }))
}

/// Map a node's controls to read from a bus.
#[wasm_bindgen(js_name = "nMap", skip_typescript)]
pub fn n_map(node_id: JsValue, tail: JsValue) -> Result<Uint8Array, JsError> {
    encode_msg(KnownMessage::NMap(NMap {
        node_id: js_i32(&node_id, "nMap: nodeId")?,
        tail: js_pairs(&tail, "nMap: tail", js_control_id, js_i32)?,
    }))
}

/// Map a node's controls to read from an audio bus.
#[wasm_bindgen(js_name = "nMapa", skip_typescript)]
pub fn n_mapa(node_id: JsValue, tail: JsValue) -> Result<Uint8Array, JsError> {
    encode_msg(KnownMessage::NMapa(NMapa {
        node_id: js_i32(&node_id, "nMapa: nodeId")?,
        tail: js_pairs(&tail, "nMapa: tail", js_control_id, js_i32)?,
    }))
}

/// Map a node's controls to read from audio buses.
#[wasm_bindgen(js_name = "nMapan", skip_typescript)]
pub fn n_mapan(node_id: JsValue, tail: JsValue) -> Result<Uint8Array, JsError> {
    encode_msg(KnownMessage::NMapan(NMapan {
        node_id: js_i32(&node_id, "nMapan: nodeId")?,
        tail: js_triples(&tail, "nMapan: tail", js_control_id, js_i32, js_i32)?,
    }))
}

/// Map a node's controls to read from buses.
#[wasm_bindgen(js_name = "nMapn", skip_typescript)]
pub fn n_mapn(node_id: JsValue, tail: JsValue) -> Result<Uint8Array, JsError> {
    encode_msg(KnownMessage::NMapn(NMapn {
        node_id: js_i32(&node_id, "nMapn: nodeId")?,
        tail: js_triples(&tail, "nMapn: tail", js_control_id, js_i32, js_i32)?,
    }))
}

/// Move and order a list of nodes.
#[wasm_bindgen(js_name = "nOrder", skip_typescript)]
pub fn n_order(
    add_action: JsValue,
    target_id: JsValue,
    node_ids: JsValue,
) -> Result<Uint8Array, JsError> {
    encode_msg(KnownMessage::NOrder(NOrder {
        add_action: js_i32(&add_action, "nOrder: addAction")?,
        target_id: js_i32(&target_id, "nOrder: targetId")?,
        node_ids: js_list(&node_ids, "nOrder: nodeIds", js_i32)?,
    }))
}

/// Get info about a node.
#[wasm_bindgen(js_name = "nQuery", skip_typescript)]
pub fn n_query(node_ids: JsValue) -> Result<Uint8Array, JsError> {
    encode_msg(KnownMessage::NQuery(NQuery {
        node_ids: js_list(&node_ids, "nQuery: nodeIds", js_i32)?,
    }))
}

/// Turn node on or off.
#[wasm_bindgen(js_name = "nRun", skip_typescript)]
pub fn n_run(tail: JsValue) -> Result<Uint8Array, JsError> {
    encode_msg(KnownMessage::NRun(NRun {
        tail: js_pairs(&tail, "nRun: tail", js_i32, js_i32)?,
    }))
}

/// Set a node's control value(s).
#[wasm_bindgen(js_name = "nSet", skip_typescript)]
pub fn n_set(node_id: JsValue, tail: JsValue) -> Result<Uint8Array, JsError> {
    encode_msg(KnownMessage::NSet(NSet {
        node_id: js_i32(&node_id, "nSet: nodeId")?,
        tail: js_pairs(&tail, "nSet: tail", js_control_id, js_numeric_value)?,
    }))
}

/// Set ranges of a node's control value(s).
#[wasm_bindgen(js_name = "nSetn", skip_typescript)]
pub fn n_setn(node_id: JsValue, tail: JsValue) -> Result<Uint8Array, JsError> {
    encode_msg(KnownMessage::NSetn(NSetn {
        node_id: js_i32(&node_id, "nSetn: nodeId")?,
        tail: js_setn(&tail, "nSetn: tail", js_control_id, js_numeric_value)?,
    }))
}

/// Trace a node.
#[wasm_bindgen(js_name = "nTrace", skip_typescript)]
pub fn n_trace(node_ids: JsValue) -> Result<Uint8Array, JsError> {
    encode_msg(KnownMessage::NTrace(NTrace {
        node_ids: js_list(&node_ids, "nTrace: nodeIds", js_i32)?,
    }))
}

/// End real time mode, close file. Not yet implemented. This message should be sent in a bundle in non real time mode. The bundle timestamp will establish the ending time of the file. This command will end non real time mode and close the sound file. Replies to sender with /done when complete.
#[wasm_bindgen(js_name = "nrtEnd", skip_typescript)]
pub fn nrt_end() -> Result<Uint8Array, JsError> {
    encode_msg(KnownMessage::NrtEnd)
}

/// Get control value(s).
#[wasm_bindgen(js_name = "sGet", skip_typescript)]
pub fn s_get(node_id: JsValue, controls: JsValue) -> Result<Uint8Array, JsError> {
    encode_msg(KnownMessage::SGet(SGet {
        node_id: js_i32(&node_id, "sGet: nodeId")?,
        controls: js_list(&controls, "sGet: controls", js_control_id)?,
    }))
}

/// Get ranges of control value(s).
#[wasm_bindgen(js_name = "sGetn", skip_typescript)]
pub fn s_getn(node_id: JsValue, tail: JsValue) -> Result<Uint8Array, JsError> {
    encode_msg(KnownMessage::SGetn(SGetn {
        node_id: js_i32(&node_id, "sGetn: nodeId")?,
        tail: js_pairs(&tail, "sGetn: tail", js_control_id, js_i32)?,
    }))
}

/// Create a new synth.
#[wasm_bindgen(js_name = "sNew", skip_typescript)]
pub fn s_new(
    def_name: JsValue,
    node_id: JsValue,
    add_action: JsValue,
    target_id: JsValue,
    tail: JsValue,
) -> Result<Uint8Array, JsError> {
    encode_msg(KnownMessage::SNew(SNew {
        def_name: js_string(&def_name, "sNew: defName")?,
        node_id: js_i32(&node_id, "sNew: nodeId")?,
        add_action: js_i32(&add_action, "sNew: addAction")?,
        target_id: js_i32(&target_id, "sNew: targetId")?,
        tail: js_pairs(&tail, "sNew: tail", js_control_id, js_control_value)?,
    }))
}

/// Auto-reassign synth's ID to a reserved value.
#[wasm_bindgen(js_name = "sNoid", skip_typescript)]
pub fn s_noid(synth_ids: JsValue) -> Result<Uint8Array, JsError> {
    encode_msg(KnownMessage::SNoid(SNoid {
        synth_ids: js_list(&synth_ids, "sNoid: synthIds", js_i32)?,
    }))
}

/// Delete synth definition.
#[wasm_bindgen(js_name = "dFree", skip_typescript)]
pub fn d_free(synth_def_names: JsValue) -> Result<Uint8Array, JsError> {
    encode_msg(KnownMessage::DFree(DFree {
        synth_def_names: js_list(&synth_def_names, "dFree: synthDefNames", js_string)?,
    }))
}

/// Load synth definition.
#[wasm_bindgen(js_name = "dLoad", skip_typescript)]
pub fn d_load(pathname_of_file: JsValue, completion_msg: JsValue) -> Result<Uint8Array, JsError> {
    encode_msg(KnownMessage::DLoad(DLoad {
        pathname_of_file: js_string(&pathname_of_file, "dLoad: pathnameOfFile")?,
        completion_msg: if completion_msg.is_undefined() {
            None
        } else {
            Some(js_blob(&completion_msg, "dLoad: completionMsg")?)
        },
    }))
}

/// Load a directory of synth definitions.
#[wasm_bindgen(js_name = "dLoadDir", skip_typescript)]
pub fn d_load_dir(
    pathname_of_directory: JsValue,
    completion_msg: JsValue,
) -> Result<Uint8Array, JsError> {
    encode_msg(KnownMessage::DLoadDir(DLoadDir {
        pathname_of_directory: js_string(&pathname_of_directory, "dLoadDir: pathnameOfDirectory")?,
        completion_msg: if completion_msg.is_undefined() {
            None
        } else {
            Some(js_blob(&completion_msg, "dLoadDir: completionMsg")?)
        },
    }))
}

/// Receive a synth definition file.
#[wasm_bindgen(js_name = "dRecv", skip_typescript)]
pub fn d_recv(buffer_of_data: JsValue, completion_msg: JsValue) -> Result<Uint8Array, JsError> {
    encode_msg(KnownMessage::DRecv(DRecv {
        buffer_of_data: js_blob(&buffer_of_data, "dRecv: bufferOfData")?,
        completion_msg: if completion_msg.is_undefined() {
            None
        } else {
            Some(js_blob(&completion_msg, "dRecv: completionMsg")?)
        },
    }))
}

/// Send a command to a unit generator.
#[wasm_bindgen(js_name = "uCmd", skip_typescript)]
pub fn u_cmd(
    node_id: JsValue,
    unit_generator_index: JsValue,
    cmd: JsValue,
    any_arguments: JsValue,
) -> Result<Uint8Array, JsError> {
    encode_msg(KnownMessage::UCmd(UCmd {
        node_id: js_i32(&node_id, "uCmd: nodeId")?,
        unit_generator_index: js_i32(&unit_generator_index, "uCmd: unitGeneratorIndex")?,
        cmd: js_string(&cmd, "uCmd: cmd")?,
        any_arguments: js_list(&any_arguments, "uCmd: anyArguments", js_osc_arg)?,
    }))
}

/// sc-app bridge extension (not in the SC command reference): register a scope-slot stream with the bridge. The bridge is the consumer, so the struct also carries from_message/decode parsers.
#[wasm_bindgen(js_name = "scopeSubscribe", skip_typescript)]
pub fn scope_subscribe(
    sub_id: JsValue,
    scope: JsValue,
    channels: JsValue,
    chunk_size: JsValue,
) -> Result<Uint8Array, JsError> {
    encode_msg(KnownMessage::ScopeSubscribe(ScopeSubscribe {
        sub_id: js_i32(&sub_id, "scopeSubscribe: subId")?,
        scope: js_i32(&scope, "scopeSubscribe: scope")?,
        channels: js_i32(&channels, "scopeSubscribe: channels")?,
        chunk_size: js_i32(&chunk_size, "scopeSubscribe: chunkSize")?,
    }))
}

/// sc-app bridge extension (not in the SC command reference): drop a scope-slot stream.
#[wasm_bindgen(js_name = "scopeUnsubscribe", skip_typescript)]
pub fn scope_unsubscribe(sub_id: JsValue) -> Result<Uint8Array, JsError> {
    encode_msg(KnownMessage::ScopeUnsubscribe(ScopeUnsubscribe {
        sub_id: js_i32(&sub_id, "scopeUnsubscribe: subId")?,
    }))
}

/// sc-app bridge extension (not in the SC command reference): a SuperDirt/Strudel event, routed by the bridge to the strudel peer. The wire format is SuperDirt's alternating key/value arg list.
#[wasm_bindgen(js_name = "dirtPlay", skip_typescript)]
pub fn dirt_play(pairs: JsValue) -> Result<Uint8Array, JsError> {
    encode_msg(KnownMessage::DirtPlay(DirtPlay {
        pairs: js_pairs(&pairs, "dirtPlay: pairs", js_string, js_osc_arg)?,
    }))
}

#[wasm_bindgen(typescript_custom_section)]
const TS_COMMANDS: &'static str = r"/** `/b_alloc` — Allocate buffer space. */
export function bAlloc(bufnum: number, numFrames: number, opts?: { numChannels?: number; completionMsg?: Uint8Array; sampleRate?: number }): Uint8Array;
/** `/b_allocRead` — Allocate buffer space and read a sound file. */
export function bAllocRead(bufnum: number, path: string, opts?: { startFrame?: number; numberOfFrames?: number; completionMsg?: Uint8Array }): Uint8Array;
/** `/b_allocReadChannel` — Allocate buffer space and read channels from a sound file. */
export function bAllocReadChannel(bufnum: number, path: string, startFrame: number, numberOfFrames: number, channels?: Array<number>, completionMsg?: Uint8Array): Uint8Array;
/** `/b_close` — Close soundfile. */
export function bClose(bufnum: number, completionMsg?: Uint8Array): Uint8Array;
/** `/b_fill` — Fill ranges of sample value(s). */
export function bFill(bufnum: number, tail?: Array<[number, number, number]>): Uint8Array;
/** `/b_free` — Free buffer data. */
export function bFree(bufnum: number, completionMsg?: Uint8Array): Uint8Array;
/** `/b_gen` — Call a command to fill a buffer. */
export function bGen(bufnum: number, cmd: string, commandArguments?: Array<number | string | Uint8Array>): Uint8Array;
/** `/b_get` — Get sample value(s). */
export function bGet(bufnum: number, sampleIndices?: Array<number>): Uint8Array;
/** `/b_getn` — Get ranges of sample value(s). */
export function bGetn(bufnum: number, tail?: Array<[number, number]>): Uint8Array;
/** `/b_query` — Get buffer info. */
export function bQuery(bufnums?: Array<number>): Uint8Array;
/** `/b_read` — Read sound file data into an existing buffer. */
export function bRead(bufnum: number, path: string, opts?: { startFrame?: number; numberOfFrames?: number; startingFrame?: number; leaveFileOpen?: number; completionMsg?: Uint8Array }): Uint8Array;
/** `/b_readChannel` — Read sound file channel data into an existing buffer. */
export function bReadChannel(bufnum: number, path: string, startFrame: number, numberOfFrames: number, startingFrame: number, leaveFileOpen: number, channels?: Array<number>, completionMsg?: Uint8Array): Uint8Array;
/** `/b_set` — Set sample value(s). */
export function bSet(bufnum: number, tail?: Array<[number, number]>): Uint8Array;
/** `/b_setn` — Set ranges of sample value(s). */
export function bSetn(bufnum: number, tail?: Array<[number, Array<number>]>): Uint8Array;
/** `/b_setSampleRate` — Set the sampling rate of the buffer. */
export function bSetSampleRate(bufnum: number, theDesiredSampling: number): Uint8Array;
/** `/b_write` — Write sound file data. */
export function bWrite(bufnum: number, path: string, headerFormat: string, sampleFormat: string, opts?: { numberOfFrames?: number; startingFrame?: number; leaveFileOpen?: number; completionMsg?: Uint8Array }): Uint8Array;
/** `/b_zero` — Zero sample data. */
export function bZero(bufnum: number, completionMsg?: Uint8Array): Uint8Array;
/** `/c_fill` — Fill ranges of bus value(s). */
export function cFill(tail?: Array<[number, number, number]>): Uint8Array;
/** `/c_get` — Get bus value(s). */
export function cGet(busIndices?: Array<number>): Uint8Array;
/** `/c_getn` — Get ranges of bus value(s). */
export function cGetn(tail?: Array<[number, number]>): Uint8Array;
/** `/c_set` — Set bus value(s). */
export function cSet(tail?: Array<[number, number]>): Uint8Array;
/** `/c_setn` — Set ranges of bus value(s). */
export function cSetn(tail?: Array<[number, Array<number>]>): Uint8Array;
/** `/g_deepFree` — Free all synths in this group and all its sub-groups. */
export function gDeepFree(groupIds?: Array<number>): Uint8Array;
/** `/g_dumpTree` — Post a representation of this group's node subtree. */
export function gDumpTree(tail?: Array<[number, number]>): Uint8Array;
/** `/g_freeAll` — Delete all nodes in a group. */
export function gFreeAll(groupIds?: Array<number>): Uint8Array;
/** `/g_head` — Add node to head of group. */
export function gHead(tail?: Array<[number, number]>): Uint8Array;
/** `/g_new` — Create a new group. */
export function gNew(tail?: Array<[number, number, number]>): Uint8Array;
/** `/g_queryTree` — Get a representation of this group's node subtree. */
export function gQueryTree(tail?: Array<[number, number]>): Uint8Array;
/** `/g_tail` — Add node to tail of group. */
export function gTail(tail?: Array<[number, number]>): Uint8Array;
/** `/p_new` — Create a new parallel group. */
export function pNew(tail?: Array<[number, number, number]>): Uint8Array;
/** `/clearSched` — Clear all scheduled bundles. Removes all bundles from the scheduling queue. */
export function clearSched(): Uint8Array;
/** `/cmd` — Plug-in defined command. */
export function cmd(cmd: string, anyArguments?: Array<number | string | Uint8Array>): Uint8Array;
/** `/dumpOSC` — Display incoming OSC messages. */
export function dumpOSC(code: number): Uint8Array;
/** `/error` — Enable/disable error message posting. */
export function error(mode: number): Uint8Array;
/** `/notify` — Register to receive notifications from server */
export function notify(enable: number, clientId?: number): Uint8Array;
/** `/quit` — Quit program. Exits the synthesis server. */
export function quit(): Uint8Array;
/** `/rtMemoryStatus` — Queries the amount of currently free real-time memory (in bytes). */
export function rtMemoryStatus(): Uint8Array;
/** `/status` — Query the status. Replies to sender with the following message: */
export function status(): Uint8Array;
/** `/sync` — Notify when async commands have completed. */
export function sync(aUniqueNumber: number): Uint8Array;
/** `/version` — Query the SuperCollider version. Replies to sender with the following message: */
export function version(): Uint8Array;
/** `/n_after` — Place a node after another. */
export function nAfter(tail?: Array<[number, number]>): Uint8Array;
/** `/n_before` — Place a node before another. */
export function nBefore(tail?: Array<[number, number]>): Uint8Array;
/** `/n_fill` — Fill ranges of a node's control value(s). */
export function nFill(nodeId: number, tail?: Array<[string | number, number, number]>): Uint8Array;
/** `/n_free` — Delete a node. */
export function nFree(nodeIds?: Array<number>): Uint8Array;
/** `/n_map` — Map a node's controls to read from a bus. */
export function nMap(nodeId: number, tail?: Array<[string | number, number]> | Record<string, number>): Uint8Array;
/** `/n_mapa` — Map a node's controls to read from an audio bus. */
export function nMapa(nodeId: number, tail?: Array<[string | number, number]> | Record<string, number>): Uint8Array;
/** `/n_mapan` — Map a node's controls to read from audio buses. */
export function nMapan(nodeId: number, tail?: Array<[string | number, number, number]>): Uint8Array;
/** `/n_mapn` — Map a node's controls to read from buses. */
export function nMapn(nodeId: number, tail?: Array<[string | number, number, number]>): Uint8Array;
/** `/n_order` — Move and order a list of nodes. */
export function nOrder(addAction: number, targetId: number, nodeIds?: Array<number>): Uint8Array;
/** `/n_query` — Get info about a node. */
export function nQuery(nodeIds?: Array<number>): Uint8Array;
/** `/n_run` — Turn node on or off. */
export function nRun(tail?: Array<[number, number]>): Uint8Array;
/** `/n_set` — Set a node's control value(s). */
export function nSet(nodeId: number, tail?: Array<[string | number, number]> | Record<string, number>): Uint8Array;
/** `/n_setn` — Set ranges of a node's control value(s). */
export function nSetn(nodeId: number, tail?: Array<[string | number, Array<number>]>): Uint8Array;
/** `/n_trace` — Trace a node. */
export function nTrace(nodeIds?: Array<number>): Uint8Array;
/** `/nrt_end` — End real time mode, close file. Not yet implemented. This message should be sent in a bundle in non real time mode. The bundle timestamp will establish the ending time of the file. This command will end non real time mode and close the sound file. Replies to sender with /done when complete. */
export function nrtEnd(): Uint8Array;
/** `/s_get` — Get control value(s). */
export function sGet(nodeId: number, controls?: Array<string | number>): Uint8Array;
/** `/s_getn` — Get ranges of control value(s). */
export function sGetn(nodeId: number, tail?: Array<[string | number, number]> | Record<string, number>): Uint8Array;
/** `/s_new` — Create a new synth. */
export function sNew(defName: string, nodeId: number, addAction: number, targetId: number, tail?: Array<[string | number, number | string]> | Record<string, number | string>): Uint8Array;
/** `/s_noid` — Auto-reassign synth's ID to a reserved value. */
export function sNoid(synthIds?: Array<number>): Uint8Array;
/** `/d_free` — Delete synth definition. */
export function dFree(synthDefNames?: Array<string>): Uint8Array;
/** `/d_load` — Load synth definition. */
export function dLoad(pathnameOfFile: string, completionMsg?: Uint8Array): Uint8Array;
/** `/d_loadDir` — Load a directory of synth definitions. */
export function dLoadDir(pathnameOfDirectory: string, completionMsg?: Uint8Array): Uint8Array;
/** `/d_recv` — Receive a synth definition file. */
export function dRecv(bufferOfData: Uint8Array, completionMsg?: Uint8Array): Uint8Array;
/** `/u_cmd` — Send a command to a unit generator. */
export function uCmd(nodeId: number, unitGeneratorIndex: number, cmd: string, anyArguments?: Array<number | string | Uint8Array>): Uint8Array;
/** `/scope/subscribe` — sc-app bridge extension (not in the SC command reference): register a scope-slot stream with the bridge. The bridge is the consumer, so the struct also carries from_message/decode parsers. */
export function scopeSubscribe(subId: number, scope: number, channels: number, chunkSize: number): Uint8Array;
/** `/scope/unsubscribe` — sc-app bridge extension (not in the SC command reference): drop a scope-slot stream. */
export function scopeUnsubscribe(subId: number): Uint8Array;
/** `/dirt/play` — sc-app bridge extension (not in the SC command reference): a SuperDirt/Strudel event, routed by the bridge to the strudel peer. The wire format is SuperDirt's alternating key/value arg list. */
export function dirtPlay(pairs?: Array<[string, number | string | Uint8Array]> | Record<string, number | string | Uint8Array>): Uint8Array;
";
