// @generated — DO NOT EDIT.
// Regenerate with `node scripts/generate_ugens_rust.mjs`.

use crate::registry::UGenRegistryEntry;
use crate::Rate;

pub(crate) const UGENS: &[UGenRegistryEntry] = &[
    UGenRegistryEntry {
        name: r"BAllPass",
        rates: &[Rate::Audio],
        defaults: &[(r"in", None), (r"freq", Some(1200.0)), (r"rq", Some(1.0))],
        num_outputs: None,
        extends: None,
        summary: None,
        doc: Some(r"All pass filter based on the Second Order Section (SOS) biquad UGen"),
        signal_range: None,
        arg_docs: &[(r"freq", r"center frequency."), (r"in", r"input signal to be processed."), (r"rq", r"the reciprocal of Q. bandwidth / cutoffFreq.")],
    },
    UGenRegistryEntry {
        name: r"BBandPass",
        rates: &[Rate::Audio],
        defaults: &[(r"in", None), (r"freq", Some(1200.0)), (r"bw", Some(1.0))],
        num_outputs: None,
        extends: None,
        summary: None,
        doc: Some(r"Band pass filter based on the Second Order Section (SOS) biquad UGen"),
        signal_range: None,
        arg_docs: &[(r"bw", r"the bandwidth in octaves between -3 dB frequencies"), (r"freq", r"center frequency"), (r"in", r"input signal to be processed")],
    },
    UGenRegistryEntry {
        name: r"BBandStop",
        rates: &[Rate::Audio],
        defaults: &[(r"in", None), (r"freq", Some(1200.0)), (r"bw", Some(1.0))],
        num_outputs: None,
        extends: None,
        summary: None,
        doc: Some(r"Band reject filter based on the Second Order Section (SOS) biquad UGen"),
        signal_range: None,
        arg_docs: &[(r"bw", r"the bandwidth in octaves between -3 dB frequencies"), (r"freq", r"center frequency"), (r"in", r"input signal to be processed")],
    },
    UGenRegistryEntry {
        name: r"BHiPass",
        rates: &[Rate::Audio],
        defaults: &[(r"in", None), (r"freq", Some(1200.0)), (r"rq", Some(1.0))],
        num_outputs: None,
        extends: None,
        summary: None,
        doc: Some(r"12db/oct rolloff - 2nd order resonant Hi Pass Filter based on the Second Order Section (SOS) biquad UGen."),
        signal_range: None,
        arg_docs: &[(r"freq", r"cutoff frequency"), (r"in", r"input signal to be processed"), (r"rq", r"the reciprocal of Q. bandwidth / cutoffFreq")],
    },
    UGenRegistryEntry {
        name: r"BHiShelf",
        rates: &[Rate::Audio],
        defaults: &[(r"in", None), (r"freq", Some(1200.0)), (r"rs", Some(1.0)), (r"db", Some(0.0))],
        num_outputs: None,
        extends: None,
        summary: None,
        doc: Some(r"Hi shelfbased on the Second Order Section (SOS) biquad UGen"),
        signal_range: None,
        arg_docs: &[(r"db", r"gain. boost/cut the center frequency in dBs"), (r"freq", r"center frequency"), (r"in", r"input signal to be processed"), (r"rs", r"the reciprocal of S. Shell boost/cut slope. When S = 1, the shelf slope is as steep as it can be and remain monotonically increasing or decreasing gain with frequency. The shelf slope, in dB/octave, remains proportional to S for all other values for a fixed freq/SampleRate.ir and db.")],
    },
    UGenRegistryEntry {
        name: r"BLowPass",
        rates: &[Rate::Audio],
        defaults: &[(r"in", None), (r"freq", Some(1200.0)), (r"rq", Some(1.0))],
        num_outputs: None,
        extends: None,
        summary: None,
        doc: Some(r"12db/oct rolloff - 2nd order resonant Low Pass Filter based on the Second Order Section (SOS) biquad UGen"),
        signal_range: None,
        arg_docs: &[(r"freq", r"cutoff frequency"), (r"in", r"input signal to be processed"), (r"rq", r"the reciprocal of Q. bandwidth / cutoffFreq")],
    },
    UGenRegistryEntry {
        name: r"BLowShelf",
        rates: &[Rate::Audio],
        defaults: &[(r"in", None), (r"freq", Some(1200.0)), (r"rs", Some(1.0)), (r"db", Some(0.0))],
        num_outputs: None,
        extends: None,
        summary: None,
        doc: Some(r"Low shelf based on the Second Order Section (SOS) biquad UGen"),
        signal_range: None,
        arg_docs: &[(r"db", r"gain. boost/cut the center frequency in dBs"), (r"freq", r"center frequency"), (r"in", r"input signal to be processed"), (r"rs", r"the reciprocal of S. Shell boost/cut slope. When S = 1, the shelf slope is as steep as it can be and remain monotonically increasing or decreasing gain with frequency. The shelf slope, in dB/octave, remains proportional to S for all other values for a fixed freq/SampleRate.ir and db.")],
    },
    UGenRegistryEntry {
        name: r"BPeakEQ",
        rates: &[Rate::Audio],
        defaults: &[(r"in", None), (r"freq", Some(1200.0)), (r"rq", Some(1.0)), (r"db", Some(0.0))],
        num_outputs: None,
        extends: None,
        summary: None,
        doc: Some(r"Parametric equalizer based on the Second Order Section (SOS) biquad UGen"),
        signal_range: None,
        arg_docs: &[(r"db", r"boost/cut the center frequency (in dBs)"), (r"freq", r"center frequency"), (r"in", r"input signal to be processed"), (r"rq", r"the reciprocal of Q. bandwidth / cutoffFreq")],
    },
];
