// @generated — DO NOT EDIT.
// Regenerate with `node scripts/generate_ugens_rust.mjs`.

use crate::registry::UGenRegistryEntry;
use crate::Rate;

pub(crate) const UGENS: &[UGenRegistryEntry] = &[
    UGenRegistryEntry {
        name: r"BufRd",
        rates: &[Rate::Audio, Rate::Control],
        defaults: &[(r"numChannels", Some(1.0)), (r"bufnum", Some(0.0)), (r"phase", Some(0.0)), (r"loop", Some(1.0)), (r"interpolation", Some(2.0))],
        num_outputs: None,
        extends: None,
        summary: Some(r"Read the contents of a buffer at a specified index"),
        doc: Some(r"reads the contents of a buffer at a given index."),
        signal_range: None,
        arg_docs: &[(r"bufnum", r"The index of the buffer to use"), (r"interpolation", r"1 means no interpolation, 2 is linear, 4 is cubic interpolation"), (r"loop", r"1 means true, 0 means false. This is modulatable."), (r"numChannels", r"The number of channels of the supplied buffer. This must be a fixed integer and not a signal or a control proxy. The architecture of the synth design cannot change after it is compiled. (Warning: if you supply a bufnum of a buffer that has a different number of channels than you have specified to buf-rd , it will fail silently)."), (r"phase", r"Audio rate modulatable index into the buffer. Warning: The phase argument only offers precision for addressing 2**24 samples (about 6.3 minutes at 44100Hz)")],
    },
    UGenRegistryEntry {
        name: r"BufWr",
        rates: &[Rate::Audio, Rate::Control],
        defaults: &[(r"inputArray", None), (r"bufnum", Some(0.0)), (r"phase", Some(0.0)), (r"loop", Some(1.0))],
        num_outputs: Some(1),
        extends: None,
        summary: None,
        doc: Some(r"writes to a buffer at a given index. Note, buf-wr (in difference to buf-rd) does not do multichannel expansion, because input is an array."),
        signal_range: None,
        arg_docs: &[(r"bufnum", r"the index of the buffer to use"), (r"inputArray", r"input ugens (channelArray)"), (r"loop", r"1 means true, 0 means false. This is modulatable"), (r"phase", r"modulatable index into the buffer (has to be audio rate).")],
    },
    UGenRegistryEntry {
        name: r"ClearBuf",
        rates: &[Rate::Scalar],
        defaults: &[(r"buf", None)],
        num_outputs: Some(0),
        extends: None,
        summary: None,
        doc: None,
        signal_range: None,
        arg_docs: &[],
    },
    UGenRegistryEntry {
        name: r"LocalBuf",
        rates: &[Rate::Scalar],
        defaults: &[(r"numChannels", Some(1.0)), (r"numFrames", None)],
        num_outputs: None,
        extends: None,
        summary: None,
        doc: None,
        signal_range: None,
        arg_docs: &[],
    },
    UGenRegistryEntry {
        name: r"MaxLocalBufs",
        rates: &[Rate::Scalar],
        defaults: &[(r"numLocalBufs", None)],
        num_outputs: None,
        extends: None,
        summary: None,
        doc: None,
        signal_range: None,
        arg_docs: &[],
    },
    UGenRegistryEntry {
        name: r"PlayBuf",
        rates: &[Rate::Audio, Rate::Control],
        defaults: &[(r"numChannels", None), (r"bufnum", Some(0.0)), (r"rate", Some(1.0)), (r"trigger", Some(1.0)), (r"startPos", Some(0.0)), (r"loop", Some(0.0)), (r"action", Some(0.0))],
        num_outputs: None,
        extends: None,
        summary: None,
        doc: Some(r"Plays back a sample resident in a buffer"),
        signal_range: None,
        arg_docs: &[(r"action", r"an integer representing an action to be executed when the buffer is finished playing. This can be used to free the enclosing synth. Action is only evaluated if loop is 0"), (r"bufnum", r"The index of the buffer to use."), (r"loop", r"1 means true, 0 means false. This is modulateable."), (r"numChannels", r"The number of channels that the buffer will be. This must be a fixed integer. The architechture of the SynthDef cannot change after it is compiled. Warning: if you supply a bufnum of a buffer that has a different numChannels then you have specified to the play-buf, it will fail silently."), (r"rate", r"1.0 is the server's sample rate, 2.0 is one octave up, 0.5 is one octave down -1.0 is backwards normal rate ... etc. Interpolation is cubic. Note: if the buffer's sample rate is different from the server's, you will need to multiply the desired playback rate by (file's rate / server's rate). The UGen (buf-rate-scale bufnum) returns this factor."), (r"startPos", r"Sample frame to start playback."), (r"trigger", r"A trigger causes a jump to the startPos. A trigger occurs when a signal changes from <= 0 to > 0.")],
    },
    UGenRegistryEntry {
        name: r"RecordBuf",
        rates: &[Rate::Audio, Rate::Control],
        defaults: &[(r"inputArray", None), (r"bufnum", Some(0.0)), (r"offset", Some(0.0)), (r"recLevel", Some(1.0)), (r"preLevel", Some(0.0)), (r"run", Some(1.0)), (r"loop", Some(1.0)), (r"trigger", Some(1.0)), (r"action", Some(0.0))],
        num_outputs: Some(1),
        extends: None,
        summary: None,
        doc: Some(r"record a stream of values into a buffer. If recLevel is 1.0 and preLevel is 0.0 then the new input overwrites the old data. If they are both 1.0 then the new data is added to the existing data. (Any other settings are also valid.) Note that the number of channels must be fixed for the defsynth, it cannot vary depending on which buffer you use."),
        signal_range: None,
        arg_docs: &[(r"action", r"an integer representing an action to be executed when the buffer is finished playing. This can be used to free the enclosing synth. Action is only evaluated if loop is 0"), (r"bufnum", r"the index of the buffer to use"), (r"inputArray", r"an Array of input channels"), (r"loop", r"If zero then don't loop, otherwise do. This is modulate-able."), (r"offset", r"an offset into the buffer in frames,"), (r"preLevel", r"value to multiply to existing data in buffer before mixing with input"), (r"recLevel", r"value to multiply by input before mixing with existing data."), (r"run", r"If zero, then recording stops, otherwise recording proceeds."), (r"trigger", r"a trigger causes a jump to the offset position in the Buffer. A trigger occurs when a signal changes from <= 0 to > 0.")],
    },
    UGenRegistryEntry {
        name: r"ScopeOut",
        rates: &[Rate::Audio],
        defaults: &[(r"inputArray", None), (r"bufnum", Some(0.0))],
        num_outputs: Some(1),
        extends: None,
        summary: None,
        doc: None,
        signal_range: None,
        arg_docs: &[],
    },
    UGenRegistryEntry {
        name: r"ScopeOut2",
        rates: &[Rate::Audio, Rate::Control],
        defaults: &[(r"inputArray", None), (r"scopeNum", Some(0.0)), (r"maxFrames", Some(4096.0)), (r"scopeFrames", Some(4096.0))],
        num_outputs: Some(1),
        extends: None,
        summary: None,
        doc: None,
        signal_range: None,
        arg_docs: &[],
    },
    UGenRegistryEntry {
        name: r"SetBuf",
        rates: &[Rate::Audio, Rate::Control],
        defaults: &[(r"buf", None), (r"values", None), (r"offset", Some(0.0))],
        num_outputs: Some(0),
        extends: None,
        summary: None,
        doc: None,
        signal_range: None,
        arg_docs: &[],
    },
    UGenRegistryEntry {
        name: r"TGrains",
        rates: &[Rate::Audio],
        defaults: &[(r"numChannels", Some(2.0)), (r"trigger", Some(0.0)), (r"bufnum", Some(0.0)), (r"rate", Some(1.0)), (r"centerPos", Some(0.0)), (r"dur", Some(0.1)), (r"pan", Some(0.0)), (r"amp", Some(0.1)), (r"interp", Some(4.0))],
        num_outputs: None,
        extends: None,
        summary: None,
        doc: Some(r"sample playback from a buffer with fine control for doing granular synthesis. Triggers generate grains from a single channel (mono) buffer. Each grain has a Hann envelope (sin^2(x) for x from 0 to pi) and is panned between two channels of multiple outputs."),
        signal_range: None,
        arg_docs: &[(r"amp", r"amplitude of the grain."), (r"bufnum", r"the index of the buffer to use. It must be a one channel (mono) buffer."), (r"centerPos", r"the position in the buffer in seconds at which the grain envelope will reach maximum amplitude."), (r"dur", r"duration of the grain in seconds"), (r"interp", r"1,2,or 4. Determines whether the grain uses (1) no interpolation, (2) linear interpolation, or (4) cubic interpolation."), (r"numChannels", r"number of output channels"), (r"pan", r"a value from -1 to 1. Determines where to pan the output in the same manner as PanAz."), (r"rate", r"1.0 is normal, 2.0 is one octave up, 0.5 is one octave down -1.0 is backwards normal rate. Unlike PlayBuf, the rate is multiplied by BufRate, so you needn't do that yourself."), (r"trigger", r"at each trigger, the following arguments are sampled and used as the arguments of a new grain. A trigger occurs when a signal changes from <= 0 to > 0. If the trigger is audio rate then the grains will start with sample accuracy.")],
    },
];
