// @generated — DO NOT EDIT.
// Regenerate with `node scripts/generate_ugens_rust.mjs`.

use crate::registry::UGenRegistryEntry;
use crate::Rate;

pub(crate) const UGENS: &[UGenRegistryEntry] = &[
    UGenRegistryEntry {
        name: r"CuspL",
        rates: &[Rate::Audio, Rate::Control],
        defaults: &[(r"freq", Some(22050.0)), (r"a", Some(1.0)), (r"b", Some(1.9)), (r"xi", Some(0.0))],
        num_outputs: None,
        extends: Some(r"CuspN"),
        summary: None,
        doc: Some(r"a linear-interpolating (cusp map chaotic) sound generator based on the difference equation: xn+1 = a - b*sqrt(|xn|)"),
        signal_range: None,
        arg_docs: &[(r"a", r"first coefficient"), (r"b", r"2nd coefficient"), (r"freq", r"iteration frequency in Hertz"), (r"xi", r"initial value of x")],
    },
    UGenRegistryEntry {
        name: r"CuspN",
        rates: &[Rate::Audio, Rate::Control],
        defaults: &[(r"freq", Some(22050.0)), (r"a", Some(1.0)), (r"b", Some(1.9)), (r"xi", Some(0.0))],
        num_outputs: None,
        extends: None,
        summary: None,
        doc: Some(r"a non-interpolating (cusp map chaotic) sound generator based on the difference equation: xn+1 = a - b*sqrt(|xn|)"),
        signal_range: None,
        arg_docs: &[(r"a", r"first coefficient"), (r"b", r"2nd coefficient"), (r"freq", r"iteration frequency in Hertz"), (r"xi", r"initial value of x")],
    },
    UGenRegistryEntry {
        name: r"FBSineC",
        rates: &[Rate::Audio, Rate::Control],
        defaults: &[(r"freq", Some(22050.0)), (r"im", Some(1.0)), (r"fb", Some(0.1)), (r"a", Some(1.1)), (r"c", Some(0.5)), (r"xi", Some(0.1)), (r"yi", Some(0.1))],
        num_outputs: None,
        extends: Some(r"FBSineN"),
        summary: None,
        doc: Some(r"a cubic-interpolating feedback sine with chaotic phase indexing sound generator. This uses a linear congruential function to drive the phase indexing of a sine wave. For im = 1, fb = 0, and a = 1 a normal sinewave results."),
        signal_range: None,
        arg_docs: &[(r"a", r"phase multiplier amount"), (r"c", r"phase increment amount"), (r"fb", r"feedback amount"), (r"freq", r"iteration frequency in Hertz"), (r"im", r"index multiplier amount"), (r"xi", r"initial value of x"), (r"yi", r"initial value of y")],
    },
    UGenRegistryEntry {
        name: r"FBSineL",
        rates: &[Rate::Audio, Rate::Control],
        defaults: &[(r"freq", Some(22050.0)), (r"im", Some(1.0)), (r"fb", Some(0.1)), (r"a", Some(1.1)), (r"c", Some(0.5)), (r"xi", Some(0.1)), (r"yi", Some(0.1))],
        num_outputs: None,
        extends: Some(r"FBSineN"),
        summary: None,
        doc: Some(r"a linear-interpolating feedback sine with chaotic phase indexing sound generator. This uses a linear congruential function to drive the phase indexing of a sine wave. For im = 1, fb = 0, and a = 1 a normal sinewave results."),
        signal_range: None,
        arg_docs: &[(r"a", r"phase multiplier amount"), (r"c", r"phase increment amount"), (r"fb", r"feedback amount"), (r"freq", r"iteration frequency in Hertz"), (r"im", r"index multiplier amount"), (r"xi", r"initial value of x"), (r"yi", r"initial value of y")],
    },
    UGenRegistryEntry {
        name: r"FBSineN",
        rates: &[Rate::Audio, Rate::Control],
        defaults: &[(r"freq", Some(22050.0)), (r"im", Some(1.0)), (r"fb", Some(0.1)), (r"a", Some(1.1)), (r"c", Some(0.5)), (r"xi", Some(0.1)), (r"yi", Some(0.1))],
        num_outputs: None,
        extends: None,
        summary: None,
        doc: Some(r"a non-interpolating feedback sine with chaotic phase indexing sound generator. This uses a linear congruential function to drive the phase indexing of a sine wave. For im = 1, fb = 0, and a = 1 a normal sinewave results."),
        signal_range: None,
        arg_docs: &[(r"a", r"phase multiplier amount"), (r"c", r"phase increment amount"), (r"fb", r"feedback amount"), (r"freq", r"iteration frequency in Hertz"), (r"im", r"index multiplier amount"), (r"xi", r"initial value of x"), (r"yi", r"initial value of y")],
    },
    UGenRegistryEntry {
        name: r"GbmanL",
        rates: &[Rate::Audio, Rate::Control],
        defaults: &[(r"freq", Some(22050.0)), (r"xi", Some(1.2)), (r"yi", Some(2.1))],
        num_outputs: None,
        extends: Some(r"GbmanN"),
        summary: None,
        doc: Some(r"A linear-interpolating (gingerbreadman map chaotic) sound generator based on the difference equations: xn+1 = 1 - yn + |xn| yn+1 = xn"),
        signal_range: None,
        arg_docs: &[(r"freq", r"iteration frequency in Hz"), (r"xi", r"initial value of x"), (r"yi", r"initial value of y")],
    },
    UGenRegistryEntry {
        name: r"GbmanN",
        rates: &[Rate::Audio, Rate::Control],
        defaults: &[(r"freq", Some(22050.0)), (r"xi", Some(1.2)), (r"yi", Some(2.1))],
        num_outputs: None,
        extends: None,
        summary: None,
        doc: Some(r"A non-interpolating (gingerbreadman map chaotic) sound generator based on the difference equations: xn+1 = 1 - yn + |xn| yn+1 = xn"),
        signal_range: None,
        arg_docs: &[(r"freq", r"iteration frequency in Hz"), (r"xi", r"initial value of x"), (r"yi", r"initial value of y")],
    },
    UGenRegistryEntry {
        name: r"HenonC",
        rates: &[Rate::Audio, Rate::Control],
        defaults: &[(r"freq", Some(22050.0)), (r"a", Some(1.4)), (r"b", Some(0.3)), (r"x0", Some(0.0)), (r"x1", Some(0.0))],
        num_outputs: None,
        extends: Some(r"HenonN"),
        summary: None,
        doc: Some(r"a cubic-interpolating (henon map chaotic) sound generator based on the difference equation: x[n+2] = 1 - a*(x[n+1]^)2 + bx[n]. This equation was discovered by French astronomer Michel Hénon while studying the orbits of stars in globular clusters."),
        signal_range: None,
        arg_docs: &[(r"a", r"1st coefficient"), (r"b", r"2nd coefficient"), (r"freq", r"iteration frequency in Hertz"), (r"x0", r"initial value of x"), (r"x1", r"second value of x")],
    },
    UGenRegistryEntry {
        name: r"HenonL",
        rates: &[Rate::Audio, Rate::Control],
        defaults: &[(r"freq", Some(22050.0)), (r"a", Some(1.4)), (r"b", Some(0.3)), (r"x0", Some(0.0)), (r"x1", Some(0.0))],
        num_outputs: None,
        extends: Some(r"HenonN"),
        summary: None,
        doc: Some(r"a linear-interpolating (henon map chaotic) sound generator based on the difference equation: x[n+2] = 1 - a*(x[n+1]^)2 + bx[n]. This equation was discovered by French astronomer Michel Hénon while studying the orbits of stars in globular clusters."),
        signal_range: None,
        arg_docs: &[(r"a", r"1st coefficient"), (r"b", r"2nd coefficient"), (r"freq", r"iteration frequency in Hertz"), (r"x0", r"initial value of x"), (r"x1", r"second value of x")],
    },
    UGenRegistryEntry {
        name: r"HenonN",
        rates: &[Rate::Audio, Rate::Control],
        defaults: &[(r"freq", Some(22050.0)), (r"a", Some(1.4)), (r"b", Some(0.3)), (r"x0", Some(0.0)), (r"x1", Some(0.0))],
        num_outputs: None,
        extends: None,
        summary: None,
        doc: Some(r"a non-interpolating (henon map chaotic) sound generator based on the difference equation: x[n+2] = 1 - a*(x[n+1]^)2 + bx[n]. This equation was discovered by French astronomer Michel Hénon while studying the orbits of stars in globular clusters."),
        signal_range: None,
        arg_docs: &[(r"a", r"1st coefficient"), (r"b", r"2nd coefficient"), (r"freq", r"iteration frequency in Hertz"), (r"x0", r"initial value of x"), (r"x1", r"second value of x")],
    },
    UGenRegistryEntry {
        name: r"LatoocarfianC",
        rates: &[Rate::Audio, Rate::Control],
        defaults: &[(r"freq", Some(22050.0)), (r"a", Some(1.0)), (r"b", Some(3.0)), (r"c", Some(0.5)), (r"d", Some(0.5)), (r"xi", Some(0.5)), (r"yi", Some(0.5))],
        num_outputs: None,
        extends: Some(r"LatoocarfianN"),
        summary: None,
        doc: Some(r"a cubic-interpolating (latoocarfian chaotic) sound generator. Parameters a and b should be in the range from -3 to +3, and parameters c and d should be in the range from 0.5 to 1.5. The function can, depending on the parameters given, give continuous chaotic output, converge to a single value (silence) or oscillate in a cycle (tone)."),
        signal_range: None,
        arg_docs: &[(r"a", r"1st coefficient"), (r"b", r"2nd coefficient"), (r"c", r"3rd coefficient"), (r"d", r"4th coefficient"), (r"freq", r"iteration frequency in Hertz"), (r"xi", r"initial value of x"), (r"yi", r"initial value of y")],
    },
    UGenRegistryEntry {
        name: r"LatoocarfianL",
        rates: &[Rate::Audio, Rate::Control],
        defaults: &[(r"freq", Some(22050.0)), (r"a", Some(1.0)), (r"b", Some(3.0)), (r"c", Some(0.5)), (r"d", Some(0.5)), (r"xi", Some(0.5)), (r"yi", Some(0.5))],
        num_outputs: None,
        extends: Some(r"LatoocarfianN"),
        summary: None,
        doc: Some(r"a linear-interpolating (latoocarfian chaotic) sound generator. Parameters a and b should be in the range from -3 to +3, and parameters c and d should be in the range from 0.5 to 1.5. The function can, depending on the parameters given, give continuous chaotic output, converge to a single value (silence) or oscillate in a cycle (tone)."),
        signal_range: None,
        arg_docs: &[(r"a", r"1st coefficient"), (r"b", r"2nd coefficient"), (r"c", r"3rd coefficient"), (r"d", r"4th coefficient"), (r"freq", r"iteration frequency in Hertz"), (r"xi", r"initial value of x"), (r"yi", r"initial value of y")],
    },
    UGenRegistryEntry {
        name: r"LatoocarfianN",
        rates: &[Rate::Audio, Rate::Control],
        defaults: &[(r"freq", Some(22050.0)), (r"a", Some(1.0)), (r"b", Some(3.0)), (r"c", Some(0.5)), (r"d", Some(0.5)), (r"xi", Some(0.5)), (r"yi", Some(0.5))],
        num_outputs: None,
        extends: None,
        summary: None,
        doc: Some(r"a non-interpolating (latoocarfian chaotic) sound generator. Parameters a and b should be in the range from -3 to +3, and parameters c and d should be in the range from 0.5 to 1.5. The function can, depending on the parameters given, give continuous chaotic output, converge to a single value (silence) or oscillate in a cycle (tone)."),
        signal_range: None,
        arg_docs: &[(r"a", r"1st coefficient"), (r"b", r"2nd coefficient"), (r"c", r"3rd coefficient"), (r"d", r"4th coefficient"), (r"freq", r"iteration frequency in Hertz"), (r"xi", r"initial value of x"), (r"yi", r"initial value of y")],
    },
    UGenRegistryEntry {
        name: r"LinCongC",
        rates: &[Rate::Audio, Rate::Control],
        defaults: &[(r"freq", Some(22050.0)), (r"a", Some(1.1)), (r"c", Some(0.13)), (r"m", Some(1.0)), (r"xi", Some(0.0))],
        num_outputs: None,
        extends: Some(r"LinCongN"),
        summary: None,
        doc: Some(r"a cubic-interpolating (linear congruential chaotic) sound generator. The output signal is automatically scaled to a range of [-1, 1]."),
        signal_range: None,
        arg_docs: &[(r"a", r"multiplier amount"), (r"c", r"increment amount"), (r"freq", r"iteration frequency in Hertz."), (r"m", r"modulus amount"), (r"xi", r"initial value of x")],
    },
    UGenRegistryEntry {
        name: r"LinCongL",
        rates: &[Rate::Audio, Rate::Control],
        defaults: &[(r"freq", Some(22050.0)), (r"a", Some(1.1)), (r"c", Some(0.13)), (r"m", Some(1.0)), (r"xi", Some(0.0))],
        num_outputs: None,
        extends: Some(r"LinCongN"),
        summary: None,
        doc: Some(r"a linear-interpolating (linear congruential chaotic) sound generator. The output signal is automatically scaled to a range of [-1, 1]."),
        signal_range: None,
        arg_docs: &[(r"a", r"multiplier amount"), (r"c", r"increment amount"), (r"freq", r"iteration frequency in Hertz."), (r"m", r"modulus amount"), (r"xi", r"initial value of x")],
    },
    UGenRegistryEntry {
        name: r"LinCongN",
        rates: &[Rate::Audio, Rate::Control],
        defaults: &[(r"freq", Some(22050.0)), (r"a", Some(1.1)), (r"c", Some(0.13)), (r"m", Some(1.0)), (r"xi", Some(0.0))],
        num_outputs: None,
        extends: None,
        summary: None,
        doc: Some(r"a non-interpolating (linear congruential chaotic) sound generator. The output signal is automatically scaled to a range of [-1, 1]."),
        signal_range: None,
        arg_docs: &[(r"a", r"multiplier amount"), (r"c", r"increment amount"), (r"freq", r"iteration frequency in Hertz."), (r"m", r"modulus amount"), (r"xi", r"initial value of x")],
    },
    UGenRegistryEntry {
        name: r"LorenzL",
        rates: &[Rate::Audio, Rate::Control],
        defaults: &[(r"freq", Some(22050.0)), (r"s", Some(10.0)), (r"r", Some(28.0)), (r"b", Some(2.667)), (r"h", Some(0.05)), (r"xi", Some(0.1)), (r"yi", Some(0.0)), (r"zi", Some(0.0))],
        num_outputs: None,
        extends: None,
        summary: None,
        doc: Some(r"lorenz chaotic generator. A strange attractor discovered by Edward N. Lorenz while studying mathematical models of the atmosphere. The time step amount h determines the rate at which the ODE is evaluated. Higher values will increase the rate, but cause more instability. A safe choice is the default amount of 0.05."),
        signal_range: None,
        arg_docs: &[(r"b", r"3rd variable"), (r"freq", r"iteration frequency in Hertz"), (r"h", r"integration time stamp"), (r"r", r"2nd variable"), (r"s", r"1st variable"), (r"xi", r"initial value of x"), (r"yi", r"initial value of y"), (r"zi", r"initial value of z")],
    },
    UGenRegistryEntry {
        name: r"QuadC",
        rates: &[Rate::Audio, Rate::Control],
        defaults: &[(r"freq", Some(22050.0)), (r"a", Some(1.0)), (r"b", Some(-1.0)), (r"c", Some(-0.75)), (r"xi", Some(0.0))],
        num_outputs: None,
        extends: Some(r"QuadN"),
        summary: None,
        doc: Some(r"a cubic-interpolating (general quadratic map chaotic) sound generator based on the difference equation: xn+1 = axn2 + bxn + c"),
        signal_range: None,
        arg_docs: &[(r"a", r"1st coefficient"), (r"b", r"2nd coefficient"), (r"c", r"3rd coefficient"), (r"freq", r"iteration frequency in Hertz"), (r"xi", r"initial value of x")],
    },
    UGenRegistryEntry {
        name: r"QuadL",
        rates: &[Rate::Audio, Rate::Control],
        defaults: &[(r"freq", Some(22050.0)), (r"a", Some(1.0)), (r"b", Some(-1.0)), (r"c", Some(-0.75)), (r"xi", Some(0.0))],
        num_outputs: None,
        extends: Some(r"QuadN"),
        summary: None,
        doc: Some(r"a linear-interpolating (general quadratic map chaotic) sound generator based on the difference equation: xn+1 = axn2 + bxn + c"),
        signal_range: None,
        arg_docs: &[(r"a", r"1st coefficient"), (r"b", r"2nd coefficient"), (r"c", r"3rd coefficient"), (r"freq", r"iteration frequency in Hertz"), (r"xi", r"initial value of x")],
    },
    UGenRegistryEntry {
        name: r"QuadN",
        rates: &[Rate::Audio, Rate::Control],
        defaults: &[(r"freq", Some(22050.0)), (r"a", Some(1.0)), (r"b", Some(-1.0)), (r"c", Some(-0.75)), (r"xi", Some(0.0))],
        num_outputs: None,
        extends: None,
        summary: None,
        doc: Some(r"a non-interpolating (general quadratic map chaotic) sound generator based on the difference equation: xn+1 = axn2 + bxn + c"),
        signal_range: None,
        arg_docs: &[(r"a", r"1st coefficient"), (r"b", r"2nd coefficient"), (r"c", r"3rd coefficient"), (r"freq", r"iteration frequency in Hertz"), (r"xi", r"initial value of x")],
    },
    UGenRegistryEntry {
        name: r"StandardL",
        rates: &[Rate::Audio, Rate::Control],
        defaults: &[(r"freq", Some(22050.0)), (r"k", Some(1.0)), (r"xi", Some(0.5)), (r"yi", Some(0.0))],
        num_outputs: None,
        extends: Some(r"StandardN"),
        summary: None,
        doc: Some(r"linear-interpolating standard map chaotic generator. The standard map is an area preserving map of a cylinder discovered by the plasma physicist Boris Chirikov."),
        signal_range: None,
        arg_docs: &[(r"freq", r"iteration frequency in Hertz"), (r"k", r"perturbation amount"), (r"xi", r"initial value of x"), (r"yi", r"initial value of y")],
    },
    UGenRegistryEntry {
        name: r"StandardN",
        rates: &[Rate::Audio, Rate::Control],
        defaults: &[(r"freq", Some(22050.0)), (r"k", Some(1.0)), (r"xi", Some(0.5)), (r"yi", Some(0.0))],
        num_outputs: None,
        extends: None,
        summary: None,
        doc: Some(r"standard map chaotic generator. The standard map is an area preserving map of a cylinder discovered by the plasma physicist Boris Chirikov."),
        signal_range: None,
        arg_docs: &[(r"freq", r"iteration frequency in Hertz"), (r"k", r"perturbation amount"), (r"xi", r"initial value of x"), (r"yi", r"initial value of y")],
    },
];
