// @generated — DO NOT EDIT.
// Regenerate with `node scripts/generate_ugens_rust.mjs`.

use crate::registry::UGenRegistryEntry;
use crate::Rate;

pub(crate) const UGENS: &[UGenRegistryEntry] = &[
    UGenRegistryEntry {
        name: r"AllpassC",
        rates: &[Rate::Audio, Rate::Control],
        defaults: &[(r"in", Some(0.0)), (r"maxDelayTime", Some(0.2)), (r"delayTime", Some(0.2)), (r"decayTime", Some(1.0))],
        num_outputs: None,
        extends: Some(r"CombN"),
        summary: None,
        doc: Some(r"all pass delay line, cubic interpolation"),
        signal_range: None,
        arg_docs: &[(r"decayTime", r"time for the echoes to decay by 60 decibels. If this time is negative then the feedback coefficient will be negative, thus emphasizing only odd harmonics at an octave lower."), (r"delayTime", r"delay time in seconds"), (r"in", r"the input signal"), (r"maxDelayTime", r"the maximum delay time in seconds. Used to initialize the delay buffer size")],
    },
    UGenRegistryEntry {
        name: r"AllpassL",
        rates: &[Rate::Audio, Rate::Control],
        defaults: &[(r"in", Some(0.0)), (r"maxDelayTime", Some(0.2)), (r"delayTime", Some(0.2)), (r"decayTime", Some(1.0))],
        num_outputs: None,
        extends: Some(r"CombN"),
        summary: None,
        doc: Some(r"all pass delay line, linear interpolation"),
        signal_range: None,
        arg_docs: &[(r"decayTime", r"time for the echoes to decay by 60 decibels. If this time is negative then the feedback coefficient will be negative, thus emphasizing only odd harmonics at an octave lower."), (r"delayTime", r"delay time in seconds"), (r"in", r"the input signal"), (r"maxDelayTime", r"the maximum delay time in seconds. Used to initialize the delay buffer size")],
    },
    UGenRegistryEntry {
        name: r"AllpassN",
        rates: &[Rate::Audio, Rate::Control],
        defaults: &[(r"in", Some(0.0)), (r"maxDelayTime", Some(0.2)), (r"delayTime", Some(0.2)), (r"decayTime", Some(1.0))],
        num_outputs: None,
        extends: Some(r"CombN"),
        summary: None,
        doc: Some(r"all pass delay line, no interpolation. See also AllpassC which uses cubic interpolation, and AllpassL which uses linear interpolation. Cubic interpolation is more computationally expensive than linear, but more accurate."),
        signal_range: None,
        arg_docs: &[(r"decayTime", r"time for the echoes to decay by 60 decibels. If this time is negative then the feedback coefficient will be negative, thus emphasizing only odd harmonics at an octave lower."), (r"delayTime", r"delay time in seconds"), (r"in", r"the input signal"), (r"maxDelayTime", r"the maximum delay time in seconds. Used to initialize the delay buffer size")],
    },
    UGenRegistryEntry {
        name: r"BufAllpassC",
        rates: &[Rate::Audio],
        defaults: &[(r"buf", Some(0.0)), (r"in", Some(0.0)), (r"delayTime", Some(0.2)), (r"decayTime", Some(1.0))],
        num_outputs: None,
        extends: Some(r"BufCombN"),
        summary: None,
        doc: Some(r"buffer based all pass delay line with cubic interpolation"),
        signal_range: None,
        arg_docs: &[(r"buf", r"buffer number"), (r"decayTime", r"time for the echoes to decay by 60 decibels. If this time is negative then the feedback coefficient will be negative, thus emphasizing only odd harmonics at an octave lower."), (r"delayTime", r"delay time in seconds"), (r"in", r"the input signal")],
    },
    UGenRegistryEntry {
        name: r"BufAllpassL",
        rates: &[Rate::Audio],
        defaults: &[(r"buf", Some(0.0)), (r"in", Some(0.0)), (r"delayTime", Some(0.2)), (r"decayTime", Some(1.0))],
        num_outputs: None,
        extends: Some(r"BufCombN"),
        summary: None,
        doc: Some(r"buffer based all pass delay line with linear interpolation"),
        signal_range: None,
        arg_docs: &[(r"buf", r"buffer number"), (r"decayTime", r"time for the echoes to decay by 60 decibels. If this time is negative then the feedback coefficient will be negative, thus emphasizing only odd harmonics at an octave lower."), (r"delayTime", r"delay time in seconds"), (r"in", r"the input signal")],
    },
    UGenRegistryEntry {
        name: r"BufAllpassN",
        rates: &[Rate::Audio],
        defaults: &[(r"buf", Some(0.0)), (r"in", Some(0.0)), (r"delayTime", Some(0.2)), (r"decayTime", Some(1.0))],
        num_outputs: None,
        extends: Some(r"BufCombN"),
        summary: None,
        doc: Some(r"buffer based all pass delay line with no interpolation. See also BufAllpassC which uses cubic interpolation, and BufAllpassL which uses linear interpolation. Cubic interpolation is more computationally expensive than linear, but more accurate."),
        signal_range: None,
        arg_docs: &[(r"buf", r"buffer number"), (r"decayTime", r"time for the echoes to decay by 60 decibels. If this time is negative then the feedback coefficient will be negative, thus emphasizing only odd harmonics at an octave lower."), (r"delayTime", r"delay time in seconds"), (r"in", r"the input signal")],
    },
    UGenRegistryEntry {
        name: r"BufCombC",
        rates: &[Rate::Audio],
        defaults: &[(r"buf", Some(0.0)), (r"in", Some(0.0)), (r"delayTime", Some(0.2)), (r"decayTime", Some(1.0))],
        num_outputs: None,
        extends: Some(r"BufCombN"),
        summary: None,
        doc: Some(r"buffer based comb delay line with cubic interpolation"),
        signal_range: None,
        arg_docs: &[(r"buf", r"buffer number"), (r"decayTime", r"time for the echoes to decay by 60 decibels. If this time is negative then the feedback coefficient will be negative, thus emphasizing only odd harmonics at an octave lower."), (r"delayTime", r"delay time in seconds"), (r"in", r"the input signal")],
    },
    UGenRegistryEntry {
        name: r"BufCombL",
        rates: &[Rate::Audio],
        defaults: &[(r"buf", Some(0.0)), (r"in", Some(0.0)), (r"delayTime", Some(0.2)), (r"decayTime", Some(1.0))],
        num_outputs: None,
        extends: Some(r"BufCombN"),
        summary: None,
        doc: Some(r"buffer based comb delay line with linear interpolation"),
        signal_range: None,
        arg_docs: &[(r"buf", r"buffer number"), (r"decayTime", r"time for the echoes to decay by 60 decibels. If this time is negative then the feedback coefficient will be negative, thus emphasizing only odd harmonics at an octave lower."), (r"delayTime", r"delay time in seconds"), (r"in", r"the input signal")],
    },
    UGenRegistryEntry {
        name: r"BufCombN",
        rates: &[Rate::Audio],
        defaults: &[(r"buf", Some(0.0)), (r"in", Some(0.0)), (r"delayTime", Some(0.2)), (r"decayTime", Some(1.0))],
        num_outputs: None,
        extends: None,
        summary: None,
        doc: Some(r"buffer based comb delay line with no interpolation. See also [BufCombL] which uses linear interpolation, and BufCombC which uses cubic interpolation. Cubic interpolation is more computationally expensive than linear, but more accurate."),
        signal_range: None,
        arg_docs: &[(r"buf", r"buffer number"), (r"decayTime", r"time for the echoes to decay by 60 decibels. If this time is negative then the feedback coefficient will be negative, thus emphasizing only odd harmonics at an octave lower."), (r"delayTime", r"delay time in seconds"), (r"in", r"the input signal")],
    },
    UGenRegistryEntry {
        name: r"BufDelayC",
        rates: &[Rate::Audio, Rate::Control],
        defaults: &[(r"buf", Some(0.0)), (r"in", Some(0.0)), (r"delayTime", Some(0.2))],
        num_outputs: None,
        extends: Some(r"BufDelayN"),
        summary: None,
        doc: Some(r"buffer based simple delay line with cubic interpolation"),
        signal_range: None,
        arg_docs: &[(r"buf", r"buffer number"), (r"delayTime", r"delay time in seconds"), (r"in", r"the input signal")],
    },
    UGenRegistryEntry {
        name: r"BufDelayL",
        rates: &[Rate::Audio, Rate::Control],
        defaults: &[(r"buf", Some(0.0)), (r"in", Some(0.0)), (r"delayTime", Some(0.2))],
        num_outputs: None,
        extends: Some(r"BufDelayN"),
        summary: None,
        doc: Some(r"buffer based simple delay line with linear interpolation"),
        signal_range: None,
        arg_docs: &[(r"buf", r"buffer number"), (r"delayTime", r"delay time in seconds"), (r"in", r"the input signal")],
    },
    UGenRegistryEntry {
        name: r"BufDelayN",
        rates: &[Rate::Audio, Rate::Control],
        defaults: &[(r"buf", Some(0.0)), (r"in", Some(0.0)), (r"delayTime", Some(0.2))],
        num_outputs: None,
        extends: None,
        summary: None,
        doc: Some(r"buffer based simple delay line with no interpolation. See also BufDelayL which uses linear interpolation, and BufDelayC which uses cubic interpolation. Cubic interpolation is more computationally expensive than linear, but more accurate."),
        signal_range: None,
        arg_docs: &[(r"buf", r"buffer number"), (r"delayTime", r"delay time in seconds"), (r"in", r"the input signal")],
    },
    UGenRegistryEntry {
        name: r"CombC",
        rates: &[Rate::Audio, Rate::Control],
        defaults: &[(r"in", Some(0.0)), (r"maxDelayTime", Some(0.2)), (r"delayTime", Some(0.2)), (r"decayTime", Some(1.0))],
        num_outputs: None,
        extends: Some(r"CombN"),
        summary: None,
        doc: Some(r"comb delay line, cubic interpolation"),
        signal_range: None,
        arg_docs: &[(r"decayTime", r"time for the echoes to decay by 60 decibels. If this time is negative then the feedback coefficient will be negative, thus emphasizing only odd harmonics at an octave lower."), (r"delayTime", r"delay time in seconds"), (r"in", r"the input signal"), (r"maxDelayTime", r"the maximum delay time in seconds. Used to initialize the delay buffer size")],
    },
    UGenRegistryEntry {
        name: r"CombL",
        rates: &[Rate::Audio, Rate::Control],
        defaults: &[(r"in", Some(0.0)), (r"maxDelayTime", Some(0.2)), (r"delayTime", Some(0.2)), (r"decayTime", Some(1.0))],
        num_outputs: None,
        extends: Some(r"CombN"),
        summary: None,
        doc: Some(r"comb delay line, linear interpolation"),
        signal_range: None,
        arg_docs: &[(r"decayTime", r"time for the echoes to decay by 60 decibels. If this time is negative then the feedback coefficient will be negative, thus emphasizing only odd harmonics at an octave lower."), (r"delayTime", r"delay time in seconds"), (r"in", r"the input signal"), (r"maxDelayTime", r"the maximum delay time in seconds. Used to initialize the delay buffer size")],
    },
    UGenRegistryEntry {
        name: r"CombN",
        rates: &[Rate::Audio, Rate::Control],
        defaults: &[(r"in", Some(0.0)), (r"maxDelayTime", Some(0.2)), (r"delayTime", Some(0.2)), (r"decayTime", Some(1.0))],
        num_outputs: None,
        extends: None,
        summary: None,
        doc: Some(r"comb delay line, no interpolation. See also CombL which uses linear interpolation, and CombC which uses cubic interpolation. Cubic interpolation is more computationally expensive than linear, but more accurate."),
        signal_range: None,
        arg_docs: &[(r"decayTime", r"time for the echoes to decay by 60 decibels. If this time is negative then the feedback coefficient will be negative, thus emphasizing only odd harmonics at an octave lower."), (r"delayTime", r"delay time in seconds"), (r"in", r"the input signal"), (r"maxDelayTime", r"the maximum delay time in seconds. Used to initialize the delay buffer size")],
    },
    UGenRegistryEntry {
        name: r"DelTapRd",
        rates: &[Rate::Audio, Rate::Control],
        defaults: &[(r"buffer", Some(0.0)), (r"phase", Some(0.0)), (r"delay", Some(0.0)), (r"interp", Some(1.0))],
        num_outputs: None,
        extends: None,
        summary: None,
        doc: Some(r"Tap a delay line from a del-tap-wr UGen"),
        signal_range: None,
        arg_docs: &[(r"buffer", r"buffer where del-tap-wr has written signal. Max delay time is based on buffer size."), (r"delay", r"A delay time in seconds."), (r"interp", r"the kind of interpolation to be used. 1 is none, 2 is linear, 4 is cubic."), (r"phase", r"the current phase of the del-tap-wr UGen. This is the output of DelTapWr.")],
    },
    UGenRegistryEntry {
        name: r"DelTapWr",
        rates: &[Rate::Audio, Rate::Control],
        defaults: &[(r"buffer", Some(0.0)), (r"in", Some(0.0))],
        num_outputs: None,
        extends: None,
        summary: None,
        doc: Some(r"Tap a delay line from a del-tap-wr UGen"),
        signal_range: None,
        arg_docs: &[(r"buffer", r"the buffer to write signal into. Max delay time is based on buffer size."), (r"in", r"the signal to write to the buffer.")],
    },
    UGenRegistryEntry {
        name: r"Delay1",
        rates: &[Rate::Audio, Rate::Control],
        defaults: &[(r"in", Some(0.0))],
        num_outputs: None,
        extends: None,
        summary: None,
        doc: Some(r"delay input signal by one frame of samples. Note: for audio-rate signals the delay is 1 audio frame, and for control-rate signals the delay is 1 control period."),
        signal_range: None,
        arg_docs: &[(r"in", r"input to be delayed.")],
    },
    UGenRegistryEntry {
        name: r"Delay2",
        rates: &[Rate::Audio, Rate::Control],
        defaults: &[(r"in", Some(0.0))],
        num_outputs: None,
        extends: Some(r"Delay1"),
        summary: None,
        doc: Some(r"delay input signal by two frames of samples"),
        signal_range: None,
        arg_docs: &[(r"in", r"input to be delayed.")],
    },
    UGenRegistryEntry {
        name: r"DelayC",
        rates: &[Rate::Audio, Rate::Control],
        defaults: &[(r"in", Some(0.0)), (r"maxDelayTime", Some(0.2)), (r"delayTime", Some(0.2))],
        num_outputs: None,
        extends: Some(r"DelayN"),
        summary: None,
        doc: Some(r"simple delay line, cubic interpolation."),
        signal_range: None,
        arg_docs: &[(r"delayTime", r"delay time in seconds"), (r"in", r"the input signal"), (r"maxDelayTime", r"the maximum delay time in seconds. Used to initialize the delay buffer size")],
    },
    UGenRegistryEntry {
        name: r"DelayL",
        rates: &[Rate::Audio, Rate::Control],
        defaults: &[(r"in", Some(0.0)), (r"maxDelayTime", Some(0.2)), (r"delayTime", Some(0.2))],
        num_outputs: None,
        extends: Some(r"DelayN"),
        summary: None,
        doc: Some(r"simple delay line, linear interpolation."),
        signal_range: None,
        arg_docs: &[(r"delayTime", r"delay time in seconds"), (r"in", r"the input signal"), (r"maxDelayTime", r"the maximum delay time in seconds. Used to initialize the delay buffer size")],
    },
    UGenRegistryEntry {
        name: r"DelayN",
        rates: &[Rate::Audio, Rate::Control],
        defaults: &[(r"in", Some(0.0)), (r"maxDelayTime", Some(0.2)), (r"delayTime", Some(0.2))],
        num_outputs: None,
        extends: None,
        summary: None,
        doc: Some(r"simple delay line, no interpolation. See also DelayL which uses linear interpolation, and DelayC which uses cubic interpolation. Cubic interpolation is more computationally expensive than linear, but more accurate."),
        signal_range: None,
        arg_docs: &[(r"delayTime", r"delay time in seconds"), (r"in", r"the input signal"), (r"maxDelayTime", r"the maximum delay time in seconds. Used to initialize the delay buffer size")],
    },
];
