// @generated — DO NOT EDIT.
// Regenerate with `node scripts/generate_ugens_rust.mjs`.

use crate::registry::UGenRegistryEntry;
use crate::Rate;

pub(crate) const UGENS: &[UGenRegistryEntry] = &[
    UGenRegistryEntry {
        name: r"Dbrown",
        rates: &[],
        defaults: &[(r"length", None), (r"lo", Some(0.0)), (r"hi", Some(1.0)), (r"step", Some(0.01))],
        num_outputs: None,
        extends: None,
        summary: None,
        doc: Some(r"This ugen has been internalised for scserver compatibility. Please use the dbrown cgen instead."),
        signal_range: None,
        arg_docs: &[(r"length", r"Default: positive infinity")],
    },
    UGenRegistryEntry {
        name: r"Dbufrd",
        rates: &[],
        defaults: &[(r"bufnum", Some(0.0)), (r"phase", Some(0.0)), (r"loop", Some(1.0))],
        num_outputs: None,
        extends: None,
        summary: None,
        doc: Some(r"Read values from a buffer on demand, using phase (index) value that is also pulled on demand. All inputs can be either demand ugen or any other ugen."),
        signal_range: None,
        arg_docs: &[(r"bufnum", r"buffer number to read from"), (r"loop", r"when phase exceeds number of frames in buffer, loops when set to 1"), (r"phase", r"index into the buffer")],
    },
    UGenRegistryEntry {
        name: r"Dbufwr",
        rates: &[],
        defaults: &[(r"bufnum", Some(0.0)), (r"phase", Some(0.0)), (r"input", Some(0.0)), (r"loop", Some(1.0))],
        num_outputs: None,
        extends: None,
        summary: None,
        doc: Some(r"This ugen has been internalised for scserver compatibility. Please use the dbufwr cgen instead."),
        signal_range: None,
        arg_docs: &[],
    },
    UGenRegistryEntry {
        name: r"Demand",
        rates: &[Rate::Audio, Rate::Control],
        defaults: &[(r"trig", None), (r"reset", Some(0.0)), (r"demandUgens", None)],
        num_outputs: None,
        extends: None,
        summary: None,
        doc: Some(r"On every trigger it demands the next value from each of the demand ugens passed as args. Used to pull values from the other demand rate ugens. By design, a reset trigger only resets the demand ugens; it does not reset the value at Demand's output. Demand continues to hold its value until the next value is demanded, at which point its output value will be the first expected item in the list."),
        signal_range: None,
        arg_docs: &[(r"demandUgens", r"list of demand rate ugens"), (r"reset", r"Resets the list of ugens when triggered."), (r"trig", r"Can be any signal. A trigger happens when the signal changes from non-positive to positive.")],
    },
    UGenRegistryEntry {
        name: r"DemandEnvGen",
        rates: &[Rate::Audio, Rate::Control],
        defaults: &[(r"level", None), (r"dur", None), (r"shape", Some(1.0)), (r"curve", Some(0.0)), (r"gate", Some(1.0)), (r"reset", Some(1.0)), (r"levelScale", Some(1.0)), (r"levelBias", Some(0.0)), (r"timeScale", Some(1.0)), (r"action", Some(0.0))],
        num_outputs: None,
        extends: None,
        summary: None,
        doc: Some(r"Plays back break point envelope contours (levels, times, shapes) given by demand ugens. The next values are called when the next node is reached."),
        signal_range: None,
        arg_docs: &[(r"action", r"Default: NO-ACTION"), (r"curve", r"demand ugen (or other ugen) returning curve values - if shape is 5, this is the curve factor. The possible values are: 0 - flat segments, 1 - linear segments, the default, 2 - natural exponential growth and decay. In this case, the levels must all be nonzero and the have the same sign, 3 - sinusoidal S shaped segments, 4 - sinusoidal segments shaped like the sides of a Welch window, a Float - a curvature value for all segments, an Array of Floats - curvature values for each segments."), (r"dur", r"demand ugen (or other ugen) returning time values"), (r"gate", r"control rate gate if gate is x >= 1, the ugen runs, if gate is 0 > x > 1, the ugen is released at the next level (doneAction), if gate is x <= 0, the ugen is sampled end held"), (r"level", r"demand ugen (or other ugen) returning level values"), (r"levelBias", r"demand ugen returning level offset values"), (r"levelScale", r"demand ugen returning level scaling values"), (r"reset", r"if reset crosses from nonpositive to positive, the ugen is reset at the next level. If it is > 1, it is reset immediately."), (r"shape", r"demand ugen (or other ugen) returning shape number - the number given is the shape number"), (r"timeScale", r"demand ugen returning time scaling values")],
    },
    UGenRegistryEntry {
        name: r"Dgeom",
        rates: &[],
        defaults: &[(r"length", None), (r"start", Some(1.0)), (r"grow", Some(2.0))],
        num_outputs: None,
        extends: None,
        summary: None,
        doc: Some(r"This ugen has been internalised for scserver compatibility. Please use the dgeom cgen instead."),
        signal_range: None,
        arg_docs: &[(r"length", r"Default: positive infinity")],
    },
    UGenRegistryEntry {
        name: r"Dibrown",
        rates: &[],
        defaults: &[(r"length", None), (r"lo", Some(0.0)), (r"hi", Some(1.0)), (r"step", Some(0.01))],
        num_outputs: None,
        extends: Some(r"Dbrown"),
        summary: None,
        doc: Some(r"This ugen has been internalised for scserver compatibility. Please use the dibrown cgen instead."),
        signal_range: None,
        arg_docs: &[(r"length", r"Default: positive infinity")],
    },
    UGenRegistryEntry {
        name: r"Diwhite",
        rates: &[],
        defaults: &[(r"length", None), (r"lo", Some(0.0)), (r"hi", Some(1.0))],
        num_outputs: None,
        extends: Some(r"Dwhite"),
        summary: None,
        doc: Some(r"This ugen has been internalised for scserver compatibility. Please use the diwhite cgen instead."),
        signal_range: None,
        arg_docs: &[(r"length", r"Default: positive infinity")],
    },
    UGenRegistryEntry {
        name: r"Donce",
        rates: &[],
        defaults: &[(r"in", None)],
        num_outputs: None,
        extends: None,
        summary: None,
        doc: None,
        signal_range: None,
        arg_docs: &[],
    },
    UGenRegistryEntry {
        name: r"Dpoll",
        rates: &[],
        defaults: &[(r"in", None), (r"trigId", Some(-1.0)), (r"label", None), (r"run", Some(1.0))],
        num_outputs: None,
        extends: None,
        summary: None,
        doc: Some(r"Print the value of an input demand ugen. The print-out is in the form: label: value block offset: offset. WARNING: Printing values from the Server is intensive for the CPU. Poll should be used for debugging purposes."),
        signal_range: None,
        arg_docs: &[(r"in", r"demand ugen to poll values from"), (r"label", r"a label string"), (r"run", r"activation switch 0 or 1 (can be a demand ugen)"), (r"trigId", r"if greater than 0, a '/tr' message is sent back to the client (similar to send-trig)")],
    },
    UGenRegistryEntry {
        name: r"Drand",
        rates: &[],
        defaults: &[(r"list", None), (r"numRepeats", Some(1.0))],
        num_outputs: None,
        extends: Some(r"Dseq"),
        summary: None,
        doc: Some(r"Demand rate random sequence generator. Generate a random ordering of an input sequence."),
        signal_range: None,
        arg_docs: &[(r"list", r"array of values or other ugens"), (r"numRepeats", r"number of repeats")],
    },
    UGenRegistryEntry {
        name: r"Dseq",
        rates: &[],
        defaults: &[(r"list", None), (r"numRepeats", Some(1.0))],
        num_outputs: None,
        extends: None,
        summary: None,
        doc: Some(r"Demand rate sequence generator. Outputs a sequence of values, possibly repeating multiple times. Use INF as a repeat val to create an endless loop."),
        signal_range: None,
        arg_docs: &[(r"list", r"array of values or other ugens"), (r"numRepeats", r"number of repeats")],
    },
    UGenRegistryEntry {
        name: r"Dser",
        rates: &[],
        defaults: &[(r"list", None), (r"count", Some(1.0))],
        num_outputs: None,
        extends: None,
        summary: None,
        doc: Some(r"Demand rate sequence generator. Generates a sequence of values like dseq, except outputs only count total values, rather than repeating."),
        signal_range: None,
        arg_docs: &[(r"count", r"number of values to return"), (r"list", r"array of values or other ugens")],
    },
    UGenRegistryEntry {
        name: r"Dseries",
        rates: &[],
        defaults: &[(r"length", None), (r"start", Some(1.0)), (r"step", Some(1.0))],
        num_outputs: None,
        extends: None,
        summary: None,
        doc: Some(r"This ugen has been internalised for scserver compatibility. Please use the dseries cgen instead."),
        signal_range: None,
        arg_docs: &[(r"length", r"Default: positive infinity.")],
    },
    UGenRegistryEntry {
        name: r"Dshuf",
        rates: &[],
        defaults: &[(r"list", None), (r"numRepeats", Some(1.0))],
        num_outputs: None,
        extends: Some(r"Dseq"),
        summary: None,
        doc: Some(r"Demand rate random sequence generator. Shuffle a sequence once and then output it one or more times."),
        signal_range: None,
        arg_docs: &[(r"list", r"array of values or other ugens"), (r"numRepeats", r"number of repeats")],
    },
    UGenRegistryEntry {
        name: r"Dstutter",
        rates: &[],
        defaults: &[(r"numRepeats", None), (r"in", None)],
        num_outputs: None,
        extends: None,
        summary: None,
        doc: Some(r"Replicates input values n times on demand. Both inputs can be demand rate ugens."),
        signal_range: None,
        arg_docs: &[(r"in", r"input ugen"), (r"numRepeats", r"number of repeats (can be a demand ugen)")],
    },
    UGenRegistryEntry {
        name: r"Dswitch",
        rates: &[],
        defaults: &[(r"list", None), (r"index", None)],
        num_outputs: None,
        extends: Some(r"Dswitch1"),
        summary: None,
        doc: Some(r"A demand rate switch. In difference to Dswitch1, Dswitch embeds all items of an input demand ugen first before looking up the next index."),
        signal_range: None,
        arg_docs: &[(r"index", r"which of the inputs to return"), (r"list", r"array of values or other ugens")],
    },
    UGenRegistryEntry {
        name: r"Dswitch1",
        rates: &[],
        defaults: &[(r"list", None), (r"index", None)],
        num_outputs: None,
        extends: None,
        summary: None,
        doc: Some(r"A demand rate switch that can be used to select one of multiple demand rate inputs."),
        signal_range: None,
        arg_docs: &[(r"index", r"which of the inputs to return"), (r"list", r"array of values or other ugens")],
    },
    UGenRegistryEntry {
        name: r"Duty",
        rates: &[Rate::Audio, Rate::Control],
        defaults: &[(r"dur", Some(1.0)), (r"reset", Some(0.0)), (r"action", Some(0.0)), (r"level", Some(1.0))],
        num_outputs: None,
        extends: None,
        summary: None,
        doc: Some(r"This ugen has been internalised for scserver compatibility. Please use the duty cgen instead."),
        signal_range: None,
        arg_docs: &[(r"action", r"Default: NO-ACTION")],
    },
    UGenRegistryEntry {
        name: r"Dwhite",
        rates: &[],
        defaults: &[(r"length", None), (r"lo", Some(0.0)), (r"hi", Some(1.0))],
        num_outputs: None,
        extends: None,
        summary: None,
        doc: Some(r"This ugen has been internalised for scserver compatibility. Please use the dwhite cgen instead."),
        signal_range: None,
        arg_docs: &[(r"length", r"Default: positive infinity")],
    },
    UGenRegistryEntry {
        name: r"Dxrand",
        rates: &[],
        defaults: &[(r"list", None), (r"numRepeats", Some(1.0))],
        num_outputs: None,
        extends: Some(r"Dseq"),
        summary: None,
        doc: Some(r"Demand rate random sequence generator. Generate a random ordering of the given sequence without repeating any element until all elements have been returned."),
        signal_range: None,
        arg_docs: &[(r"list", r"array of values or other ugens"), (r"numRepeats", r"number of repeats")],
    },
    UGenRegistryEntry {
        name: r"TDuty",
        rates: &[Rate::Audio, Rate::Control],
        defaults: &[(r"dur", Some(1.0)), (r"reset", Some(0.0)), (r"action", Some(0.0)), (r"level", Some(1.0)), (r"gapFirst", Some(0.0))],
        num_outputs: None,
        extends: Some(r"Duty"),
        summary: None,
        doc: Some(r"This ugen has been internalised for scserver compatibility. Please use the tduty cgen instead."),
        signal_range: None,
        arg_docs: &[(r"action", r"Default: NO-ACTION")],
    },
];
