// @generated — DO NOT EDIT.
// Regenerate with `node scripts/generate_ugens_rust.mjs`.

use crate::registry::UGenRegistryEntry;
use crate::Rate;

pub(crate) const UGENS: &[UGenRegistryEntry] = &[
    UGenRegistryEntry {
        name: r"Convolution",
        rates: &[Rate::Audio],
        defaults: &[(r"in", None), (r"kernel", None), (r"framesize", Some(512.0))],
        num_outputs: None,
        extends: None,
        summary: None,
        doc: Some(r"Strict convolution of two continuously changing inputs. Also see convolution2 for a cheaper CPU cost alternative for the case of a fixed kernel which can be changed with a trigger message. See Steven W Smith, The Scientist and Engineer's Guide to Digital Signal Processing: chapter 18: http:// www.dspguide.com/ch18.htm"),
        signal_range: None,
        arg_docs: &[(r"framesize", r"size of FFT frame, must be a power of two"), (r"in", r"processing target"), (r"kernel", r"processing kernel.")],
    },
    UGenRegistryEntry {
        name: r"Convolution2",
        rates: &[Rate::Audio],
        defaults: &[(r"in", None), (r"kernel", None), (r"trigger", None), (r"framesize", Some(512.0))],
        num_outputs: None,
        extends: None,
        summary: None,
        doc: Some(r"Strict convolution with fixed kernel which can be updated using a trigger signal. See Steven W Smith, The Scientist and Engineer's Guide to Digital Signal Processing: chapter 18: http:// www.dspguide.com/ch18.htm"),
        signal_range: None,
        arg_docs: &[(r"framesize", r"size of FFT frame, must be a power of two. Convolution uses twice this number internally, maximum value you can give this argument is 2^16 = 65536. Note that it gets progressively more expensive to run for higher powers! 512, 1024, 2048, 4096 standard."), (r"in", r"processing target"), (r"kernel", r"buffer index for the fixed kernel, may be modulated in combination with the trigger"), (r"trigger", r"update the kernel on a change from <= 0 to > 0")],
    },
    UGenRegistryEntry {
        name: r"Convolution2L",
        rates: &[Rate::Audio],
        defaults: &[(r"in", None), (r"kernel", None), (r"trigger", None), (r"framesize", Some(512.0)), (r"crossfade", Some(1.0))],
        num_outputs: None,
        extends: None,
        summary: None,
        doc: Some(r"Strict convolution with fixed kernel which can be updated using a trigger signal. There is a linear crossfade between the buffers upon change. See Steven W Smith, The Scientist and Engineer's Guide to Digital Signal Processing: chapter 18: http://www.dspguide.com/ch18.htm"),
        signal_range: None,
        arg_docs: &[(r"crossfade", r"The number of periods over which a crossfade is made. The default is 1. This must be an integer."), (r"framesize", r"size of FFT frame, must be a power of two. Convolution uses twice this number internally, maximum value you can give this argument is 2^16=65536. Note that it gets progressively more expensive to run for higher powers! 512, 1024, 2048, 4096 standard."), (r"in", r"processing target"), (r"kernel", r"buffer index for the fixed kernel, may be modulated in combination with the trigger"), (r"trigger", r"update the kernel on a change from <= 0 to > 0")],
    },
    UGenRegistryEntry {
        name: r"Convolution3",
        rates: &[Rate::Audio, Rate::Control],
        defaults: &[(r"in", None), (r"kernel", None), (r"trigger", Some(0.0)), (r"framesize", Some(512.0))],
        num_outputs: None,
        extends: None,
        summary: None,
        doc: Some(r"Strict convolution with fixed kernel which can be updated using a trigger signal. The convolution is performed in the time domain, which is highly inefficient, and probably only useful for either very short kernel sizes, or for control rate signals."),
        signal_range: None,
        arg_docs: &[(r"framesize", r"size of FFT frame, does not have to be a power of two."), (r"in", r"processing target"), (r"kernel", r"buffer index for the fixed kernel, may be modulated in combination with the trigger"), (r"trigger", r"update the kernel on a change from <= 0 to > 0")],
    },
    UGenRegistryEntry {
        name: r"PV_ConformalMap",
        rates: &[Rate::Control],
        defaults: &[(r"buffer", None), (r"areal", Some(0.0)), (r"aimag", Some(0.0))],
        num_outputs: None,
        extends: None,
        summary: None,
        doc: Some(r"Applies the conformal mapping z -> (z-a)/(1-za*) to the phase vocoder bins z with a given by the real and imag inputs to the UGen. i.e., makes a transformation of the complex plane so the output is full of phase vocoder artifacts but may be musically fun. Usually keep |a|<1 but you can of course try bigger values to make it really noisy. a=0 should give back the input mostly unperturbed. See http://mathworld.wolfram.com/ConformalMapping.html"),
        signal_range: None,
        arg_docs: &[(r"aimag", r"imaginary part of a."), (r"areal", r"real part of a."), (r"buffer", r"buffer number of buffer to act on, passed in through a chain (see examples below).")],
    },
    UGenRegistryEntry {
        name: r"PV_HainsworthFoote",
        rates: &[Rate::Audio],
        defaults: &[(r"buffer", None), (r"proph", Some(0.0)), (r"propf", Some(0.0)), (r"threshold", Some(1.0)), (r"waitTime", Some(0.04))],
        num_outputs: None,
        extends: None,
        summary: None,
        doc: Some(r"FFT onset detector based on work described in: Hainsworth, S. (2003) Techniques for the Automated Analysis of Musical Audio. PhD, University of Cambridge engineering dept. See especially p128. The Hainsworth metric is a modification of the Kullback Liebler distance. The onset detector has general ability to spot spectral change, so may have some ability to track chord changes aside from obvious transient jolts, but there's no guarantee it won't be confused by frequency modulation artifacts. Hainsworth metric on it's own gives good results but Foote might be useful in some situations: experimental."),
        signal_range: None,
        arg_docs: &[(r"buffer", r"FFT buffer to read from"), (r"propf", r"What strength of detection signal from Foote metric to use. The Foote metric is normalised to [0.0,1.0]"), (r"proph", r"What strength of detection signal from Hainsworth metric to use."), (r"threshold", r"Threshold hold level for allowing a detection"), (r"waitTime", r"If triggered, minimum wait until a further frame can cause another spot (useful to stop multiple detects on heavy signals)")],
    },
    UGenRegistryEntry {
        name: r"PV_JensenAndersen",
        rates: &[Rate::Audio],
        defaults: &[(r"buffer", None), (r"propsc", Some(0.25)), (r"prophfe", Some(0.25)), (r"prophfc", Some(0.25)), (r"propsf", Some(0.25)), (r"threshold", Some(1.0)), (r"waitTime", Some(0.04))],
        num_outputs: None,
        extends: None,
        summary: None,
        doc: Some(r"FFT feature detector for onset detection based on work described in: Jensen,K. & Andersen, T. H. (2003). Real-time Beat Estimation Using Feature Extraction. In Proceedings of the Computer Music Modeling and Retrieval Symposium, Lecture Notes in Computer Science. Springer Verlag. First order derivatives of the features are taken. Threshold may need to be set low to pick up on changes."),
        signal_range: None,
        arg_docs: &[(r"buffer", r"FFT buffer to read from."), (r"prophfc", r"Proportion of high frequency content feature."), (r"prophfe", r"Proportion of high frequency energy feature."), (r"propsc", r"Proportion of spectral centroid feature."), (r"propsf", r"Proportion of spectral flux feature."), (r"threshold", r"Threshold level for allowing a detection"), (r"waitTime", r"If triggered, minimum wait until a further frame can cause another spot (useful to stop multiple detects on heavy signals)")],
    },
    UGenRegistryEntry {
        name: r"RunningSum",
        rates: &[Rate::Audio, Rate::Control],
        defaults: &[(r"in", None), (r"numsamp", Some(40.0))],
        num_outputs: None,
        extends: None,
        summary: None,
        doc: Some(r"A running sum over a user specified number of samples, useful for running RMS power windowing."),
        signal_range: None,
        arg_docs: &[(r"in", r"Input signal"), (r"numsamp", r"How many samples to take the running sum over (initialisation time only, not modulatable.")],
    },
    UGenRegistryEntry {
        name: r"StereoConvolution2L",
        rates: &[Rate::Audio],
        defaults: &[(r"in", None), (r"kernelL", None), (r"kernelR", None), (r"trigger", None), (r"framesize", Some(512.0)), (r"crossfade", Some(1.0))],
        num_outputs: Some(2),
        extends: None,
        summary: None,
        doc: Some(r"Strict convolution with fixed kernel which can be updated using a trigger signal. There is a linear crossfade between the buffers upon change. Like convolution2L, but convolves with two buffers and outputs a stereo signal. This saves one FFT transformation per period, as compared to using two copies of convolution2L. Useful applications could include stereo reverberation or HRTF convolution. See Steven W Smith, The Scientist and Engineer's Guide to Digital Signal Processing: chapter 18: http://www.dspguide.com/ch18.htm"),
        signal_range: None,
        arg_docs: &[(r"crossfade", r"The number of periods over which a crossfade is made. This must be an integer."), (r"framesize", r"size of FFT frame, must be a power of two. Convolution uses twice this number internally, maximum value you can give this argument is 2^16=65536. Note that it gets progressively more expensive to run for higher powers! 512, 1024, 2048, 4096 standard."), (r"in", r"processing target"), (r"kernelL", r"buffer index for the fixed kernel of the left channel, may be modulated in combination with the trigger"), (r"kernelR", r"buffer index for the fixed kernel of the right channel, may be modulated in combination with the trigger"), (r"trigger", r"update the kernel on a change from <= 0 to > 0")],
    },
];
