// @generated — DO NOT EDIT.
// Regenerate with `node scripts/generate_ugens_rust.mjs`.

use crate::registry::UGenRegistryEntry;
use crate::Rate;

pub(crate) const UGENS: &[UGenRegistryEntry] = &[
    UGenRegistryEntry {
        name: r"APF",
        rates: &[Rate::Audio, Rate::Control],
        defaults: &[(r"in", Some(0.0)), (r"freq", Some(440.0)), (r"radius", Some(0.8))],
        num_outputs: None,
        extends: None,
        summary: None,
        doc: None,
        signal_range: None,
        arg_docs: &[],
    },
    UGenRegistryEntry {
        name: r"BPF",
        rates: &[Rate::Audio, Rate::Control],
        defaults: &[(r"in", Some(0.0)), (r"freq", Some(440.0)), (r"rq", Some(1.0))],
        num_outputs: None,
        extends: None,
        summary: Some(r"second order Butterworth bandpass filter"),
        doc: Some(r"A band pass filter permits the frequencies around a specified centre frequency to pass unaltered through the filter while the frequencies either side are attenuated. The frequencies that pass through are known as the bandwidth or the band pass of the filter. Used to create timbres consisting of fizzy harmonics, lo-fi qualities or very thin sounds that may form the basis of sound effects."),
        signal_range: None,
        arg_docs: &[(r"freq", r"centre frequency in Hertz"), (r"in", r"input signal to be processed"), (r"rq", r"the reciprocal of Q. bandwidth / cutoffFreq")],
    },
    UGenRegistryEntry {
        name: r"BPZ2",
        rates: &[Rate::Audio, Rate::Control],
        defaults: &[(r"in", Some(0.0))],
        num_outputs: None,
        extends: None,
        summary: None,
        doc: Some(r"two zero fixed midpass which cuts out 0 Hz and the Nyquist frequency. Implements the formula: out(i) = 0.5 * (in(i) - in(i-2))"),
        signal_range: None,
        arg_docs: &[],
    },
    UGenRegistryEntry {
        name: r"BRF",
        rates: &[Rate::Audio, Rate::Control],
        defaults: &[(r"in", Some(0.0)), (r"freq", Some(440.0)), (r"rq", Some(1.0))],
        num_outputs: None,
        extends: None,
        summary: Some(r"second order Butterworth band reject filter"),
        doc: Some(r"Band reject filters, also known as notch filters, attenuate a selected range of frequencies effectively creating a notch in the sound. This type of filter is handy for scooping out frequencies, thinning out a sound while leaving the fundamental intact, making them useful for creating timbres that contain a discernable pitch but do not have a high level of harmonic content."),
        signal_range: None,
        arg_docs: &[(r"freq", r"centre frequency in Hertz"), (r"in", r"input signal to be processed"), (r"rq", r"the reciprocal of Q. bandwidth / cutoffFreq")],
    },
    UGenRegistryEntry {
        name: r"BRZ2",
        rates: &[Rate::Audio, Rate::Control],
        defaults: &[(r"in", Some(0.0))],
        num_outputs: None,
        extends: None,
        summary: None,
        doc: Some(r"two zero fixed midcut which cuts out frequencies around 1/2 of the Nyquist frequency. Implements the formula: out(i) = 0.5 * (in(i) + in(i-2))"),
        signal_range: None,
        arg_docs: &[],
    },
    UGenRegistryEntry {
        name: r"Decay",
        rates: &[Rate::Audio, Rate::Control],
        defaults: &[(r"in", Some(0.0)), (r"decayTime", Some(1.0))],
        num_outputs: None,
        extends: None,
        summary: Some(r"triggered exponential decay."),
        doc: Some(r"This is essentially the same as integrator except that instead of supplying the coefficient directly, it is calculated from a 60 dB decay time. This is the time required for the integrator to lose 99.9 % of its value or -60dB. This is useful for exponential decaying envelopes triggered by impulses."),
        signal_range: None,
        arg_docs: &[(r"decayTime", r"60 dB decay time in seconds"), (r"in", r"input signal")],
    },
    UGenRegistryEntry {
        name: r"Decay2",
        rates: &[Rate::Audio, Rate::Control],
        defaults: &[(r"in", Some(0.0)), (r"attackTime", Some(0.01)), (r"decayTime", Some(1.0))],
        num_outputs: None,
        extends: None,
        summary: None,
        doc: Some(r"triggered exponential attack and exponential decay. Decay has a very sharp attack and can produce clicks. Decay2 rounds off the attack by subtracting one Decay from another. (decay in attack-time decay-time) equivalent to: (- (decay in attack-time decay-time) (decay in attack-time decay-time))"),
        signal_range: None,
        arg_docs: &[(r"attackTime", r"60 dB attack time in seconds."), (r"decayTime", r"60 dB decay time in seconds."), (r"in", r"input signal")],
    },
    UGenRegistryEntry {
        name: r"DetectSilence",
        rates: &[Rate::Audio, Rate::Control],
        defaults: &[(r"in", Some(0.0)), (r"amp", Some(0.0001)), (r"time", Some(0.1)), (r"action", Some(0.0))],
        num_outputs: None,
        extends: None,
        summary: None,
        doc: Some(r"If the signal input starts with silence at the beginning of the synth's duration, then DetectSilence will wait indefinitely until the first sound before starting to monitor for silence. This UGen outputs 1 if silence is detected, otherwise 0."),
        signal_range: None,
        arg_docs: &[(r"action", r"the action to perform when silence is detected. Default: NO-ACTION"), (r"amp", r"when input falls below this, evaluate done action"), (r"in", r"any source"), (r"time", r"the minimum duration of the input signal which input must fall below thresh before this triggers. The default is 0.1 seconds")],
    },
    UGenRegistryEntry {
        name: r"FOS",
        rates: &[Rate::Audio, Rate::Control],
        defaults: &[(r"in", Some(0.0)), (r"a0", Some(0.0)), (r"a1", Some(0.0)), (r"b1", Some(0.0))],
        num_outputs: None,
        extends: None,
        summary: None,
        doc: Some(r"first order filter section. Formula is equivalent to: out(i) = (a0 * in(i)) + (a1 * in(i-1)) + (b1 * out(i-1))"),
        signal_range: None,
        arg_docs: &[(r"a0", r"first coefficient"), (r"a1", r"second coefficient"), (r"b1", r"third coefficient"), (r"in", r"input signal")],
    },
    UGenRegistryEntry {
        name: r"Formlet",
        rates: &[Rate::Audio, Rate::Control],
        defaults: &[(r"in", Some(0.0)), (r"freq", Some(440.0)), (r"attackTime", Some(1.0)), (r"decayTime", Some(1.0))],
        num_outputs: None,
        extends: None,
        summary: None,
        doc: Some(r"a resonant filter whose impulse response is like that of a sine wave with a Decay2 envelope over it. The great advantage to this filter over FOF is that there is no limit to the number of overlapping grains since the grain is just the impulse response of the filter. Note that if attacktime == decaytime then the signal cancels out and if attacktime > decaytime then the impulse response is inverted."),
        signal_range: None,
        arg_docs: &[(r"attackTime", r"60 dB attack time in seconds"), (r"decayTime", r"60 dB decay time in seconds"), (r"freq", r"resonant frequency in Hertz"), (r"in", r"input signal to be processed")],
    },
    UGenRegistryEntry {
        name: r"HPF",
        rates: &[Rate::Audio, Rate::Control],
        defaults: &[(r"in", Some(0.0)), (r"freq", Some(440.0))],
        num_outputs: None,
        extends: None,
        summary: Some(r"second order high pass filter"),
        doc: Some(r"A high pass filter lets through the frequencies above the cutoff point and successfully dampens the frequencies below the cutoff point. This effectively removes the fundamental frequency of the sound, leaving only the fizz harmonic overtones. High pass filters are rarely used in the creation of instruments and are predominantly used to create effervexcent sound effects of bright timbres that can be laid over the top of another low pass sound to increase the harmonic content."),
        signal_range: None,
        arg_docs: &[(r"freq", r"cutoff frequency"), (r"in", r"input signal to be processed")],
    },
    UGenRegistryEntry {
        name: r"HPZ1",
        rates: &[Rate::Audio, Rate::Control],
        defaults: &[(r"in", Some(0.0))],
        num_outputs: None,
        extends: None,
        summary: None,
        doc: Some(r"two point difference filter. Implements the formula: out(i) = 0.5 * (in(i) - in(i-1))"),
        signal_range: None,
        arg_docs: &[],
    },
    UGenRegistryEntry {
        name: r"HPZ2",
        rates: &[Rate::Audio, Rate::Control],
        defaults: &[(r"in", Some(0.0))],
        num_outputs: None,
        extends: None,
        summary: None,
        doc: Some(r"two zero fixed highpass. Implements the formula: out(i) = 0.25 * (in(i) - (2*in(i-1)) + in(i-2))"),
        signal_range: None,
        arg_docs: &[],
    },
    UGenRegistryEntry {
        name: r"Integrator",
        rates: &[Rate::Audio, Rate::Control],
        defaults: &[(r"in", Some(0.0)), (r"coef", Some(1.0))],
        num_outputs: None,
        extends: None,
        summary: None,
        doc: Some(r"leaky integrator. Integrates an input signal with a leak. The formula implemented is: out(0) = in(0) + (coef * out(-1))"),
        signal_range: None,
        arg_docs: &[(r"coef", r"leak coefficient"), (r"in", r"input signal")],
    },
    UGenRegistryEntry {
        name: r"LPF",
        rates: &[Rate::Audio, Rate::Control],
        defaults: &[(r"in", Some(0.0)), (r"freq", Some(440.0))],
        num_outputs: None,
        extends: None,
        summary: Some(r"second order Butterworth low pass filter"),
        doc: Some(r"A low pass filter is a standard subtractive synthesis tool which removes frequencies above a defined cut-off point. This typically has the effect of making bright sounds duller. Using a low pass filter allows you to have fine-grained control of the level of brightness/dullness to tune your timbre in addition to allowing you to modulate the effect in real time thus creating movement in the sound."),
        signal_range: None,
        arg_docs: &[(r"freq", r"cutoff frequency"), (r"in", r"input signal to be processed")],
    },
    UGenRegistryEntry {
        name: r"LPZ1",
        rates: &[Rate::Audio, Rate::Control],
        defaults: &[(r"in", Some(0.0))],
        num_outputs: None,
        extends: None,
        summary: None,
        doc: Some(r"two point average filter. Implements the formula: out(i) = 0.5 * (in(i) + in(i-1))"),
        signal_range: None,
        arg_docs: &[],
    },
    UGenRegistryEntry {
        name: r"LPZ2",
        rates: &[Rate::Audio, Rate::Control],
        defaults: &[(r"in", Some(0.0))],
        num_outputs: None,
        extends: None,
        summary: None,
        doc: Some(r"two zero fixed lowpass. Implements the formula: out(i) = 0.25 * (in(i) + (2*in(i-1)) + in(i-2))"),
        signal_range: None,
        arg_docs: &[],
    },
    UGenRegistryEntry {
        name: r"Lag",
        rates: &[Rate::Audio, Rate::Control],
        defaults: &[(r"in", Some(0.0)), (r"lagTime", Some(0.1))],
        num_outputs: None,
        extends: None,
        summary: None,
        doc: Some(r"exponential lag, useful for smoothing out control signals. This is essentially the same as OnePole except that instead of supplying the coefficient directly, it is calculated from a 60 dB lag time. This is the time required for the filter to converge to within 0.01 % of a value."),
        signal_range: None,
        arg_docs: &[(r"in", r"input signal"), (r"lagTime", r"60 dB lag time in seconds")],
    },
    UGenRegistryEntry {
        name: r"Lag2",
        rates: &[Rate::Audio, Rate::Control],
        defaults: &[(r"in", Some(0.0)), (r"lagTime", Some(0.1))],
        num_outputs: None,
        extends: None,
        summary: None,
        doc: Some(r"equivalent to (lag (lag in time) time), resulting in a smoother transition. This saves on CPU as you only have to calculate the decay factor once instead of twice. See lag for more details."),
        signal_range: None,
        arg_docs: &[(r"in", r"input signal"), (r"lagTime", r"60 dB lag time in seconds")],
    },
    UGenRegistryEntry {
        name: r"Lag2UD",
        rates: &[Rate::Audio, Rate::Control],
        defaults: &[(r"in", Some(0.0)), (r"lagTimeUp", Some(0.1)), (r"lagTimeDown", Some(0.1))],
        num_outputs: None,
        extends: None,
        summary: None,
        doc: Some(r"equivalent to (lag-ud (lag-ud in up-t down-t) up-t down-t) thus resulting in a smoother transition. This saves on CPU as you only have to calculate the decay factor once instead of twice. See Lag for more details."),
        signal_range: None,
        arg_docs: &[(r"in", r"input signal"), (r"lagTimeDown", r"60 dB lag time in seconds for the downgoing signal"), (r"lagTimeUp", r"60 dB lag time in seconds for the upgoing signal")],
    },
    UGenRegistryEntry {
        name: r"Lag3",
        rates: &[Rate::Audio, Rate::Control],
        defaults: &[(r"in", Some(0.0)), (r"lagTime", Some(0.1))],
        num_outputs: None,
        extends: None,
        summary: None,
        doc: Some(r"lag3 is equivalent to (lag (lag (lag in time) time) time), thus resulting in a smoother transition. This saves on CPU as you only have to calculate the decay factor once instead of three times. See Lag for more details."),
        signal_range: None,
        arg_docs: &[(r"in", r"input signal"), (r"lagTime", r"60 dB lag time in seconds")],
    },
    UGenRegistryEntry {
        name: r"Lag3UD",
        rates: &[Rate::Audio, Rate::Control],
        defaults: &[(r"in", Some(0.0)), (r"lagTimeUp", Some(0.1)), (r"lagTimeDown", Some(0.1))],
        num_outputs: None,
        extends: None,
        summary: None,
        doc: Some(r"equivalent to (lag-ud (lag-ud (lag-ud (in up-t down-t) up-t down-t) up-t, down-t) thus resulting in a smoother transition. This saves on CPU as you only have to calculate the decay factor once instead of three times."),
        signal_range: None,
        arg_docs: &[(r"in", r"input signal"), (r"lagTimeDown", r"60 dB lag time in seconds for the downgoing signal"), (r"lagTimeUp", r"60 dB lag time in seconds for the upgoing signal")],
    },
    UGenRegistryEntry {
        name: r"LagUD",
        rates: &[Rate::Audio, Rate::Control],
        defaults: &[(r"in", Some(0.0)), (r"lagTimeUp", Some(0.1)), (r"lagTimeDown", Some(0.1))],
        num_outputs: None,
        extends: None,
        summary: None,
        doc: Some(r"the same as Lag except that you can supply a different 60 dB time for when the signal goes up, from when the signal goes down"),
        signal_range: None,
        arg_docs: &[(r"in", r"input signal"), (r"lagTimeDown", r"60 dB lag time in seconds for the downgoing signal"), (r"lagTimeUp", r"60 dB lag time in seconds for the upgoing signal")],
    },
    UGenRegistryEntry {
        name: r"LeakDC",
        rates: &[Rate::Audio, Rate::Control],
        defaults: &[(r"in", Some(0.0)), (r"coef", Some(0.995))],
        num_outputs: None,
        extends: None,
        summary: None,
        doc: Some(r"removes a DC offset from signal. For example, a square wave contains prolonged sections of the cycle which are at +1 and -1 (the top and bottom of the square sections). If you were to pass this wave through leak-dc, then these top parts would taper back towards 0 with a greater slope as you move coef from 1 to 0.. Good starting point coef values are to 0.995 for audio rate and 0.9 for control rate"),
        signal_range: None,
        arg_docs: &[(r"coef", r"leak coefficient. A value of 1 indicates no leakage and 0 indicates high leakage - essentially the rate at which the offset will return back to 0"), (r"in", r"input signal")],
    },
    UGenRegistryEntry {
        name: r"Median",
        rates: &[Rate::Audio, Rate::Control],
        defaults: &[(r"length", Some(3.0)), (r"in", Some(0.0))],
        num_outputs: None,
        extends: None,
        summary: None,
        doc: Some(r"returns the median of the last length input points. This non linear filter is good at reducing impulse noise from a signal."),
        signal_range: None,
        arg_docs: &[(r"in", r"Input signal to be processed"), (r"length", r"number of input points in which to find the median. Must be an odd number from 1 to 31. If length is 1 then Median has no effect.")],
    },
    UGenRegistryEntry {
        name: r"MidEQ",
        rates: &[Rate::Audio, Rate::Control],
        defaults: &[(r"in", Some(0.0)), (r"freq", Some(440.0)), (r"rq", Some(1.0)), (r"db", Some(0.0))],
        num_outputs: None,
        extends: None,
        summary: None,
        doc: Some(r"attenuates or boosts a frequency band"),
        signal_range: None,
        arg_docs: &[(r"db", r"amount of boost (db > 0) or attenuation (db < 0) of the frequency band"), (r"freq", r"center frequency of the band in Hertz"), (r"in", r"input signal to be processed"), (r"rq", r"the reciprocal of Q. bandwidth / cutoffFreq")],
    },
    UGenRegistryEntry {
        name: r"OnePole",
        rates: &[Rate::Audio, Rate::Control],
        defaults: &[(r"in", Some(0.0)), (r"coef", Some(0.5))],
        num_outputs: None,
        extends: None,
        summary: None,
        doc: Some(r"A one pole filter. Implements the formula: out(i) = ((1 - abs(coef)) * in(i)) + (coef * out(i-1))"),
        signal_range: None,
        arg_docs: &[(r"coef", r"feedback coefficient. Should be between -1 and +1"), (r"in", r"input signal to be processed")],
    },
    UGenRegistryEntry {
        name: r"OneZero",
        rates: &[Rate::Audio, Rate::Control],
        defaults: &[(r"in", Some(0.0)), (r"coef", Some(0.5))],
        num_outputs: None,
        extends: None,
        summary: None,
        doc: Some(r"A one zero filter. Implements the formula : out(i) = ((1 - abs(coef)) * in(i)) + (coef * in(i-1))"),
        signal_range: None,
        arg_docs: &[(r"coef", r"feed forward coefficient. +0.5 makes a two point averaging filter (see also lpz1), -0.5 makes a differentiator (see also hpz1), +1 makes a single sample delay (see also delay1), -1 makes an inverted single sample delay."), (r"in", r"input signal to be processed")],
    },
    UGenRegistryEntry {
        name: r"RHPF",
        rates: &[Rate::Audio, Rate::Control],
        defaults: &[(r"in", Some(0.0)), (r"freq", Some(440.0)), (r"rq", Some(1.0))],
        num_outputs: None,
        extends: None,
        summary: Some(r"resonant high pass filter"),
        doc: Some(r"A resonant high pass filter lets through the frequencies above the cutoff point and successfully dampens the frequencies below the cutoff point. This effectively removes the fundamental frequency of the sound, leaving only the fizz harmonic overtones. However, in addition to this behaviour, the resonant high pass filter also emphasises/resonates the frequencies around the cutoff point. The amount of emphasis is controlled by the rq param with a lower rq resulting in greater resonance. High amounts of resonance (rq ~0) can create a whistling sound around the cutoff frequency. High pass filters are rarely used in the creation of instruments and are predominantly used to create effervescent sound effects of bright timbres that can be laid over the top of another low pass sound to increase the harmonic content."),
        signal_range: None,
        arg_docs: &[(r"freq", r"cutoff frequency"), (r"in", r"input signal to be processed"), (r"rq", r"the reciprocal of Q. bandwidth / cutoffFreq. A lower rq results in more resonance")],
    },
    UGenRegistryEntry {
        name: r"RLPF",
        rates: &[Rate::Audio, Rate::Control],
        defaults: &[(r"in", Some(0.0)), (r"freq", Some(440.0)), (r"rq", Some(1.0))],
        num_outputs: None,
        extends: None,
        summary: Some(r"resonant low pass filter"),
        doc: Some(r"A resonant low pass filter is a standard subtractive synthesis tool which removes frequencies above a defined cut-off point. This typically has the effect of making bright sounds duller. However, in addition to this behaviour, the resonant low pass filter also emphasises/resonates the frequencies around the cutoff point. The amount of emphasis is controlled by the rq param with a lower rq resulting in greater resonance. High amounts of resonance (rq ~0) can create a whistling sound around the cutoff frequency. Using a low pass filter allows you to have fine-grained control of the level of brightness/dullness to tune your timbre in addition to allowing you to modulate the effect in real time thus creating movement in the sound."),
        signal_range: None,
        arg_docs: &[(r"freq", r"cutoff frequency"), (r"in", r"input signal to be processed"), (r"rq", r"the reciprocal of Q. bandwidth / cutoffFreq. A lower rq results in more resonance.")],
    },
    UGenRegistryEntry {
        name: r"Ramp",
        rates: &[Rate::Audio, Rate::Control],
        defaults: &[(r"in", Some(0.0)), (r"lagTime", Some(0.1))],
        num_outputs: None,
        extends: None,
        summary: None,
        doc: Some(r"similar to lag but with a linear rather than exponential lag, useful for smoothing out control signals"),
        signal_range: None,
        arg_docs: &[(r"in", r"input signal"), (r"lagTime", r"60 dB lag time in seconds")],
    },
    UGenRegistryEntry {
        name: r"Resonz",
        rates: &[Rate::Audio, Rate::Control],
        defaults: &[(r"in", Some(0.0)), (r"freq", Some(440.0)), (r"bwr", Some(1.0))],
        num_outputs: None,
        extends: None,
        summary: None,
        doc: Some(r#"A Note on Constant-Gain Digital Resonators,\" Computer Music Journal, vol 18, no. 4, pp. 8-10, Winter 1994.\" Computer Music Journal, vol 18, no. 4, pp. 8-10, Winter 1994."#),
        signal_range: None,
        arg_docs: &[(r"bwr", r"bandwidth ratio (reciprocal of Q). rq = bandwidth / centerFreq"), (r"freq", r"resonant frequency in Hertz"), (r"in", r"input signal to be processed")],
    },
    UGenRegistryEntry {
        name: r"Ringz",
        rates: &[Rate::Audio, Rate::Control],
        defaults: &[(r"in", Some(0.0)), (r"freq", Some(440.0)), (r"decayTime", Some(1.0))],
        num_outputs: None,
        extends: None,
        summary: None,
        doc: Some(r"Ringz is the same as Resonz, except that instead of a resonance parameter, the bandwidth is specified in a 60dB ring decay time. One Ringz is equivalent to one component of the klank ugen"),
        signal_range: None,
        arg_docs: &[(r"decayTime", r"the 60 dB decay time of the filter"), (r"freq", r"resonant frequency in Hertz"), (r"in", r"input signal to be processed")],
    },
    UGenRegistryEntry {
        name: r"SOS",
        rates: &[Rate::Audio, Rate::Control],
        defaults: &[(r"in", Some(0.0)), (r"a0", Some(0.0)), (r"a1", Some(0.0)), (r"a2", Some(0.0)), (r"b1", Some(0.0)), (r"b2", Some(0.0))],
        num_outputs: None,
        extends: None,
        summary: None,
        doc: Some(r"second order filter section (biquad). Formula is equivalent to: out(i) = (a0 * in(i)) + (a1 * in(i-1)) + (a2 * in(i-2)) + (b1 * out(i-1)) + (b2 * out(i-2))"),
        signal_range: None,
        arg_docs: &[(r"a0", r"1st coefficient"), (r"a1", r"2nd coefficient"), (r"a2", r"3rd coefficient"), (r"b1", r"4th coefficient"), (r"b2", r"5th coefficient"), (r"in", r"input signal")],
    },
    UGenRegistryEntry {
        name: r"Slew",
        rates: &[Rate::Audio, Rate::Control],
        defaults: &[(r"in", Some(0.0)), (r"up", Some(1.0)), (r"dn", Some(1.0))],
        num_outputs: None,
        extends: None,
        summary: None,
        doc: Some(r"Smooth the curve by limiting the slope of the input signal to up and dn"),
        signal_range: None,
        arg_docs: &[(r"dn", r"maximum downward slope"), (r"in", r"input signal"), (r"up", r"maximum upward slope")],
    },
    UGenRegistryEntry {
        name: r"Slope",
        rates: &[Rate::Audio, Rate::Control],
        defaults: &[(r"in", Some(0.0))],
        num_outputs: None,
        extends: None,
        summary: None,
        doc: Some(r"Measures the rate of change per second of a signal. Formula implemented is: out[i] = (in[i] - in[i-1]) * sampling_rate"),
        signal_range: None,
        arg_docs: &[(r"in", r"input signal to measure")],
    },
    UGenRegistryEntry {
        name: r"TwoPole",
        rates: &[Rate::Audio, Rate::Control],
        defaults: &[(r"in", Some(0.0)), (r"freq", Some(440.0)), (r"radius", Some(0.8))],
        num_outputs: None,
        extends: None,
        summary: None,
        doc: Some(r"a two pole filter. This provides lower level access to setting of pole location. For general purposes Resonz is better."),
        signal_range: None,
        arg_docs: &[(r"freq", r"frequency of pole angle"), (r"in", r"input signal to be processed"), (r"radius", r"radius of pole. Should be between 0 and +1")],
    },
    UGenRegistryEntry {
        name: r"TwoZero",
        rates: &[Rate::Audio, Rate::Control],
        defaults: &[(r"in", Some(0.0)), (r"freq", Some(440.0)), (r"radius", Some(0.8))],
        num_outputs: None,
        extends: None,
        summary: None,
        doc: Some(r"a two zero filter"),
        signal_range: None,
        arg_docs: &[(r"freq", r"frequency of zero angle"), (r"in", r"input signal to be processed"), (r"radius", r"radius of zero")],
    },
];
