// @generated — DO NOT EDIT.
// Regenerate with `node scripts/generate_ugens_rust.mjs`.

use crate::registry::UGenRegistryEntry;
use crate::Rate;

pub(crate) const UGENS: &[UGenRegistryEntry] = &[
    UGenRegistryEntry {
        name: r"BufChannels",
        rates: &[Rate::Control, Rate::Scalar],
        defaults: &[(r"buf", Some(0.0))],
        num_outputs: None,
        extends: None,
        summary: None,
        doc: Some(r"current number of channels of soundfile in buffer"),
        signal_range: None,
        arg_docs: &[(r"buf", r"a buffer")],
    },
    UGenRegistryEntry {
        name: r"BufDur",
        rates: &[Rate::Control, Rate::Scalar],
        defaults: &[(r"buf", Some(0.0))],
        num_outputs: None,
        extends: None,
        summary: None,
        doc: Some(r"returns the current duration of a buffer in seconds."),
        signal_range: None,
        arg_docs: &[(r"buf", r"a buffer")],
    },
    UGenRegistryEntry {
        name: r"BufFrames",
        rates: &[Rate::Control, Rate::Scalar],
        defaults: &[(r"buf", Some(0.0))],
        num_outputs: None,
        extends: None,
        summary: None,
        doc: Some(r"returns the current number of allocated frames i.e. the size of the buffer. This is the equivalent of Clojure's count on a seq."),
        signal_range: None,
        arg_docs: &[(r"buf", r"a buffer")],
    },
    UGenRegistryEntry {
        name: r"BufRateScale",
        rates: &[Rate::Control, Rate::Scalar],
        defaults: &[(r"buf", Some(0.0))],
        num_outputs: None,
        extends: None,
        summary: None,
        doc: Some(r"returns a ratio by which the playback of a buffer is to be scaled"),
        signal_range: None,
        arg_docs: &[(r"buf", r"a buffer")],
    },
    UGenRegistryEntry {
        name: r"BufSampleRate",
        rates: &[Rate::Control, Rate::Scalar],
        defaults: &[(r"buf", Some(0.0))],
        num_outputs: None,
        extends: None,
        summary: None,
        doc: Some(r"returns the buffers current sample rate"),
        signal_range: None,
        arg_docs: &[(r"buf", r"a buffer")],
    },
    UGenRegistryEntry {
        name: r"BufSamples",
        rates: &[Rate::Control, Rate::Scalar],
        defaults: &[(r"buf", Some(0.0))],
        num_outputs: None,
        extends: None,
        summary: None,
        doc: Some(r"current number of samples allocated in the buffer"),
        signal_range: None,
        arg_docs: &[(r"buf", r"a buffer")],
    },
    UGenRegistryEntry {
        name: r"CheckBadValues",
        rates: &[Rate::Control, Rate::Scalar],
        defaults: &[(r"in", None), (r"id", Some(0.0)), (r"post", Some(2.0))],
        num_outputs: None,
        extends: None,
        summary: None,
        doc: Some(r"test for infinity, not-a-number, and denormals. If one of these is found, it posts a warning. Its output is as follows: 0 = a normal float, 1 = NaN, 2 = infinity, and 3 = a denormal."),
        signal_range: None,
        arg_docs: &[(r"id", r"an id number to identify this UGen."), (r"in", r"the UGen whose output is to be tested"), (r"post", r"One of three post modes: 0 = no posting; 1 = post a line for every bad value; 2 = post a line only when the floating-point classification changes (e.g., normal -> NaN and vice versa)")],
    },
    UGenRegistryEntry {
        name: r"ControlDur",
        rates: &[Rate::Scalar],
        defaults: &[],
        num_outputs: None,
        extends: None,
        summary: None,
        doc: Some(r"returns the current control rate block duration of the server in seconds"),
        signal_range: None,
        arg_docs: &[],
    },
    UGenRegistryEntry {
        name: r"ControlRate",
        rates: &[Rate::Scalar],
        defaults: &[],
        num_outputs: None,
        extends: None,
        summary: None,
        doc: Some(r"returns the current control rate of the server"),
        signal_range: None,
        arg_docs: &[],
    },
    UGenRegistryEntry {
        name: r"NumAudioBuses",
        rates: &[Rate::Scalar],
        defaults: &[],
        num_outputs: None,
        extends: None,
        summary: None,
        doc: Some(r"returns the number of audio buses allocated on the server."),
        signal_range: None,
        arg_docs: &[],
    },
    UGenRegistryEntry {
        name: r"NumBuffers",
        rates: &[Rate::Scalar],
        defaults: &[],
        num_outputs: None,
        extends: None,
        summary: None,
        doc: Some(r"returns the number of buffers allocated on the server"),
        signal_range: None,
        arg_docs: &[],
    },
    UGenRegistryEntry {
        name: r"NumControlBuses",
        rates: &[Rate::Scalar],
        defaults: &[],
        num_outputs: None,
        extends: None,
        summary: None,
        doc: Some(r"returns the number of control buses allocated on the server"),
        signal_range: None,
        arg_docs: &[],
    },
    UGenRegistryEntry {
        name: r"NumInputBuses",
        rates: &[Rate::Scalar],
        defaults: &[],
        num_outputs: None,
        extends: None,
        summary: None,
        doc: Some(r"returns the number of input buses allocated on the server. This is the number of hardware inputs provided by the host machine such as a mic."),
        signal_range: None,
        arg_docs: &[],
    },
    UGenRegistryEntry {
        name: r"NumOutputBuses",
        rates: &[Rate::Scalar],
        defaults: &[],
        num_outputs: None,
        extends: None,
        summary: None,
        doc: Some(r"returns the number of output buses allocated on the server. This is the number of hardware outputs provided by the host machine such as left and right speakers."),
        signal_range: None,
        arg_docs: &[],
    },
    UGenRegistryEntry {
        name: r"NumRunningSynths",
        rates: &[Rate::Scalar, Rate::Control],
        defaults: &[],
        num_outputs: None,
        extends: None,
        summary: None,
        doc: Some(r"returns the number of currently running synths"),
        signal_range: None,
        arg_docs: &[],
    },
    UGenRegistryEntry {
        name: r"Poll",
        rates: &[Rate::Audio, Rate::Control],
        defaults: &[(r"trig", Some(0.0)), (r"in", Some(0.0)), (r"label", None), (r"trigId", Some(-1.0))],
        num_outputs: None,
        extends: None,
        summary: None,
        doc: Some(r"This ugen has been internalised for scserver compatibility. Please use the poll cgen instead."),
        signal_range: None,
        arg_docs: &[(r"in", r"the signal you want to poll"), (r"label", r"a string or symbol to be printed with the polled value"), (r"trig", r"a non-positive to positive transition telling Poll to return a value"), (r"trigId", r"if greater than 0, a '/tr' message is sent back to the client (similar to send-trig)")],
    },
    UGenRegistryEntry {
        name: r"RadiansPerSample",
        rates: &[Rate::Scalar],
        defaults: &[],
        num_outputs: None,
        extends: None,
        summary: None,
        doc: None,
        signal_range: None,
        arg_docs: &[],
    },
    UGenRegistryEntry {
        name: r"SampleDur",
        rates: &[Rate::Scalar],
        defaults: &[],
        num_outputs: None,
        extends: None,
        summary: None,
        doc: Some(r"returns the current sample duration of the server in seconds"),
        signal_range: None,
        arg_docs: &[],
    },
    UGenRegistryEntry {
        name: r"SampleRate",
        rates: &[Rate::Scalar],
        defaults: &[],
        num_outputs: None,
        extends: None,
        summary: None,
        doc: Some(r"returns the current sample rate"),
        signal_range: None,
        arg_docs: &[],
    },
    UGenRegistryEntry {
        name: r"SubsampleOffset",
        rates: &[Rate::Scalar],
        defaults: &[],
        num_outputs: None,
        extends: None,
        summary: None,
        doc: Some(r"offset from synth start within one sample"),
        signal_range: None,
        arg_docs: &[],
    },
];
