// @generated — DO NOT EDIT.
// Regenerate with `node scripts/generate_ugens_rust.mjs`.

use crate::registry::UGenRegistryEntry;
use crate::Rate;

pub(crate) const UGENS: &[UGenRegistryEntry] = &[
    UGenRegistryEntry {
        name: r"A2K",
        rates: &[Rate::Control],
        defaults: &[(r"in", Some(0.0))],
        num_outputs: None,
        extends: None,
        summary: None,
        doc: Some(r"audio rate to control rate converter via linear interpolation"),
        signal_range: None,
        arg_docs: &[(r"in", r"input signal")],
    },
    UGenRegistryEntry {
        name: r"AmpComp",
        rates: &[Rate::Scalar, Rate::Audio, Rate::Control],
        defaults: &[(r"freq", Some(261.6256)), (r"root", Some(261.6256)), (r"exp", Some(0.3333))],
        num_outputs: None,
        extends: None,
        summary: Some(r#"Basic psychoacoustic amplitude compensation." , :rates #{:ir :ar :kr} :check (when-ar (first-input-ar "freq must be audio rate")) :doc "amplitude compensation: because higher frequencies are normally perceived as louder. Note that for frequencies very much smaller than root the amplitudes can become very high. In this case limit the freqor use amp-comp-a Implements the (optimized) formula: compensationFactor = (root / freq) ** exp"#),
        doc: Some(r"amplitude compensation: because higher frequencies are normally perceived as louder. Note that for frequencies very much smaller than root the amplitudes can become very high. In this case limit the freqor use amp-comp-a Implements the (optimized) formula: compensationFactor = (root / freq) ** exp"),
        signal_range: None,
        arg_docs: &[(r"exp", r"Exponent: how steep the curve decreases for increasing freq"), (r"freq", r"Input frequency value. For freq == root, the output is 1.0."), (r"root", r"Root freq relative to which the curve is calculated (usually lowest freq)")],
    },
    UGenRegistryEntry {
        name: r"AmpCompA",
        rates: &[Rate::Scalar, Rate::Audio, Rate::Control],
        defaults: &[(r"freq", Some(1000.0)), (r"root", Some(0.0)), (r"minAmp", Some(0.32)), (r"rootAmp", Some(1.0))],
        num_outputs: None,
        extends: Some(r"AmpComp"),
        summary: Some(r"Basic psychoacoustic amplitude compensation (ANSI A-weighting curve)."),
        doc: Some(r"Higher frequencies are normally perceived as louder, which amp-comp-a compensates. Following the measurings by Fletcher and Munson, the ANSI standard describes a function for loudness vs. frequency. Note that this curve is only valid for standardized amplitude. 1 For a simpler but more flexible curve, see amp-comp"),
        signal_range: None,
        arg_docs: &[(r"freq", r"Input frequency value. For freq == root, the output is root-amp"), (r"minAmp", r"Amplitude at the minimum point of the curve (around 2512 Hz)"), (r"root", r"Root freq relative to which the curve is calculated (usually lowest freq)"), (r"rootAmp", r"Amplitude at the root frequency.")],
    },
    UGenRegistryEntry {
        name: r"DC",
        rates: &[Rate::Audio, Rate::Control],
        defaults: &[(r"in", None)],
        num_outputs: None,
        extends: None,
        summary: None,
        doc: Some(r"outputs the initial value you give it."),
        signal_range: None,
        arg_docs: &[(r"in", r"constant value to output, cannot be modulated, set at initialisation time")],
    },
    UGenRegistryEntry {
        name: r"K2A",
        rates: &[Rate::Audio],
        defaults: &[(r"in", Some(0.0))],
        num_outputs: None,
        extends: None,
        summary: None,
        doc: Some(r"control rate to audio rate converter via linear interpolation."),
        signal_range: None,
        arg_docs: &[(r"in", r"input signal")],
    },
    UGenRegistryEntry {
        name: r"LinExp",
        rates: &[Rate::Audio, Rate::Control],
        defaults: &[(r"in", Some(0.0)), (r"srclo", Some(0.0)), (r"srchi", Some(1.0)), (r"dstlo", Some(1.0)), (r"dsthi", Some(2.0))],
        num_outputs: None,
        extends: None,
        summary: Some(r"Map a linear range to an exponential range"),
        doc: Some(r"Convert from a linear range to an exponential range. The dstlo and dsthi arguments must be nonzero and have the same sign."),
        signal_range: None,
        arg_docs: &[(r"dsthi", r"Upper limit of output range"), (r"dstlo", r"Lower limit of output range"), (r"in", r"Input to convert"), (r"srchi", r"Upper limit of input range"), (r"srclo", r"Lower limit of input range")],
    },
    UGenRegistryEntry {
        name: r"Line",
        rates: &[Rate::Audio, Rate::Control],
        defaults: &[(r"start", Some(0.0)), (r"end", Some(1.0)), (r"dur", Some(1.0)), (r"action", Some(0.0))],
        num_outputs: None,
        extends: None,
        summary: Some(r"Line generator."),
        doc: Some(r"Generates a line from the start value to the end value."),
        signal_range: None,
        arg_docs: &[(r"action", r"A done action to be evaluated when the line is completed. Default: NO-ACTION"), (r"dur", r"Duration in seconds"), (r"end", r"Ending value"), (r"start", r"Starting value")],
    },
    UGenRegistryEntry {
        name: r"Silent",
        rates: &[Rate::Audio],
        defaults: &[(r"numChannels", Some(1.0))],
        num_outputs: None,
        extends: None,
        summary: None,
        doc: Some(r"Continuously outputs 0"),
        signal_range: None,
        arg_docs: &[(r"numChannels", r"Number of channels of silence.")],
    },
    UGenRegistryEntry {
        name: r"T2A",
        rates: &[Rate::Audio],
        defaults: &[(r"in", Some(0.0)), (r"offset", Some(0.0))],
        num_outputs: None,
        extends: None,
        summary: None,
        doc: Some(r"control rate trigger to audio rate trigger converter (maximally one per control period)."),
        signal_range: None,
        arg_docs: &[(r"in", r"input signal"), (r"offset", r"sample offset within control period")],
    },
    UGenRegistryEntry {
        name: r"T2K",
        rates: &[Rate::Control],
        defaults: &[(r"in", Some(0.0))],
        num_outputs: None,
        extends: Some(r"A2K"),
        summary: None,
        doc: Some(r"audio rate trigger to control rate trigger converter. Uses the maxiumum trigger in the input during each control period."),
        signal_range: None,
        arg_docs: &[(r"in", r"input signal")],
    },
    UGenRegistryEntry {
        name: r"XLine",
        rates: &[Rate::Audio, Rate::Control],
        defaults: &[(r"start", Some(1.0)), (r"end", Some(2.0)), (r"dur", Some(1.0)), (r"action", Some(0.0))],
        num_outputs: None,
        extends: None,
        summary: Some(r"Exponential line generator."),
        doc: Some(r"Generates an exponential curve from the start value to the end value. Both the start and end values must be non-zero and have the same sign."),
        signal_range: None,
        arg_docs: &[(r"action", r"A done action to be evaluated when the line is completed. Default: NO-ACTION"), (r"dur", r"Duration in seconds"), (r"end", r"Ending value"), (r"start", r"Starting value")],
    },
];
