// @generated — DO NOT EDIT.
// Regenerate with `node scripts/generate_ugens_rust.mjs`.

use crate::registry::UGenRegistryEntry;
use crate::Rate;

pub(crate) const UGENS: &[UGenRegistryEntry] = &[
    UGenRegistryEntry {
        name: r"BrownNoise",
        rates: &[Rate::Audio, Rate::Control],
        defaults: &[],
        num_outputs: None,
        extends: None,
        summary: Some(r"Noise whose spectrum falls off in power by 6 dB per octave."),
        doc: Some(r"Useful for generating percussive sounds such as snares and hand claps. Also useful for simulating wind or sea effects, for producing breath effects in wind instrument timbres or for producing the typical trance leads."),
        signal_range: None,
        arg_docs: &[],
    },
    UGenRegistryEntry {
        name: r"ClipNoise",
        rates: &[Rate::Audio],
        defaults: &[],
        num_outputs: None,
        extends: None,
        summary: Some(r"Noise whose values are either -1 or 1."),
        doc: Some(r"This produces the maximum energy for the least peak to peak amplitude. Useful for generating percussive sounds such as snares and hand claps. Also useful for simulating wind or sea effects, for producing breath effects in wind instrument timbres or for producing the typical trance leads."),
        signal_range: None,
        arg_docs: &[],
    },
    UGenRegistryEntry {
        name: r"Crackle",
        rates: &[Rate::Audio, Rate::Control],
        defaults: &[(r"chaosParam", Some(1.5))],
        num_outputs: None,
        extends: None,
        summary: Some(r"Chaotic noise generator"),
        doc: Some(r"A noise generator based on a chaotic function. Useful for generating percussive sounds such as snares and hand claps. Also useful for simulating wind or sea effects, for producing breath effects in wind instrument timbres or for producing the typical trance leads."),
        signal_range: None,
        arg_docs: &[(r"chaosParam", r"a parameter of the chaotic function with useful values from just below 1.0 to just above 2.0. Towards 2.0 the sound crackles.")],
    },
    UGenRegistryEntry {
        name: r"Dust",
        rates: &[Rate::Audio, Rate::Control],
        defaults: &[(r"density", Some(0.0))],
        num_outputs: None,
        extends: None,
        summary: None,
        doc: Some(r"Generates random impulses from 0 to +1."),
        signal_range: None,
        arg_docs: &[(r"density", r"average number of impulses per second")],
    },
    UGenRegistryEntry {
        name: r"Dust2",
        rates: &[Rate::Audio, Rate::Control],
        defaults: &[(r"density", Some(0.0))],
        num_outputs: None,
        extends: None,
        summary: None,
        doc: Some(r"Generates random impulses from -1 to +1."),
        signal_range: None,
        arg_docs: &[(r"density", r"average number of impulses per second.")],
    },
    UGenRegistryEntry {
        name: r"GrayNoise",
        rates: &[Rate::Audio],
        defaults: &[],
        num_outputs: None,
        extends: None,
        summary: Some(r"Random impulses from -1 to +1 given a density"),
        doc: Some(r"Creates a sequence of random impulses from -1 to +1. Generates noise which results from flipping random bits in a word. This type of noise has a high RMS level relative to its peak to peak level. The spectrum is emphasized towards lower frequencies. Useful for generating percussive sounds such as snares and hand claps. Also useful for simulating wind or sea effects, for producing breath effects in wind instrument timbres or for producing the typical trance leads."),
        signal_range: None,
        arg_docs: &[],
    },
    UGenRegistryEntry {
        name: r"Hasher",
        rates: &[Rate::Audio],
        defaults: &[(r"in", Some(0.0))],
        num_outputs: None,
        extends: None,
        summary: None,
        doc: Some(r"Returns a unique output value from zero to one for each input value according to a hash function. The same input value will always produce the same output value. The input need not be from zero to one."),
        signal_range: None,
        arg_docs: &[(r"in", r"input signal")],
    },
    UGenRegistryEntry {
        name: r"LFClipNoise",
        rates: &[Rate::Audio, Rate::Control],
        defaults: &[(r"freq", Some(500.0))],
        num_outputs: None,
        extends: None,
        summary: None,
        doc: Some(r"Randomly generates the values -1 or +1 at a rate given by the nearest integer division of the sample rate by the freq argument. It is probably pretty hard on your speakers!"),
        signal_range: None,
        arg_docs: &[(r"freq", r"approximate rate at which to generate random values.")],
    },
    UGenRegistryEntry {
        name: r"LFDClipNoise",
        rates: &[Rate::Audio, Rate::Control],
        defaults: &[(r"freq", Some(500.0))],
        num_outputs: None,
        extends: None,
        summary: None,
        doc: Some(r"Like lf-clip-noise, it generates the values -1 or +1 at a rate given by the freq argument, with two differences: * no time quantization * fast recovery from low freq values. (lf-clip-noise, as well as lf-noise0,1,2 quantize to the nearest integer division of the samplerate, and they poll the freq argument only when scheduled; thus they often seem to hang when freqs get very low). If you don't need very high or very low freqs, or use fixed freqs lf-noise0 is more efficient."),
        signal_range: None,
        arg_docs: &[(r"freq", r"rate at which to generate random values.")],
    },
    UGenRegistryEntry {
        name: r"LFDNoise0",
        rates: &[Rate::Audio, Rate::Control],
        defaults: &[(r"freq", Some(500.0))],
        num_outputs: None,
        extends: None,
        summary: None,
        doc: Some(r"Like lf-noise0, it generates random values between -1 and 1 at a rate given by the freq argument, with two differences: p * no time quantization * fast recovery from low freq values. (lf-noise0,1,2 quantize to the nearest integer division of the samplerate and they poll the freq argument only when scheduled, and thus seem to hang when freqs get very low). If you don't need very high or very low freqs, or use fixed freqs lf-noise0 is more efficient."),
        signal_range: None,
        arg_docs: &[(r"freq", r"rate at which to generate random values.")],
    },
    UGenRegistryEntry {
        name: r"LFDNoise1",
        rates: &[Rate::Audio, Rate::Control],
        defaults: &[(r"freq", Some(500.0))],
        num_outputs: None,
        extends: None,
        summary: None,
        doc: Some(r"Like lf-noise1, it generates linearly interpolated random values between -1 and 1 at a rate given by the freq argument, with two differences: * no time quantization * fast recovery from low freq values. (lf-noise0,1,2 quantize to the nearest integer division of the samplerate and they poll the freq argument only when scheduled, and thus seem to hang when freqs get very low). If you don't need very high or very low freqs, or use fixed freqs lf-noise1 is more efficient."),
        signal_range: None,
        arg_docs: &[(r"freq", r"rate at which to generate random values.")],
    },
    UGenRegistryEntry {
        name: r"LFDNoise3",
        rates: &[Rate::Audio, Rate::Control],
        defaults: &[(r"freq", Some(500.0))],
        num_outputs: None,
        extends: None,
        summary: None,
        doc: Some(r"Similar to lf-noise2, it generates polynomially interpolated random values between -1 and 1 at a rate given by the freq argument, with 3 differences: * no time quantization * fast recovery from low freq values * cubic instead of quadratic interpolation (lf-noise0,1,2 quantize to the nearest integer division of the samplerate and they poll the freq argument only when scheduled, and thus seem to hang when freqs get very low). If you don't need very high or very low freqs, or use fixed freqs lf-noise2 is more efficient."),
        signal_range: None,
        arg_docs: &[(r"freq", r"rate at which to generate random values.")],
    },
    UGenRegistryEntry {
        name: r"LFNoise0",
        rates: &[Rate::Audio, Rate::Control],
        defaults: &[(r"freq", Some(500.0))],
        num_outputs: None,
        extends: None,
        summary: None,
        doc: Some(r"Generates random values between -1 and 1 at a rate (the rate is not guaranteed but approximate)"),
        signal_range: None,
        arg_docs: &[(r"freq", r"approximate rate at which to generate random values.")],
    },
    UGenRegistryEntry {
        name: r"LFNoise1",
        rates: &[Rate::Audio, Rate::Control],
        defaults: &[(r"freq", Some(500.0))],
        num_outputs: None,
        extends: None,
        summary: None,
        doc: Some(r"Generates linearly interpolated random values between -1 and 1 at the supplied rate (the rate is not guaranteed but approximate)."),
        signal_range: None,
        arg_docs: &[(r"freq", r"approximate rate at which to generate random values.")],
    },
    UGenRegistryEntry {
        name: r"LFNoise2",
        rates: &[Rate::Audio, Rate::Control],
        defaults: &[(r"freq", Some(500.0))],
        num_outputs: None,
        extends: None,
        summary: None,
        doc: Some(r"Generates quadratically interpolated random values between -1 and 1 at the supplied rate (the rate is not guaranteed but approximate). Note: quadratic interpolation means that the noise values can occasionally extend beyond the normal range of +-1, if the freq varies in certain ways. If this is undesirable then you might like to clip2 the values or use a linearly-interpolating unit instead."),
        signal_range: None,
        arg_docs: &[(r"freq", r"approximate rate at which to generate random values.")],
    },
    UGenRegistryEntry {
        name: r"Logistic",
        rates: &[Rate::Audio],
        defaults: &[(r"chaosParam", Some(3.0)), (r"freq", Some(1000.0)), (r"init", Some(0.5))],
        num_outputs: None,
        extends: None,
        summary: None,
        doc: Some(r"A noise generator based on the logistic map: y = chaos-param * y * (1.0 - y) y will stay in the range of 0.0 to 1.0 for normal values of the chaos-param. This leads to a DC offset and may cause a pop when you stop the Synth. For output you might want to combine this UGen with a LeakDC or rescale around 0.0 via mul and add: see example below."),
        signal_range: None,
        arg_docs: &[(r"chaosParam", r"a parameter of the chaotic function with useful values from 0.0 to 4.0. Chaos occurs from 3.57 up. Don't use values outside this range if you don't want the UGen to blow up."), (r"freq", r"Frequency of calculation; if over the sampling rate, this is clamped to the sampling rate"), (r"init", r"Initial value of y (see equation below)")],
    },
    UGenRegistryEntry {
        name: r"MantissaMask",
        rates: &[Rate::Audio],
        defaults: &[(r"in", Some(0.0)), (r"bits", Some(3.0))],
        num_outputs: None,
        extends: None,
        summary: None,
        doc: Some(r"Masks off bits in the mantissa of the floating point sample value. This introduces a quantization noise, but is less severe than linearly quantizing the signal."),
        signal_range: None,
        arg_docs: &[(r"bits", r"the number of mantissa bits to preserve. a number from 0 to 23."), (r"in", r"input signal")],
    },
    UGenRegistryEntry {
        name: r"PinkNoise",
        rates: &[Rate::Audio, Rate::Control],
        defaults: &[],
        num_outputs: None,
        extends: None,
        summary: Some(r"Noise whose spectrum falls off in power by 3 dB per octave."),
        doc: Some(r"Noise that gives equal power over the span of each octave. Useful for generating percussive sounds such as snares and hand claps. Also useful for simulating wind or sea effects, for producing breath effects in wind instrument timbres or for producing the typical trance leads. This version gives 8 octaves of pink noise."),
        signal_range: None,
        arg_docs: &[],
    },
    UGenRegistryEntry {
        name: r"WhiteNoise",
        rates: &[Rate::Audio, Rate::Control],
        defaults: &[],
        num_outputs: None,
        extends: None,
        summary: Some(r"Noise whose spectrum has equal power at all frequencies."),
        doc: Some(r"Noise that contains equal amounts of energy at every frequency - comparable to radio static. Useful for generating percussive sounds such as snares and hand claps. Also useful for simulating wind or sea effects, for producing breath effects in wind instrument timbres or for producing the typical trance leads."),
        signal_range: None,
        arg_docs: &[],
    },
];
