// @generated — DO NOT EDIT.
// Regenerate with `node scripts/generate_ugens_rust.mjs`.

use crate::registry::UGenRegistryEntry;
use crate::Rate;

pub(crate) const UGENS: &[UGenRegistryEntry] = &[
    UGenRegistryEntry {
        name: r"Balance2",
        rates: &[Rate::Audio],
        defaults: &[(r"left", None), (r"right", None), (r"pos", Some(0.0)), (r"level", Some(1.0))],
        num_outputs: Some(2),
        extends: None,
        summary: None,
        doc: Some(r"Equal power panning balances two channels; by panning, you are favouring one or other channel in the mix, and the other loses power. The middle pan position (pos=0.0) corresponds to the original stereo mix; full left (pos of -1) is essentially just left channel playing, full right (pos of 1) just the right. The output of Balance2 remains a stereo signal."),
        signal_range: None,
        arg_docs: &[(r"left", r"channel 1 of input stereo signal"), (r"level", r"a control rate level input."), (r"pos", r"pan position, -1 is left, +1 is right"), (r"right", r"channel 2 of input stereo signal")],
    },
    UGenRegistryEntry {
        name: r"BiPanB2",
        rates: &[Rate::Audio, Rate::Control],
        defaults: &[(r"inA", None), (r"inB", None), (r"azimuth", None), (r"gain", Some(1.0))],
        num_outputs: Some(3),
        extends: None,
        summary: None,
        doc: Some(r"Encode a two channel signal to two dimensional ambisonic B-format. This puts two channels at opposite poles of a 2D ambisonic field. This is one way to map a stereo sound onto a soundfield. It is equivalent to: PanB2(inA, azimuth, gain) + PanB2(inB, azimuth + 1, gain)"),
        signal_range: None,
        arg_docs: &[(r"azimuth", r"position around the circle from -1 to +1. -1 is behind, -0.5 is left, 0 is forward, +0.5 is right, +1 is behind."), (r"gain", r"amplitude control"), (r"inA", r"input signal A"), (r"inB", r"input signal B")],
    },
    UGenRegistryEntry {
        name: r"DecodeB2",
        rates: &[Rate::Audio, Rate::Control],
        defaults: &[(r"numChannels", None), (r"w", None), (r"x", None), (r"y", None), (r"orientation", Some(0.5))],
        num_outputs: None,
        extends: None,
        summary: None,
        doc: Some(r"2D Ambisonic B-format decoder. Decode a two dimensional ambisonic B-format signal to a set of speakers in a regular polygon. The outputs will be in clockwise order. The position of the first speaker is either center or left of center."),
        signal_range: None,
        arg_docs: &[(r"numChannels", r"number of output speakers. Typically 4 to 8."), (r"orientation", r"Should be zero if the front is a vertex of the polygon. The first speaker will be directly in front. Should be 0.5 if the front bisects a side of the polygon. Then the first speaker will be the one left of center. Default is 0.5."), (r"w", r"B-format signal"), (r"x", r"B-format signal"), (r"y", r"B-format signal")],
    },
    UGenRegistryEntry {
        name: r"LinPan2",
        rates: &[Rate::Audio, Rate::Control],
        defaults: &[(r"in", None), (r"pos", Some(0.0)), (r"level", Some(1.0))],
        num_outputs: Some(2),
        extends: Some(r"Pan2"),
        summary: None,
        doc: Some(r"Two channel (stereo) linear panner. This one sounds more like the Rhodes tremolo than Pan2."),
        signal_range: None,
        arg_docs: &[(r"in", r"input signal"), (r"level", r"a control rate level input"), (r"pos", r"pan position, -1 is left, +1 is right")],
    },
    UGenRegistryEntry {
        name: r"LinXFade2",
        rates: &[Rate::Audio, Rate::Control],
        defaults: &[(r"inA", None), (r"inB", None), (r"pan", Some(0.0)), (r"level", Some(1.0))],
        num_outputs: None,
        extends: None,
        summary: None,
        doc: Some(r"Two channel linear crossfader."),
        signal_range: None,
        arg_docs: &[(r"inA", r"input signal A"), (r"inB", r"input signal B"), (r"level", r"a control rate level input"), (r"pan", r"cross fade position from -1 to +1")],
    },
    UGenRegistryEntry {
        name: r"Pan2",
        rates: &[Rate::Audio, Rate::Control],
        defaults: &[(r"in", None), (r"pos", Some(0.0)), (r"level", Some(1.0))],
        num_outputs: Some(2),
        extends: None,
        summary: None,
        doc: Some(r"Two channel (stereo) equal power panner."),
        signal_range: None,
        arg_docs: &[(r"in", r"input signal"), (r"level", r"a control rate level input"), (r"pos", r"pan position, -1 is left, +1 is right")],
    },
    UGenRegistryEntry {
        name: r"Pan4",
        rates: &[Rate::Audio, Rate::Control],
        defaults: &[(r"in", None), (r"xpos", Some(0.0)), (r"ypos", Some(0.0)), (r"level", Some(1.0))],
        num_outputs: Some(4),
        extends: None,
        summary: None,
        doc: Some(r"Four channel equal power panner. Outputs are in order LeftFront, RightFront, LeftBack, RightBack."),
        signal_range: None,
        arg_docs: &[(r"in", r"input signal"), (r"level", r"a control rate level input."), (r"xpos", r"x pan position from -1 to +1 (left to right)"), (r"ypos", r"y pan position from -1 to +1 (back to front)")],
    },
    UGenRegistryEntry {
        name: r"PanAz",
        rates: &[Rate::Audio, Rate::Control],
        defaults: &[(r"numChannels", None), (r"in", None), (r"pos", Some(0.0)), (r"level", Some(1.0)), (r"width", Some(2.0)), (r"orientation", Some(0.5))],
        num_outputs: None,
        extends: None,
        summary: None,
        doc: Some(r"Multichannel equal power panner."),
        signal_range: None,
        arg_docs: &[(r"in", r"input signal"), (r"level", r"a control rate level input."), (r"numChannels", r"number of output channels"), (r"orientation", r"Should be zero if the front is a vertex of the polygon. The first speaker will be directly in front. Should be 0.5 if the front bisects a side of the polygon. Then the first speaker will be the one left of center. Default is 0.5."), (r"pos", r"pan position. Channels are evenly spaced over a cyclic period of 2.0 with 0.0 equal to the position directly in front, 2.0/numChans a clockwise shift 1/numChans of the way around the ring, 4.0/numChans equal to a shift of 2/numChans, etc. Thus all channels will be cyclically panned through if a sawtooth wave from -1 to +1 is used to modulate the pos. N.B. Front may or may not correspond to a speaker depending on the setting of the orientation arg, see below."), (r"width", r"The width of the panning envelope. Nominally this is 2.0 which pans between pairs of adjacent speakers. Width values greater than two will spread the pan over greater numbers of speakers. Width values less than one will leave silent gaps between speakers.")],
    },
    UGenRegistryEntry {
        name: r"PanB",
        rates: &[Rate::Audio, Rate::Control],
        defaults: &[(r"in", None), (r"azimuth", Some(0.0)), (r"elevation", Some(0.0)), (r"gain", Some(1.0))],
        num_outputs: Some(4),
        extends: None,
        summary: None,
        doc: Some(r"Ambisonic B format panner. Output channels are in order W,X,Y,Z."),
        signal_range: None,
        arg_docs: &[(r"azimuth", r"in radians, -pi to +pi"), (r"elevation", r"in radians, -0.5pi to +0.5pi"), (r"gain", r"a control rate level input"), (r"in", r"input signal")],
    },
    UGenRegistryEntry {
        name: r"PanB2",
        rates: &[Rate::Audio, Rate::Control],
        defaults: &[(r"in", None), (r"azimuth", Some(0.0)), (r"gain", Some(1.0))],
        num_outputs: Some(3),
        extends: None,
        summary: None,
        doc: Some(r"Encode a mono signal to two dimensional ambisonic B-format."),
        signal_range: None,
        arg_docs: &[(r"azimuth", r"position around the circle from -1 to +1. -1 is behind, -0.5 is left, 0 is forward, +0.5 is right, +1 is behind."), (r"gain", r"amplitude control"), (r"in", r"input signal")],
    },
    UGenRegistryEntry {
        name: r"Rotate2",
        rates: &[Rate::Audio, Rate::Control],
        defaults: &[(r"x", None), (r"y", None), (r"pos", Some(0.0))],
        num_outputs: Some(2),
        extends: None,
        summary: None,
        doc: Some(r"Rotate2 can be used for rotating an ambisonic B-format sound field around an axis. Rotate2 does an equal power rotation so it also works well on stereo sounds. It takes two audio inputs (x, y) and an angle control (pos). It outputs two channels (x, y). It computes this: xout = cos(angle) * xin + sin(angle) * yin; yout = cos(angle) * yin - sin(angle) * xin; where angle = pos * pi, so that -1 becomes -pi and +1 becomes +pi. This allows you to use an LFSaw to do continuous rotation around a circle."),
        signal_range: None,
        arg_docs: &[(r"pos", r"angle to rotate around the circle from -1 to +1. -1 is 180 degrees, -0.5 is left, 0 is forward, +0.5 is right, +1 is behind."), (r"x", r"input signal"), (r"y", r"input signal")],
    },
    UGenRegistryEntry {
        name: r"XFade2",
        rates: &[Rate::Audio, Rate::Control],
        defaults: &[(r"inA", None), (r"inB", None), (r"pan", Some(0.0)), (r"level", Some(1.0))],
        num_outputs: None,
        extends: None,
        summary: None,
        doc: Some(r"Equal power two channel cross fade"),
        signal_range: None,
        arg_docs: &[(r"inA", r"input signal A"), (r"inB", r"input signal B"), (r"level", r"Output level - 0 being silent and 1 being original volume"), (r"pan", r"Pan between the two input signals with -1 being inA only and 1 being inB only with values between being a mix of the two.")],
    },
];
