// @generated — DO NOT EDIT.
// Regenerate with `node scripts/generate_ugens_rust.mjs`.

use crate::registry::UGenRegistryEntry;
use crate::Rate;

pub(crate) const UGENS: &[UGenRegistryEntry] = &[
    UGenRegistryEntry {
        name: r"Clip",
        rates: &[Rate::Audio, Rate::Control],
        defaults: &[(r"in", Some(0.0)), (r"lo", Some(0.0)), (r"hi", Some(1.0))],
        num_outputs: None,
        extends: None,
        summary: Some(r"Clip a signal outside given thresholds."),
        doc: Some(r"Clip a signal outside given thresholds. This differs from the ugen clip2 in that it allows one to set both low and high thresholds."),
        signal_range: None,
        arg_docs: &[(r"hi", r"High threshold of clipping. Must be greater then lo"), (r"in", r"The signal to be clipped"), (r"lo", r"Low threshold of clipping. Must be less then hi")],
    },
    UGenRegistryEntry {
        name: r"Fold",
        rates: &[Rate::Audio, Rate::Control],
        defaults: &[(r"in", Some(0.0)), (r"lo", Some(0.0)), (r"hi", Some(1.0))],
        num_outputs: None,
        extends: Some(r"InRange"),
        summary: Some(r"Fold a signal outside given thresholds."),
        doc: Some(r"Folds input wave to within the lo and hi thresholds. This differs from the ugen fold2 in that it allows one to set both low and high thresholds."),
        signal_range: None,
        arg_docs: &[(r"hi", r"high threshold"), (r"in", r"input signal"), (r"lo", r"low threshold")],
    },
    UGenRegistryEntry {
        name: r"Gate",
        rates: &[Rate::Audio, Rate::Control],
        defaults: &[(r"in", Some(0.0)), (r"trig", Some(0.0))],
        num_outputs: None,
        extends: Some(r"Latch"),
        summary: Some(r"Gate or hold"),
        doc: Some(r"Lets signal flow when trig is positive, otherwise holds last input value"),
        signal_range: None,
        arg_docs: &[(r"in", r"Input signal."), (r"trig", r"Trigger. Trigger can be any signal. A trigger happens when the signal changes from non-positive to positive.")],
    },
    UGenRegistryEntry {
        name: r"InRange",
        rates: &[Rate::Audio, Rate::Control],
        defaults: &[(r"in", Some(0.0)), (r"lo", Some(0.0)), (r"hi", Some(1.0))],
        num_outputs: None,
        extends: None,
        summary: Some(r"Tests if a signal is within a given range"),
        doc: Some(r"If in is >= lo and <= hi output 1.0, otherwise output 0.0. Output is initially zero."),
        signal_range: None,
        arg_docs: &[(r"hi", r"high threshold"), (r"in", r"input signal"), (r"lo", r"low threshold")],
    },
    UGenRegistryEntry {
        name: r"InRect",
        rates: &[Rate::Audio, Rate::Control],
        defaults: &[(r"x", Some(0.0)), (r"y", Some(0.0)), (r"left", None), (r"top", None), (r"right", None), (r"bottom", None)],
        num_outputs: None,
        extends: None,
        summary: Some(r"Test if a point is within a given rectangle."),
        doc: Some(r"Outputs one if the 2d coordinate of x,y input values falls inside a rectangle, else zero"),
        signal_range: None,
        arg_docs: &[(r"x", r"X component signal"), (r"y", r"Y component signal")],
    },
    UGenRegistryEntry {
        name: r"LastValue",
        rates: &[Rate::Audio, Rate::Control],
        defaults: &[(r"in", Some(0.0)), (r"diff", Some(0.01))],
        num_outputs: None,
        extends: None,
        summary: Some(r"Output the last value before the input changed"),
        doc: Some(r"Output the last value before the input changed by a threshold of diff"),
        signal_range: None,
        arg_docs: &[(r"diff", r"difference threshold"), (r"in", r"input signal")],
    },
    UGenRegistryEntry {
        name: r"Latch",
        rates: &[Rate::Audio, Rate::Control],
        defaults: &[(r"in", Some(0.0)), (r"trig", Some(0.0))],
        num_outputs: None,
        extends: None,
        summary: Some(r"Sample and hold"),
        doc: Some(r"Holds input signal value when triggered."),
        signal_range: None,
        arg_docs: &[(r"in", r"Input signal."), (r"trig", r"Trigger. Trigger can be any signal. A trigger happens when the signal changes from non-positive to positive.")],
    },
    UGenRegistryEntry {
        name: r"LeastChange",
        rates: &[Rate::Audio, Rate::Control],
        defaults: &[(r"a", Some(0.0)), (r"b", Some(0.0))],
        num_outputs: None,
        extends: Some(r"MostChange"),
        summary: Some(r"Output least changed"),
        doc: Some(r"output whichever signal changed the least"),
        signal_range: None,
        arg_docs: &[(r"a", r"first input"), (r"b", r"second input")],
    },
    UGenRegistryEntry {
        name: r"MostChange",
        rates: &[Rate::Audio, Rate::Control],
        defaults: &[(r"a", Some(0.0)), (r"b", Some(0.0))],
        num_outputs: None,
        extends: None,
        summary: Some(r"Output most changed"),
        doc: Some(r"output whichever signal changed the most"),
        signal_range: None,
        arg_docs: &[(r"a", r"first input"), (r"b", r"second input")],
    },
    UGenRegistryEntry {
        name: r"Peak",
        rates: &[Rate::Audio, Rate::Control],
        defaults: &[(r"trig", Some(0.0)), (r"reset", Some(0.0))],
        num_outputs: None,
        extends: Some(r"PulseCount"),
        summary: Some(r"Track peak signal amplitude"),
        doc: Some(r"Outputs the peak amplitude of the signal so far, a trigger resets to current value"),
        signal_range: None,
        arg_docs: &[(r"reset", r"Resets the counter to zero when triggered."), (r"trig", r"Trigger. Trigger can be any signal. A trigger happens when the signal changes from non-positive to positive.")],
    },
    UGenRegistryEntry {
        name: r"PeakFollower",
        rates: &[Rate::Audio, Rate::Control],
        defaults: &[(r"in", Some(0.0)), (r"decay", Some(0.999))],
        num_outputs: None,
        extends: None,
        summary: Some(r"Track peak signal amplitude"),
        doc: Some(r"Outputs the peak signal amplitude, falling with decay over time until reaching signal level"),
        signal_range: None,
        arg_docs: &[(r"decay", r"decay factor."), (r"in", r"input signal.")],
    },
    UGenRegistryEntry {
        name: r"Phasor",
        rates: &[Rate::Audio, Rate::Control],
        defaults: &[(r"trig", Some(0.0)), (r"rate", Some(1.0)), (r"start", Some(0.0)), (r"end", Some(1.0)), (r"resetPos", Some(0.0))],
        num_outputs: None,
        extends: None,
        summary: Some(r"Resettable linear ramp between two levels"),
        doc: Some(r"Phasor is a linear ramp between start and end values. When its trigger input crosses from non-positive to positive, Phasor's output will jump to its reset position. Upon reaching the end of its ramp Phasor will wrap back to its start. N.B. Since end is defined as the wrap point, its value is never actually output."),
        signal_range: None,
        arg_docs: &[(r"end", r"End point of the ramp"), (r"rate", r"The amount of change per sample i.e at a rate of 1 the value of each sample will be 1 greater than the preceding sample"), (r"resetPos", r"The value to jump to upon receiving a trigger"), (r"start", r"Starting point of the ramp"), (r"trig", r"When triggered, reset value to reset-pos (default: 0, phasor outputs start initially)")],
    },
    UGenRegistryEntry {
        name: r"Pitch",
        rates: &[Rate::Control],
        defaults: &[(r"in", None), (r"initFreq", Some(440.0)), (r"minFreq", Some(60.0)), (r"maxFreq", Some(4000.0)), (r"execFreq", Some(100.0)), (r"maxBinsPerOctave", Some(16.0)), (r"median", Some(1.0)), (r"ampThreshold", Some(0.01)), (r"peakThreshold", Some(0.5)), (r"downSample", Some(1.0)), (r"clar", Some(0.0))],
        num_outputs: Some(2),
        extends: None,
        summary: Some(r"Autocorrelation pitch follower"),
        doc: Some(r"This is a better pitch follower than zero-crossing, but more costly of CPU. For most purposes the default settings can be used and only in needs to be supplied. Pitch returns two values (via an Array of OutputProxys, a freq which is the pitch estimate and has-freq, which tells whether a pitch was found. Some vowels are still problematic, for instance a wide open mouth sound somewhere between a low pitched short 'a' sound as in 'sat', and long 'i' sound as in 'fire', contains enough overtone energy to confuse the algorithm. None of these settings are time variable."),
        signal_range: None,
        arg_docs: &[(r"ampThreshold", r"Minum peak to peak amplitude of input signal before pitch estimation is performed."), (r"clar", r"Clarity measurement (purity of the pitched signal) if greater than 0."), (r"downSample", r"Down sample the input signal by an integer factor. Helps reduce CPU overthead. Also reduces pitch resolution."), (r"execFreq", r"The target rate to periodically execute in cps. Clipped between min-freq and max-freq."), (r"in", r"Input signal"), (r"initFreq", r"Value of output pitch until first pitch detected."), (r"maxBinsPerOctave", r"Number of lags for course search. A larger value will cause the coarse search to take longer, a smaller value will cause the subsequent fine search to take longer."), (r"maxFreq", r"Maximum frequency of execution."), (r"median", r"Median filter value of length median on the output estimation. Helps eliminate outliers and jitter. Value of 1 means no filter."), (r"minFreq", r"Minimum frequency of execution."), (r"peakThreshold", r"Finds the next peak that is above peak-threshold times the amplitude of the peak at lag zero. A value of 0.5 does a pretty good job of eliminating overtones.")],
    },
    UGenRegistryEntry {
        name: r"PulseCount",
        rates: &[Rate::Audio, Rate::Control],
        defaults: &[(r"trig", Some(0.0)), (r"reset", Some(0.0))],
        num_outputs: None,
        extends: None,
        summary: Some(r"Pulse counter"),
        doc: Some(r"Each input trigger increments a counter value that is output."),
        signal_range: None,
        arg_docs: &[(r"reset", r"Resets the counter to zero when triggered."), (r"trig", r"Trigger. Trigger can be any signal. A trigger happens when the signal changes from non-positive to positive.")],
    },
    UGenRegistryEntry {
        name: r"PulseDivider",
        rates: &[Rate::Audio, Rate::Control],
        defaults: &[(r"trig", Some(0.0)), (r"div", Some(2.0)), (r"startVal", Some(0.0))],
        num_outputs: None,
        extends: None,
        summary: Some(r"Pulse divider"),
        doc: Some(r"Outputs a trigger every div input triggers"),
        signal_range: None,
        arg_docs: &[(r"div", r"Number of pulses to divide by."), (r"startVal", r"Starting value for the trigger count. This lets you start somewhere in the middle of a count, or if startCount is negative it adds that many counts to the first time the output is triggers."), (r"trig", r"Trigger. Trigger can be any signal. A trigger happens when the signal changes from non-positive to positive.")],
    },
    UGenRegistryEntry {
        name: r"RunningMax",
        rates: &[Rate::Audio, Rate::Control],
        defaults: &[(r"in", Some(0.0)), (r"trig", Some(0.0))],
        num_outputs: None,
        extends: Some(r"Latch"),
        summary: Some(r"Track maximum level"),
        doc: Some(r"Outputs the maximum value received at the input. When triggered, the maximum output value is reset to the current value."),
        signal_range: None,
        arg_docs: &[(r"in", r"Input signal."), (r"trig", r"Trigger. Trigger can be any signal. A trigger happens when the signal changes from non-positive to positive.")],
    },
    UGenRegistryEntry {
        name: r"RunningMin",
        rates: &[Rate::Audio, Rate::Control],
        defaults: &[(r"in", Some(0.0)), (r"trig", Some(0.0))],
        num_outputs: None,
        extends: Some(r"Latch"),
        summary: Some(r"Track minimum level"),
        doc: Some(r"Outputs the minimum value received at the input. When triggered, the minimum output value is reset to the current value."),
        signal_range: None,
        arg_docs: &[(r"in", r"Input signal."), (r"trig", r"Trigger. Trigger can be any signal. A trigger happens when the signal changes from non-positive to positive.")],
    },
    UGenRegistryEntry {
        name: r"Schmidt",
        rates: &[Rate::Audio, Rate::Control],
        defaults: &[(r"in", Some(0.0)), (r"lo", Some(0.0)), (r"hi", Some(1.0))],
        num_outputs: None,
        extends: Some(r"InRange"),
        summary: Some(r"Schmidt trigger"),
        doc: Some(r"Outout one when signal greater than high, and zero when lower than low."),
        signal_range: None,
        arg_docs: &[(r"hi", r"high threshold"), (r"in", r"input signal"), (r"lo", r"low threshold")],
    },
    UGenRegistryEntry {
        name: r"SendReply",
        rates: &[Rate::Audio, Rate::Control],
        defaults: &[(r"trig", Some(0.0)), (r"cmdName", None), (r"values", Some(0.0)), (r"replyId", Some(-1.0))],
        num_outputs: Some(0),
        extends: None,
        summary: Some(r"Send information via OSC to Overtone"),
        doc: Some(r#"Send an array of values from the server via an message. The OSC message is formed with cmd-name as the path, followed by two compulsary args: node-id (the id of the node that sent the message) and reply-id (the value specified in the params). These args are then followed by the list of values specified in the params. For example, if the ugen is used as follows: (send-reply tr \"/foobar\" [1 2 3] 42) When the trig tr triggers, Overtone will receive an event that looks like the following (where 32 represents the node-id of the synth that sent the message): {:path \"/foobar\"#),
        signal_range: None,
        arg_docs: &[(r"cmdName", r"A string or symbol, as a message name."), (r"replyId", r"Integer id (similar to that used by send-trig)"), (r"trig", r"Input trigger signal"), (r"values", r"Array of ugens, or valid ugen inputs")],
    },
    UGenRegistryEntry {
        name: r"SendTrig",
        rates: &[Rate::Audio, Rate::Control],
        defaults: &[(r"in", Some(0.0)), (r"id", Some(0.0)), (r"value", Some(0.0))],
        num_outputs: Some(0),
        extends: None,
        summary: Some(r"Send a /tr OSC message to Overtone"),
        doc: Some(r#"On receiving a trigger sends a :trigger event with id and value. This command is the mechanism that synths can use to trigger events in clients. The trigger message sent back to the client is this: int - node ID int - trigger ID float - trigger value This is then presented as an event on the event-stream which is a map containing the key :path with the string \"/tr\" and the key :args containing a sequence of the values in the above order. i.e. {:path /tr, :args (34 3 123.0)} See on-trigger, on-latest-trigger and on-sync-trigger for registering handlers for trigger events."#),
        signal_range: None,
        arg_docs: &[(r"id", r"an integer that will be passed with the trigger message. This is useful if you have more than one send-trig in a synth design. Consider using trig-id to genearate a unique id."), (r"in", r"input trigger signal"), (r"value", r"A ugen or float that will be polled at the time of trigger, and its value passed with the trigger message")],
    },
    UGenRegistryEntry {
        name: r"SetResetFF",
        rates: &[Rate::Audio, Rate::Control],
        defaults: &[(r"trig", Some(0.0)), (r"reset", Some(0.0))],
        num_outputs: None,
        extends: Some(r"PulseCount"),
        summary: Some(r"Set-reset flip flop"),
        doc: Some(r"When a trigger is received the output is set to 1.0 Subsequent triggers have no effect When a trigger is received in the reset input, the output is set back to 0.0 One use of this is to have some precipitating event cause something to happen until you reset it."),
        signal_range: None,
        arg_docs: &[(r"reset", r"Resets the counter to zero when triggered."), (r"trig", r"Trigger. Trigger can be any signal. A trigger happens when the signal changes from non-positive to positive.")],
    },
    UGenRegistryEntry {
        name: r"Stepper",
        rates: &[Rate::Audio, Rate::Control],
        defaults: &[(r"trig", Some(0.0)), (r"reset", Some(0.0)), (r"min", Some(0.0)), (r"max", Some(7.0)), (r"step", Some(1.0)), (r"resetval", Some(1.0))],
        num_outputs: None,
        extends: None,
        summary: Some(r"Pulse counter"),
        doc: Some(r"Triggers increment a counter which is output as a signal. The counter loops around from max to min by step increments"),
        signal_range: None,
        arg_docs: &[(r"max", r"maximum value of the counter."), (r"min", r"minimum value of the counter."), (r"reset", r"Resets the counter to resetval when triggered."), (r"resetval", r"value to which the counter is reset when it receives a reset trigger."), (r"step", r"step value each trigger. May be negative."), (r"trig", r"Trigger. Trigger can be any signal. A trigger happens when the signal changes from non-positive to positive.")],
    },
    UGenRegistryEntry {
        name: r"Sweep",
        rates: &[Rate::Audio, Rate::Control],
        defaults: &[(r"trig", Some(0.0)), (r"rate", Some(1.0))],
        num_outputs: None,
        extends: None,
        summary: Some(r"Triggered linear ramp"),
        doc: Some(r"outputs a linear increasing signal by rate/second when trig input crosses from non-positive to positive"),
        signal_range: None,
        arg_docs: &[(r"rate", r"rate in seconds"), (r"trig", r"trigger input")],
    },
    UGenRegistryEntry {
        name: r"TDelay",
        rates: &[Rate::Audio, Rate::Control],
        defaults: &[(r"trig", Some(0.0)), (r"dur", Some(0.1))],
        num_outputs: None,
        extends: None,
        summary: Some(r"Trigger delay"),
        doc: Some(r"Delays an input trigger by dur, ignoring other triggers in the meantime"),
        signal_range: None,
        arg_docs: &[(r"dur", r"delay time in seconds."), (r"trig", r"input trigger signal.")],
    },
    UGenRegistryEntry {
        name: r"TWindex",
        rates: &[Rate::Audio, Rate::Control],
        defaults: &[(r"trig", None), (r"channelsArray", None), (r"normalize", Some(0.0))],
        num_outputs: None,
        extends: None,
        summary: Some(r"Triggered window"),
        doc: Some(r"When triggered, returns a random index value based on array as a list of probabilities. By default the list of probabilities should sum to 1.0, when the normalize flag is set to 1, the values get normalized by the ugen (less efficient)."),
        signal_range: None,
        arg_docs: &[(r"channelsArray", r"list of probabilities"), (r"normalize", r"normalise flag - 0 off, 1 on"), (r"trig", r"Trigger - can be any signal. A trigger happens when the signal changes from non-positive to positive.")],
    },
    UGenRegistryEntry {
        name: r"Timer",
        rates: &[Rate::Audio, Rate::Control],
        defaults: &[(r"trig", Some(0.0))],
        num_outputs: None,
        extends: None,
        summary: Some(r"Trigger timer"),
        doc: Some(r"Outputs time since last trigger"),
        signal_range: None,
        arg_docs: &[(r"trig", r"trigger input")],
    },
    UGenRegistryEntry {
        name: r"ToggleFF",
        rates: &[Rate::Audio, Rate::Control],
        defaults: &[(r"trig", Some(0.0))],
        num_outputs: None,
        extends: None,
        summary: Some(r"Toggle flip flop"),
        doc: Some(r"Flip-flops between zero and one each trigger"),
        signal_range: None,
        arg_docs: &[(r"trig", r"trigger input")],
    },
    UGenRegistryEntry {
        name: r"Trapezoid",
        rates: &[Rate::Audio, Rate::Control],
        defaults: &[(r"in", Some(0.0)), (r"a", Some(0.2)), (r"b", Some(0.4)), (r"c", Some(0.6)), (r"d", Some(0.8))],
        num_outputs: None,
        extends: None,
        summary: None,
        doc: None,
        signal_range: None,
        arg_docs: &[],
    },
    UGenRegistryEntry {
        name: r"Trig",
        rates: &[Rate::Audio, Rate::Control],
        defaults: &[(r"trig", Some(0.0)), (r"dur", Some(0.1))],
        num_outputs: None,
        extends: Some(r"Trig1"),
        summary: Some(r"Timed trigger"),
        doc: Some(r"When a nonpositive to positive transition occurs at the input, Trig outputs the level of the triggering input for the specified duration, otherwise it outputs zero."),
        signal_range: None,
        arg_docs: &[(r"dur", r"duration of the trigger output in seconds."), (r"trig", r"trigger. Trigger can be any signal. A trigger happens when the signal changes from non-positive to positive.")],
    },
    UGenRegistryEntry {
        name: r"Trig1",
        rates: &[Rate::Audio, Rate::Control],
        defaults: &[(r"trig", Some(0.0)), (r"dur", Some(0.1))],
        num_outputs: None,
        extends: None,
        summary: Some(r"Timed trigger"),
        doc: Some(r"Outputs one for dur seconds whenever the input goes from negative to positive, otherwise outputs 0."),
        signal_range: None,
        arg_docs: &[(r"dur", r"duration of the trigger output in seconds."), (r"trig", r"trigger. Trigger can be any signal. A trigger happens when the signal changes from non-positive to positive.")],
    },
    UGenRegistryEntry {
        name: r"Wrap",
        rates: &[Rate::Audio, Rate::Control],
        defaults: &[(r"in", Some(0.0)), (r"lo", Some(0.0)), (r"hi", Some(1.0))],
        num_outputs: None,
        extends: Some(r"InRange"),
        summary: Some(r"Wrap a signal outside given thresholds."),
        doc: Some(r"Wraps input wave to the low and high thresholds. This differs from the ugen wrap2 in that it allows one to set both low and high thresholds."),
        signal_range: None,
        arg_docs: &[(r"hi", r"high threshold"), (r"in", r"input signal"), (r"lo", r"low threshold")],
    },
    UGenRegistryEntry {
        name: r"ZeroCrossing",
        rates: &[Rate::Audio, Rate::Control],
        defaults: &[(r"in", Some(0.0))],
        num_outputs: None,
        extends: None,
        summary: Some(r"Zero crossing frequency follower"),
        doc: Some(r"Outputs a frequency based upon the distance between interceptions of the X axis. The X intercepts are determined via linear interpolation so this gives better than just integer wavelength resolution. This is a very crude pitch follower, but can be useful in some situations."),
        signal_range: None,
        arg_docs: &[(r"in", r"input signal")],
    },
];
