// @vitest-environment node
//
// Source-graph guard for the icon font wiring. The font ships as separate /assets
// woff2 referenced by the foundation's head <link>, and vite-plugin-lit-css returns
// empty .css under vitest — so we can't assert on a compiled CSSResult here. Instead
// we pin the IMPORT GRAPH the build relies on:
//   - the head foundation entry (index.scss) pulls in icons.scss, so the head <link>
//     carries the three Phosphor @font-face rules (document-wide registration);
//   - icons.scss references ONLY the woff2 files — never the stock style.css imports,
//     whose woff/ttf/svg fallbacks (~9.4 MB) and per-icon `.ph-*` rule sheets
//     (~100 KB/weight, duplicated into the shadow CSSResult = boot JS) this model
//     exists to avoid; glyphs are addressed by codepoint instead (sc-icon/codepoints.ts,
//     generated by scripts/generate-icon-codepoints.mjs).
// "The glyph actually paints" is covered by the headless render check, not here.

import { describe, expect, it } from "vitest";
import { readFileSync } from "node:fs";
import { resolve } from "node:path";

// vitest runs from the package dir.
const read = (p: string) => readFileSync(resolve(process.cwd(), p), "utf8");

describe("foundation icon font (import graph)", () => {
  it("the head foundation entry pulls in the icon font", () => {
    const index = read("src/foundations/index.scss");
    expect(index).toMatch(/@use\s+["']\.\/icons["']/);
  });

  it("icons.scss registers the three weights from their woff2 only", () => {
    const icons = read("src/foundations/icons.scss");
    for (const file of ["Phosphor.woff2", "Phosphor-Fill.woff2", "Phosphor-Duotone.woff2"]) {
      expect(icons).toContain(file);
    }
    // No stock style.css imports (glyph-rule + multi-format bloat)…
    expect(icons).not.toMatch(/@import/);
    // …and no dead font formats.
    expect(icons).not.toMatch(/\.(ttf|woff|svg)\b(?!2)/);
  });

  it("the generated codepoint maps cover every weight", () => {
    const codepoints = read("src/components/sc-icon/codepoints.ts");
    for (const map of ["REGULAR", "FILL", "DUOTONE"]) {
      expect(codepoints).toContain(`export const ${map}`);
    }
    expect(codepoints).toContain('"play"');
  });

  it("the font-free shadow base does NOT pull in the icon font", () => {
    // The fonts must never enter a shadow CSSResult — the shadow base components adopt
    // is reset.scss, which is fonts/icons-free.
    const reset = read("src/foundations/reset.scss");
    expect(reset).not.toContain("icons");
    expect(reset).not.toContain("@phosphor");
  });
});
