//! Emits the UGen registry + typed-builder surfaces from the committed
//! spec at `assets/specs/ugens.json` (repo root):
//!
//! - `OUT_DIR/ugen_specs.rs` — plain `UGenRegistryEntry` const slices per
//!   category + `ALL_SLICES` (pure data, no macro).
//! - `OUT_DIR/ugen_builders.rs` — one `sc_ugens!` invocation (struct +
//!   rate factories + setters + `build`, see `src/ugens_macro.rs`).
//! - `OUT_DIR/ugen_builders_wasm.rs` — one `sc_ugens_wasm!` invocation
//!   (one exported fn per ugen × rate) + the generated TypeScript
//!   custom section.
//!
//! All name computation lives HERE (snake/camel conversion, raw-ident
//! keyword escaping) — the macros only assemble tokens.

use std::fmt::Write as _;
use std::path::Path;

use sc_spec_types::{NumOutputs, UgenArgKind, UgenSpec};

const RUST_KEYWORDS: &[&str] = &[
    "as", "box", "break", "const", "continue", "crate", "dyn", "else", "enum", "extern", "false",
    "fn", "for", "if", "impl", "in", "let", "loop", "match", "mod", "move", "mut", "pub", "ref",
    "return", "static", "struct", "trait", "true", "type", "unsafe", "use", "where", "while",
];

fn main() {
    let manifest = std::env::var("CARGO_MANIFEST_DIR").unwrap();
    let specs_dir = Path::new(&manifest).join("../../../assets/specs");
    println!(
        "cargo:rerun-if-changed={}",
        specs_dir.join("ugens.json").display()
    );
    println!(
        "cargo:rerun-if-changed={}",
        specs_dir.join("envs.json").display()
    );

    let spec = sc_spec_types::load_ugens(&specs_dir.join("ugens.json"))
        .unwrap_or_else(|e| panic!("invalid ugens spec: {e}"));
    let envs = sc_spec_types::load_envs(&specs_dir.join("envs.json"))
        .unwrap_or_else(|e| panic!("invalid envs spec: {e}"));

    let out_dir = std::env::var("OUT_DIR").unwrap();
    let out = Path::new(&out_dir);
    std::fs::write(out.join("ugen_specs.rs"), render_specs(&spec)).unwrap();
    std::fs::write(out.join("ugen_builders.rs"), render_builders(&spec)).unwrap();
    std::fs::write(out.join("ugen_builders_wasm.rs"), render_wasm(&spec)).unwrap();
    std::fs::write(out.join("env_shapes.rs"), render_envs(&envs)).unwrap();
}

const HEADER: &str = "// @generated by build.rs from assets/specs/ugens.json — do not edit.\n\n";

// ── name conversion (ports of the old generator's converters — the wasm
//    js-name surface must stay byte-identical) ──────────────────────────

fn camel_to_snake(s: &str) -> String {
    // ([a-z0-9])([A-Z]) → $1_$2 ; ([A-Z]+)([A-Z][a-z]) → $1_$2 ; lowercase
    let mut pass1 = String::new();
    let chars: Vec<char> = s.chars().collect();
    for i in 0..chars.len() {
        pass1.push(chars[i]);
        if i + 1 < chars.len()
            && (chars[i].is_ascii_lowercase() || chars[i].is_ascii_digit())
            && chars[i + 1].is_ascii_uppercase()
        {
            pass1.push('_');
        }
    }
    let chars: Vec<char> = pass1.chars().collect();
    let mut pass2 = String::new();
    for i in 0..chars.len() {
        pass2.push(chars[i]);
        if i + 2 < chars.len()
            && chars[i].is_ascii_uppercase()
            && chars[i + 1].is_ascii_uppercase()
            && chars[i + 2].is_ascii_lowercase()
        {
            pass2.push('_');
        }
    }
    pass2.to_lowercase()
}

fn snake_to_camel(s: &str) -> String {
    let mut out = String::new();
    let mut upper = false;
    for c in s.chars() {
        if c == '_' {
            upper = true;
        } else if upper {
            out.push(c.to_ascii_uppercase());
            upper = false;
        } else {
            out.push(c);
        }
    }
    out
}

/// Rust field ident for a spec arg name: snake case, `r#`-escaped when it
/// collides with a keyword.
fn field_ident(name: &str) -> String {
    let snake = camel_to_snake(name);
    if RUST_KEYWORDS.contains(&snake.as_str()) {
        format!("r#{snake}")
    } else {
        snake
    }
}

/// JS/TS object key for a spec arg name (matches the old generator:
/// snake, then camel — `sendID` → `sendId`).
fn js_key(name: &str) -> String {
    snake_to_camel(&camel_to_snake(name))
}

fn doc_attrs(out: &mut String, indent: &str, text: &str) {
    for line in text.lines() {
        writeln!(
            out,
            "{indent}#[doc = \"{}\"]",
            line.replace('\\', "\\\\").replace('"', "\\\"")
        )
        .unwrap();
    }
}

fn f32_lit(v: f64) -> String {
    sc_spec_types::f32_literal(v)
}

// ── ugen_specs.rs ───────────────────────────────────────────────────────

fn render_specs(spec: &sc_spec_types::UgensSpec) -> String {
    let mut out = String::from(HEADER);
    for cat in &spec.categories {
        // lookup_ugen binary-searches each slice by name — emit sorted
        // regardless of spec order so a hand-edited insert can't silently
        // break the lookup.
        let mut ugens: Vec<_> = cat.ugens.iter().collect();
        ugens.sort_by(|a, b| a.name.cmp(&b.name));
        writeln!(
            out,
            "const {}: &[UGenRegistryEntry] = &[",
            cat.name.to_uppercase()
        )
        .unwrap();
        for u in ugens {
            out.push_str("    UGenRegistryEntry {\n");
            writeln!(out, "        name: r\"{}\",", u.name).unwrap();
            let rates: Vec<String> = u
                .rates
                .iter()
                .map(|r| format!("Rate::{}", r.rate_variant()))
                .collect();
            writeln!(out, "        rates: &[{}],", rates.join(", ")).unwrap();
            let defaults: Vec<String> = u
                .args
                .iter()
                .map(|a| {
                    let d = match a.default {
                        Some(v) => format!("Some({})", f32_lit(v)),
                        None => "None".to_string(),
                    };
                    format!("(r\"{}\", {d})", a.name)
                })
                .collect();
            writeln!(out, "        defaults: &[{}],", defaults.join(", ")).unwrap();
            let num_outputs = match &u.num_outputs {
                Some(NumOutputs::Fixed(n)) => format!("Some({n})"),
                // `fromArg` counts are runtime builder state; the registry
                // (like today) records no static count for them.
                Some(NumOutputs::FromArg { .. }) | None => "None".to_string(),
            };
            writeln!(out, "        num_outputs: {num_outputs},").unwrap();
            writeln!(out, "        extends: {},", opt_str(&u.extends)).unwrap();
            writeln!(out, "        summary: {},", opt_str(&u.summary)).unwrap();
            writeln!(out, "        doc: {},", opt_str(&u.doc)).unwrap();
            writeln!(out, "        signal_range: {},", opt_str(&u.signal_range)).unwrap();
            let arg_docs: Vec<String> = u
                .args
                .iter()
                .filter_map(|a| {
                    a.doc
                        .as_ref()
                        .map(|d| format!("(r\"{}\", {})", a.name, raw_str(d)))
                })
                .collect();
            writeln!(out, "        arg_docs: &[{}],", arg_docs.join(", ")).unwrap();
            out.push_str("    },\n");
        }
        out.push_str("];\n\n");
    }
    out.push_str("pub(crate) const ALL_SLICES: &[(&str, &[UGenRegistryEntry])] = &[\n");
    for cat in &spec.categories {
        writeln!(out, "    (\"{}\", {}),", cat.name, cat.name.to_uppercase()).unwrap();
    }
    out.push_str("];\n");
    out
}

fn opt_str(v: &Option<String>) -> String {
    match v {
        Some(s) => format!("Some({})", raw_str(s)),
        None => "None".to_string(),
    }
}

/// A Rust raw-string literal for arbitrary doc text (picks enough `#`s).
fn raw_str(s: &str) -> String {
    let mut hashes = 0;
    while s.contains(&format!("\"{}", "#".repeat(hashes))) {
        hashes += 1;
    }
    let h = "#".repeat(hashes);
    format!("r{h}\"{s}\"{h}")
}

// ── shared builder-shape helpers ────────────────────────────────────────

struct BuilderField {
    ident: String,
    js: String,
    kind: UgenArgKind,
    doc: Option<String>,
    init: String,
}

fn builder_fields(u: &UgenSpec) -> Vec<BuilderField> {
    u.args
        .iter()
        .map(|a| {
            let init = match a.kind {
                UgenArgKind::Input => {
                    format!("UGenInput::Constant({})", f32_lit(a.default.unwrap_or(0.0)))
                }
                UgenArgKind::InputArray => "Vec::new()".to_string(),
                UgenArgKind::U32 => format!("{}u32", a.default.unwrap_or(1.0) as u32),
            };
            BuilderField {
                ident: field_ident(&a.name),
                js: js_key(&a.name),
                kind: a.kind,
                doc: a.doc.clone(),
                init,
            }
        })
        .collect()
}

fn kind_kw(kind: UgenArgKind) -> &'static str {
    match kind {
        UgenArgKind::Input => "input",
        UgenArgKind::InputArray => "array",
        UgenArgKind::U32 => "u32",
    }
}

fn field_ty(kind: UgenArgKind) -> &'static str {
    match kind {
        UgenArgKind::Input => "UGenInput",
        UgenArgKind::InputArray => "Vec<UGenInput>",
        UgenArgKind::U32 => "u32",
    }
}

/// The `build()` push list, in wire order: `buildOrder` when the spec
/// pins one, else the pushed args in declaration order.
fn push_list(u: &UgenSpec) -> Vec<(UgenArgKind, String)> {
    let pushed = |name: &str| {
        let a = u
            .args
            .iter()
            .find(|a| a.name == name)
            .unwrap_or_else(|| panic!("{}: buildOrder names unknown arg {name}", u.name));
        (a.kind, field_ident(&a.name))
    };
    match &u.build_order {
        Some(order) => order.iter().map(|n| pushed(n)).collect(),
        None => u
            .args
            .iter()
            .filter(|a| a.kind != UgenArgKind::U32)
            .map(|a| (a.kind, field_ident(&a.name)))
            .collect(),
    }
}

fn outputs_tokens(u: &UgenSpec) -> String {
    match &u.num_outputs {
        Some(NumOutputs::Fixed(n)) => format!("fixed {n}"),
        Some(NumOutputs::FromArg { from_arg }) => format!("from {}", field_ident(from_arg)),
        None => "fixed 1".to_string(),
    }
}

fn has_builder(u: &UgenSpec) -> bool {
    !u.no_builder && !u.rates.is_empty()
}

// ── ugen_builders.rs ────────────────────────────────────────────────────

fn render_builders(spec: &sc_spec_types::UgensSpec) -> String {
    let mut out = String::from(HEADER);
    out.push_str("sc_ugens! {\n");
    for cat in &spec.categories {
        for u in cat.ugens.iter().filter(|u| has_builder(u)) {
            if let Some(summary) = &u.summary {
                doc_attrs(&mut out, "    ", summary);
            }
            if let Some(doc) = &u.doc {
                if u.summary.is_some() {
                    out.push_str("    #[doc = \"\"]\n");
                }
                doc_attrs(&mut out, "    ", doc);
            }
            writeln!(out, "    {} class r\"{}\" {{", u.name, u.name).unwrap();
            let rates: Vec<String> = u
                .rates
                .iter()
                .map(|r| format!("({}, {})", r.suffix(), r.rate_variant()))
                .collect();
            writeln!(out, "        rates [ {} ]", rates.join(", ")).unwrap();
            out.push_str("        fields [\n");
            for f in builder_fields(u) {
                if let Some(doc) = &f.doc {
                    doc_attrs(&mut out, "            ", doc);
                }
                writeln!(
                    out,
                    "            {} {}: {} = {},",
                    kind_kw(f.kind),
                    f.ident,
                    field_ty(f.kind),
                    f.init
                )
                .unwrap();
            }
            out.push_str("        ]\n");
            writeln!(out, "        outputs ( {} )", outputs_tokens(u)).unwrap();
            let pushes: Vec<String> = push_list(u)
                .iter()
                .map(|(k, f)| format!("({} {f})", kind_kw(*k)))
                .collect();
            writeln!(out, "        push [ {} ]", pushes.join(", ")).unwrap();
            out.push_str("    }\n");
        }
    }
    out.push_str("}\n");
    out
}

// ── env_shapes.rs ───────────────────────────────────────────────────────

fn render_envs(envs: &sc_spec_types::EnvsSpec) -> String {
    let mut out = String::from(HEADER);
    writeln!(
        out,
        "pub static ENV_SHAPES: [EnvShapeEntry; {}] = [",
        envs.shapes.len()
    )
    .unwrap();
    for shape in &envs.shapes {
        out.push_str("    EnvShapeEntry {\n");
        writeln!(out, "        name: \"{}\",", shape.name).unwrap();
        writeln!(
            out,
            "        release_node: {},",
            opt_i32(shape.release_node)
        )
        .unwrap();
        writeln!(out, "        loop_node: {},", opt_i32(shape.loop_node)).unwrap();
        out.push_str("        args: &[\n");
        for a in &shape.args {
            let call = if a.array {
                format!("aarg(\"{}\", {})", a.name, a.modulatable)
            } else if a.modulatable {
                format!(
                    "marg(\"{}\", {})",
                    a.name,
                    sc_spec_types::f32_literal(a.default)
                )
            } else {
                format!(
                    "arg(\"{}\", {})",
                    a.name,
                    sc_spec_types::f32_literal(a.default)
                )
            };
            writeln!(out, "            {call},").unwrap();
        }
        out.push_str("        ],\n    },\n");
    }
    out.push_str("];\n");
    out
}

fn opt_i32(v: Option<i32>) -> String {
    match v {
        Some(n) => format!("Some({n})"),
        None => "None".to_string(),
    }
}

// ── ugen_builders_wasm.rs ───────────────────────────────────────────────

fn render_wasm(spec: &sc_spec_types::UgensSpec) -> String {
    let mut out = String::from(HEADER);
    let mut ts = String::new();
    out.push_str("sc_ugens_wasm! {\n");
    for cat in &spec.categories {
        for u in cat.ugens.iter().filter(|u| has_builder(u)) {
            let fields = builder_fields(u);
            writeln!(out, "    class {} \"{}\" :: {} {{", u.name, u.name, u.name).unwrap();
            for rate in &u.rates {
                writeln!(out, "        {} {{", rate.suffix()).unwrap();
                for f in &fields {
                    writeln!(
                        out,
                        "            {} {} \"{}\",",
                        kind_kw(f.kind),
                        f.ident,
                        f.js
                    )
                    .unwrap();
                }
                out.push_str("        }\n");
            }
            out.push_str("    }\n");

            // TS: one class per UGen with a static method per rate —
            // `SinOsc.ar({ freq })`, matching SuperCollider; the def is
            // ambient (the enclosing `new SynthDef(name, () => …)` build).
            let args_ty = if fields.is_empty() {
                "args?: Record<string, never>".to_string()
            } else {
                let keys: Vec<String> = fields
                    .iter()
                    .map(|f| {
                        let ty = match f.kind {
                            UgenArgKind::Input => "UGenInputLike",
                            UgenArgKind::InputArray => "UGenInputLike[]",
                            UgenArgKind::U32 => "number",
                        };
                        format!("{}?: {}", f.js, ty)
                    })
                    .collect();
                format!("args?: {{ {} }}", keys.join("; "))
            };
            writeln!(ts, "export class {} {{", u.name).unwrap();
            writeln!(ts, "  private constructor();").unwrap();
            for rate in &u.rates {
                writeln!(ts, "  static {}({args_ty}): UGenInput;", rate.suffix()).unwrap();
            }
            ts.push_str("}\n");
        }
    }
    out.push_str("}\n\n");
    out.push_str("#[wasm_bindgen(typescript_custom_section)]\n");
    writeln!(out, "const TS_BUILDERS: &'static str = {};", raw_str(&ts)).unwrap();
    out
}
