use serde::Serialize;

use crate::{specs, Rate};

/// One UGen's registry entry — every field preserved verbatim from the
/// curated JSON specs in `src/assets/ugens/*.json`. All payloads are
/// `'static` references, so entries are `const`-constructible and live
/// directly in the binary.
///
/// Regenerated by `scripts/generate_ugens_rust.mjs` into the private
/// `ugens` sibling module (one `.rs` per JSON category).
#[derive(Debug, Clone, Copy, Serialize)]
#[serde(rename_all = "camelCase")]
pub struct UGenRegistryEntry {
    pub name: &'static str,
    pub rates: &'static [Rate],
    /// Declared parameter order `(name, optional default)`. Matches SC's wire
    /// order with the usual caveat that `channelsArray` / `inputArray` are
    /// reordered to the end of the input list at compile time.
    pub defaults: &'static [(&'static str, Option<f32>)],
    /// Output count. `None` means the JSON didn't specify it, and scsynth
    /// treats that as 1.
    pub num_outputs: Option<u32>,
    /// Parent UGen name when this entry inherits args/rates via Overtone's
    /// `:extends`. Retained for documentation; inheritance is already
    /// materialized into `rates` / `defaults` / `num_outputs`.
    pub extends: Option<&'static str>,
    pub summary: Option<&'static str>,
    pub doc: Option<&'static str>,
    pub signal_range: Option<&'static str>,
    /// Per-argument documentation, sorted by argument name.
    pub arg_docs: &'static [(&'static str, &'static str)],
}

/// Look up a UGen by its class name (e.g. `"SinOsc"`). Returns `None` if the
/// UGen isn't in the bundled registry.
pub fn lookup_ugen(name: &str) -> Option<&'static UGenRegistryEntry> {
    // Each per-category slice is independently sorted, so binary-search each
    // until one yields a hit. 24 slices × ~O(log 32) ≈ 120 comparisons
    // worst-case — still cheap and avoids concatenating into one slice.
    for (_, slice) in specs::ALL_SLICES {
        if let Ok(i) = slice.binary_search_by(|e| e.name.cmp(name)) {
            return Some(&slice[i]);
        }
    }
    None
}

/// Return the full registry grouped by category (the JSON source file each
/// UGen came from). Each inner slice is sorted by UGen name. Useful for
/// callers that want to browse / document the dataset.
pub fn ugens_by_category() -> &'static [(&'static str, &'static [UGenRegistryEntry])] {
    specs::ALL_SLICES
}

#[cfg(test)]
mod tests {
    use super::*;

    fn total_entries() -> usize {
        specs::ALL_SLICES.iter().map(|(_, s)| s.len()).sum()
    }

    #[test]
    fn registry_populated() {
        assert!(total_entries() > 300);
    }

    #[test]
    fn every_slice_is_sorted_by_name() {
        for (_, slice) in specs::ALL_SLICES {
            for pair in slice.windows(2) {
                assert!(
                    pair[0].name < pair[1].name,
                    "slice not sorted: {} >= {}",
                    pair[0].name,
                    pair[1].name,
                );
            }
        }
    }

    #[test]
    fn common_ugens_present() {
        for class in ["SinOsc", "Out", "BinaryOpUGen", "RecordBuf", "Phasor"] {
            assert!(
                lookup_ugen(class).is_some(),
                "expected {class} in registry"
            );
        }
    }

    #[test]
    fn out_has_zero_outputs() {
        let entry = lookup_ugen("Out").expect("Out in registry");
        assert_eq!(entry.num_outputs, Some(0));
    }

    #[test]
    fn sinosc_has_freq_default_440() {
        let entry = lookup_ugen("SinOsc").expect("SinOsc in registry");
        let freq = entry.defaults.iter().find(|(n, _)| *n == "freq").unwrap();
        assert_eq!(freq.1, Some(440.0));
    }
}
