// @generated — DO NOT EDIT. Regenerate with scripts/generate_specs.mjs.
//
// Auto-generated UGen spec data — one file per source category.

import { UGenRegistryEntry } from '../registry.js';

export const UGENS: UGenRegistryEntry[] = [
  {
    name: "CuspL",
    rates: ['audio', 'control'],
    defaults: [
      { name: "freq", default: 22050 },
      { name: "a", default: 1 },
      { name: "b", default: 1.899999976158142 },
      { name: "xi", default: 0 },
    ],
    numOutputs: null,
    extends: "CuspN",
    summary: null,
    doc: "a linear-interpolating (cusp map chaotic) sound generator based on the difference equation: xn+1 = a - b*sqrt(|xn|)",
    signalRange: null,
    argDocs: [
      { name: "a", doc: "first coefficient" },
      { name: "b", doc: "2nd coefficient" },
      { name: "freq", doc: "iteration frequency in Hertz" },
      { name: "xi", doc: "initial value of x" },
    ],
  },
  {
    name: "CuspN",
    rates: ['audio', 'control'],
    defaults: [
      { name: "freq", default: 22050 },
      { name: "a", default: 1 },
      { name: "b", default: 1.899999976158142 },
      { name: "xi", default: 0 },
    ],
    numOutputs: null,
    extends: null,
    summary: null,
    doc: "a non-interpolating (cusp map chaotic) sound generator based on the difference equation: xn+1 = a - b*sqrt(|xn|)",
    signalRange: null,
    argDocs: [
      { name: "a", doc: "first coefficient" },
      { name: "b", doc: "2nd coefficient" },
      { name: "freq", doc: "iteration frequency in Hertz" },
      { name: "xi", doc: "initial value of x" },
    ],
  },
  {
    name: "FBSineC",
    rates: ['audio', 'control'],
    defaults: [
      { name: "freq", default: 22050 },
      { name: "im", default: 1 },
      { name: "fb", default: 0.10000000149011612 },
      { name: "a", default: 1.100000023841858 },
      { name: "c", default: 0.5 },
      { name: "xi", default: 0.10000000149011612 },
      { name: "yi", default: 0.10000000149011612 },
    ],
    numOutputs: null,
    extends: "FBSineN",
    summary: null,
    doc: "a cubic-interpolating feedback sine with chaotic phase indexing sound generator. This uses a linear congruential function to drive the phase indexing of a sine wave. For im = 1, fb = 0, and a = 1 a normal sinewave results.",
    signalRange: null,
    argDocs: [
      { name: "a", doc: "phase multiplier amount" },
      { name: "c", doc: "phase increment amount" },
      { name: "fb", doc: "feedback amount" },
      { name: "freq", doc: "iteration frequency in Hertz" },
      { name: "im", doc: "index multiplier amount" },
      { name: "xi", doc: "initial value of x" },
      { name: "yi", doc: "initial value of y" },
    ],
  },
  {
    name: "FBSineL",
    rates: ['audio', 'control'],
    defaults: [
      { name: "freq", default: 22050 },
      { name: "im", default: 1 },
      { name: "fb", default: 0.10000000149011612 },
      { name: "a", default: 1.100000023841858 },
      { name: "c", default: 0.5 },
      { name: "xi", default: 0.10000000149011612 },
      { name: "yi", default: 0.10000000149011612 },
    ],
    numOutputs: null,
    extends: "FBSineN",
    summary: null,
    doc: "a linear-interpolating feedback sine with chaotic phase indexing sound generator. This uses a linear congruential function to drive the phase indexing of a sine wave. For im = 1, fb = 0, and a = 1 a normal sinewave results.",
    signalRange: null,
    argDocs: [
      { name: "a", doc: "phase multiplier amount" },
      { name: "c", doc: "phase increment amount" },
      { name: "fb", doc: "feedback amount" },
      { name: "freq", doc: "iteration frequency in Hertz" },
      { name: "im", doc: "index multiplier amount" },
      { name: "xi", doc: "initial value of x" },
      { name: "yi", doc: "initial value of y" },
    ],
  },
  {
    name: "FBSineN",
    rates: ['audio', 'control'],
    defaults: [
      { name: "freq", default: 22050 },
      { name: "im", default: 1 },
      { name: "fb", default: 0.10000000149011612 },
      { name: "a", default: 1.100000023841858 },
      { name: "c", default: 0.5 },
      { name: "xi", default: 0.10000000149011612 },
      { name: "yi", default: 0.10000000149011612 },
    ],
    numOutputs: null,
    extends: null,
    summary: null,
    doc: "a non-interpolating feedback sine with chaotic phase indexing sound generator. This uses a linear congruential function to drive the phase indexing of a sine wave. For im = 1, fb = 0, and a = 1 a normal sinewave results.",
    signalRange: null,
    argDocs: [
      { name: "a", doc: "phase multiplier amount" },
      { name: "c", doc: "phase increment amount" },
      { name: "fb", doc: "feedback amount" },
      { name: "freq", doc: "iteration frequency in Hertz" },
      { name: "im", doc: "index multiplier amount" },
      { name: "xi", doc: "initial value of x" },
      { name: "yi", doc: "initial value of y" },
    ],
  },
  {
    name: "GbmanL",
    rates: ['audio', 'control'],
    defaults: [
      { name: "freq", default: 22050 },
      { name: "xi", default: 1.2000000476837158 },
      { name: "yi", default: 2.0999999046325684 },
    ],
    numOutputs: null,
    extends: "GbmanN",
    summary: null,
    doc: "A linear-interpolating (gingerbreadman map chaotic) sound generator based on the difference equations: xn+1 = 1 - yn + |xn| yn+1 = xn",
    signalRange: null,
    argDocs: [
      { name: "freq", doc: "iteration frequency in Hz" },
      { name: "xi", doc: "initial value of x" },
      { name: "yi", doc: "initial value of y" },
    ],
  },
  {
    name: "GbmanN",
    rates: ['audio', 'control'],
    defaults: [
      { name: "freq", default: 22050 },
      { name: "xi", default: 1.2000000476837158 },
      { name: "yi", default: 2.0999999046325684 },
    ],
    numOutputs: null,
    extends: null,
    summary: null,
    doc: "A non-interpolating (gingerbreadman map chaotic) sound generator based on the difference equations: xn+1 = 1 - yn + |xn| yn+1 = xn",
    signalRange: null,
    argDocs: [
      { name: "freq", doc: "iteration frequency in Hz" },
      { name: "xi", doc: "initial value of x" },
      { name: "yi", doc: "initial value of y" },
    ],
  },
  {
    name: "HenonC",
    rates: ['audio', 'control'],
    defaults: [
      { name: "freq", default: 22050 },
      { name: "a", default: 1.399999976158142 },
      { name: "b", default: 0.30000001192092896 },
      { name: "x0", default: 0 },
      { name: "x1", default: 0 },
    ],
    numOutputs: null,
    extends: "HenonN",
    summary: null,
    doc: "a cubic-interpolating (henon map chaotic) sound generator based on the difference equation: x[n+2] = 1 - a*(x[n+1]^)2 + bx[n]. This equation was discovered by French astronomer Michel Hénon while studying the orbits of stars in globular clusters.",
    signalRange: null,
    argDocs: [
      { name: "a", doc: "1st coefficient" },
      { name: "b", doc: "2nd coefficient" },
      { name: "freq", doc: "iteration frequency in Hertz" },
      { name: "x0", doc: "initial value of x" },
      { name: "x1", doc: "second value of x" },
    ],
  },
  {
    name: "HenonL",
    rates: ['audio', 'control'],
    defaults: [
      { name: "freq", default: 22050 },
      { name: "a", default: 1.399999976158142 },
      { name: "b", default: 0.30000001192092896 },
      { name: "x0", default: 0 },
      { name: "x1", default: 0 },
    ],
    numOutputs: null,
    extends: "HenonN",
    summary: null,
    doc: "a linear-interpolating (henon map chaotic) sound generator based on the difference equation: x[n+2] = 1 - a*(x[n+1]^)2 + bx[n]. This equation was discovered by French astronomer Michel Hénon while studying the orbits of stars in globular clusters.",
    signalRange: null,
    argDocs: [
      { name: "a", doc: "1st coefficient" },
      { name: "b", doc: "2nd coefficient" },
      { name: "freq", doc: "iteration frequency in Hertz" },
      { name: "x0", doc: "initial value of x" },
      { name: "x1", doc: "second value of x" },
    ],
  },
  {
    name: "HenonN",
    rates: ['audio', 'control'],
    defaults: [
      { name: "freq", default: 22050 },
      { name: "a", default: 1.399999976158142 },
      { name: "b", default: 0.30000001192092896 },
      { name: "x0", default: 0 },
      { name: "x1", default: 0 },
    ],
    numOutputs: null,
    extends: null,
    summary: null,
    doc: "a non-interpolating (henon map chaotic) sound generator based on the difference equation: x[n+2] = 1 - a*(x[n+1]^)2 + bx[n]. This equation was discovered by French astronomer Michel Hénon while studying the orbits of stars in globular clusters.",
    signalRange: null,
    argDocs: [
      { name: "a", doc: "1st coefficient" },
      { name: "b", doc: "2nd coefficient" },
      { name: "freq", doc: "iteration frequency in Hertz" },
      { name: "x0", doc: "initial value of x" },
      { name: "x1", doc: "second value of x" },
    ],
  },
  {
    name: "LatoocarfianC",
    rates: ['audio', 'control'],
    defaults: [
      { name: "freq", default: 22050 },
      { name: "a", default: 1 },
      { name: "b", default: 3 },
      { name: "c", default: 0.5 },
      { name: "d", default: 0.5 },
      { name: "xi", default: 0.5 },
      { name: "yi", default: 0.5 },
    ],
    numOutputs: null,
    extends: "LatoocarfianN",
    summary: null,
    doc: "a cubic-interpolating (latoocarfian chaotic) sound generator. Parameters a and b should be in the range from -3 to +3, and parameters c and d should be in the range from 0.5 to 1.5. The function can, depending on the parameters given, give continuous chaotic output, converge to a single value (silence) or oscillate in a cycle (tone).",
    signalRange: null,
    argDocs: [
      { name: "a", doc: "1st coefficient" },
      { name: "b", doc: "2nd coefficient" },
      { name: "c", doc: "3rd coefficient" },
      { name: "d", doc: "4th coefficient" },
      { name: "freq", doc: "iteration frequency in Hertz" },
      { name: "xi", doc: "initial value of x" },
      { name: "yi", doc: "initial value of y" },
    ],
  },
  {
    name: "LatoocarfianL",
    rates: ['audio', 'control'],
    defaults: [
      { name: "freq", default: 22050 },
      { name: "a", default: 1 },
      { name: "b", default: 3 },
      { name: "c", default: 0.5 },
      { name: "d", default: 0.5 },
      { name: "xi", default: 0.5 },
      { name: "yi", default: 0.5 },
    ],
    numOutputs: null,
    extends: "LatoocarfianN",
    summary: null,
    doc: "a linear-interpolating (latoocarfian chaotic) sound generator. Parameters a and b should be in the range from -3 to +3, and parameters c and d should be in the range from 0.5 to 1.5. The function can, depending on the parameters given, give continuous chaotic output, converge to a single value (silence) or oscillate in a cycle (tone).",
    signalRange: null,
    argDocs: [
      { name: "a", doc: "1st coefficient" },
      { name: "b", doc: "2nd coefficient" },
      { name: "c", doc: "3rd coefficient" },
      { name: "d", doc: "4th coefficient" },
      { name: "freq", doc: "iteration frequency in Hertz" },
      { name: "xi", doc: "initial value of x" },
      { name: "yi", doc: "initial value of y" },
    ],
  },
  {
    name: "LatoocarfianN",
    rates: ['audio', 'control'],
    defaults: [
      { name: "freq", default: 22050 },
      { name: "a", default: 1 },
      { name: "b", default: 3 },
      { name: "c", default: 0.5 },
      { name: "d", default: 0.5 },
      { name: "xi", default: 0.5 },
      { name: "yi", default: 0.5 },
    ],
    numOutputs: null,
    extends: null,
    summary: null,
    doc: "a non-interpolating (latoocarfian chaotic) sound generator. Parameters a and b should be in the range from -3 to +3, and parameters c and d should be in the range from 0.5 to 1.5. The function can, depending on the parameters given, give continuous chaotic output, converge to a single value (silence) or oscillate in a cycle (tone).",
    signalRange: null,
    argDocs: [
      { name: "a", doc: "1st coefficient" },
      { name: "b", doc: "2nd coefficient" },
      { name: "c", doc: "3rd coefficient" },
      { name: "d", doc: "4th coefficient" },
      { name: "freq", doc: "iteration frequency in Hertz" },
      { name: "xi", doc: "initial value of x" },
      { name: "yi", doc: "initial value of y" },
    ],
  },
  {
    name: "LinCongC",
    rates: ['audio', 'control'],
    defaults: [
      { name: "freq", default: 22050 },
      { name: "a", default: 1.100000023841858 },
      { name: "c", default: 0.12999999523162842 },
      { name: "m", default: 1 },
      { name: "xi", default: 0 },
    ],
    numOutputs: null,
    extends: "LinCongN",
    summary: null,
    doc: "a cubic-interpolating (linear congruential chaotic) sound generator. The output signal is automatically scaled to a range of [-1, 1].",
    signalRange: null,
    argDocs: [
      { name: "a", doc: "multiplier amount" },
      { name: "c", doc: "increment amount" },
      { name: "freq", doc: "iteration frequency in Hertz." },
      { name: "m", doc: "modulus amount" },
      { name: "xi", doc: "initial value of x" },
    ],
  },
  {
    name: "LinCongL",
    rates: ['audio', 'control'],
    defaults: [
      { name: "freq", default: 22050 },
      { name: "a", default: 1.100000023841858 },
      { name: "c", default: 0.12999999523162842 },
      { name: "m", default: 1 },
      { name: "xi", default: 0 },
    ],
    numOutputs: null,
    extends: "LinCongN",
    summary: null,
    doc: "a linear-interpolating (linear congruential chaotic) sound generator. The output signal is automatically scaled to a range of [-1, 1].",
    signalRange: null,
    argDocs: [
      { name: "a", doc: "multiplier amount" },
      { name: "c", doc: "increment amount" },
      { name: "freq", doc: "iteration frequency in Hertz." },
      { name: "m", doc: "modulus amount" },
      { name: "xi", doc: "initial value of x" },
    ],
  },
  {
    name: "LinCongN",
    rates: ['audio', 'control'],
    defaults: [
      { name: "freq", default: 22050 },
      { name: "a", default: 1.100000023841858 },
      { name: "c", default: 0.12999999523162842 },
      { name: "m", default: 1 },
      { name: "xi", default: 0 },
    ],
    numOutputs: null,
    extends: null,
    summary: null,
    doc: "a non-interpolating (linear congruential chaotic) sound generator. The output signal is automatically scaled to a range of [-1, 1].",
    signalRange: null,
    argDocs: [
      { name: "a", doc: "multiplier amount" },
      { name: "c", doc: "increment amount" },
      { name: "freq", doc: "iteration frequency in Hertz." },
      { name: "m", doc: "modulus amount" },
      { name: "xi", doc: "initial value of x" },
    ],
  },
  {
    name: "LorenzL",
    rates: ['audio', 'control'],
    defaults: [
      { name: "freq", default: 22050 },
      { name: "s", default: 10 },
      { name: "r", default: 28 },
      { name: "b", default: 2.6670000553131104 },
      { name: "h", default: 0.05000000074505806 },
      { name: "xi", default: 0.10000000149011612 },
      { name: "yi", default: 0 },
      { name: "zi", default: 0 },
    ],
    numOutputs: null,
    extends: null,
    summary: null,
    doc: "lorenz chaotic generator. A strange attractor discovered by Edward N. Lorenz while studying mathematical models of the atmosphere. The time step amount h determines the rate at which the ODE is evaluated. Higher values will increase the rate, but cause more instability. A safe choice is the default amount of 0.05.",
    signalRange: null,
    argDocs: [
      { name: "b", doc: "3rd variable" },
      { name: "freq", doc: "iteration frequency in Hertz" },
      { name: "h", doc: "integration time stamp" },
      { name: "r", doc: "2nd variable" },
      { name: "s", doc: "1st variable" },
      { name: "xi", doc: "initial value of x" },
      { name: "yi", doc: "initial value of y" },
      { name: "zi", doc: "initial value of z" },
    ],
  },
  {
    name: "QuadC",
    rates: ['audio', 'control'],
    defaults: [
      { name: "freq", default: 22050 },
      { name: "a", default: 1 },
      { name: "b", default: -1 },
      { name: "c", default: -0.75 },
      { name: "xi", default: 0 },
    ],
    numOutputs: null,
    extends: "QuadN",
    summary: null,
    doc: "a cubic-interpolating (general quadratic map chaotic) sound generator based on the difference equation: xn+1 = axn2 + bxn + c",
    signalRange: null,
    argDocs: [
      { name: "a", doc: "1st coefficient" },
      { name: "b", doc: "2nd coefficient" },
      { name: "c", doc: "3rd coefficient" },
      { name: "freq", doc: "iteration frequency in Hertz" },
      { name: "xi", doc: "initial value of x" },
    ],
  },
  {
    name: "QuadL",
    rates: ['audio', 'control'],
    defaults: [
      { name: "freq", default: 22050 },
      { name: "a", default: 1 },
      { name: "b", default: -1 },
      { name: "c", default: -0.75 },
      { name: "xi", default: 0 },
    ],
    numOutputs: null,
    extends: "QuadN",
    summary: null,
    doc: "a linear-interpolating (general quadratic map chaotic) sound generator based on the difference equation: xn+1 = axn2 + bxn + c",
    signalRange: null,
    argDocs: [
      { name: "a", doc: "1st coefficient" },
      { name: "b", doc: "2nd coefficient" },
      { name: "c", doc: "3rd coefficient" },
      { name: "freq", doc: "iteration frequency in Hertz" },
      { name: "xi", doc: "initial value of x" },
    ],
  },
  {
    name: "QuadN",
    rates: ['audio', 'control'],
    defaults: [
      { name: "freq", default: 22050 },
      { name: "a", default: 1 },
      { name: "b", default: -1 },
      { name: "c", default: -0.75 },
      { name: "xi", default: 0 },
    ],
    numOutputs: null,
    extends: null,
    summary: null,
    doc: "a non-interpolating (general quadratic map chaotic) sound generator based on the difference equation: xn+1 = axn2 + bxn + c",
    signalRange: null,
    argDocs: [
      { name: "a", doc: "1st coefficient" },
      { name: "b", doc: "2nd coefficient" },
      { name: "c", doc: "3rd coefficient" },
      { name: "freq", doc: "iteration frequency in Hertz" },
      { name: "xi", doc: "initial value of x" },
    ],
  },
  {
    name: "StandardL",
    rates: ['audio', 'control'],
    defaults: [
      { name: "freq", default: 22050 },
      { name: "k", default: 1 },
      { name: "xi", default: 0.5 },
      { name: "yi", default: 0 },
    ],
    numOutputs: null,
    extends: "StandardN",
    summary: null,
    doc: "linear-interpolating standard map chaotic generator. The standard map is an area preserving map of a cylinder discovered by the plasma physicist Boris Chirikov.",
    signalRange: null,
    argDocs: [
      { name: "freq", doc: "iteration frequency in Hertz" },
      { name: "k", doc: "perturbation amount" },
      { name: "xi", doc: "initial value of x" },
      { name: "yi", doc: "initial value of y" },
    ],
  },
  {
    name: "StandardN",
    rates: ['audio', 'control'],
    defaults: [
      { name: "freq", default: 22050 },
      { name: "k", default: 1 },
      { name: "xi", default: 0.5 },
      { name: "yi", default: 0 },
    ],
    numOutputs: null,
    extends: null,
    summary: null,
    doc: "standard map chaotic generator. The standard map is an area preserving map of a cylinder discovered by the plasma physicist Boris Chirikov.",
    signalRange: null,
    argDocs: [
      { name: "freq", doc: "iteration frequency in Hertz" },
      { name: "k", doc: "perturbation amount" },
      { name: "xi", doc: "initial value of x" },
      { name: "yi", doc: "initial value of y" },
    ],
  },
];
