// @generated — DO NOT EDIT. Regenerate with scripts/generate_specs.mjs.
//
// Auto-generated UGen spec data — one file per source category.

import { UGenRegistryEntry } from "../registry.js";

export const UGENS: UGenRegistryEntry[] = [
  {
    name: "FFT",
    rates: ["control"],
    defaults: [
      { name: "buffer", default: null },
      { name: "in", default: 0 },
      { name: "hop", default: 0.5 },
      { name: "wintype", default: 0 },
      { name: "active", default: 1 },
      { name: "winsize", default: 0 },
    ],
    numOutputs: null,
    extends: null,
    summary: null,
    doc: "fast fourier transform, converts input data from the time to the frequency domain and stores the result in a buffer (audio waveform -> graph equalizer bands) Output is -1 except when an FFT frame is ready, when the output is the buffer index. This creates a special kind of slower pseudo-rate (built on top of control rate) which all the pv-ugens understand.",
    signalRange: null,
    argDocs: [
      {
        name: "active",
        doc: "is a simple control allowing FFT analysis to be active (>0) or inactive (<=0). This is mainly useful for signal analysis processes which are only intended to analyse at specific times rather than continuously",
      },
      {
        name: "buffer",
        doc: "The buffer where a frame will be held. Its size must be a power of two. local-buf is useful here, because processes should not share data between synths. (Note: most PV UGens operate on this data in place. Use buffer-2n if you wish to create an external buffer.",
      },
      {
        name: "hop",
        doc: "the amount of offset from one FFT analysis frame to the next, measured in multiples of the analysis frame size. This can range between zero and one, and the default is 0.5 (meaning each frame has a 50% overlap with the preceding/following frames).",
      },
      {
        name: "in",
        doc: "the signal to be analyzed. The signal's rate determines the rate at which the input is read.",
      },
      {
        name: "winsize",
        doc: "the windowed audio frames are usually the same size as the buffer. If you wish the FFT to be zero-padded then you can specify a window size smaller than the actual buffer size (e.g. window size 1024 with buffer size 2048). Both values must still be a power of two. Leave this at its default of zero for no zero-padding.",
      },
      {
        name: "wintype",
        doc: "defines how the data is windowed: RECT is for rectangular windowing, simple but typically not recommended; SINE (the default) is for Sine windowing, typically recommended for phase-vocoder work; HANN is for Hann windowing, typically recommended for analysis work.",
      },
    ],
  },
  {
    name: "FFTTrigger",
    rates: ["control"],
    defaults: [
      { name: "buffer", default: null },
      { name: "hop", default: 0.5 },
      { name: "polar", default: 0 },
    ],
    numOutputs: null,
    extends: null,
    summary: null,
    doc: "Outputs the necessary signal for FFT chains, without doing an FFT on a signal",
    signalRange: null,
    argDocs: [
      { name: "buffer", doc: "a buffer to condition for FFT use" },
      { name: "hop", doc: "the hop size for timing triggers" },
      {
        name: "polar",
        doc: "a flag. If 0.0, the buffer will be prepared for complex data, if > 0.0, polar data is set up.",
      },
    ],
  },
  {
    name: "IFFT",
    rates: ["audio", "control"],
    defaults: [
      { name: "chain", default: null },
      { name: "wintype", default: 0 },
      { name: "winsize", default: 0 },
    ],
    numOutputs: null,
    extends: null,
    summary: null,
    doc: "inverse fast fourier transform, converts buffer data from frequency domain to time domain The IFFT UGen converts the FFT data in-place (in the original FFT buffer) and overlap-adds the result to produce a continuous signal at its output.",
    signalRange: null,
    argDocs: [
      {
        name: "chain",
        doc: "The FFT chain signal coming originally from an FFT UGen, perhaps via other PV UGens.",
      },
      {
        name: "winsize",
        doc: "can be used to account for zero-padding, in the same way as the FFT UGen.",
      },
      {
        name: "wintype",
        doc: "defines how the data is windowed: RECT is for rectangular windowing, simple but typically not recommended; SINE (the default) is for Sine windowing, typically recommended for phase-vocoder work; HANN is for Hann windowing, typically recommended for analysis work.",
      },
    ],
  },
  {
    name: "PV_Add",
    rates: ["control"],
    defaults: [
      { name: "bufferA", default: null },
      { name: "bufferB", default: null },
    ],
    numOutputs: null,
    extends: "PV_MagMul",
    summary: null,
    doc: "complex addition: RealA + RealB, ImagA + ImagB",
    signalRange: null,
    argDocs: [
      { name: "bufferA", doc: "fft buffer A" },
      { name: "bufferB", doc: "fft buffer B" },
    ],
  },
  {
    name: "PV_BinScramble",
    rates: ["control"],
    defaults: [
      { name: "buffer", default: null },
      { name: "wipe", default: 0 },
      { name: "width", default: 0.20000000298023224 },
      { name: "trig", default: 0 },
    ],
    numOutputs: null,
    extends: null,
    summary: null,
    doc: "randomizes the order of the bins. The trigger will select a new random ordering.",
    signalRange: null,
    argDocs: [
      { name: "buffer", doc: "fft buffer" },
      { name: "trig", doc: "a trigger selects a new random ordering." },
      {
        name: "width",
        doc: "a value from zero to one, indicating the maximum randomized distance of a bin from its original location in the spectrum.",
      },
      { name: "wipe", doc: "scrambles more bins as wipe moves from zero to one." },
    ],
  },
  {
    name: "PV_BinShift",
    rates: ["control"],
    defaults: [
      { name: "buffer", default: null },
      { name: "stretch", default: 1 },
      { name: "shift", default: 0 },
    ],
    numOutputs: null,
    extends: null,
    summary: null,
    doc: "shift and scale the positions of the bins. Can be used as a very crude frequency shifter/scaler.",
    signalRange: null,
    argDocs: [
      { name: "buffer", doc: "fft buffer." },
      { name: "shift", doc: "add an offset to bin position." },
      { name: "stretch", doc: "scale bin location by factor." },
    ],
  },
  {
    name: "PV_BinWipe",
    rates: ["control"],
    defaults: [
      { name: "bufferA", default: null },
      { name: "bufferB", default: null },
      { name: "wipe", default: 0 },
    ],
    numOutputs: null,
    extends: null,
    summary: null,
    doc: "copies low bins from one input and the high bins of the other",
    signalRange: null,
    argDocs: [
      { name: "bufferA", doc: "fft buffer A" },
      { name: "bufferB", doc: "fft buffer B" },
      {
        name: "wipe",
        doc: "can range between -1 and +1; if wipe == 0 then the output is the same as inA; if wipe > 0 then it begins replacing with bins from inB from the bottom up;if wipe < 0 then it begins replacing with bins from inB from the top down.",
      },
    ],
  },
  {
    name: "PV_BrickWall",
    rates: ["control"],
    defaults: [
      { name: "buffer", default: null },
      { name: "wipe", default: 0 },
    ],
    numOutputs: null,
    extends: null,
    summary: null,
    doc: "clears bins above or below a cutoff point",
    signalRange: null,
    argDocs: [
      { name: "buffer", doc: "fft buffer" },
      {
        name: "wipe",
        doc: "can range between -1 and +1. if wipe == 0 then there is no effect; if wipe > 0 then it acts like a high pass filter, clearing bins from the bottom up; if wipe < 0 then it acts like a low pass filter, clearing bins from the top down.",
      },
    ],
  },
  {
    name: "PV_Conj",
    rates: ["control"],
    defaults: [{ name: "buffer", default: null }],
    numOutputs: null,
    extends: "PV_MagSquared",
    summary: null,
    doc: "converts the FFT frames to their complex conjugate (i.e. reverses the sign of their imaginary part). This is not usually a useful audio effect in itself, but may be a component of other analysis or transformation processes...",
    signalRange: null,
    argDocs: [{ name: "buffer", doc: "fft buffer" }],
  },
  {
    name: "PV_Copy",
    rates: ["control"],
    defaults: [
      { name: "bufferA", default: null },
      { name: "bufferB", default: null },
    ],
    numOutputs: null,
    extends: "PV_MagMul",
    summary: null,
    doc: "copies the spectral frame in bufferA to bufferB at that point in the chain of PV UGens. This allows for parallel processing of spectral data without the need for multiple FFT UGens, and to copy out data at that point in the chain for other purposes. bufferA and bufferB must be the same size.",
    signalRange: null,
    argDocs: [
      { name: "bufferA", doc: "source buffer" },
      { name: "bufferB", doc: "destination buffer" },
    ],
  },
  {
    name: "PV_CopyPhase",
    rates: ["control"],
    defaults: [
      { name: "bufferA", default: null },
      { name: "bufferB", default: null },
    ],
    numOutputs: null,
    extends: "PV_MagMul",
    summary: null,
    doc: "combines magnitudes of first input and phases of the second input",
    signalRange: null,
    argDocs: [
      { name: "bufferA", doc: "fft buffer A" },
      { name: "bufferB", doc: "fft buffer B" },
    ],
  },
  {
    name: "PV_Diffuser",
    rates: ["control"],
    defaults: [
      { name: "buffer", default: null },
      { name: "trig", default: 0 },
    ],
    numOutputs: null,
    extends: null,
    summary: null,
    doc: "adds a different constant random phase shift to each bin. The trigger will select a new set of random phases.",
    signalRange: null,
    argDocs: [
      { name: "buffer", doc: "fft buffer" },
      { name: "trig", doc: "a trigger selects a new set of random values." },
    ],
  },
  {
    name: "PV_Div",
    rates: ["control"],
    defaults: [
      { name: "bufferA", default: null },
      { name: "bufferB", default: null },
    ],
    numOutputs: null,
    extends: "PV_MagMul",
    summary: null,
    doc: "complex division",
    signalRange: null,
    argDocs: [
      { name: "bufferA", doc: "fft buffer A" },
      { name: "bufferB", doc: "fft buffer B" },
    ],
  },
  {
    name: "PV_LocalMax",
    rates: ["control"],
    defaults: [
      { name: "buffer", default: null },
      { name: "threshold", default: 0 },
    ],
    numOutputs: null,
    extends: "PV_MagAbove",
    summary: null,
    doc: "passes only bins whose magnitude is above a threshold and above their nearest neighbors",
    signalRange: null,
    argDocs: [
      { name: "buffer", doc: "fft buffer" },
      { name: "threshold", doc: "magnitude threshold." },
    ],
  },
  {
    name: "PV_MagAbove",
    rates: ["control"],
    defaults: [
      { name: "buffer", default: null },
      { name: "threshold", default: 0 },
    ],
    numOutputs: null,
    extends: null,
    summary: null,
    doc: "passes only bins whose magnitude is above a threshold",
    signalRange: null,
    argDocs: [
      { name: "buffer", doc: "fft buffer" },
      { name: "threshold", doc: "magnitude threshold." },
    ],
  },
  {
    name: "PV_MagBelow",
    rates: ["control"],
    defaults: [
      { name: "buffer", default: null },
      { name: "threshold", default: 0 },
    ],
    numOutputs: null,
    extends: "PV_MagAbove",
    summary: null,
    doc: "passes only bins whose magnitude is below a threshold",
    signalRange: null,
    argDocs: [
      { name: "buffer", doc: "fft buffer" },
      { name: "threshold", doc: "magnitude threshold." },
    ],
  },
  {
    name: "PV_MagClip",
    rates: ["control"],
    defaults: [
      { name: "buffer", default: null },
      { name: "threshold", default: 0 },
    ],
    numOutputs: null,
    extends: "PV_MagAbove",
    summary: null,
    doc: "clips bin magnitudes to a maximum threshold",
    signalRange: null,
    argDocs: [
      { name: "buffer", doc: "fft buffer" },
      { name: "threshold", doc: "magnitude threshold." },
    ],
  },
  {
    name: "PV_MagDiv",
    rates: ["control"],
    defaults: [
      { name: "bufferA", default: null },
      { name: "bufferB", default: null },
      { name: "zeroed", default: 0.00009999999747378752 },
    ],
    numOutputs: null,
    extends: null,
    summary: null,
    doc: "divides magnitudes of two inputs and keeps the phases of the first input",
    signalRange: null,
    argDocs: [
      { name: "bufferA", doc: "fft buffer A." },
      { name: "bufferB", doc: "fft buffer B." },
      {
        name: "zeroed",
        doc: "number to use when bins are zeroed out, i.e. causing division by zero",
      },
    ],
  },
  {
    name: "PV_MagFreeze",
    rates: ["control"],
    defaults: [
      { name: "buffer", default: null },
      { name: "freeze", default: 0 },
    ],
    numOutputs: null,
    extends: null,
    summary: null,
    doc: "freezes magnitudes at current levels when freeze > 0",
    signalRange: null,
    argDocs: [
      { name: "buffer", doc: "fft buffer" },
      { name: "freeze", doc: "if freeze > 0 then magnitudes are frozen at current levels." },
    ],
  },
  {
    name: "PV_MagMul",
    rates: ["control"],
    defaults: [
      { name: "bufferA", default: null },
      { name: "bufferB", default: null },
    ],
    numOutputs: null,
    extends: null,
    summary: null,
    doc: "multiplies magnitudes of two inputs and keeps the phases of the first input",
    signalRange: null,
    argDocs: [
      { name: "bufferA", doc: "fft buffer A" },
      { name: "bufferB", doc: "fft buffer B" },
    ],
  },
  {
    name: "PV_MagNoise",
    rates: ["control"],
    defaults: [{ name: "buffer", default: null }],
    numOutputs: null,
    extends: "PV_MagSquared",
    summary: null,
    doc: "magnitudes are multiplied with noise",
    signalRange: null,
    argDocs: [{ name: "buffer", doc: "fft buffer" }],
  },
  {
    name: "PV_MagShift",
    rates: ["control"],
    defaults: [
      { name: "buffer", default: null },
      { name: "stretch", default: 1 },
      { name: "shift", default: 0 },
    ],
    numOutputs: null,
    extends: "PV_BinShift",
    summary: null,
    doc: "shift and stretch the positions of only the magnitude of the bins. Can be used as a very crude frequency shifter/scaler.",
    signalRange: null,
    argDocs: [
      { name: "buffer", doc: "fft buffer." },
      { name: "shift", doc: "add an offset to bin position." },
      { name: "stretch", doc: "scale bin location by factor." },
    ],
  },
  {
    name: "PV_MagSmear",
    rates: ["control"],
    defaults: [
      { name: "buffer", default: null },
      { name: "bins", default: 0 },
    ],
    numOutputs: null,
    extends: null,
    summary: null,
    doc: "average a bin's magnitude with its neighbors",
    signalRange: null,
    argDocs: [
      {
        name: "bins",
        doc: "number of bins to average on each side of bin. As this number rises, so will CPU usage.",
      },
      { name: "buffer", doc: "fft buffer" },
    ],
  },
  {
    name: "PV_MagSquared",
    rates: ["control"],
    defaults: [{ name: "buffer", default: null }],
    numOutputs: null,
    extends: null,
    summary: null,
    doc: "squares the magnitudes and renormalizes to previous peak. This makes weak bins weaker.",
    signalRange: null,
    argDocs: [{ name: "buffer", doc: "fft buffer" }],
  },
  {
    name: "PV_Max",
    rates: ["control"],
    defaults: [
      { name: "bufferA", default: null },
      { name: "bufferB", default: null },
    ],
    numOutputs: null,
    extends: "PV_MagMul",
    summary: null,
    doc: "output copies bins with the maximum magnitude of the two inputs",
    signalRange: null,
    argDocs: [
      { name: "bufferA", doc: "fft buffer A" },
      { name: "bufferB", doc: "fft buffer B" },
    ],
  },
  {
    name: "PV_Min",
    rates: ["control"],
    defaults: [
      { name: "bufferA", default: null },
      { name: "bufferB", default: null },
    ],
    numOutputs: null,
    extends: "PV_MagMul",
    summary: null,
    doc: "output copies bins with the minimum magnitude of the two inputs",
    signalRange: null,
    argDocs: [
      { name: "bufferA", doc: "fft buffer A" },
      { name: "bufferB", doc: "fft buffer B" },
    ],
  },
  {
    name: "PV_Mul",
    rates: ["control"],
    defaults: [
      { name: "bufferA", default: null },
      { name: "bufferB", default: null },
    ],
    numOutputs: null,
    extends: "PV_MagMul",
    summary: null,
    doc: "complex multiplication: (RealA * RealB) - (ImagA * ImagB) (ImagA * RealB) + (RealA * ImagB)",
    signalRange: null,
    argDocs: [
      { name: "bufferA", doc: "fft buffer A" },
      { name: "bufferB", doc: "fft buffer B" },
    ],
  },
  {
    name: "PV_PhaseShift",
    rates: ["control"],
    defaults: [
      { name: "buffer", default: null },
      { name: "shift", default: null },
    ],
    numOutputs: null,
    extends: null,
    summary: null,
    doc: "shift phase of all bins",
    signalRange: null,
    argDocs: [
      { name: "buffer", doc: "fft buffer" },
      { name: "shift", doc: "phase shift in radians" },
    ],
  },
  {
    name: "PV_PhaseShift270",
    rates: ["control"],
    defaults: [{ name: "buffer", default: null }],
    numOutputs: null,
    extends: "PV_MagSquared",
    summary: null,
    doc: "shift phase of all bins by 270 degrees",
    signalRange: null,
    argDocs: [{ name: "buffer", doc: "fft buffer" }],
  },
  {
    name: "PV_PhaseShift90",
    rates: ["control"],
    defaults: [{ name: "buffer", default: null }],
    numOutputs: null,
    extends: "PV_MagSquared",
    summary: null,
    doc: "shift phase of all bins by 90 degrees",
    signalRange: null,
    argDocs: [{ name: "buffer", doc: "fft buffer" }],
  },
  {
    name: "PV_RandComb",
    rates: ["control"],
    defaults: [
      { name: "buffer", default: null },
      { name: "wipe", default: 0 },
      { name: "trig", default: 0 },
    ],
    numOutputs: null,
    extends: null,
    summary: null,
    doc: "randomly clear bins",
    signalRange: null,
    argDocs: [
      { name: "buffer", doc: "fft buffer." },
      { name: "trig", doc: "a trigger selects a new random ordering." },
      { name: "wipe", doc: "clears bins from input in a random order as wipe goes from 0 to 1." },
    ],
  },
  {
    name: "PV_RandWipe",
    rates: ["control"],
    defaults: [
      { name: "bufferA", default: null },
      { name: "bufferB", default: null },
      { name: "wipe", default: 0 },
      { name: "trig", default: 0 },
    ],
    numOutputs: null,
    extends: null,
    summary: null,
    doc: "cross fades between two sounds by copying bins in a random order",
    signalRange: null,
    argDocs: [
      { name: "bufferA", doc: "fft buffer A." },
      { name: "bufferB", doc: "fft buffer B." },
      { name: "trig", doc: "a trigger selects a new random ordering." },
      { name: "wipe", doc: "copies bins from bufferB in a random order as wipe goes from 0 to 1." },
    ],
  },
  {
    name: "PV_RectComb",
    rates: ["control"],
    defaults: [
      { name: "buffer", default: null },
      { name: "numTeeth", default: 0 },
      { name: "phase", default: 0 },
      { name: "width", default: 0.5 },
    ],
    numOutputs: null,
    extends: null,
    summary: null,
    doc: "makes a series of gaps in a spectrum",
    signalRange: null,
    argDocs: [
      { name: "buffer", doc: "fft buffer." },
      { name: "numTeeth", doc: "number of teeth in the comb." },
      { name: "phase", doc: "starting phase of comb pulse." },
      { name: "width", doc: "pulse width of comb." },
    ],
  },
  {
    name: "PV_RectComb2",
    rates: ["control"],
    defaults: [
      { name: "bufferA", default: null },
      { name: "bufferB", default: null },
      { name: "numTeeth", default: 0 },
      { name: "phase", default: 0 },
      { name: "width", default: 0.5 },
    ],
    numOutputs: null,
    extends: null,
    summary: null,
    doc: "alternates blocks of bins between the two inputs",
    signalRange: null,
    argDocs: [
      { name: "bufferA", doc: "fft buffer A." },
      { name: "bufferB", doc: "fft buffer B." },
      { name: "numTeeth", doc: "number of teeth in the comb." },
      { name: "phase", doc: "starting phase of comb pulse." },
      { name: "width", doc: "pulse width of comb." },
    ],
  },
];
