// @generated — DO NOT EDIT. Regenerate with scripts/generate_specs.mjs.
//
// Auto-generated UGen spec data — one file per source category.

import { UGenRegistryEntry } from "../registry.js";

export const UGENS: UGenRegistryEntry[] = [
  {
    name: "Ball",
    rates: ["audio"],
    defaults: [
      { name: "in", default: 0 },
      { name: "g", default: 1 },
      { name: "damp", default: 0 },
      { name: "friction", default: 0.009999999776482582 },
    ],
    numOutputs: null,
    extends: null,
    summary: null,
    doc: "models the path of a bouncing object that is reflected by a vibrating surface",
    signalRange: null,
    argDocs: [
      { name: "damp", doc: "damping on impact" },
      { name: "friction", doc: "proximity from which on attraction to surface starts" },
      { name: "g", doc: "gravity" },
      { name: "in", doc: "modulated surface level" },
    ],
  },
  {
    name: "FreeVerb",
    rates: ["audio"],
    defaults: [
      { name: "in", default: null },
      { name: "mix", default: 0.33000001311302185 },
      { name: "room", default: 0.5 },
      { name: "damp", default: 0.5 },
    ],
    numOutputs: null,
    extends: null,
    summary: null,
    doc: "A reverb coded from experiments with faust. Valid parameter range from 0 to 1. Values outside this range are clipped by the UGen.",
    signalRange: null,
    argDocs: [
      { name: "damp", doc: "Reverb HF damp. range 0..1" },
      { name: "in", doc: "The input signal" },
      { name: "mix", doc: "Dry/wet balance. range 0..1" },
      { name: "room", doc: "Room size. rage 0..1" },
    ],
  },
  {
    name: "FreeVerb2",
    rates: ["audio"],
    defaults: [
      { name: "in", default: null },
      { name: "in2", default: null },
      { name: "mix", default: 0.33000001311302185 },
      { name: "room", default: 0.5 },
      { name: "damp", default: 0.5 },
    ],
    numOutputs: 2,
    extends: null,
    summary: null,
    doc: "A two-channel reverb coded from experiments with faust. Valid parameter range from 0 to 1. Values outside this range are clipped by the UGen.",
    signalRange: null,
    argDocs: [
      { name: "damp", doc: "Reverb HF damp. range 0..1" },
      { name: "in", doc: "Input signal channel 1" },
      { name: "in2", doc: "Input signal channel 2" },
      { name: "mix", doc: "Dry/wet balance. range 0..1" },
      { name: "room", doc: "Room size. rage 0..1" },
    ],
  },
  {
    name: "FreqShift",
    rates: ["audio"],
    defaults: [
      { name: "in", default: null },
      { name: "freq", default: 0 },
      { name: "phase", default: 0 },
    ],
    numOutputs: null,
    extends: null,
    summary: null,
    doc: "FreqShift implements single sideband amplitude modulation, also known as frequency shifting, but not to be confused with pitch shifting. Frequency shifting moves all the components of a signal by a fixed amount but does not preserve the original harmonic relationships.",
    signalRange: null,
    argDocs: [
      { name: "freq", doc: "Amount of shift in cycles per second" },
      { name: "in", doc: "The signal to process" },
      { name: "phase", doc: "Phase of the frequency shift (0 - 2pi)" },
    ],
  },
  {
    name: "GVerb",
    rates: ["audio"],
    defaults: [
      { name: "in", default: null },
      { name: "roomsize", default: 10 },
      { name: "revtime", default: 3 },
      { name: "damping", default: 0.5 },
      { name: "inputbw", default: 0.5 },
      { name: "spread", default: 15 },
      { name: "drylevel", default: 1 },
      { name: "earlyreflevel", default: 0.699999988079071 },
      { name: "taillevel", default: 0.5 },
      { name: "maxroomsize", default: 300 },
    ],
    numOutputs: 2,
    extends: null,
    summary: null,
    doc: 'A two-channel reverb UGen, based on the \\"GVerb\\" LADSPA effect by Juhana Sadeharju (kouhia at nic.funet.fi). WARNING - in the current version of the server, there are severe noise issues when you attempt to modify the roomsize or set it to a value greater than 40.',
    signalRange: null,
    argDocs: [
      {
        name: "damping",
        doc: "0 to 1, high frequency rolloff, 0 damps the reverb signal completely, 1 not at all",
      },
      { name: "drylevel", doc: "amount of dry signal" },
      { name: "earlyreflevel", doc: "amount of early reflection level" },
      { name: "in", doc: "mono input" },
      { name: "inputbw", doc: "0 to 1, same as damping control, but on the input signal" },
      { name: "maxroomsize", doc: "to set the size of the delay lines." },
      { name: "revtime", doc: "in seconds" },
      { name: "roomsize", doc: "in squared meters." },
      { name: "spread", doc: "a control on the stereo spread and diffusion of the reverb signal" },
      { name: "taillevel", doc: "amount of tail level" },
    ],
  },
  {
    name: "Gendy1",
    rates: ["audio", "control"],
    defaults: [
      { name: "ampdist", default: 1 },
      { name: "durdist", default: 1 },
      { name: "adparam", default: 1 },
      { name: "ddparam", default: 1 },
      { name: "minfreq", default: 440 },
      { name: "maxfreq", default: 660 },
      { name: "ampscale", default: 0.5 },
      { name: "durscale", default: 0.5 },
      { name: "initCps", default: 12 },
      { name: "knum", default: 12 },
    ],
    numOutputs: null,
    extends: null,
    summary: null,
    doc: "An implementation of the dynamic stochastic synthesis generator conceived by Iannis Xenakis and described in Formalized Music (1992, Stuyvesant, NY: Pendragon Press) chapter 9 (pp 246-254) and chapters 13 and 14 (pp 289-322). The BASIC program in the book was written by Marie-Helene Serra so I think it helpful to credit her too. The program code has been adapted to avoid infinities in the probability distribution functions. The distributions are hard-coded in C but there is an option to have new amplitude or time breakpoints sampled from a continuous controller input.",
    signalRange: null,
    argDocs: [
      {
        name: "adparam",
        doc: "A parameter for the shape of the amplitude probability distribution, requires values in the range 0.0001 to 1 (there are safety checks in the code so don't worry too much if you want to modulate!)",
      },
      {
        name: "ampdist",
        doc: "Choice of probability distribution for the next perturbation of the amplitude of a control point. The distributions are (adapted from the GENDYN program in Formalized Music): 0- LINEAR,1- CAUCHY, 2- LOGIST, 3- HYPERBCOS, 4- ARCSINE, 5- EXPON, 6- SINUS, Where the sinus (Xenakis' name) is in this implementation taken as sampling from a third party oscillator. See example below.",
      },
      {
        name: "ampscale",
        doc: "Normally 0.0 to 1.0, multiplier for the distribution's delta value for amplitude. An ampscale of 1.0 allows the full range of -1 to 1 for a change of amplitude.",
      },
      {
        name: "ddparam",
        doc: "A parameter for the shape of the duration probability distribution, requires values in the range 0.0001 to 1",
      },
      {
        name: "durdist",
        doc: "Choice of distribution for the perturbation of the current inter control point duration.",
      },
      {
        name: "durscale",
        doc: "Normally 0.0 to 1.0, multiplier for the distribution's delta value for duration. An ampscale of 1.0 allows the full range of -1 to 1 for a change of duration.",
      },
      {
        name: "initCps",
        doc: "Initialise the number of control points in the memory. Xenakis specifies 12. There would be this number of control points per cycle of the oscillator, though the oscillator's period will constantly change due to the duration distribution.",
      },
      { name: "knum", doc: "Current number of utilised control points, allows modulation." },
      {
        name: "maxfreq",
        doc: "Maximum allowed frequency of oscillation for the Gendy1 oscillator, so gives the smallest period the duration is allowed to take on.",
      },
      {
        name: "minfreq",
        doc: "Minimum allowed frequency of oscillation for the Gendy1 oscillator, so gives the largest period the duration is allowed to take on.",
      },
    ],
  },
  {
    name: "Gendy2",
    rates: ["audio", "control"],
    defaults: [
      { name: "ampdist", default: 1 },
      { name: "durdist", default: 1 },
      { name: "adparam", default: 1 },
      { name: "ddparam", default: 1 },
      { name: "minfreq", default: 440 },
      { name: "maxfreq", default: 660 },
      { name: "ampscale", default: 0.5 },
      { name: "durscale", default: 0.5 },
      { name: "initCps", default: 12 },
      { name: "knum", default: 12 },
      { name: "a", default: 1.1699999570846558 },
      { name: "c", default: 0.3100000023841858 },
    ],
    numOutputs: null,
    extends: null,
    summary: null,
    doc: "See gendy1 help file for background. This variant of GENDYN is closer to that presented in Hoffmann, Peter. (2000) The New GENDYN Program. Computer Music Journal 24:2, pp 31-38.",
    signalRange: null,
    argDocs: [
      {
        name: "a",
        doc: "parameter for Lehmer random number generator perturbed by Xenakis as in ((old*a)+c)%1.0",
      },
      {
        name: "adparam",
        doc: "A parameter for the shape of the amplitude probability distribution, requires values in the range 0.0001 to 1 (there are safety checks in the code so don't worry too much if you want to modulate!)",
      },
      {
        name: "ampdist",
        doc: "Choice of probability distribution for the next perturbation of the amplitude of a control point. The distributions are (adapted from the GENDYN program in Formalized Music): 0- LINEAR, 1- CAUCHY, 2- LOGIST, 3- HYPERBCOS, 4- ARCSINE, 5- EXPON, 6- SINUS, Where the sinus (Xenakis' name) is in this implementation taken as sampling from a third party oscillator.",
      },
      {
        name: "ampscale",
        doc: "Normally 0.0 to 1.0, multiplier for the distribution's delta value for amplitude. An ampscale of 1.0 allows the full range of -1 to 1 for a change of amplitude.",
      },
      { name: "c", doc: "parameter for Lehmer random number generator perturbed by Xenakis" },
      {
        name: "ddparam",
        doc: "A parameter for the shape of the duration probability distribution, requires values in the range 0.0001 to 1",
      },
      {
        name: "durdist",
        doc: "Choice of distribution for the perturbation of the current inter control point duration.",
      },
      {
        name: "durscale",
        doc: "Normally 0.0 to 1.0, multiplier for the distribution's delta value for duration. An ampscale of 1.0 allows the full range of -1 to 1 for a change of duration.",
      },
      {
        name: "initCps",
        doc: "Initialise the number of control points in the memory. Xenakis specifies 12. There would be this number of control points per cycle of the oscillator, though the oscillator's period will constantly change due to the duration distribution.",
      },
      { name: "knum", doc: "Current number of utilised control points, allows modulation." },
      {
        name: "maxfreq",
        doc: "Maximum allowed frequency of oscillation for the Gendy1 oscillator, so gives the smallest period the duration is allowed to take on.",
      },
      {
        name: "minfreq",
        doc: "Minimum allowed frequency of oscillation for the Gendy1 oscillator, so gives the largest period the duration is allowed to take on.",
      },
    ],
  },
  {
    name: "Gendy3",
    rates: ["audio", "control"],
    defaults: [
      { name: "ampdist", default: 1 },
      { name: "durdist", default: 1 },
      { name: "adparam", default: 1 },
      { name: "ddparam", default: 1 },
      { name: "freq", default: 440 },
      { name: "ampscale", default: 0.5 },
      { name: "durscale", default: 0.5 },
      { name: "initCps", default: 12 },
      { name: "knum", default: 12 },
    ],
    numOutputs: null,
    extends: null,
    summary: null,
    doc: "See Gendy1 help file for background. This variant of GENDYN normalises the durations in each period to force oscillation at the desired pitch. The breakpoints still get perturbed as in Gendy1. There is some glitching in the oscillator caused by the stochastic effects: control points as they vary cause big local jumps of amplitude. Put ampscale and durscale low to minimise this. All parameters can be modulated at control rate except for initCPs which is used only at initialisation.",
    signalRange: null,
    argDocs: [
      {
        name: "adparam",
        doc: "A parameter for the shape of the amplitude probability distribution, requires values in the range 0.0001 to 1 (there are safety checks in the code so don't worry too much if you want to modulate!)",
      },
      {
        name: "ampdist",
        doc: "Choice of probability distribution for the next perturbation of the amplitude of a control point. The distributions are (adapted from the GENDYN program in Formalized Music): 0- LINEAR,1- CAUCHY, 2- LOGIST, 3- HYPERBCOS, 4- ARCSINE, 5- EXPON, 6- SINUS, Where the sinus (Xenakis' name) is in this implementation taken as sampling from a third party oscillator.",
      },
      {
        name: "ampscale",
        doc: "Normally 0.0 to 1.0, multiplier for the distribution's delta value for amplitude. An ampscale of 1.0 allows the full range of -1 to 1 for a change of amplitude.",
      },
      {
        name: "ddparam",
        doc: "A parameter for the shape of the duration probability distribution, requires values in the range 0.0001 to 1",
      },
      {
        name: "durdist",
        doc: "Choice of distribution for the perturbation of the current inter control point duration.",
      },
      {
        name: "durscale",
        doc: "Normally 0.0 to 1.0, multiplier for the distribution's delta value for duration. An ampscale of 1.0 allows the full range of -1 to 1 for a change of duration.",
      },
      { name: "freq", doc: "Oscillation frquency." },
      {
        name: "initCps",
        doc: "Initialise the number of control points in the memory. Xenakis specifies 12. There would be this number of control points per cycle of the oscillator, though the oscillator's period will constantly change due to the duration distribution.",
      },
      { name: "knum", doc: "Current number of utilised control points, allows modulation." },
    ],
  },
  {
    name: "Hilbert",
    rates: ["audio"],
    defaults: [{ name: "in", default: null }],
    numOutputs: 2,
    extends: null,
    summary: null,
    doc: null,
    signalRange: null,
    argDocs: [],
  },
  {
    name: "MoogFF",
    rates: ["audio", "control"],
    defaults: [
      { name: "in", default: 0 },
      { name: "freq", default: 100 },
      { name: "gain", default: 2 },
      { name: "reset", default: 0 },
    ],
    numOutputs: null,
    extends: null,
    summary: null,
    doc: "A digital implementation of the Moog VCF (filter).",
    signalRange: null,
    argDocs: [
      { name: "freq", doc: "The cutoff frequency" },
      { name: "gain", doc: "The filter resonance gain, between zero and 4" },
      { name: "in", doc: "The input signal" },
      {
        name: "reset",
        doc: "When greater than zero, this will reset the state of the digital filters at the beginning of a computational block.",
      },
    ],
  },
  {
    name: "PartConv",
    rates: ["audio"],
    defaults: [
      { name: "in", default: null },
      { name: "fftsize", default: null },
      { name: "irbufnum", default: null },
    ],
    numOutputs: null,
    extends: null,
    summary: null,
    doc: "Partitioned convolution. Various additional buffers must be supplied. Mono impulse response only! If inputting multiple channels, you'll need independent PartConvs, one for each channel. But the charm is: impulse response can be as large as you like (CPU load increases with IR size. Various tradeoffs based on fftsize choice, due to rarer but larger FFTs. This plug-in uses amortisation to spread processing and avoid spikes). Normalisation factors difficult to anticipate; convolution piles up multiple copies of the input on top of itself, so can easily overload.",
    signalRange: null,
    argDocs: [
      {
        name: "fftsize",
        doc: "Spectral convolution partition size (twice partition size). You must ensure that the blocksize divides the partition size and there are at least two blocks per partition (to allow for amortisation)",
      },
      { name: "in", doc: "Processing target." },
      {
        name: "irbufnum",
        doc: "Prepared buffer of spectra for each partition of the inpulse response",
      },
    ],
  },
  {
    name: "PitchShift",
    rates: ["audio"],
    defaults: [
      { name: "in", default: null },
      { name: "windowSize", default: 0.20000000298023224 },
      { name: "pitchRatio", default: 1 },
      { name: "pitchDispersion", default: 0 },
      { name: "timeDispersion", default: 0 },
    ],
    numOutputs: null,
    extends: null,
    summary: null,
    doc: "A time domain granular pitch shifter. Grains have a triangular amplitude envelope and an overlap of 4:1.",
    signalRange: null,
    argDocs: [
      { name: "in", doc: "The input signal." },
      {
        name: "pitchDispersion",
        doc: "The maximum random deviation of the pitch from the pitchRatio.",
      },
      { name: "pitchRatio", doc: "The ratio of the pitch shift. Must be from 0.0 to 4.0" },
      {
        name: "timeDispersion",
        doc: "A random offset of from zero to timeDispersion seconds is added to the delay of each grain. Use of some dispersion can alleviate a hard comb filter effect due to uniform grain placement. It can also be an effect in itself. timeDispersion can be no larger than windowSize.",
      },
      {
        name: "windowSize",
        doc: "The size of the grain window in seconds. This value cannot be modulated.",
      },
    ],
  },
  {
    name: "Pluck",
    rates: ["audio"],
    defaults: [
      { name: "in", default: 0 },
      { name: "trig", default: 1 },
      { name: "maxdelaytime", default: 0.20000000298023224 },
      { name: "delaytime", default: 0.20000000298023224 },
      { name: "decaytime", default: 1 },
      { name: "coef", default: 0.5 },
    ],
    numOutputs: null,
    extends: null,
    summary: null,
    doc: "Implements the Karplus-Strong style of synthesis, where a delay line (normally starting with noise) is filtered and fed back on itself so that over time it becomes periodic.",
    signalRange: null,
    argDocs: [
      {
        name: "coef",
        doc: "The coef of the internal OnePole filter. Values should be between -1 and +1 (larger values will be unstable... so be careful!).",
      },
      {
        name: "decaytime",
        doc: "Time for the echoes to decay by 60 decibels. Negative times emphasize odd partials.",
      },
      { name: "delaytime", doc: "Delay time in seconds." },
      { name: "in", doc: "An excitation signal." },
      {
        name: "maxdelaytime",
        doc: "The max delay time in seconds (initializes the internal delay buffer).",
      },
      {
        name: "trig",
        doc: "Upon a negative to positive transition, the excitation signal will be fed into the delay line.",
      },
    ],
  },
  {
    name: "Spring",
    rates: ["audio"],
    defaults: [
      { name: "in", default: 0 },
      { name: "spring", default: 0 },
      { name: "damp", default: 0 },
    ],
    numOutputs: null,
    extends: null,
    summary: null,
    doc: "Physical model of resonating spring",
    signalRange: null,
    argDocs: [
      { name: "damp", doc: "Damping" },
      { name: "in", doc: "Modulated input force" },
      { name: "spring", doc: "Spring constant (incl. mass)" },
    ],
  },
  {
    name: "TBall",
    rates: ["audio"],
    defaults: [
      { name: "in", default: 0 },
      { name: "g", default: 10 },
      { name: "damp", default: 0 },
      { name: "friction", default: 0.009999999776482582 },
    ],
    numOutputs: null,
    extends: null,
    summary: null,
    doc: "models the impacts of a bouncing object that is reflected by a vibrating surface",
    signalRange: null,
    argDocs: [
      { name: "damp", doc: "damping on impact" },
      { name: "friction", doc: "proximity from which on attraction to surface starts" },
      { name: "g", doc: "gravity" },
      { name: "in", doc: "modulated surface level" },
    ],
  },
];
