// GENERATED by scripts/generate-synthdef-compiler.sh — do not edit.
/** Instantiate the wasm: node (vitest included) feeds the bytes from disk,
 *  browsers let the glue fetch its own Vite-emitted asset. */
export function initWasm(): Promise<unknown>;
