/**
 * The binary boundary: the wasm-bindgen build of the scsynthdef-compiler
 * crate (`pkg/`, regenerated by `yarn generate:synthdef-compiler`).
 * Instantiation is explicit at module load — node (vitest included) feeds
 * the bytes from disk via the generated pkg/init.js loader, browsers fetch
 * the Vite-emitted asset. Everything below is synchronous afterwards.
 */

import { initWasm } from "../pkg/init.js";

await initWasm();

// The compiler core, re-exported as-is: the SynthDef graph-builder class,
// the SCgf parser, operator specialIndex lookups, and the envelope
// build/encode functions (error strings pinned by the app's tests).
export {
  SynthDef,
  binaryOpIndex,
  unaryOpIndex,
  buildEnvRun,
  encodeEnvRun,
  registryJson,
  envShapesJson,
} from "../pkg/scsynthdef_compiler.js";
export type { UGenInput, UGenInputLike } from "../pkg/scsynthdef_compiler.js";

import { parseScgf as parseScgfRaw } from "../pkg/scsynthdef_compiler.js";
import type { SynthDefJson } from "./scgf-json.js";

/** Parse SCgf v2 bytes into the structured JSON form. */
export function parseScgf(bytes: Uint8Array): SynthDefJson {
  return parseScgfRaw(bytes) as SynthDefJson;
}
