// GENERATED by scripts/generate-server-commands.sh — do not edit.
import init from "./scserver_commands.js";

/** Instantiate the wasm: node (vitest included) feeds the bytes from disk,
 *  browsers let the glue fetch its own Vite-emitted asset. */
export async function initWasm() {
  if (typeof process !== "undefined" && process.versions?.node) {
    const { readFile } = await import("node:fs/promises");
    const bytes = await readFile(new URL("./scserver_commands_bg.wasm", import.meta.url));
    return init({ module_or_path: bytes });
  }
  return init();
}
