#!/usr/bin/env bash
# Regenerate packages/server-commands/pkg — the wasm-bindgen build of the
# scserver-commands crate (the package's encode/decode engine, with
# tsify-generated TypeScript types whose discriminant IS the OSC address).
# The output is COMMITTED (like the generated XSD), so frontend work needs
# no wasm toolchain; rerun this whenever the crate changes.
#
# Prereqs (one-time):
#   rustup target add wasm32-unknown-unknown
#   cargo install wasm-pack
set -euo pipefail
cd "$(dirname "$0")/.."

rm -rf packages/server-commands/pkg
wasm-pack build src-tauri/crates/scserver-commands \
  --release --target web \
  --out-dir "$(pwd)/packages/server-commands/pkg" --out-name scserver_commands -- --features wasm

# wasm-pack writes an npm manifest + .gitignore into the out dir; this pkg is
# an internal committed artifact consumed by path, not published.
rm -f packages/server-commands/pkg/.gitignore packages/server-commands/pkg/package.json

# The dual-environment instantiation helper. It lives IN pkg/ on purpose:
# vitest externalizes pkg/ (vite.config.ts server.deps.external), so this
# module runs as native node ESM with a real file:// import.meta.url — the
# package's own TS sources are inlined through the vite pipeline where
# import.meta.url is NOT a file URL and fs loading would break.
cat > packages/server-commands/pkg/init.js <<'JSEOF'
// GENERATED by scripts/generate-server-commands.sh — do not edit.
import init from "./scserver_commands.js";

/** Instantiate the wasm: node (vitest included) feeds the bytes from disk,
 *  browsers let the glue fetch its own Vite-emitted asset. */
export async function initWasm() {
  if (typeof process !== "undefined" && process.versions?.node) {
    const { readFile } = await import("node:fs/promises");
    const bytes = await readFile(new URL("./scserver_commands_bg.wasm", import.meta.url));
    return init({ module_or_path: bytes });
  }
  return init();
}
JSEOF
cat > packages/server-commands/pkg/init.d.ts <<'DTSEOF'
// GENERATED by scripts/generate-server-commands.sh — do not edit.
/** Instantiate the wasm: node (vitest included) feeds the bytes from disk,
 *  browsers let the glue fetch its own Vite-emitted asset. */
export function initWasm(): Promise<unknown>;
DTSEOF

# The generated surface the package wraps — regenerating with a crate that
# lost one of these is a build break waiting to happen; fail here instead.
for sym in "export function encode" "export function decode_reply" "export type ServerReply"; do
  grep -q "$sym" packages/server-commands/pkg/scserver_commands.d.ts || {
    echo "ERROR: '$sym' missing from the generated .d.ts" >&2
    exit 1
  }
done
echo "OK: packages/server-commands/pkg regenerated"
