#!/usr/bin/env bash
# Regenerate packages/synthdef-compiler/pkg — the wasm-bindgen build of the
# scsynthdef-compiler crate (the package's encode/decode engine, with
# tsify-generated TypeScript types whose discriminant IS the OSC address).
# The output is COMMITTED (like the generated XSD), so frontend work needs
# no wasm toolchain; rerun this whenever the crate changes.
#
# Prereqs (one-time):
#   rustup target add wasm32-unknown-unknown
#   cargo install wasm-pack
set -euo pipefail
cd "$(dirname "$0")/.."

# Refresh the committed Rust registries before building their wasm surface.
yarn tsx packages/synthdef-compiler/scripts/generate-rust.ts

rm -rf packages/synthdef-compiler/pkg
wasm-pack build src-tauri/crates/scsynthdef-compiler \
  --release --target web \
  --out-dir "$(pwd)/packages/synthdef-compiler/pkg" --out-name scsynthdef_compiler -- --features wasm

# wasm-pack writes an npm manifest + .gitignore into the out dir; this pkg is
# an internal committed artifact consumed by path, not published.
rm -f packages/synthdef-compiler/pkg/.gitignore packages/synthdef-compiler/pkg/package.json

# The dual-environment instantiation helper. It lives IN pkg/ on purpose:
# vitest externalizes pkg/ (vite.config.ts server.deps.external), so this
# module runs as native node ESM with a real file:// import.meta.url — the
# package's own TS sources are inlined through the vite pipeline where
# import.meta.url is NOT a file URL and fs loading would break.
cat > packages/synthdef-compiler/pkg/init.js <<'JSEOF'
// GENERATED by scripts/generate-synthdef-compiler.sh — do not edit.
import init from "./scsynthdef_compiler.js";

/** Instantiate the wasm: node (vitest included) feeds the bytes from disk,
 *  browsers let the glue fetch its own Vite-emitted asset. */
export async function initWasm() {
  if (typeof process !== "undefined" && process.versions?.node) {
    const { readFile } = await import("node:fs/promises");
    const bytes = await readFile(new URL("./scsynthdef_compiler_bg.wasm", import.meta.url));
    return init({ module_or_path: bytes });
  }
  return init();
}
JSEOF
cat > packages/synthdef-compiler/pkg/init.d.ts <<'DTSEOF'
// GENERATED by scripts/generate-synthdef-compiler.sh — do not edit.
/** Instantiate the wasm: node (vitest included) feeds the bytes from disk,
 *  browsers let the glue fetch its own Vite-emitted asset. */
export function initWasm(): Promise<unknown>;
DTSEOF

# The generated surface the package wraps — regenerating with a crate that
# lost one of these is a build break waiting to happen; fail here instead.
for sym in "export class SynthDef" "export function parseScgf" "export class SinOsc" "export function buildEnvRun"; do
  grep -q "$sym" packages/synthdef-compiler/pkg/scsynthdef_compiler.d.ts || {
    echo "ERROR: '$sym' missing from the generated .d.ts" >&2
    exit 1
  }
done
echo "OK: packages/synthdef-compiler/pkg regenerated"
