//! Emits `OUT_DIR/commands_registry.rs` from the committed spec at
//! `assets/specs/server-commands.json` (repo root): one `sc_commands!`
//! invocation covering every standard SC command, plus the
//! `for_each_command!` callback macro that carries the full arm list into
//! `define_known_message!` (where `commands.rs` injects the hand-maintained
//! bridge arms).

use std::fmt::Write as _;
use std::path::Path;

use sc_spec_types::{CommandSpec, FieldForm, ListTy, OptionScalarTy, ScalarTy, TupleTy};

fn main() {
    let manifest = std::env::var("CARGO_MANIFEST_DIR").unwrap();
    let spec_path =
        Path::new(&manifest).join("../../../packages/server-commands/specs/server-commands.json");
    println!("cargo:rerun-if-changed={}", spec_path.display());

    let spec = sc_spec_types::load_commands(&spec_path)
        .unwrap_or_else(|e| panic!("invalid server-commands spec: {e}"));

    let mut out = String::from(
        "// @generated by build.rs from assets/specs/server-commands.json — do not edit.\n\n",
    );

    // The bridge commands are hand-maintained invocations in commands.rs
    // for now (step 2 of the migration generates them too).
    let spec_commands: Vec<_> = spec
        .commands
        .iter()
        .filter(|c| c.category != "bridge")
        .collect();

    out.push_str("sc_commands! {\n");
    for cmd in &spec_commands {
        render_command(&mut out, cmd);
    }
    out.push_str("}\n\n");

    // The callback list: define_known_message! receives the hand-written
    // bridge arms (all payload) first, then the spec arms.
    out.push_str("macro_rules! for_each_command {\n");
    out.push_str("    ($cb:ident { $($extra:tt)* }) => {\n");
    out.push_str("        $cb! {\n");
    out.push_str("            payload {\n");
    out.push_str("                $($extra)*\n");
    for cmd in spec_commands.iter().filter(|c| !c.fields.is_empty()) {
        writeln!(
            out,
            "                {} \"{}\",",
            cmd.struct_name, cmd.address
        )
        .unwrap();
    }
    out.push_str("            }\n");
    out.push_str("            unit {\n");
    for cmd in spec_commands.iter().filter(|c| c.fields.is_empty()) {
        writeln!(
            out,
            "                {} \"{}\",",
            cmd.struct_name, cmd.address
        )
        .unwrap();
    }
    out.push_str("            }\n");
    out.push_str("        }\n");
    out.push_str("    };\n");
    out.push_str("}\n");

    let out_path = Path::new(&std::env::var("OUT_DIR").unwrap()).join("commands_registry.rs");
    std::fs::write(&out_path, out).unwrap();
}

fn render_command(out: &mut String, cmd: &CommandSpec) {
    if let Some(doc) = &cmd.doc {
        push_doc(out, "    ", doc);
    }
    writeln!(out, "    \"{}\" {} {{", cmd.address, cmd.struct_name).unwrap();
    for field in &cmd.fields {
        if let Some(doc) = &field.doc {
            push_doc(out, "        ", doc);
        }
        let name = &field.name;
        let line = match &field.form {
            FieldForm::Scalar(t) => format!("scalar {name}: {}", scalar_ty(*t)),
            FieldForm::OptionScalar(t) => format!("opt {name}: {}", option_scalar_ty(*t)),
            FieldForm::Completion => format!("completion {name}"),
            FieldForm::Blob => format!("blob {name}"),
            FieldForm::List(t) => format!("list {name}: {}", list_ty(*t)),
            FieldForm::Variadic => format!("variadic {name}"),
            FieldForm::Tail(tys) => {
                let inner: Vec<&str> = tys.iter().map(|t| tuple_ty(*t)).collect();
                format!("tail {name}: ({})", inner.join(", "))
            }
            FieldForm::SetnTail { head, values } => {
                format!("setn {name}: ({}, {})", tuple_ty(*head), tuple_ty(*values))
            }
        };
        writeln!(out, "        {line},").unwrap();
    }
    out.push_str("    }\n");
}

fn push_doc(out: &mut String, indent: &str, doc: &str) {
    for line in doc.lines() {
        writeln!(
            out,
            "{indent}#[doc = \"{}\"]",
            line.replace('\\', "\\\\").replace('"', "\\\"")
        )
        .unwrap();
    }
}

fn scalar_ty(t: ScalarTy) -> &'static str {
    match t {
        ScalarTy::I32 => "i32",
        ScalarTy::F32 => "f32",
        ScalarTy::String => "String",
    }
}

fn option_scalar_ty(t: OptionScalarTy) -> &'static str {
    match t {
        OptionScalarTy::I32 => "i32",
        OptionScalarTy::F32 => "f32",
    }
}

fn list_ty(t: ListTy) -> &'static str {
    match t {
        ListTy::I32 => "i32",
        ListTy::String => "String",
        ListTy::ControlId => "ControlId",
    }
}

fn tuple_ty(t: TupleTy) -> &'static str {
    match t {
        TupleTy::I32 => "i32",
        TupleTy::F32 => "f32",
        TupleTy::String => "String",
        TupleTy::ControlId => "ControlId",
        TupleTy::NumericValue => "NumericValue",
        TupleTy::ControlValue => "ControlValue",
        TupleTy::OscArg => "OscArg",
    }
}
