// @generated by packages/server-commands/scripts/generate-rust.ts from specs/server-commands.json — do not edit.
// Regenerate with `yarn generate:server-commands`.

use serde::{Deserialize, Serialize};
#[cfg(feature = "wasm")]
use tsify::Tsify;

use crate::args::{osc_args, OscArg};
use crate::commands::OtherMsg;
use crate::{CommandError, OscMessage};

mod custom;
pub use custom::*;
pub(crate) use custom::{as_int, take_double, take_float, take_int, take_string};

#[doc = "Acknowledges an async command. `command` is the first wire arg — the address of the ACKNOWLEDGED command; the reply's own address, /done, is the serde tag."]
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[cfg_attr(feature = "wasm", derive(Tsify))]
#[serde(rename_all = "camelCase")]
pub struct DoneReply {
    #[doc = "Address of the command being acknowledged (e.g. /notify)."]
    pub command: String,
    #[doc = "Any additional args (e.g. the clientID a /notify ack echoes)."]
    pub extras: Vec<OscArg>,
}

#[doc = "An async command failed."]
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[cfg_attr(feature = "wasm", derive(Tsify))]
#[serde(rename_all = "camelCase")]
pub struct FailReply {
    #[doc = "Address of the command that failed."]
    pub command: String,
    #[doc = "The error message (empty when scsynth omits it)."]
    pub error: String,
    pub extras: Vec<OscArg>,
}

#[doc = "A bundle's timetag was already in the past when it arrived."]
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[cfg_attr(feature = "wasm", derive(Tsify))]
#[serde(rename_all = "camelCase")]
pub struct LateReply {
    pub seconds: i32,
    pub fractions: i32,
    pub late_secs: i32,
    pub late_fracs: i32,
}

#[doc = "Node notification (node started) — shared arg layout for the /n_* family; the last two fields are only present when the node is a group."]
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[cfg_attr(feature = "wasm", derive(Tsify))]
#[serde(rename_all = "camelCase")]
pub struct NodeInfo {
    pub node_id: i32,
    pub parent_id: i32,
    pub prev_node: i32,
    pub next_node: i32,
    #[doc = "1 if the node is a group, 0 if a synth."]
    pub is_group: i32,
    #[doc = "Present only when the node is a group."]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    #[cfg_attr(feature = "wasm", tsify(optional))]
    pub head_node: Option<i32>,
    #[doc = "Present only when the node is a group."]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    #[cfg_attr(feature = "wasm", tsify(optional))]
    pub tail_node: Option<i32>,
}

#[doc = "Reply to /status — the server's load and node counts."]
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[cfg_attr(feature = "wasm", derive(Tsify))]
#[serde(rename_all = "camelCase")]
pub struct StatusReply {
    pub unused: i32,
    pub num_ugens: i32,
    pub num_synths: i32,
    pub num_groups: i32,
    pub num_synth_defs: i32,
    pub avg_cpu: f32,
    pub peak_cpu: f32,
    pub nominal_sample_rate: f64,
    pub actual_sample_rate: f64,
}

#[doc = "A SendTrig fired."]
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[cfg_attr(feature = "wasm", derive(Tsify))]
#[serde(rename_all = "camelCase")]
pub struct TrReply {
    pub node_id: i32,
    pub trigger_id: i32,
    pub value: f32,
}

#[doc = "Samples read from a buffer in response to /b_getn. The wire carries bufnum, startIndex, N, then N samples."]
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[cfg_attr(feature = "wasm", derive(Tsify))]
#[serde(rename_all = "camelCase")]
pub struct BSetnReply {
    pub bufnum: i32,
    pub start: i32,
    pub samples: Vec<f32>,
}

#[doc = "Response to a /sync command — carries the sync id supplied by the client so callers can correlate request and reply."]
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[cfg_attr(feature = "wasm", derive(Tsify))]
#[serde(rename_all = "camelCase")]
pub struct SyncedReply {
    pub sync_id: i32,
}

/// Every catalogued server-to-client reply, one variant per address —
/// adjacently tagged like the command side: a decoded reply crosses the
/// wasm boundary as `{ "address": "/n_go", "args": { …fields } }`.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[cfg_attr(feature = "wasm", derive(Tsify))]
#[serde(tag = "address", content = "args")]
pub enum KnownReply {
    #[doc = "Acknowledges an async command. `command` is the first wire arg — the address of the ACKNOWLEDGED command; the reply's own address, /done, is the serde tag."]
    #[serde(rename = "/done")]
    Done(DoneReply),
    #[doc = "An async command failed."]
    #[serde(rename = "/fail")]
    Fail(FailReply),
    #[doc = "A bundle's timetag was already in the past when it arrived."]
    #[serde(rename = "/late")]
    Late(LateReply),
    #[doc = "Node notification (node started) — shared arg layout for the /n_* family; the last two fields are only present when the node is a group."]
    #[serde(rename = "/n_go")]
    NGo(NodeInfo),
    #[doc = "Node notification (node ended) — shared arg layout for the /n_* family; the last two fields are only present when the node is a group."]
    #[serde(rename = "/n_end")]
    NEnd(NodeInfo),
    #[doc = "Node notification (node resumed) — shared arg layout for the /n_* family; the last two fields are only present when the node is a group."]
    #[serde(rename = "/n_on")]
    NOn(NodeInfo),
    #[doc = "Node notification (node paused) — shared arg layout for the /n_* family; the last two fields are only present when the node is a group."]
    #[serde(rename = "/n_off")]
    NOff(NodeInfo),
    #[doc = "Node notification (node moved) — shared arg layout for the /n_* family; the last two fields are only present when the node is a group."]
    #[serde(rename = "/n_move")]
    NMove(NodeInfo),
    #[doc = "Node notification (reply to /n_query) — shared arg layout for the /n_* family; the last two fields are only present when the node is a group."]
    #[serde(rename = "/n_info")]
    NInfo(NodeInfo),
    #[doc = "Reply to /status — the server's load and node counts."]
    #[serde(rename = "/status.reply")]
    StatusReply(StatusReply),
    #[doc = "A SendTrig fired."]
    #[serde(rename = "/tr")]
    Tr(TrReply),
    #[doc = "Samples read from a buffer in response to /b_getn. The wire carries bufnum, startIndex, N, then N samples."]
    #[serde(rename = "/b_setn")]
    BSetn(BSetnReply),
    #[doc = "Response to a /sync command — carries the sync id supplied by the client so callers can correlate request and reply."]
    #[serde(rename = "/synced")]
    Synced(SyncedReply),
    #[doc = "sc-app bridge extension: one streamed scope chunk (bridge-emitted; big-endian float32 blob with a native-endian encode fast path — the struct, parser and encoders are hand-written)."]
    #[serde(rename = "/scope/chunk")]
    ScopeChunk(ScopeChunkReply),
    #[doc = "Reply to /g_queryTree — the depth-first node tree, with per-synth controls when the query asked for them (variable recursive layout; the struct and parser are hand-written)."]
    #[serde(rename = "/g_queryTree.reply")]
    QueryTree(QueryTreeReply),
}

/// A reply in transit: catalogued, or the raw fallback for any address the
/// parser doesn't know (shares [`OtherMsg`] with the command side). Plain
/// enum — the wasm boundary serializes each arm itself, so no serde here.
#[derive(Debug, Clone, PartialEq)]
pub enum ServerReply {
    Known(KnownReply),
    Other(OtherMsg),
}

impl ServerReply {
    /// Decode raw OSC reply bytes into a typed variant.
    pub fn decode(bytes: &[u8]) -> Result<Self, CommandError> {
        Self::from_message(OscMessage::decode(bytes)?)
    }

    /// Dispatch an already-decoded message into the typed variant whose
    /// OSC address it matches. Unknown addresses become `Other(..)`.
    pub fn from_message(msg: OscMessage) -> Result<Self, CommandError> {
        let known = |k: KnownReply| Ok(Self::Known(k));
        match msg.address.as_str() {
            "/done" => known(KnownReply::Done(DoneReply {
                command: take_string(&msg, 0, "/done")?,
                extras: msg.args.get(1..).map(osc_args).unwrap_or_default(),
            })),
            "/fail" => known(KnownReply::Fail(FailReply {
                command: take_string(&msg, 0, "/fail")?,
                error: take_string(&msg, 1, "/fail").unwrap_or_default(),
                extras: msg.args.get(2..).map(osc_args).unwrap_or_default(),
            })),
            "/late" => known(KnownReply::Late(LateReply {
                seconds: take_int(&msg, 0, "/late")?,
                fractions: take_int(&msg, 1, "/late")?,
                late_secs: take_int(&msg, 2, "/late")?,
                late_fracs: take_int(&msg, 3, "/late")?,
            })),
            "/n_go" => known(KnownReply::NGo(NodeInfo {
                node_id: take_int(&msg, 0, "/n_go")?,
                parent_id: take_int(&msg, 1, "/n_go")?,
                prev_node: take_int(&msg, 2, "/n_go")?,
                next_node: take_int(&msg, 3, "/n_go")?,
                is_group: take_int(&msg, 4, "/n_go")?,
                head_node: msg.args.get(5).and_then(as_int),
                tail_node: msg.args.get(6).and_then(as_int),
            })),
            "/n_end" => known(KnownReply::NEnd(NodeInfo {
                node_id: take_int(&msg, 0, "/n_end")?,
                parent_id: take_int(&msg, 1, "/n_end")?,
                prev_node: take_int(&msg, 2, "/n_end")?,
                next_node: take_int(&msg, 3, "/n_end")?,
                is_group: take_int(&msg, 4, "/n_end")?,
                head_node: msg.args.get(5).and_then(as_int),
                tail_node: msg.args.get(6).and_then(as_int),
            })),
            "/n_on" => known(KnownReply::NOn(NodeInfo {
                node_id: take_int(&msg, 0, "/n_on")?,
                parent_id: take_int(&msg, 1, "/n_on")?,
                prev_node: take_int(&msg, 2, "/n_on")?,
                next_node: take_int(&msg, 3, "/n_on")?,
                is_group: take_int(&msg, 4, "/n_on")?,
                head_node: msg.args.get(5).and_then(as_int),
                tail_node: msg.args.get(6).and_then(as_int),
            })),
            "/n_off" => known(KnownReply::NOff(NodeInfo {
                node_id: take_int(&msg, 0, "/n_off")?,
                parent_id: take_int(&msg, 1, "/n_off")?,
                prev_node: take_int(&msg, 2, "/n_off")?,
                next_node: take_int(&msg, 3, "/n_off")?,
                is_group: take_int(&msg, 4, "/n_off")?,
                head_node: msg.args.get(5).and_then(as_int),
                tail_node: msg.args.get(6).and_then(as_int),
            })),
            "/n_move" => known(KnownReply::NMove(NodeInfo {
                node_id: take_int(&msg, 0, "/n_move")?,
                parent_id: take_int(&msg, 1, "/n_move")?,
                prev_node: take_int(&msg, 2, "/n_move")?,
                next_node: take_int(&msg, 3, "/n_move")?,
                is_group: take_int(&msg, 4, "/n_move")?,
                head_node: msg.args.get(5).and_then(as_int),
                tail_node: msg.args.get(6).and_then(as_int),
            })),
            "/n_info" => known(KnownReply::NInfo(NodeInfo {
                node_id: take_int(&msg, 0, "/n_info")?,
                parent_id: take_int(&msg, 1, "/n_info")?,
                prev_node: take_int(&msg, 2, "/n_info")?,
                next_node: take_int(&msg, 3, "/n_info")?,
                is_group: take_int(&msg, 4, "/n_info")?,
                head_node: msg.args.get(5).and_then(as_int),
                tail_node: msg.args.get(6).and_then(as_int),
            })),
            "/status.reply" => known(KnownReply::StatusReply(StatusReply {
                unused: take_int(&msg, 0, "/status.reply")?,
                num_ugens: take_int(&msg, 1, "/status.reply")?,
                num_synths: take_int(&msg, 2, "/status.reply")?,
                num_groups: take_int(&msg, 3, "/status.reply")?,
                num_synth_defs: take_int(&msg, 4, "/status.reply")?,
                avg_cpu: take_float(&msg, 5, "/status.reply")?,
                peak_cpu: take_float(&msg, 6, "/status.reply")?,
                nominal_sample_rate: take_double(&msg, 7, "/status.reply")?,
                actual_sample_rate: take_double(&msg, 8, "/status.reply")?,
            })),
            "/tr" => known(KnownReply::Tr(TrReply {
                node_id: take_int(&msg, 0, "/tr")?,
                trigger_id: take_int(&msg, 1, "/tr")?,
                value: take_float(&msg, 2, "/tr")?,
            })),
            "/b_setn" => {
                // wire: …, N, sample0 … sampleN-1
                let count = take_int(&msg, 2, "/b_setn")? as usize;
                let mut samples = Vec::with_capacity(count);
                for i in 0..count {
                    samples.push(take_float(&msg, 3 + i, "/b_setn")?);
                }
                known(KnownReply::BSetn(BSetnReply {
                    bufnum: take_int(&msg, 0, "/b_setn")?,
                    start: take_int(&msg, 1, "/b_setn")?,
                    samples: samples,
                }))
            }
            "/synced" => known(KnownReply::Synced(SyncedReply {
                sync_id: take_int(&msg, 0, "/synced")?,
            })),
            "/scope/chunk" => known(KnownReply::ScopeChunk(ScopeChunkReply::parse(&msg)?)),
            "/g_queryTree.reply" => known(KnownReply::QueryTree(QueryTreeReply::parse(&msg)?)),
            _ => Ok(Self::Other(OtherMsg {
                address: msg.address,
                args: osc_args(&msg.args),
            })),
        }
    }
}
