// @generated by packages/synthdef-compiler/scripts/generate-rust.ts from specs/ugens.json — do not edit.
// Regenerate with `yarn generate:synthdef-compiler`.

#![allow(
    non_camel_case_types,
    unused_mut,
    unused_variables,
    clippy::useless_conversion,
    clippy::needless_update
)]

use crate::{Rate, SynthDef, UGenInput};

sc_ugens! {
    #[doc = "Multiply the input source by mul then add the add value. Equivalent to, but more efficient than, (+ add (* mul in))"]
    MulAdd class r"MulAdd" {
        rates [ (ir, Scalar), (ar, Audio), (kr, Control) ]
        fields [
            #[doc = "Input to modify"]
            input r#in: UGenInput = UGenInput::Constant(0.0),
            #[doc = "Multiplier Value"]
            input mul: UGenInput = UGenInput::Constant(0.0),
            #[doc = "Addition Value"]
            input add: UGenInput = UGenInput::Constant(0.0),
        ]
        outputs ( fixed 1 )
        push [ (input r#in), (input mul), (input add) ]
    }
}
