// @generated by packages/synthdef-compiler/scripts/generate-rust.ts from specs/ugens.json — do not edit.
// Regenerate with `yarn generate:synthdef-compiler`.

#![allow(
    non_camel_case_types,
    unused_mut,
    unused_variables,
    clippy::useless_conversion,
    clippy::needless_update
)]

use crate::{Rate, SynthDef, UGenInput};

sc_ugens! {
    #[doc = "All pass filter based on the Second Order Section (SOS) biquad UGen"]
    BAllPass class r"BAllPass" {
        rates [ (ar, Audio) ]
        fields [
            #[doc = "input signal to be processed."]
            input r#in: UGenInput = UGenInput::Constant(0.0),
            #[doc = "center frequency."]
            input freq: UGenInput = UGenInput::Constant(1200.0),
            #[doc = "the reciprocal of Q. bandwidth / cutoffFreq."]
            input rq: UGenInput = UGenInput::Constant(1.0),
        ]
        outputs ( fixed 1 )
        push [ (input r#in), (input freq), (input rq) ]
    }
    #[doc = "Band pass filter based on the Second Order Section (SOS) biquad UGen"]
    BBandPass class r"BBandPass" {
        rates [ (ar, Audio) ]
        fields [
            #[doc = "input signal to be processed"]
            input r#in: UGenInput = UGenInput::Constant(0.0),
            #[doc = "center frequency"]
            input freq: UGenInput = UGenInput::Constant(1200.0),
            #[doc = "the bandwidth in octaves between -3 dB frequencies"]
            input bw: UGenInput = UGenInput::Constant(1.0),
        ]
        outputs ( fixed 1 )
        push [ (input r#in), (input freq), (input bw) ]
    }
    #[doc = "Band reject filter based on the Second Order Section (SOS) biquad UGen"]
    BBandStop class r"BBandStop" {
        rates [ (ar, Audio) ]
        fields [
            #[doc = "input signal to be processed"]
            input r#in: UGenInput = UGenInput::Constant(0.0),
            #[doc = "center frequency"]
            input freq: UGenInput = UGenInput::Constant(1200.0),
            #[doc = "the bandwidth in octaves between -3 dB frequencies"]
            input bw: UGenInput = UGenInput::Constant(1.0),
        ]
        outputs ( fixed 1 )
        push [ (input r#in), (input freq), (input bw) ]
    }
    #[doc = "12db/oct rolloff - 2nd order resonant Hi Pass Filter based on the Second Order Section (SOS) biquad UGen."]
    BHiPass class r"BHiPass" {
        rates [ (ar, Audio) ]
        fields [
            #[doc = "input signal to be processed"]
            input r#in: UGenInput = UGenInput::Constant(0.0),
            #[doc = "cutoff frequency"]
            input freq: UGenInput = UGenInput::Constant(1200.0),
            #[doc = "the reciprocal of Q. bandwidth / cutoffFreq"]
            input rq: UGenInput = UGenInput::Constant(1.0),
        ]
        outputs ( fixed 1 )
        push [ (input r#in), (input freq), (input rq) ]
    }
    #[doc = "Hi shelfbased on the Second Order Section (SOS) biquad UGen"]
    BHiShelf class r"BHiShelf" {
        rates [ (ar, Audio) ]
        fields [
            #[doc = "input signal to be processed"]
            input r#in: UGenInput = UGenInput::Constant(0.0),
            #[doc = "center frequency"]
            input freq: UGenInput = UGenInput::Constant(1200.0),
            #[doc = "the reciprocal of S. Shell boost/cut slope. When S = 1, the shelf slope is as steep as it can be and remain monotonically increasing or decreasing gain with frequency. The shelf slope, in dB/octave, remains proportional to S for all other values for a fixed freq/SampleRate.ir and db."]
            input rs: UGenInput = UGenInput::Constant(1.0),
            #[doc = "gain. boost/cut the center frequency in dBs"]
            input db: UGenInput = UGenInput::Constant(0.0),
        ]
        outputs ( fixed 1 )
        push [ (input r#in), (input freq), (input rs), (input db) ]
    }
    #[doc = "12db/oct rolloff - 2nd order resonant Low Pass Filter based on the Second Order Section (SOS) biquad UGen"]
    BLowPass class r"BLowPass" {
        rates [ (ar, Audio) ]
        fields [
            #[doc = "input signal to be processed"]
            input r#in: UGenInput = UGenInput::Constant(0.0),
            #[doc = "cutoff frequency"]
            input freq: UGenInput = UGenInput::Constant(1200.0),
            #[doc = "the reciprocal of Q. bandwidth / cutoffFreq"]
            input rq: UGenInput = UGenInput::Constant(1.0),
        ]
        outputs ( fixed 1 )
        push [ (input r#in), (input freq), (input rq) ]
    }
    #[doc = "Low shelf based on the Second Order Section (SOS) biquad UGen"]
    BLowShelf class r"BLowShelf" {
        rates [ (ar, Audio) ]
        fields [
            #[doc = "input signal to be processed"]
            input r#in: UGenInput = UGenInput::Constant(0.0),
            #[doc = "center frequency"]
            input freq: UGenInput = UGenInput::Constant(1200.0),
            #[doc = "the reciprocal of S. Shell boost/cut slope. When S = 1, the shelf slope is as steep as it can be and remain monotonically increasing or decreasing gain with frequency. The shelf slope, in dB/octave, remains proportional to S for all other values for a fixed freq/SampleRate.ir and db."]
            input rs: UGenInput = UGenInput::Constant(1.0),
            #[doc = "gain. boost/cut the center frequency in dBs"]
            input db: UGenInput = UGenInput::Constant(0.0),
        ]
        outputs ( fixed 1 )
        push [ (input r#in), (input freq), (input rs), (input db) ]
    }
    #[doc = "Parametric equalizer based on the Second Order Section (SOS) biquad UGen"]
    BPeakEQ class r"BPeakEQ" {
        rates [ (ar, Audio) ]
        fields [
            #[doc = "input signal to be processed"]
            input r#in: UGenInput = UGenInput::Constant(0.0),
            #[doc = "center frequency"]
            input freq: UGenInput = UGenInput::Constant(1200.0),
            #[doc = "the reciprocal of Q. bandwidth / cutoffFreq"]
            input rq: UGenInput = UGenInput::Constant(1.0),
            #[doc = "boost/cut the center frequency (in dBs)"]
            input db: UGenInput = UGenInput::Constant(0.0),
        ]
        outputs ( fixed 1 )
        push [ (input r#in), (input freq), (input rq), (input db) ]
    }
}
