// @generated by packages/synthdef-compiler/scripts/generate-rust.ts from specs/ugens.json — do not edit.
// Regenerate with `yarn generate:synthdef-compiler`.

#![allow(
    non_camel_case_types,
    unused_mut,
    unused_variables,
    clippy::useless_conversion,
    clippy::needless_update
)]

use crate::{Rate, SynthDef, UGenInput};

sc_ugens! {
    #[doc = "Amplitude follower"]
    #[doc = ""]
    #[doc = "Tracks the peak amplitude of a signal."]
    Amplitude class r"Amplitude" {
        rates [ (ar, Audio), (kr, Control) ]
        fields [
            #[doc = "input signal"]
            input r#in: UGenInput = UGenInput::Constant(0.0),
            #[doc = "60dB convergence time for following attacks"]
            input attack_time: UGenInput = UGenInput::Constant(0.01),
            #[doc = "60dB convergence time for following decays"]
            input release_time: UGenInput = UGenInput::Constant(0.01),
        ]
        outputs ( fixed 1 )
        push [ (input r#in), (input attack_time), (input release_time) ]
    }
    #[doc = "General purpose hard-knee dynamic range processor."]
    #[doc = ""]
    #[doc = "The compander will modify the amplitude of the in signal based on an analysis of the control signal. Typically the in and control signals are the same. The amplitude of the control signal is calcuated using RMS (Root Mean Square) and the final amplitude of the in signal is calculated as a function of the amplitude threshold, and slopes either side (below and above) with some temporal modifications in terms of attack and release phases. It is a hard-knee processor which means that the response curve is a sharp angle rather than a rounded edge. If the control amplitude is less than the threshold, the slope below is used to calculate the amplitude modification. If this is steep (greater than 1) this will reduce the amplitude of quiet signals (the quieter the control amplitude the greater the reduction affect). Values < 1.0 are possible, but it means that a very low-level control signal will cause the input signal to be amplified, which would raise the noise floor. If the control amplitude is greater than the threshold, the slope above is used to calculate the amplitude modification. If this is steep (greater than 1) this will create expansion - loud signals will be made louder). Less than 1 will achieve compressions (louder signals are attenuated). The clamp and relax times modify when the amplitude modification takes place and ends. May be used to define: compressers, expanders, limiters, gates and duckers. For more information see: http://en.wikipedia.org/wiki/Audio_level_compression"]
    Compander class r"Compander" {
        rates [ (ar, Audio) ]
        fields [
            #[doc = "The signal to be compressed / expanded / gated"]
            input r#in: UGenInput = UGenInput::Constant(0.0),
            #[doc = "The signal whose amplitude determines the gain applied to the input signal. Often the same as in (for standard gating or compression) but should be different for ducking."]
            input control: UGenInput = UGenInput::Constant(0.0),
            #[doc = "Control signal amplitude threshold, which determines the break point between slope-below and slope-above. Typically a value between 0 and 1."]
            input thresh: UGenInput = UGenInput::Constant(0.5),
            #[doc = "Slope of the amplitude curve below the threshold. A value of 1 means the output amplitude will match the control signal amplitude."]
            input slope_below: UGenInput = UGenInput::Constant(1.0),
            #[doc = "Slope of the amplitude curve above the threshold. A value of 1 means the output amplitude will match the control signal amplitude."]
            input slope_above: UGenInput = UGenInput::Constant(1.0),
            #[doc = "Time taken for the amplitude adjustment to kick in fully (in seconds). This is usually pretty small, not much more than 10 milliseconds (the default value). Also known as the time of the attack phase."]
            input clamp_time: UGenInput = UGenInput::Constant(0.01),
            #[doc = "The amount of time for the amplitude adjustment to be released. Usually a bit longer than clamp-time; if both times are too short, you can get some (possibly unwanted) artifacts. Also known as the time of the release phase."]
            input relax_time: UGenInput = UGenInput::Constant(0.1),
        ]
        outputs ( fixed 1 )
        push [ (input r#in), (input control), (input thresh), (input slope_below), (input slope_above), (input clamp_time), (input relax_time) ]
    }
    #[doc = "Limits the input amplitude to the given level. Limiter will not overshoot like Compander will, but it needs to look ahead in the audio. Thus there is a delay equal to twice the lookAheadTime. Limiter, unlike Compander, is completely transparent for an in range signal."]
    Limiter class r"Limiter" {
        rates [ (ar, Audio) ]
        fields [
            #[doc = "The input signal"]
            input r#in: UGenInput = UGenInput::Constant(0.0),
            #[doc = "The peak output amplitude level to which to normalize the input"]
            input level: UGenInput = UGenInput::Constant(1.0),
            #[doc = "The buffer delay time. Shorter times will produce smaller delays and quicker transient response times, but may introduce amplitude modulation artifacts. (AKA lookAheadTime)"]
            input dur: UGenInput = UGenInput::Constant(0.01),
        ]
        outputs ( fixed 1 )
        push [ (input r#in), (input level), (input dur) ]
    }
    #[doc = "flattens dynamics. Normalizes the input amplitude to the given level. Normalize will not overshoot like Compander will, but it needs to look ahead in the audio. Thus there is a delay equal to twice the lookAheadTime."]
    Normalizer class r"Normalizer" {
        rates [ (ar, Audio) ]
        fields [
            #[doc = "The input signal"]
            input r#in: UGenInput = UGenInput::Constant(0.0),
            #[doc = "The peak output amplitude level to which to normalize the input"]
            input level: UGenInput = UGenInput::Constant(1.0),
            #[doc = "The buffer delay time. Shorter times will produce smaller delays and quicker transient response times, but may introduce amplitude modulation artifacts. (AKA lookAheadTime)"]
            input dur: UGenInput = UGenInput::Constant(0.01),
        ]
        outputs ( fixed 1 )
        push [ (input r#in), (input level), (input dur) ]
    }
}
