// @generated by packages/synthdef-compiler/scripts/generate-rust.ts from specs/ugens.json — do not edit.
// Regenerate with `yarn generate:synthdef-compiler`.

#![allow(
    non_camel_case_types,
    unused_mut,
    unused_variables,
    clippy::useless_conversion,
    clippy::needless_update
)]

use crate::{Rate, SynthDef, UGenInput};

sc_ugens! {
    #[doc = "On every trigger it demands the next value from each of the demand ugens passed as args. Used to pull values from the other demand rate ugens. By design, a reset trigger only resets the demand ugens; it does not reset the value at Demand's output. Demand continues to hold its value until the next value is demanded, at which point its output value will be the first expected item in the list."]
    Demand class r"Demand" {
        rates [ (ar, Audio), (kr, Control) ]
        fields [
            #[doc = "Can be any signal. A trigger happens when the signal changes from non-positive to positive."]
            input trig: UGenInput = UGenInput::Constant(0.0),
            #[doc = "Resets the list of ugens when triggered."]
            input reset: UGenInput = UGenInput::Constant(0.0),
            #[doc = "list of demand rate ugens"]
            input demand_ugens: UGenInput = UGenInput::Constant(0.0),
        ]
        outputs ( fixed 1 )
        push [ (input trig), (input reset), (input demand_ugens) ]
    }
    #[doc = "Plays back break point envelope contours (levels, times, shapes) given by demand ugens. The next values are called when the next node is reached."]
    DemandEnvGen class r"DemandEnvGen" {
        rates [ (ar, Audio), (kr, Control) ]
        fields [
            #[doc = "demand ugen (or other ugen) returning level values"]
            input level: UGenInput = UGenInput::Constant(0.0),
            #[doc = "demand ugen (or other ugen) returning time values"]
            input dur: UGenInput = UGenInput::Constant(0.0),
            #[doc = "demand ugen (or other ugen) returning shape number - the number given is the shape number"]
            input shape: UGenInput = UGenInput::Constant(1.0),
            #[doc = "demand ugen (or other ugen) returning curve values - if shape is 5, this is the curve factor. The possible values are: 0 - flat segments, 1 - linear segments, the default, 2 - natural exponential growth and decay. In this case, the levels must all be nonzero and the have the same sign, 3 - sinusoidal S shaped segments, 4 - sinusoidal segments shaped like the sides of a Welch window, a Float - a curvature value for all segments, an Array of Floats - curvature values for each segments."]
            input curve: UGenInput = UGenInput::Constant(0.0),
            #[doc = "control rate gate if gate is x >= 1, the ugen runs, if gate is 0 > x > 1, the ugen is released at the next level (doneAction), if gate is x <= 0, the ugen is sampled end held"]
            input gate: UGenInput = UGenInput::Constant(1.0),
            #[doc = "if reset crosses from nonpositive to positive, the ugen is reset at the next level. If it is > 1, it is reset immediately."]
            input reset: UGenInput = UGenInput::Constant(1.0),
            #[doc = "demand ugen returning level scaling values"]
            input level_scale: UGenInput = UGenInput::Constant(1.0),
            #[doc = "demand ugen returning level offset values"]
            input level_bias: UGenInput = UGenInput::Constant(0.0),
            #[doc = "demand ugen returning time scaling values"]
            input time_scale: UGenInput = UGenInput::Constant(1.0),
            #[doc = "Default: NO-ACTION"]
            input action: UGenInput = UGenInput::Constant(0.0),
        ]
        outputs ( fixed 1 )
        push [ (input level), (input dur), (input shape), (input curve), (input gate), (input reset), (input level_scale), (input level_bias), (input time_scale), (input action) ]
    }
    #[doc = "This ugen has been internalised for scserver compatibility. Please use the duty cgen instead."]
    Duty class r"Duty" {
        rates [ (ar, Audio), (kr, Control) ]
        fields [
            input dur: UGenInput = UGenInput::Constant(1.0),
            input reset: UGenInput = UGenInput::Constant(0.0),
            #[doc = "Default: NO-ACTION"]
            input action: UGenInput = UGenInput::Constant(0.0),
            input level: UGenInput = UGenInput::Constant(1.0),
        ]
        outputs ( fixed 1 )
        push [ (input dur), (input reset), (input action), (input level) ]
    }
    #[doc = "This ugen has been internalised for scserver compatibility. Please use the tduty cgen instead."]
    TDuty class r"TDuty" {
        rates [ (ar, Audio), (kr, Control) ]
        fields [
            input dur: UGenInput = UGenInput::Constant(1.0),
            input reset: UGenInput = UGenInput::Constant(0.0),
            #[doc = "Default: NO-ACTION"]
            input action: UGenInput = UGenInput::Constant(0.0),
            input level: UGenInput = UGenInput::Constant(1.0),
            input gap_first: UGenInput = UGenInput::Constant(0.0),
        ]
        outputs ( fixed 1 )
        push [ (input dur), (input reset), (input action), (input level), (input gap_first) ]
    }
}
