// @generated by packages/synthdef-compiler/scripts/generate-rust.ts from specs/ugens.json — do not edit.
// Regenerate with `yarn generate:synthdef-compiler`.

#![allow(
    non_camel_case_types,
    unused_mut,
    unused_variables,
    clippy::useless_conversion,
    clippy::needless_update
)]

use crate::{Rate, SynthDef, UGenInput};

sc_ugens! {
    #[doc = "Outputs a one when the src ugen (typically an envelope) has finished"]
    Done class r"Done" {
        rates [ (kr, Control) ]
        fields [
            #[doc = "ugen to monitor"]
            input src: UGenInput = UGenInput::Constant(0.0),
        ]
        outputs ( fixed 1 )
        push [ (input src) ]
    }
    #[doc = "envelope generator, interpolates across a path of control points over time, see the overtone.sc.envelope functions to generate the control points array Note: The actual minimum duration of a segment is not zero, but one sample step for audio rate and one block for control rate. This may result in asynchronicity when in two envelopes of different number of levels, the envelope times add up to the same total duration. Similarly, when modulating times, the new time is only updated at the end of the current segment - this may lead to asynchronicity of two envelopes with modulated times."]
    EnvGen class r"EnvGen" {
        rates [ (ar, Audio), (kr, Control) ]
        fields [
            #[doc = "an Array of Controls."]
            input envelope: UGenInput = UGenInput::Constant(0.0),
            #[doc = "this triggers the envelope and holds it open while > 0. If the envelope is fixed-length (e.g. perc), the gate argument is used as a simple trigger. If it is an sustaining envelope (e.g. adsr, asr), the envelope is held open until the gate becomes 0, at which point is released. If the gate of an env-gen is set to -1 or below, then the envelope will cutoff immediately. The time for it to cutoff is the amount less than -1, with -1 being as fast as possible, -1.5 being a cutoff in 0.5 seconds, etc. The cutoff shape is linear."]
            input gate: UGenInput = UGenInput::Constant(1.0),
            #[doc = "scales the levels of the breakpoints."]
            input level_scale: UGenInput = UGenInput::Constant(1.0),
            #[doc = "offsets the levels of the breakpoints."]
            input level_bias: UGenInput = UGenInput::Constant(0.0),
            #[doc = "scales the durations of the segments."]
            input time_scale: UGenInput = UGenInput::Constant(1.0),
            #[doc = "an integer representing an action to be executed when the env is finished playing. This can be used to free the enclosing synth, etc."]
            input action: UGenInput = UGenInput::Constant(0.0),
        ]
        outputs ( fixed 1 )
        push [ (input envelope), (input gate), (input level_scale), (input level_bias), (input time_scale), (input action) ]
    }
    #[doc = "Free the specified node when triggered"]
    Free class r"Free" {
        rates [ (kr, Control) ]
        fields [
            #[doc = "when triggered, frees node"]
            input trig: UGenInput = UGenInput::Constant(0.0),
            #[doc = "node to be freed"]
            input id: UGenInput = UGenInput::Constant(0.0),
        ]
        outputs ( fixed 1 )
        push [ (input trig), (input id) ]
    }
    #[doc = "Free the enclosing synth when triggered"]
    FreeSelf class r"FreeSelf" {
        rates [ (kr, Control) ]
        fields [
            #[doc = "input signal"]
            input r#in: UGenInput = UGenInput::Constant(0.0),
        ]
        outputs ( fixed 1 )
        push [ (input r#in) ]
    }
    #[doc = "Free the enclosing synth when the src ugen finishes (e.g. env-gen, play-buf, linen...)"]
    FreeSelfWhenDone class r"FreeSelfWhenDone" {
        rates [ (kr, Control) ]
        fields [
            #[doc = "the ugen to check for done"]
            input src: UGenInput = UGenInput::Constant(0.0),
        ]
        outputs ( fixed 1 )
        push [ (input src) ]
    }
    IEnvGen class r"IEnvGen" {
        rates [ (ar, Audio), (kr, Control) ]
        fields [
            #[doc = "an InterplEnv (this is static for the life of the UGen)"]
            input ienvelope: UGenInput = UGenInput::Constant(0.0),
            #[doc = "a point to access within the InterplEnv"]
            input index: UGenInput = UGenInput::Constant(0.0),
        ]
        outputs ( fixed 1 )
        push [ (input ienvelope), (input index) ]
    }
    #[doc = "A linear envelope generator, rises to sus-level over attack-time seconds and after the gate goes non-positive falls over release-time to finally perform the (optional) action"]
    Linen class r"Linen" {
        rates [ (kr, Control) ]
        fields [
            #[doc = "Input trigger"]
            input gate: UGenInput = UGenInput::Constant(1.0),
            #[doc = "Time taken to rise to susLevel in seconds"]
            input attack_time: UGenInput = UGenInput::Constant(0.01),
            #[doc = "Level to hold the envelope at until gate is triggered"]
            input sus_level: UGenInput = UGenInput::Constant(1.0),
            #[doc = "Time to fall from susLevel back to 0 after the gate has been triggered"]
            input release_time: UGenInput = UGenInput::Constant(1.0),
            #[doc = "done action"]
            input action: UGenInput = UGenInput::Constant(0.0),
        ]
        outputs ( fixed 1 )
        push [ (input gate), (input attack_time), (input sus_level), (input release_time), (input action) ]
    }
    #[doc = "Pause a specified node when triggered"]
    Pause class r"Pause" {
        rates [ (kr, Control) ]
        fields [
            #[doc = "when gate is 0, node is paused, when 1 it runs"]
            input gate: UGenInput = UGenInput::Constant(0.0),
            #[doc = "node to be paused"]
            input id: UGenInput = UGenInput::Constant(0.0),
        ]
        outputs ( fixed 1 )
        push [ (input gate), (input id) ]
    }
    #[doc = "Pause the enclosing synth when triggered"]
    PauseSelf class r"PauseSelf" {
        rates [ (kr, Control) ]
        fields [
            #[doc = "input signal"]
            input r#in: UGenInput = UGenInput::Constant(0.0),
        ]
        outputs ( fixed 1 )
        push [ (input r#in) ]
    }
    #[doc = "Pause the enclosing synth when the src ugen finishes (e.g. env-gen, play-buf, linen...)"]
    PauseSelfWhenDone class r"PauseSelfWhenDone" {
        rates [ (kr, Control) ]
        fields [
            #[doc = "the ugen to check for done"]
            input src: UGenInput = UGenInput::Constant(0.0),
        ]
        outputs ( fixed 1 )
        push [ (input src) ]
    }
}
