// @generated by packages/synthdef-compiler/scripts/generate-rust.ts from specs/ugens.json — do not edit.
// Regenerate with `yarn generate:synthdef-compiler`.

#![allow(
    non_camel_case_types,
    unused_mut,
    unused_variables,
    clippy::useless_conversion,
    clippy::needless_update
)]

use crate::{Rate, SynthDef, UGenInput};

sc_ugens! {
    #[doc = "Granular synthesis with sound stored in a buffer"]
    GrainBuf class r"GrainBuf" {
        rates [ (ar, Audio) ]
        fields [
            #[doc = "the number of channels to output. If 1, mono is returned and pan is ignored."]
            u32 num_channels: u32 = 1u32,
            #[doc = "a kr or ar trigger to start a new grain. If ar, grains after the start of the synth are sample accurate."]
            input trigger: UGenInput = UGenInput::Constant(0.0),
            #[doc = "size of the grain (in seconds)."]
            input dur: UGenInput = UGenInput::Constant(1.0),
            #[doc = "the buffer holding a mono audio signal. If using multi-channel files, use Buffer.readChannel."]
            input sndbuf: UGenInput = UGenInput::Constant(0.0),
            #[doc = "the playback rate of the sampled sound"]
            input rate: UGenInput = UGenInput::Constant(1.0),
            #[doc = "the playback position for the grain to start with (0 is beginning, 1 is end of file)"]
            input pos: UGenInput = UGenInput::Constant(0.0),
            #[doc = "the interpolation method used for pitchshifting grains: 1 = no interpolation 2 = linear 4 = cubic interpolation (more computationally intensive)"]
            input interp: UGenInput = UGenInput::Constant(2.0),
            #[doc = "Determines where to pan the output. If num-channels = 1, no panning is done; if num-channels = 2, panning is similar to Pan2; if num-channels > 2, pannins is the same as PanAz."]
            input pan: UGenInput = UGenInput::Constant(0.0),
            #[doc = "the buffer number containing a singal to use for the grain envelope. -1 uses a built-in Hanning envelope."]
            input envbufnum: UGenInput = UGenInput::Constant(-1.0),
            #[doc = "the maximum number of overlapping grains that can be used at a given time. This value is set at the UGens init time and can't be modified. This can be set lower for more efficient use of memory."]
            input max_grains: UGenInput = UGenInput::Constant(512.0),
        ]
        outputs ( from num_channels )
        push [ (input trigger), (input dur), (input sndbuf), (input rate), (input pos), (input interp), (input pan), (input envbufnum), (input max_grains) ]
    }
    #[doc = "Granular synthesis with frequency modulated sine tones"]
    GrainFM class r"GrainFM" {
        rates [ (ar, Audio) ]
        fields [
            #[doc = "the number of channels to output. If 1, mono is returned and pan is ignored."]
            u32 num_channels: u32 = 1u32,
            #[doc = "a kr or ar trigger to start a new grain. If ar, grains after the start of the synth are sample accurate."]
            input trigger: UGenInput = UGenInput::Constant(0.0),
            #[doc = "size of the grain."]
            input dur: UGenInput = UGenInput::Constant(1.0),
            #[doc = "the frequency of the FM grain's carrier oscillator"]
            input car_freq: UGenInput = UGenInput::Constant(440.0),
            #[doc = "the frequency of the FM grain's modulating oscillator"]
            input mod_freq: UGenInput = UGenInput::Constant(440.0),
            #[doc = "the FM index"]
            input index: UGenInput = UGenInput::Constant(1.0),
            #[doc = "Determines where to pan the output. If num-channels = 1, no panning is done; if num-channels = 2, panning is similar to Pan2; if numChannels > 2, pannins is the same as PanAz."]
            input pan: UGenInput = UGenInput::Constant(0.0),
            #[doc = "the buffer number containing a singal to use for the grain envelope. -1 uses a built-in Hanning envelope."]
            input envbufnum: UGenInput = UGenInput::Constant(-1.0),
            #[doc = "the maximum number of overlapping grains that can be used at a given time. This value is set at the UGens init time and can't be modified. This can be set lower for more efficient use of memory."]
            input max_grains: UGenInput = UGenInput::Constant(512.0),
        ]
        outputs ( from num_channels )
        push [ (input trigger), (input dur), (input car_freq), (input mod_freq), (input index), (input pan), (input envbufnum), (input max_grains) ]
    }
    #[doc = "Granulate an input signal"]
    GrainIn class r"GrainIn" {
        rates [ (ar, Audio) ]
        fields [
            #[doc = "the number of channels to output. If 1, mono is returned and pan is ignored."]
            u32 num_channels: u32 = 1u32,
            #[doc = "a kr or ar trigger to start a new grain. If ar, grains after the start of the synth are sample accurate."]
            input trigger: UGenInput = UGenInput::Constant(0.0),
            #[doc = "size of the grain."]
            input dur: UGenInput = UGenInput::Constant(1.0),
            #[doc = "the input to granulate"]
            input r#in: UGenInput = UGenInput::Constant(0.0),
            #[doc = "Determines where to pan the output. If num-channels = 1, no panning is done; if num-channels = 2, panning is similar to Pan2; if num-channels > 2, pannins is the same as PanAz."]
            input pan: UGenInput = UGenInput::Constant(0.0),
            #[doc = "the buffer number containing a singal to use for the grain envelope. -1 uses a built-in Hanning envelope."]
            input envbufnum: UGenInput = UGenInput::Constant(-1.0),
            #[doc = "the maximum number of overlapping grains that can be used at a given time. This value is set at the UGens init time and can't be modified. This can be set lower for more efficient use of memory."]
            input max_grains: UGenInput = UGenInput::Constant(512.0),
        ]
        outputs ( from num_channels )
        push [ (input trigger), (input dur), (input r#in), (input pan), (input envbufnum), (input max_grains) ]
    }
    #[doc = "Granular synthesis with sine tones"]
    GrainSin class r"GrainSin" {
        rates [ (ar, Audio) ]
        fields [
            #[doc = "the number of channels to output. If 1, mono is returned and pan is ignored."]
            u32 num_channels: u32 = 1u32,
            #[doc = "a kr or ar trigger to start a new grain. If ar, grains after the start of the synth are sample accurate."]
            input trigger: UGenInput = UGenInput::Constant(0.0),
            #[doc = "size of the grain."]
            input dur: UGenInput = UGenInput::Constant(1.0),
            #[doc = "the frequency of the grain's oscillator"]
            input freq: UGenInput = UGenInput::Constant(440.0),
            #[doc = "Determines where to pan the output. If num-channels = 1, no panning is done; if num-channels = 2, panning is similar to Pan2; if numChannels > 2, pannins is the same as PanAz."]
            input pan: UGenInput = UGenInput::Constant(0.0),
            #[doc = "the buffer number containing a singal to use for the grain envelope. -1 uses a built-in Hanning envelope."]
            input envbufnum: UGenInput = UGenInput::Constant(-1.0),
            #[doc = "the maximum number of overlapping grains that can be used at a given time. This value is set at the UGens init time and can't be modified. This can be set lower for more efficient use of memory."]
            input max_grains: UGenInput = UGenInput::Constant(512.0),
        ]
        outputs ( from num_channels )
        push [ (input trigger), (input dur), (input freq), (input pan), (input envbufnum), (input max_grains) ]
    }
    #[doc = "A granular time stretcher and pitchshifter. Inspired by Chad Kirby's SuperCollider2 Warp1 class, which was inspired by Richard Karpen's sndwarp for CSound."]
    Warp1 class r"Warp1" {
        rates [ (ar, Audio) ]
        fields [
            #[doc = "the number of channels in the soundfile used in bufnum."]
            u32 num_channels: u32 = 1u32,
            #[doc = "the buffer number of a mono soundfile."]
            input bufnum: UGenInput = UGenInput::Constant(0.0),
            #[doc = "the position in the buffer. The value should be between 0 and 1, with 0 being the begining of the buffer, and 1 the end."]
            input pointer: UGenInput = UGenInput::Constant(0.0),
            #[doc = "the amount of frequency shift. 1.0 is normal, 0.5 is one octave down, 2.0 is one octave up. Negative values play the soundfile backwards."]
            input freq_scale: UGenInput = UGenInput::Constant(1.0),
            #[doc = "the size of each grain window."]
            input window_size: UGenInput = UGenInput::Constant(0.2),
            #[doc = "the buffer number containing a singal to use for the grain envelope. -1 uses a built-in Hanning envelope."]
            input envbufnum: UGenInput = UGenInput::Constant(-1.0),
            #[doc = "the number of overlaping windows."]
            input overlaps: UGenInput = UGenInput::Constant(8.0),
            #[doc = "the amount of randomness to the windowing function. Must be between 0 (no randomness) to 1.0 (probably to random actually)"]
            input window_rand_ratio: UGenInput = UGenInput::Constant(0.0),
            #[doc = "the interpolation method used for pitchshifting grains. 1 = no interpolation. 2 = linear. 4 = cubic interpolation (more computationally intensive)."]
            input interp: UGenInput = UGenInput::Constant(1.0),
        ]
        outputs ( from num_channels )
        push [ (input bufnum), (input pointer), (input freq_scale), (input window_size), (input envbufnum), (input overlaps), (input window_rand_ratio), (input interp) ]
    }
}
