// @generated by packages/synthdef-compiler/scripts/generate-rust.ts from specs/ugens.json — do not edit.
// Regenerate with `yarn generate:synthdef-compiler`.

#![allow(
    non_camel_case_types,
    unused_mut,
    unused_variables,
    clippy::useless_conversion,
    clippy::needless_update
)]

use crate::{Rate, SynthDef, UGenInput};

sc_ugens! {
    #[doc = "Chorusing wavetable lookup oscillator. Produces sum of two signals at (freq +/- (beats / 2)). Due to summing, the peak amplitude is twice that of the wavetable."]
    COsc class r"COsc" {
        rates [ (ar, Audio), (kr, Control) ]
        fields [
            #[doc = "The number of a buffer filled in wavetable format"]
            input bufnum: UGenInput = UGenInput::Constant(0.0),
            #[doc = "Frequency in Hertz"]
            input freq: UGenInput = UGenInput::Constant(440.0),
            #[doc = "Beat frequency in Hertz"]
            input beats: UGenInput = UGenInput::Constant(0.5),
        ]
        outputs ( fixed 1 )
        push [ (input bufnum), (input freq), (input beats) ]
    }
    #[doc = "the input signal value is truncated to an integer value and used as an index into an octave repeating table of note values (indices wrap around the table)"]
    DegreeToKey class r"DegreeToKey" {
        rates [ (ar, Audio), (kr, Control) ]
        fields [
            #[doc = "Index of the buffer which contains the steps for each scale degree."]
            input bufnum: UGenInput = UGenInput::Constant(0.0),
            #[doc = "The input signal."]
            input r#in: UGenInput = UGenInput::Constant(0.0),
            #[doc = "The number of steps per octave in the scale. The default is 12."]
            input octave: UGenInput = UGenInput::Constant(12.0),
        ]
        outputs ( fixed 1 )
        push [ (input bufnum), (input r#in), (input octave) ]
    }
    #[doc = "search a buffer for a value"]
    DetectIndex class r"DetectIndex" {
        rates [ (ar, Audio), (kr, Control) ]
        fields [
            input bufnum: UGenInput = UGenInput::Constant(0.0),
            input r#in: UGenInput = UGenInput::Constant(0.0),
        ]
        outputs ( fixed 1 )
        push [ (input bufnum), (input r#in) ]
    }
    #[doc = "Generates a set of harmonics around a formant frequency at a given fundamental frequency. The frequency inputs are read at control rate only, so if you use an audio rate UGen as an input, it will only be sampled at the start of each audio synthesis block."]
    Formant class r"Formant" {
        rates [ (ar, Audio) ]
        fields [
            #[doc = "Fundamental frequency in Hertz (control rate)"]
            input fundfreq: UGenInput = UGenInput::Constant(440.0),
            #[doc = "Formant frequency in Hertz (control rate)"]
            input formfreq: UGenInput = UGenInput::Constant(1760.0),
            #[doc = "Pulse width frequency in Hertz. Controls the bandwidth of the formant (control rate)"]
            input bwfreq: UGenInput = UGenInput::Constant(880.0),
        ]
        outputs ( fixed 1 )
        push [ (input fundfreq), (input formfreq), (input bwfreq) ]
    }
    #[doc = "non band limited impulse oscillator. Outputs a single 1 every freq cycles per second and 0 the rest of the time."]
    Impulse class r"Impulse" {
        rates [ (ar, Audio), (kr, Control) ]
        fields [
            #[doc = "Frequency in Hertz"]
            input freq: UGenInput = UGenInput::Constant(440.0),
            #[doc = "Phase offset in cycles ( 0..1 )"]
            input phase: UGenInput = UGenInput::Constant(0.0),
        ]
        outputs ( fixed 1 )
        push [ (input freq), (input phase) ]
    }
    #[doc = "the input signal value is truncated to an integer and used as an index into the table"]
    Index class r"Index" {
        rates [ (ar, Audio), (kr, Control) ]
        fields [
            input bufnum: UGenInput = UGenInput::Constant(0.0),
            input r#in: UGenInput = UGenInput::Constant(0.0),
        ]
        outputs ( fixed 1 )
        push [ (input bufnum), (input r#in) ]
    }
    #[doc = "finds the (lowest) point in the buffer at which the input signal lies in-between the two values, and returns the index"]
    IndexInBetween class r"IndexInBetween" {
        rates [ (ar, Audio), (kr, Control) ]
        fields [
            input bufnum: UGenInput = UGenInput::Constant(0.0),
            input r#in: UGenInput = UGenInput::Constant(0.0),
        ]
        outputs ( fixed 1 )
        push [ (input bufnum), (input r#in) ]
    }
    #[doc = "an oscillator outputting a sine like shape made of two cubic pieces"]
    LFCub class r"LFCub" {
        rates [ (ar, Audio), (kr, Control) ]
        fields [
            #[doc = "Frequency in Hertz"]
            input freq: UGenInput = UGenInput::Constant(440.0),
            #[doc = "Initial phase offset. For efficiency reasons this is a value ranging from 0 to 2."]
            input iphase: UGenInput = UGenInput::Constant(0.0),
        ]
        outputs ( fixed 1 )
        push [ (input freq), (input iphase) ]
    }
    #[doc = "A non-band-limited gaussian function oscillator. Output ranges from minval to 1. LFGauss implements the formula: f(x) = exp(squared(x - iphase) / (-2.0 * squared(width))) where x is to vary in the range -1 to 1 over the period dur. minval is the initial value at -1"]
    LFGauss class r"LFGauss" {
        rates [ (ar, Audio), (kr, Control) ]
        fields [
            #[doc = "Duration of one full cycle ( for freq input: dur = 1 / freq )"]
            input duration: UGenInput = UGenInput::Constant(1.0),
            #[doc = "Relative width of the bell. Best to keep below 0.25 when used as envelope."]
            input width: UGenInput = UGenInput::Constant(0.1),
            #[doc = "Initial offset"]
            input iphase: UGenInput = UGenInput::Constant(0.0),
            #[doc = "If loop is > 0, UGen oscillates. Otherwise it calls the done action after one cycle"]
            input r#loop: UGenInput = UGenInput::Constant(1.0),
            #[doc = "Action to be evaluated after cycle completes. Default: NO-ACTION."]
            input action: UGenInput = UGenInput::Constant(0.0),
        ]
        outputs ( fixed 1 )
        push [ (input duration), (input width), (input iphase), (input r#loop), (input action) ]
    }
    #[doc = "a non band-limited parabolic oscillator outputing a high of 1 and a low of zero."]
    LFPar class r"LFPar" {
        rates [ (ar, Audio), (kr, Control) ]
        fields [
            #[doc = "Frequency in Hertz"]
            input freq: UGenInput = UGenInput::Constant(440.0),
            #[doc = "Initial phase offset. For efficiency reasons this is a value ranging from 0 to 2."]
            input iphase: UGenInput = UGenInput::Constant(0.0),
        ]
        outputs ( fixed 1 )
        push [ (input freq), (input iphase) ]
    }
    #[doc = "A non-band-limited pulse oscillator. Outputs a high value of one and a low value of zero."]
    LFPulse class r"LFPulse" {
        rates [ (ar, Audio), (kr, Control) ]
        fields [
            #[doc = "Frequency in Hertz"]
            input freq: UGenInput = UGenInput::Constant(440.0),
            #[doc = "Initial phase offset in cycles ( 0..1 )"]
            input iphase: UGenInput = UGenInput::Constant(0.0),
            #[doc = "Pulse width duty cycle from zero to one"]
            input width: UGenInput = UGenInput::Constant(0.5),
        ]
        outputs ( fixed 1 )
        push [ (input freq), (input iphase), (input width) ]
    }
    #[doc = "low freq (i.e. not band limited) sawtooth oscillator"]
    LFSaw class r"LFSaw" {
        rates [ (ar, Audio), (kr, Control) ]
        fields [
            #[doc = "Frequency in Hertz"]
            input freq: UGenInput = UGenInput::Constant(440.0),
            #[doc = "Initial phase offset. For efficiency reasons this is a value ranging from 0 to 2."]
            input iphase: UGenInput = UGenInput::Constant(0.0),
        ]
        outputs ( fixed 1 )
        push [ (input freq), (input iphase) ]
    }
    #[doc = "a non-band-limited triangle oscillator"]
    #[doc = ""]
    #[doc = "The triangle wave shape features two linear slopes and is not as harmonically rich as a sawtooth wave since it only contains odd harmonics (partials). Ideally, this type of wave form is mixed with a sine, square or pulse wave to add a sparkling or bright effect to a sound and is often employed on pads to give them a glittery feel."]
    LFTri class r"LFTri" {
        rates [ (ar, Audio), (kr, Control) ]
        fields [
            #[doc = "Frequency in Hertz"]
            input freq: UGenInput = UGenInput::Constant(440.0),
            #[doc = "Initial phase offset. For efficiency reasons this is a value ranging from 0 to 2."]
            input iphase: UGenInput = UGenInput::Constant(0.0),
        ]
        outputs ( fixed 1 )
        push [ (input freq), (input iphase) ]
    }
    #[doc = "Linear interpolating wavetable lookup oscillator with frequency and phase modulation inputs. This oscillator requires a buffer to be filled with a wavetable format signal. This preprocesses the Signal into a form which can be used efficiently by the Oscillator. The buffer size must be a power of 2. This can be achieved by creating a Buffer object and sending it one of the b_gen messages (sine1, sine2, sine3) with the wavetable flag set to true. This can also be achieved by creating a Signal object and sending it the 'asWavetable' message, saving it to disk, and having the server load it from there."]
    Osc class r"Osc" {
        rates [ (ar, Audio), (kr, Control) ]
        fields [
            #[doc = "Lookup buffer"]
            input buffer: UGenInput = UGenInput::Constant(0.0),
            #[doc = "Frequency in Hertz"]
            input freq: UGenInput = UGenInput::Constant(440.0),
            #[doc = "Phase offset or modulator in radians"]
            input phase: UGenInput = UGenInput::Constant(0.0),
        ]
        outputs ( fixed 1 )
        push [ (input buffer), (input freq), (input phase) ]
    }
    #[doc = "select the output signal from an array of inputs"]
    Select class r"Select" {
        rates [ (ar, Audio), (kr, Control) ]
        fields [
            #[doc = "Index of array to select"]
            input which: UGenInput = UGenInput::Constant(0.0),
            #[doc = "List of ugens to choose from"]
            array channels_array: Vec<UGenInput> = Vec::new(),
        ]
        outputs ( fixed 1 )
        push [ (input which), (array channels_array) ]
    }
    #[doc = "performs waveshaping on the input signal by indexing into a table"]
    Shaper class r"Shaper" {
        rates [ (ar, Audio), (kr, Control) ]
        fields [
            input bufnum: UGenInput = UGenInput::Constant(0.0),
            input r#in: UGenInput = UGenInput::Constant(0.0),
        ]
        outputs ( fixed 1 )
        push [ (input bufnum), (input r#in) ]
    }
    #[doc = "Sine table lookup oscillator"]
    #[doc = ""]
    #[doc = "Outputs a sine wave with values oscillating between -1 and 1 similar to osc except that the table has already been fixed as a sine table of 8192 entries. Sine waves are often used for creating sub-basses or are mixed with other waveforms to add extra body or bottom end to a sound. They contain no harmonics and consist entirely of the fundamental frequency. This means that they're not suitable for subtractive synthesis i.e. passing through filters such as a hpf or lpf. However, they are useful for additive synthesis i.e. adding multiple sine waves together at different frequencies, amplitudes and phase to create new timbres."]
    SinOsc class r"SinOsc" {
        rates [ (ar, Audio), (kr, Control) ]
        fields [
            #[doc = "Frequency in Hertz"]
            input freq: UGenInput = UGenInput::Constant(440.0),
            #[doc = "Phase offset or modulator in radians"]
            input phase: UGenInput = UGenInput::Constant(0.0),
        ]
        outputs ( fixed 1 )
        push [ (input freq), (input phase) ]
    }
    #[doc = "Sine oscillator with phase modulation feedback"]
    #[doc = ""]
    #[doc = "Different feedback values results in a modulation between a sine wave and a sawtooth like wave. Overmodulation causes chaotic oscillation."]
    SinOscFB class r"SinOscFB" {
        rates [ (ar, Audio), (kr, Control) ]
        fields [
            #[doc = "Frequency of oscillator"]
            input freq: UGenInput = UGenInput::Constant(440.0),
            #[doc = "amplitude of phase feedback in radians"]
            input feedback: UGenInput = UGenInput::Constant(0.0),
        ]
        outputs ( fixed 1 )
        push [ (input freq), (input feedback) ]
    }
    #[doc = "hard sync sawtooth wave oscillator"]
    #[doc = ""]
    #[doc = "A sawtooth wave that is hard synched to a fundamental pitch. This produces an effect similar to moving formants or pulse width modulation. The sawtooth oscillator has its phase reset when the sync oscillator completes a cycle. This is not a band limited waveform, so it may alias."]
    SyncSaw class r"SyncSaw" {
        rates [ (ar, Audio), (kr, Control) ]
        fields [
            #[doc = "Frequency of the fundamental."]
            input sync_freq: UGenInput = UGenInput::Constant(440.0),
            #[doc = "Frequency of the slave synched sawtooth wave. saw-freq should always be greater than sync-freq."]
            input saw_freq: UGenInput = UGenInput::Constant(440.0),
        ]
        outputs ( fixed 1 )
        push [ (input sync_freq), (input saw_freq) ]
    }
    #[doc = "A wavetable lookup oscillator which can be swept smoothly across wavetables. All the wavetables must be allocated to the same size. Fractional values of table will interpolate between two adjacent tables. This oscillator requires at least two buffers to be filled with a wavetable format signal. This preprocesses the Signal into a form which can be used efficiently by the Oscillator. The buffer size must be a power of 2."]
    VOsc class r"VOsc" {
        rates [ (ar, Audio), (kr, Control) ]
        fields [
            #[doc = "Buffer index. Can be swept continuously among adjacent wavetable buffers of the same size."]
            input bufpos: UGenInput = UGenInput::Constant(0.0),
            #[doc = "Frequency in Hertz"]
            input freq: UGenInput = UGenInput::Constant(440.0),
            #[doc = "Phase offset of modulator in radians"]
            input phase: UGenInput = UGenInput::Constant(0.0),
        ]
        outputs ( fixed 1 )
        push [ (input bufpos), (input freq), (input phase) ]
    }
    #[doc = "Three variable wavetable oscillators. A wavetable lookup oscillator which can be swept smoothly across wavetables. All the wavetables must be allocated to the same size. Fractional values of table will interpolate between two adjacent tables. This unit generator contains three oscillators at different frequencies, mixed together. This oscillator requires at least two buffers to be filled with a wavetable format signal. This preprocesses the Signal into a form which can be used efficiently by the Oscillator. The buffer size must be a power of 2."]
    VOsc3 class r"VOsc3" {
        rates [ (ar, Audio), (kr, Control) ]
        fields [
            #[doc = "Buffer index. Can be swept continuously among adjacent wavetable buffers of the same size."]
            input bufpos: UGenInput = UGenInput::Constant(0.0),
            #[doc = "Frequency in Hertz of first oscillator"]
            input freq1: UGenInput = UGenInput::Constant(110.0),
            #[doc = "Frequency in Hertz of second oscillator"]
            input freq2: UGenInput = UGenInput::Constant(220.0),
            #[doc = "Frequency in Hertz of third oscillator"]
            input freq3: UGenInput = UGenInput::Constant(440.0),
        ]
        outputs ( fixed 1 )
        push [ (input bufpos), (input freq1), (input freq2), (input freq3) ]
    }
    #[doc = "a variable duty cycle saw wave oscillator"]
    VarSaw class r"VarSaw" {
        rates [ (ar, Audio), (kr, Control) ]
        fields [
            #[doc = "Frequency in Hertz"]
            input freq: UGenInput = UGenInput::Constant(440.0),
            #[doc = "Initial phase offset in cycles ( 0..1 )"]
            input iphase: UGenInput = UGenInput::Constant(0.0),
            #[doc = "Duty cycle from zero to one. (0 = downward sawtooth, 0.5 = triangle, 1 = upward sawtooth)"]
            input width: UGenInput = UGenInput::Constant(0.5),
        ]
        outputs ( fixed 1 )
        push [ (input freq), (input iphase), (input width) ]
    }
    #[doc = "Models a slow frequency modulation."]
    #[doc = ""]
    #[doc = "Vibrato is a slow frequency modulation. Consider the systematic deviation in pitch of a singer around a fundamental frequency, or a violinist whose finger wobbles in position on the fingerboard, slightly tightening and loosening the string to add shimmer to the pitch. There is often also a delay before vibrato is established on a note. This UGen models these processes; by setting more extreme settings, you can get back to the timbres of FM synthesis. You can also add in some noise to the vibrato rate and vibrato size (modulation depth) to make for a more realistic motor pattern. The vibrato output is a waveform based on a squared envelope shape with four stages marking out 0.0 to 1.0, 1.0 to 0.0, 0.0 to -1.0, and -1.0 back to 0.0. Vibrato rate determines how quickly you move through these stages."]
    Vibrato class r"Vibrato" {
        rates [ (ar, Audio), (kr, Control) ]
        fields [
            #[doc = "Fundamental frequency in Hertz. If the Vibrato UGen is running at audio rate, this must not be a constant, but an actual audio rate UGen"]
            input freq: UGenInput = UGenInput::Constant(440.0),
            #[doc = "Vibrato rate, speed of wobble in Hertz. Note that if this is set to a low value (and definitely with 0.0), you may never get vibrato back, since the rate input is only checked at the end of a cycle."]
            input rate: UGenInput = UGenInput::Constant(6.0),
            #[doc = "Size of vibrato frequency deviation around the fundamental, as a proportion of the fundamental. 0.02 = 2% of the fundamental."]
            input depth: UGenInput = UGenInput::Constant(0.02),
            #[doc = "Delay before vibrato is established in seconds (a singer tends to attack a note and then stabilise with vibrato, for instance)."]
            input delay: UGenInput = UGenInput::Constant(0.0),
            #[doc = "Transition time in seconds from no vibrato to full vibrato after the initial delay time."]
            input onset: UGenInput = UGenInput::Constant(0.0),
            #[doc = "Noise on the rate, expressed as a proportion of the rate; can change once per cycle of vibrato."]
            input rate_variation: UGenInput = UGenInput::Constant(0.04),
            #[doc = "Noise on the depth of modulation, expressed as a proportion of the depth; can change once per cycle of vibrato. The noise affects independently the up and the down part of vibrato shape within a cycle."]
            input depth_variation: UGenInput = UGenInput::Constant(0.1),
            #[doc = "Initial phase of vibrato modulation, allowing starting above or below the fundamental rather than on it."]
            input iphase: UGenInput = UGenInput::Constant(0.0),
        ]
        outputs ( fixed 1 )
        push [ (input freq), (input rate), (input depth), (input delay), (input onset), (input rate_variation), (input depth_variation), (input iphase) ]
    }
    #[doc = "the input signal value is truncated to an integer value and used as an index into the table (out of range index values are wrapped)"]
    WrapIndex class r"WrapIndex" {
        rates [ (ar, Audio), (kr, Control) ]
        fields [
            input bufnum: UGenInput = UGenInput::Constant(0.0),
            input r#in: UGenInput = UGenInput::Constant(0.0),
        ]
        outputs ( fixed 1 )
        push [ (input bufnum), (input r#in) ]
    }
}
