// @generated by packages/synthdef-compiler/scripts/generate-rust.ts from specs/ugens.json — do not edit.
// Regenerate with `yarn generate:synthdef-compiler`.

#![allow(
    non_camel_case_types,
    unused_mut,
    unused_variables,
    clippy::useless_conversion,
    clippy::needless_update
)]

use crate::{Rate, SynthDef, UGenInput};

sc_ugens! {
    #[doc = "Equal power panning balances two channels; by panning, you are favouring one or other channel in the mix, and the other loses power. The middle pan position (pos=0.0) corresponds to the original stereo mix; full left (pos of -1) is essentially just left channel playing, full right (pos of 1) just the right. The output of Balance2 remains a stereo signal."]
    Balance2 class r"Balance2" {
        rates [ (ar, Audio), (kr, Control) ]
        fields [
            #[doc = "channel 1 of input stereo signal"]
            input left: UGenInput = UGenInput::Constant(0.0),
            #[doc = "channel 2 of input stereo signal"]
            input right: UGenInput = UGenInput::Constant(0.0),
            #[doc = "pan position, -1 is left, +1 is right"]
            input pos: UGenInput = UGenInput::Constant(0.0),
            #[doc = "a control rate level input."]
            input level: UGenInput = UGenInput::Constant(1.0),
        ]
        outputs ( fixed 2 )
        push [ (input left), (input right), (input pos), (input level) ]
    }
    #[doc = "Encode a two channel signal to two dimensional ambisonic B-format. This puts two channels at opposite poles of a 2D ambisonic field. This is one way to map a stereo sound onto a soundfield. It is equivalent to: PanB2(inA, azimuth, gain) + PanB2(inB, azimuth + 1, gain)"]
    BiPanB2 class r"BiPanB2" {
        rates [ (ar, Audio), (kr, Control) ]
        fields [
            #[doc = "input signal A"]
            input in_a: UGenInput = UGenInput::Constant(0.0),
            #[doc = "input signal B"]
            input in_b: UGenInput = UGenInput::Constant(0.0),
            #[doc = "position around the circle from -1 to +1. -1 is behind, -0.5 is left, 0 is forward, +0.5 is right, +1 is behind."]
            input azimuth: UGenInput = UGenInput::Constant(0.0),
            #[doc = "amplitude control"]
            input gain: UGenInput = UGenInput::Constant(1.0),
        ]
        outputs ( fixed 3 )
        push [ (input in_a), (input in_b), (input azimuth), (input gain) ]
    }
    #[doc = "2D Ambisonic B-format decoder. Decode a two dimensional ambisonic B-format signal to a set of speakers in a regular polygon. The outputs will be in clockwise order. The position of the first speaker is either center or left of center."]
    DecodeB2 class r"DecodeB2" {
        rates [ (ar, Audio), (kr, Control) ]
        fields [
            #[doc = "number of output speakers. Typically 4 to 8."]
            u32 num_channels: u32 = 1u32,
            #[doc = "B-format signal"]
            input w: UGenInput = UGenInput::Constant(0.0),
            #[doc = "B-format signal"]
            input x: UGenInput = UGenInput::Constant(0.0),
            #[doc = "B-format signal"]
            input y: UGenInput = UGenInput::Constant(0.0),
            #[doc = "Should be zero if the front is a vertex of the polygon. The first speaker will be directly in front. Should be 0.5 if the front bisects a side of the polygon. Then the first speaker will be the one left of center. Default is 0.5."]
            input orientation: UGenInput = UGenInput::Constant(0.5),
        ]
        outputs ( from num_channels )
        push [ (input w), (input x), (input y), (input orientation) ]
    }
    #[doc = "Two channel (stereo) linear panner. This one sounds more like the Rhodes tremolo than Pan2."]
    LinPan2 class r"LinPan2" {
        rates [ (ar, Audio), (kr, Control) ]
        fields [
            #[doc = "input signal"]
            input r#in: UGenInput = UGenInput::Constant(0.0),
            #[doc = "pan position, -1 is left, +1 is right"]
            input pos: UGenInput = UGenInput::Constant(0.0),
            #[doc = "a control rate level input"]
            input level: UGenInput = UGenInput::Constant(1.0),
        ]
        outputs ( fixed 2 )
        push [ (input r#in), (input pos), (input level) ]
    }
    #[doc = "Two channel linear crossfader."]
    LinXFade2 class r"LinXFade2" {
        rates [ (ar, Audio), (kr, Control) ]
        fields [
            #[doc = "input signal A"]
            input in_a: UGenInput = UGenInput::Constant(0.0),
            #[doc = "input signal B"]
            input in_b: UGenInput = UGenInput::Constant(0.0),
            #[doc = "cross fade position from -1 to +1"]
            input pan: UGenInput = UGenInput::Constant(0.0),
            #[doc = "a control rate level input"]
            input level: UGenInput = UGenInput::Constant(1.0),
        ]
        outputs ( fixed 1 )
        push [ (input in_a), (input in_b), (input pan), (input level) ]
    }
    #[doc = "Two channel (stereo) equal power panner."]
    Pan2 class r"Pan2" {
        rates [ (ar, Audio), (kr, Control) ]
        fields [
            #[doc = "input signal"]
            input r#in: UGenInput = UGenInput::Constant(0.0),
            #[doc = "pan position, -1 is left, +1 is right"]
            input pos: UGenInput = UGenInput::Constant(0.0),
            #[doc = "a control rate level input"]
            input level: UGenInput = UGenInput::Constant(1.0),
        ]
        outputs ( fixed 2 )
        push [ (input r#in), (input pos), (input level) ]
    }
    #[doc = "Four channel equal power panner. Outputs are in order LeftFront, RightFront, LeftBack, RightBack."]
    Pan4 class r"Pan4" {
        rates [ (ar, Audio), (kr, Control) ]
        fields [
            #[doc = "input signal"]
            input r#in: UGenInput = UGenInput::Constant(0.0),
            #[doc = "x pan position from -1 to +1 (left to right)"]
            input xpos: UGenInput = UGenInput::Constant(0.0),
            #[doc = "y pan position from -1 to +1 (back to front)"]
            input ypos: UGenInput = UGenInput::Constant(0.0),
            #[doc = "a control rate level input."]
            input level: UGenInput = UGenInput::Constant(1.0),
        ]
        outputs ( fixed 4 )
        push [ (input r#in), (input xpos), (input ypos), (input level) ]
    }
    #[doc = "Multichannel equal power panner."]
    PanAz class r"PanAz" {
        rates [ (ar, Audio), (kr, Control) ]
        fields [
            #[doc = "number of output channels"]
            u32 num_channels: u32 = 1u32,
            #[doc = "input signal"]
            input r#in: UGenInput = UGenInput::Constant(0.0),
            #[doc = "pan position. Channels are evenly spaced over a cyclic period of 2.0 with 0.0 equal to the position directly in front, 2.0/numChans a clockwise shift 1/numChans of the way around the ring, 4.0/numChans equal to a shift of 2/numChans, etc. Thus all channels will be cyclically panned through if a sawtooth wave from -1 to +1 is used to modulate the pos. N.B. Front may or may not correspond to a speaker depending on the setting of the orientation arg, see below."]
            input pos: UGenInput = UGenInput::Constant(0.0),
            #[doc = "a control rate level input."]
            input level: UGenInput = UGenInput::Constant(1.0),
            #[doc = "The width of the panning envelope. Nominally this is 2.0 which pans between pairs of adjacent speakers. Width values greater than two will spread the pan over greater numbers of speakers. Width values less than one will leave silent gaps between speakers."]
            input width: UGenInput = UGenInput::Constant(2.0),
            #[doc = "Should be zero if the front is a vertex of the polygon. The first speaker will be directly in front. Should be 0.5 if the front bisects a side of the polygon. Then the first speaker will be the one left of center. Default is 0.5."]
            input orientation: UGenInput = UGenInput::Constant(0.5),
        ]
        outputs ( from num_channels )
        push [ (input r#in), (input pos), (input level), (input width), (input orientation) ]
    }
    #[doc = "Ambisonic B format panner. Output channels are in order W,X,Y,Z."]
    PanB class r"PanB" {
        rates [ (ar, Audio), (kr, Control) ]
        fields [
            #[doc = "input signal"]
            input r#in: UGenInput = UGenInput::Constant(0.0),
            #[doc = "in radians, -pi to +pi"]
            input azimuth: UGenInput = UGenInput::Constant(0.0),
            #[doc = "in radians, -0.5pi to +0.5pi"]
            input elevation: UGenInput = UGenInput::Constant(0.0),
            #[doc = "a control rate level input"]
            input gain: UGenInput = UGenInput::Constant(1.0),
        ]
        outputs ( fixed 4 )
        push [ (input r#in), (input azimuth), (input elevation), (input gain) ]
    }
    #[doc = "Encode a mono signal to two dimensional ambisonic B-format."]
    PanB2 class r"PanB2" {
        rates [ (ar, Audio), (kr, Control) ]
        fields [
            #[doc = "input signal"]
            input r#in: UGenInput = UGenInput::Constant(0.0),
            #[doc = "position around the circle from -1 to +1. -1 is behind, -0.5 is left, 0 is forward, +0.5 is right, +1 is behind."]
            input azimuth: UGenInput = UGenInput::Constant(0.0),
            #[doc = "amplitude control"]
            input gain: UGenInput = UGenInput::Constant(1.0),
        ]
        outputs ( fixed 3 )
        push [ (input r#in), (input azimuth), (input gain) ]
    }
    #[doc = "Rotate2 can be used for rotating an ambisonic B-format sound field around an axis. Rotate2 does an equal power rotation so it also works well on stereo sounds. It takes two audio inputs (x, y) and an angle control (pos). It outputs two channels (x, y). It computes this: xout = cos(angle) * xin + sin(angle) * yin; yout = cos(angle) * yin - sin(angle) * xin; where angle = pos * pi, so that -1 becomes -pi and +1 becomes +pi. This allows you to use an LFSaw to do continuous rotation around a circle."]
    Rotate2 class r"Rotate2" {
        rates [ (ar, Audio), (kr, Control) ]
        fields [
            #[doc = "input signal"]
            input x: UGenInput = UGenInput::Constant(0.0),
            #[doc = "input signal"]
            input y: UGenInput = UGenInput::Constant(0.0),
            #[doc = "angle to rotate around the circle from -1 to +1. -1 is 180 degrees, -0.5 is left, 0 is forward, +0.5 is right, +1 is behind."]
            input pos: UGenInput = UGenInput::Constant(0.0),
        ]
        outputs ( fixed 2 )
        push [ (input x), (input y), (input pos) ]
    }
    #[doc = "Equal power two channel cross fade"]
    XFade2 class r"XFade2" {
        rates [ (ar, Audio), (kr, Control) ]
        fields [
            #[doc = "input signal A"]
            input in_a: UGenInput = UGenInput::Constant(0.0),
            #[doc = "input signal B"]
            input in_b: UGenInput = UGenInput::Constant(0.0),
            #[doc = "Pan between the two input signals with -1 being inA only and 1 being inB only with values between being a mix of the two."]
            input pan: UGenInput = UGenInput::Constant(0.0),
            #[doc = "Output level - 0 being silent and 1 being original volume"]
            input level: UGenInput = UGenInput::Constant(1.0),
        ]
        outputs ( fixed 1 )
        push [ (input in_a), (input in_b), (input pan), (input level) ]
    }
}
