// Style Dictionary build: design tokens (tokens/*.json) → CSS custom properties
// + a typed TS token module. Run via `yarn tokens`. Outputs land in
// src/foundations/generated/ (committed, so vite/tsc resolve them from source).
//
// The CSS goes on :root (loaded once by the app; inherits into every shadow
// root). The TS module exports one `as const` object per top-level token group
// (space, color, font, …) so src/ + components can consume token values in JS.

import StyleDictionary from "style-dictionary";

/** Serialize the nested token tree to grouped `export const` objects. */
function tsGroupedFormat({ dictionary }) {
  const isLeaf = (n) =>
    n && typeof n === "object" && "value" in n && typeof n.value !== "object";
  const ser = (n) =>
    isLeaf(n)
      ? JSON.stringify(n.value)
      : `{ ${Object.entries(n)
          .map(([k, v]) => `${JSON.stringify(k)}: ${ser(v)}`)
          .join(", ")} }`;
  const groups = Object.entries(dictionary.tokens).map(
    ([group, node]) => `export const ${group} = ${ser(node)} as const;`,
  );
  return `// AUTO-GENERATED by Style Dictionary (yarn tokens) — do not edit.\n\n${groups.join(
    "\n\n",
  )}\n`;
}

const sd = new StyleDictionary({
  source: ["tokens/**/*.json"],
  hooks: { formats: { "ts/grouped": tsGroupedFormat } },
  platforms: {
    css: {
      transformGroup: "css",
      buildPath: "src/foundations/generated/",
      files: [
        {
          destination: "tokens.generated.css",
          format: "css/variables",
          options: { selector: ":root", outputReferences: true },
        },
      ],
    },
    ts: {
      transformGroup: "js",
      buildPath: "src/foundations/generated/",
      files: [{ destination: "tokens.generated.ts", format: "ts/grouped" }],
    },
  },
});

await sd.buildAllPlatforms();
